### ISSUE TITLE
Peer connectivity latency metrics

### ISSUE THREAD

**Issue by avive** [spacemeshos/go-spacemesh#10]
Add peers connection latency metrics per peer and use them in routing table ops. e.g. drop from table peers with very high latency.

**Comment by dgonzalez** [comment]
I have the perfect solution for this:
https://github.com/dgonzalez/vishnu

I need to add a couple of examples to it (very rough so far) and it will make perfect sense for using here. What we are looking is some sort of circuit breaker that can inform about telemetry on nodes and open the circuit (stop connecting to that peer) in case of problems.

Will have a look to this next.

**Comment by avive** [comment]
Nice. Can you please elaborate a bit more abut this here?
The solution needs to work in the context of the peer DHT-baesd discovery features - we have a basic partial implementation of DHT but without any notion of peers latency. The basic idea is to have a notion of connection latency based on recent communications with a peer and drop peers with high latency from the DHT routing table. A good reference to this feature is go-lib-p2p.

**Comment by dgonzalez** [comment]
This works similar to (forget about the syntax):
```
vishnu := Vishnu{...}
vishnu.add(peer1)
vishnu.add(peer2)
vishnu.add(peer3)

vishnu.With(func (peerX, stats) {
   before = TimeNow()
   peerX.communicateWithIt(...)
   after = TimeNow()
   latency = after - before
   stats["latency"] = latency
})
```

Then the next time that you execute `With` in order to select another peer, Vishnu is going to select the one with less latency (the healthier one, criteria can be configured with a rating function). Also, if there is a problem connecting to a peer, it will stop using it for 30 seconds and bring it back into the loop after that for a test and see if it has been recovered.

Not sure how clear it is but I intend to have better examples this week.

**Comment by avive** [comment]
@dgonzalez are you working on this? I believe we should start with something basic:
1. Record new latency measurement for the round-trip time of a protocol message and response parts. e.g. Store t when ping message was sent, calc latency as the diff between time where pong was received by sender and update the remote peer metrics.
2. Use exponential smoothing to decay old measurements https://en.wikipedia.org/wiki/Exponential_smoothing
3. Have a notion of peer latency based on the exponentially decayed moving average
4. Have DHT occasionally ping all known peers to update latency.
5. Use the latency in the DHT to make decisions regarding which peers to remove from the routing table.

**Comment by dgonzalez** [comment]
Not so far. I am working on the Merkle.
