### ISSUE TITLE
error when running dockerrun-all  failed to copy directory

### ISSUE THREAD

**Issue by y0sher** [spacemeshos/go-spacemesh#1000]
# Overview / Motivation

```
failed to copy files: failed to copy directory: mkdir /var/lib/docker/overlay2/acfeebd67ea3d95879b67a607fa6273057dda8169be0f6d3b092d55f5a8b794a/merged/go-spacemesh: not a directory
```
# The Task
TODO: Clearly describe the issue requirements here...

# Implementation Notes
TODO: Add links to relevant resources, specs, related issues, etc...

# Contribution Guidelines
Important: Issue assignment to developers will be by the order of their application and proficiency level according to the tasks complexity. We will not assign tasks to developers who have'nt introduced themselves on our Gitter [dev channel](https://gitter.im/spacemesh-os/Lobby)

1. Introduce yourself on go-spacemesh [dev chat channel](https://gitter.im/spacemesh-os/Lobby) - ask our team any question you may have about this task
2. Fork branch `develop` to your own repo and work in your repo
3. You must document all methods, enums and types with [godoc comments](https://blog.golang.org/godoc-documenting-go-code)
4. You must write go unit tests for all types and methods when submitting a component, and integration tests if you submit a feature
5. When ready for code review, submit a PR from your repo back to branch `develop`
6. Attach relevant issue to PR

**Comment by beckmani** [comment]
@y0sher , This can happen if you have a binary called "go-spacemesh" in the repository.
(when you build the project locally)
Please verify it.
If this is the case then we need to change the name of the directory in Docker build to another name.  (not go-spacemesh)
