### ISSUE TITLE
ATX processing

### ISSUE THREAD

**Issue by barakshani** [spacemeshos/go-spacemesh#1016]
# Overview / Motivation
The same ATX may be included in multiple blocks.
ATX process and validity should not happen twice; for example, during the first process we update the list of published ATXs, so during the second validity "previous ATX" would fail.

# The Task
1. Add locking for Process ATX - so it is not processed simultaneously. 
2. Add IsProcessed flag, which tells us if an ATX was processed, so we don't process/validate it twice.

# Implementation Notes
TODO: Add links to relevant resources, specs, related issues, etc...

# Contribution Guidelines
Important: Issue assignment to developers will be by the order of their application and proficiency level according to the tasks complexity. We will not assign tasks to developers who have'nt introduced themselves on our Gitter [dev channel](https://gitter.im/spacemesh-os/Lobby)

1. Introduce yourself on go-spacemesh [dev chat channel](https://gitter.im/spacemesh-os/Lobby) - ask our team any question you may have about this task
2. Fork branch `develop` to your own repo and work in your repo
3. You must document all methods, enums and types with [godoc comments](https://blog.golang.org/godoc-documenting-go-code)
4. You must write go unit tests for all types and methods when submitting a component, and integration tests if you submit a feature
5. When ready for code review, submit a PR from your repo back to branch `develop`
6. Attach relevant issue to PR

**Comment by moshababo** [comment]
@noamnelke is this still missing in the implementation?
