### ISSUE TITLE
Optimize the block view selected for proving the active set size

### ISSUE THREAD

**Issue by zalmen** [spacemeshos/go-spacemesh#1017]
# Overview / Motivation
Currently, when generating an ATX we choose all orphan blocks as the view that proves the active set size. We need to optimize the view in order to ease the traversal when validating the ATX.

# The Task
TODO: Clearly describe the issue requirements here...

# Implementation Notes
TODO: Add links to relevant resources, specs, related issues, etc...

# Contribution Guidelines
Important: Issue assignment to developers will be by the order of their application and proficiency level according to the tasks complexity. We will not assign tasks to developers who have'nt introduced themselves on our Gitter [dev channel](https://gitter.im/spacemesh-os/Lobby)

1. Introduce yourself on go-spacemesh [dev chat channel](https://gitter.im/spacemesh-os/Lobby) - ask our team any question you may have about this task
2. Fork branch `develop` to your own repo and work in your repo
3. You must document all methods, enums and types with [godoc comments](https://blog.golang.org/godoc-documenting-go-code)
4. You must write go unit tests for all types and methods when submitting a component, and integration tests if you submit a feature
5. When ready for code review, submit a PR from your repo back to branch `develop`
6. Attach relevant issue to PR

**Comment by barakshani** [comment]
Ideally, all ATX gives exactly the same view (first layer of their publication epoch), so active-set verification/ traversal should happen only once.

Moreover, a miner that verifies the active set, should also publish her ATX's view. If possible, she should have a cache with the active set ATXs along the previous epoch, so she won't have to do the traversal at all.
