### ISSUE TITLE
Blocks conflict in epoch beacon

### ISSUE THREAD

**Issue by barakshani** [spacemeshos/go-spacemesh#1019]
# Overview / Motivation
Validity to produce blocks is based (among others) on the Epoch Beacon.
This beacon is computed locally and should be the same for all nodes. Its value is published in each block.
We need to address the case when different blocks (of different miners) have different beacons.

# The Task
For blocks in the **same** epoch,
if layer(x) > layer(b), and b is in the view of x,
if the epoch beacon is different,
when when counting votes on b, we consider the vote of x to have weight 0.

**Comment by almogdepaz** [comment]
@barakshani milestone ?

**Comment by barakshani** [comment]
next one, where we finish all protocol tasks

**Comment by antonlerner** [comment]
@nkryuchkov close this if you address it in your pr
