### ISSUE TITLE
Use goreleaser to build and release new versions

### ISSUE THREAD

**Issue by dgonzalez** [spacemeshos/go-spacemesh#102]
Use goreleaser or similar so that we can release new versions on one command building the binaries for several platforms and architectures.

The main reason for adding this is automate the process of new releases as much as possible.

**Comment by dgonzalez** [comment]
More info in the project: https://github.com/goreleaser/goreleaser

**Comment by avive** [comment]
thanks for sharing - looks interesting. let's explore.
