### ISSUE TITLE
NIPST recovery

### ISSUE THREAD

**Issue by zalmen** [spacemeshos/go-spacemesh#1065]
# The Motivation
Building a NIPSt as a long and demanding process, in case we failed in the middle of it we would like to do the best effort to continue the process instead of starting from scratch

# The Requirement
1. We need to persistently store the status of the NIPST and be able to continue in case of failures. 
2. We need to be able to retrieve data that might have sent while we were down and is needed in order to continue the construction of the NIPST (e.g. PoET proofs)

**Comment by moshababo** [comment]
Already implemented.
