### ISSUE TITLE
Retrieve PoET proofs without knowing the PoET reference 

### ISSUE THREAD

**Issue by zalmen** [spacemeshos/go-spacemesh#1066]
# Overview / Motivation
In case the node crashed while building a NIPST and before receiving the PoET proof, and while it was down, the PoET sent its proof. If the node wants to continue building the NIPST it will have to have a way to retrieve the PoET proof only with the PoET id and the round number (without the proof's reference).

# The Task
Currently, we're thinking of two ways to approach this problem -
1. Fetch the PoET proof from the node neighbors, as an extension to the sync protocol.
2. Fetch the proof from the PoET itself which will support this type of queries (YUVAL: personally I prefer this approach to avoid extra burden on the already-complicated sync protocol) 

# Implementation Notes
TODO: Add links to relevant resources, specs, related issues, etc...

# Contribution Guidelines
Important: Issue assignment to developers will be by the order of their application and proficiency level according to the tasks complexity. We will not assign tasks to developers who have'nt introduced themselves on our Gitter [dev channel](https://gitter.im/spacemesh-os/Lobby)

1. Introduce yourself on go-spacemesh [dev chat channel](https://gitter.im/spacemesh-os/Lobby) - ask our team any question you may have about this task
2. Fork branch `develop` to your own repo and work in your repo
3. You must document all methods, enums and types with [godoc comments](https://blog.golang.org/godoc-documenting-go-code)
4. You must write go unit tests for all types and methods when submitting a component, and integration tests if you submit a feature
5. When ready for code review, submit a PR from your repo back to branch `develop`
6. Attach relevant issue to PR

**Comment by moshababo** [comment]
Obsolete.
