### ISSUE TITLE
When taking prevAtx as positioning, need to check that prevAtx epoch is correct

### ISSUE THREAD

**Issue by antonlerner** [spacemeshos/go-spacemesh#1068]
# Overview / Motivation
in the following code, need to check if b.prevAtx is in the correct epoch before using it as positioning. 
Or drop this optimisation al together.
```
// GetPositioningAtx return the atx object for the positioning atx according to requested epochId
func (b *Builder) GetPositioningAtx(epochId types.EpochId) (*types.ActivationTx, error) {
	posAtxId, err := b.GetPositioningAtxId(epochId)
	if err != nil {
		if b.prevATX != nil {
			//if the atx was created by this miner but have not propagated as an atx to the notwork yet, use the cached atx
			return b.prevATX, nil
		} else {
			return nil, fmt.Errorf("cannot find pos atx id: %v", err)
		}
	}
```
# The Task
TODO: Clearly describe the issue requirements here...

# Implementation Notes
TODO: Add links to relevant resources, specs, related issues, etc...

# Contribution Guidelines
Important: Issue assignment to developers will be by the order of their application and proficiency level according to the tasks complexity. We will not assign tasks to developers who have'nt introduced themselves on our Gitter [dev channel](https://gitter.im/spacemesh-os/Lobby)

1. Introduce yourself on go-spacemesh [dev chat channel](https://gitter.im/spacemesh-os/Lobby) - ask our team any question you may have about this task
2. Fork branch `develop` to your own repo and work in your repo
3. You must document all methods, enums and types with [godoc comments](https://blog.golang.org/godoc-documenting-go-code)
4. You must write go unit tests for all types and methods when submitting a component, and integration tests if you submit a feature
5. When ready for code review, submit a PR from your repo back to branch `develop`
6. Attach relevant issue to PR

**Comment by barakshani** [comment]
The function calls GetPositioningAtxId(), which "returns a randomly selected atx from the provided epoch epochId".

You should not take *any* ATX from the previous ATX. Ideally you should 'build upon' you previous ATXs, as they should always have exactly one epoch of difference.
If there is no previous ATX in the previous epoch, then we need to take either the latest ATX in the previous epoch, or something with similar layer index to our ATX (so the difference would be of an epoch)

**Comment by moshababo** [comment]
Obsolete.
