### ISSUE TITLE
bug in IsIdentityActive()

### ISSUE THREAD

**Issue by barakshani** [spacemeshos/go-spacemesh#1083]
The function fetches the last ATX of a miner and checks if lastAtxTargetEpoch > epoch. If the condition holds, we take the previous ATX in the ATX list (the assumption is that the miner already published an ATX for the current epoch, so the previous one gives her activation for this epoch).

If the miners published 1 ATX in epoch j, but 2 ATXs for the current epoch j+1, we won't even access the desired ATX. The miner is still eligible to create blocks (at least with the epoch-j ATX).

Generally, we should not consider the ATXs merely as a list, without context.

It is also not clear why we need the condition lastAtxTargetEpoch < epoch,
as it will fail anyway at the last line of this function.

**Comment by barakshani** [comment]
@noamnelke does https://github.com/spacemeshos/go-spacemesh/pull/1710 solve this issue?

**Comment by noamnelke** [comment]
Yes. `IsIdentityActive()` wasn't used at the time of the time of #1710 so I've deleted it. We now have an index of all of a node's ATXs by target epoch so we can always fetch exactly the ATX we need.
