### ISSUE TITLE
Running automation when .pyc files present fails the test

### ISSUE THREAD

**Issue by gavraz** [spacemeshos/go-spacemesh#1091]
We need to make sure that the presence of .pyc files in any directory does not break the test.
It waists a lot of time to discover it during the test.

_________________________________________________________________________________________________________________ ERROR collecting test_bs.py _________________________________________________________________________________________________________________
import file mismatch:
imported module 'tests.test_bs' has this __file__ attribute:
  /Users/elad/go/src/github.com/spacemeshos/go-spacemesh/tests/test_bs.py
which is not the same as the test file we want to collect:
  /go-spacemesh/tests/test_bs.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=================================================================================================================== 1 error in 0.52 seconds ===================================================================================================================
make: *** [dockerrun-mining] Error 2

**Comment by beckmani** [comment]
should not happen anymore as pycache is now in dockerignore
