### ISSUE TITLE
Write additional tests

### ISSUE THREAD

**Issue by avive** [spacemeshos/go-spacemesh#11]
Add additional tests to all packages and get us to above 90% tests code coverage.

**Comment by avive** [comment]
For example, package p2p tests code coverage is now only at 60.2%

**Comment by avive** [comment]
Follow these steps to view tests code coverage for a package:
- cd to a package directory
- `go test ./.... -coverprofile=cover.out`
- `go tool cover -html=cover.out`

**Comment by vorsprung** [comment]
Hi,
I've added test_aes.go, has 100% coverage in https://github.com/spacemeshos/go-spacemesh/pull/52
Hope this helps

**Comment by vorsprung** [comment]
There's a problem with testing crypto/randg.go "GetRandom*" functions
 
If we really need to be sure that the rand.Read is working correctly (and I think we do) then the way it works needs to be adjusted to pass a function pointer.  Normally this function pointer will be rand.Read but for tests will be something else. 

I tried to write a mock for rand.Read but it seems that "Go doesn't work like that" see my SO question here

https://stackoverflow.com/questions/48366328/using-mockgen-in-reflect-mode/48372347#48372347

I'll probably move the "real" GetRandom* functions to behind a facade.  Commits etc as soon as I have time :)

**Comment by avive** [comment]
I think this is fine and can see how it can make it testable using mocks.
