### ISSUE TITLE
Separate PoST proof data from metadata

### ISSUE THREAD

**Issue by moshababo** [spacemeshos/go-spacemesh#1104]
# Overview / Motivation
When generating a PoST, the following parameters need to be provided: `id`, `space`, `difficulty`, `challenge`, `numProvenLabels`. When validating the proof, the validation is based on these parameters. 

At the moment some of these fields are attached to the proof, and some are not. This can lead to a security problem wheres the validator side would forget to assert these values against the expected ones, before validating the proof.

# The Task
When generating a PoST, return the proof in addition to a metadata object, which will contain these parameters, and must be sent in addition to the proof, to be used by the validator.

In addition, add assertion to `id` as part of the activation transaction syntactic validation. It must match the transaction signer public key.

**Comment by moshababo** [comment]
@noamnelke should we close this?

**Comment by noamnelke** [comment]
Private case of #1134 - closing
