### ISSUE TITLE
Inconsistent proof structure

### ISSUE THREAD

**Issue by noamnelke** [spacemeshos/go-spacemesh#1134]
Proof structures currently sometimes contain challenges and metadata and sometimes don't.

I believe that proofs should always exclude any challenge or externally verifiable metadata and those data should be passed into the verifier separately from the proof (optionally, in a consolidated "proof metadata" structure).

This is important for consistency (to make it easy for developers to guess where a piece of information is stored). It also makes naming easier and code more readable (e.g. the post proof challenge is actually the poet proof ref, but for generality's sake we currently call it simply `Challenge` in the post proof, making it harder to understand what that challenge actually is).

Most importantly, though, changing this will make it clear which information in a proof must be validated externally to the proof validation function, reducing the potential for dangerous oversights.

**Comment by moshababo** [comment]
Closed by https://github.com/spacemeshos/post/pull/41.
