### ISSUE TITLE
Separate ATX header and content (also separate between immutable and aux. data - see comment)

### ISSUE THREAD

**Issue by noamnelke** [spacemeshos/go-spacemesh#1136]
Header should exclude fields that are only required for validation and propagation (incl. syncing other nodes).

The structure should be: 
```
Atx{
	Header{
		Id // this should either be removed entirely, or, if we want to cache it - separate objects should be created for storing and sending over the wire
		NipstChallenge{
			NodeId
			PubLayerId
			Sequence
			StartTick
			EndTick
			PosAtxId
			PrevAtxId
		}
		ActiveSetSize
		Coinbase
	}
	View
	Nipst{
		Space
		NipstChallenge (hash of: NodeId, Sequence, PrevAtxId, PubLayerId, StartTick, PosAtxId)
		PostProof{
			Identity (NodeId)
			Challenge (PoetProofRef)
			MerkleRoot
			ProofNodes
			ProvenLeaves
		}
	}
}
```

Fetching ATX from the DB should only return the header, unless full ATX is explicitly requested (e.g. when a neighbor requests it).

**Comment by zalmen** [comment]
There is another issue that should be handled as part of this work:
Currently, the ActivationTx struct has an inner cache for the AtxId (to avoid calculating the id every time we need it - the calculation of an id includes serialization of the entire atx).
We need to separate between immutable data which is written to the db and auxiliary data that is need in the memory only and can be modified (e.g. the id cache)

**Comment by noamnelke** [comment]
fixed
