### ISSUE TITLE
GPU optimization for init function

### ISSUE THREAD

**Issue by zalmen** [spacemeshos/go-spacemesh#1137]
Hash parameters (tentative, waiting for the research team to finalize)  -
Iddo:
We want scrypt that's around twice faster that Litecoin's parameters,
so (N=512,r=1,p=1) with chacha20 and sha3 seems ok as a starting point
(not the final thing that we'd want, just a similar running time to
the final thing that we'd want), it's implemented for example in
https://github.com/floodyberry/scrypt-jane

There parameters are supposed to give about 1500 kh/s on a strong 7970
gpu (so PoST init will be 2 days, with dual gpu it'd be 1 day), if you
cannot reach 1500 kh/s then try N=256 too.

**Comment by avive** [comment]
I will start researching this and sync with iddo regarding more details regarding what we should try.

**Comment by avive** [comment]
https://github.com/spacemeshos/scrypt_playground
https://da-data.blogspot.com/2013/12/inside-better-cuda-based-scrypt-miner.html

**Comment by avive** [comment]
Better defining the task: So, what @iddo333 recommends for the mainnet timeframe is a standalone process that is using scrypt-jane codebase at its core for scrypt and support both AMG and NVIDIA GPUs optimized execution and gives us flexibility to modify scrypt as needed.

**Comment by avive** [comment]
OpenCL AMD miner based on scrypt-jane: https://github.com/Thirtybird/YACMiner
Nvidia CUDA miner based on scrypt-jane: https://github.com/cbuchner1/CudaMiner

**Comment by avive** [comment]
So we'd like to have a standalone c/c++ console app with an IPC that all Spacemesh full nodes can use to setup POST init. Platforms: OS X, Linux, Windows.

**Comment by avive** [comment]
MVP Requirements:
1. Use `chacha20` as the mix function and `sha3` as the hash function. 
2. Support the standard scrypt params  (N, r, p) - for more info read the scrypt-jane repo readme
3. Provide optimized execution for each of these architectures: AMD GPUs and Nvidia GPUs.
4. Reuse existing open source implementations when possible. e.g. YACMiner and CudaMiner for AMD and Nvidia.
5. Must be packaged as a standalone on the following host OSes: OS X, Linux, Windows 10 Home.
6. Performance must be on-par with scrypt-based GPU miners in terms of MHPs.
7. Provide an IPC or an RPC API for local full-nodes to drive the stand-alone miner process.

`scrypt(input_bytes, input_len, salt_bytes, salt_len, Nfactor, pfactor, rfactor, out out_bytes, out out_bytes_len)`

salt - agreed constant.

**Comment by avive** [comment]
We are waiting for legal to finalize the contract with the contractor so they can start implementing.
