### ISSUE TITLE
Add a windows-based docker file and test

### ISSUE THREAD

**Issue by y0sher** [spacemeshos/go-spacemesh#114]
#### Feature description
We want to be able to use docker to run Spacemesh on a container on windows.
#### Main Reason for adding this feature
Spacemesh should be cross platform and work across different file systems, thus testing it on windows is as important as linux or osx.

https://hub.docker.com/r/microsoft/windowsservercore/

**Comment by wehrv** [comment]
Since Linux Containers on Windows using HyperV and WSL2 works quite well and is expected to be generally available "any day now", wouldn't concentrating on performance and correctness of the Linux container version of Spacemesh give excellent availability to interested users?

**Comment by lrettig** [comment]
> Since Linux Containers on Windows using HyperV and WSL2 works quite well and is expected to be generally available "any day now", wouldn't concentrating on performance and correctness of the Linux container version of Spacemesh give excellent availability to interested users?

This is a good point. In our case however, we have many users (home smeshers/wallet users) who will be running the node software natively on Windows PCs, so I'm not sure that would be sufficient.

**Comment by lrettig** [comment]
I don't think this is a priority right now. The node/app work very well natively on Windows. We can revisit this in future if it's requested.
