### ISSUE TITLE
[CRIT] make dockerrun-all doesn't run with the latest code

### ISSUE THREAD

**Issue by gavraz** [spacemeshos/go-spacemesh#1148]
Sometimes the command make dockerrun-all does not run with the latest code even though the code has been committed and pushed.

**Comment by gavraz** [comment]
@zalmen please prioritize this bug.

**Comment by beckmani** [comment]
@gavraz,  please add branch name on which you encountered this behavior. 
Also, if you have the dockerrun-all stdout, it will be great

**Comment by gavraz** [comment]
@beckmani sorry but I didn't see your comment. I don't remember the branch's name. In addition, it could be something with the environment.
I suggest reviewing the code and considering docker cache.
In case we go for a Jenkins solution - it may bypass this issue. Still, I suggest looking into it.
