### ISSUE TITLE
when eligible to produce multiple blocks, same txs and atxs are used

### ISSUE THREAD

**Issue by y0sher** [spacemeshos/go-spacemesh#1149]
# Overview / Motivation

on a new tick, we check for our eligibility proofs, if we are eligible to create a block, we pop the txs and atxs we have in our pools and put them in our block. but if we're eligible to create more then one block, we include the previous txs and atxs  in the block again. 

this overloads the network without a good reason, though we have another problem that blocks with less than 15 txs get a smaller reward.

**Comment by lrettig** [comment]
This will be dealt with soon as part of transaction selection
