### ISSUE TITLE
If possible, PosAtx and PrevAtx should be the same

### ISSUE THREAD

**Issue by noamnelke** [spacemeshos/go-spacemesh#1166]
We currently randomly select a positioning ATX from the current epoch. This can cause the ATXs layer relative to the epoch to fluctuate.

In order to stabilize the relative layer we should select the previous ATX as a positioning ATX, if it's available, and a random ATX with the highest possible layer ID, otherwise.

cc: @barakshani

**Comment by noamnelke** [comment]
Proven by the test in https://github.com/spacemeshos/go-spacemesh/pull/1165

- [ ] Unskip test when fixing

**Comment by moshababo** [comment]
@noamnelke is it still relevant?

**Comment by poszu** [comment]
Closing as already implemented
