### ISSUE TITLE
Union of consensus view for hare oracle in active set size calculation

### ISSUE THREAD

**Issue by gavraz** [spacemeshos/go-spacemesh#1167]
The consensus view for layer X should be rounded to a constant (previous) layer so that we union the consensus view for layers that fall in that range.
Illustration
-PC--------|-L3--C----L1-L2----|
PC - is the constant of the previous layer
C is the constant (C=PC+layerPerEpoch)
| represents an epoch
L1, L2, L3 are the layers.
L1 & L2 - should be calculated according to layer C
L3 - should be calculated according to PC

**Comment by barakshani** [comment]
Two thing to consider:
1. What if the constant layer does not expand the entire view (compared to the layer we would have taken without rounding)? Most of the time, this will not be an issue, since the difference in ATXs should be very small.
2. What if someone aims to attack the constant layer?
