### ISSUE TITLE
Hare logs

### ISSUE THREAD

**Issue by barakshani** [spacemeshos/go-spacemesh#1173]
1. The log 'A node did note pass eligibility' does not specify the reason. At the moment the reason, e.g. 'Should not participate', is printed in a separate log. We should combine the reason with the original message.

Moreover, there should be different logs if a miner checked her eligibility, or someone else's (who sent a message).
With 'A node did note pass eligibility' it seems the latter....

Add layer and round numbers to the log.

2. Some of the prints assume rounds are 1-4, and some 0-3. Should be consistent.
Moreover, 'round x ended' logs may be greater than 4, but we only use 1-4 (iteratively).

Add layer number to the log.

3. We should not use words like failed/ invalid/ cannot for logs that we expect to see in a normal run.

4. We see the message "Ignoring message because either the layer has already unregistered or the layer is out of sync" just after we did "Unregistered layer X".

This situation is normal - we had enough Notify so we terminated, and we keep on getting Notify messages - but the log (in general) indicates that something is wrong.

We should check if the message is for the last unregistered layer, and if so have a different log that indicates a happy flow, e.g.: "ignoring message since Hare just terminated".

**Comment by barakshani** [comment]
@gavraz please review

**Comment by gavraz** [comment]
#1747
