### ISSUE TITLE
Possible spam attack using old block id

### ISSUE THREAD

**Issue by gavraz** [spacemeshos/go-spacemesh#1183]
if _, err := bl.GetBlock(blk.Id); err == nil {
		bl.Info("we already know this block %v ", blk.ID())
		return true
	}

The function HandleNewBlock returns true for known blocks which causes the block to be propagated.
An attacker can set an old block id (which he knows we have) and then send his spam block, causing the network to propagate a spam block.

We should probably calculate the block id from the block's data.
In addition, @see issue #1182

**Comment by almogdepaz** [comment]
whats the difference from #1182  ?

**Comment by gavraz** [comment]
The point is that regardless of how we treat #1182 , we need to use a hash on the block data as its id.
Of course that If we would have decided to propagate them anyway it would lead to the issue described here.
