### ISSUE TITLE
sync requests all blocks from neighbors if one block is missing

### ISSUE THREAD

**Issue by y0sher** [spacemeshos/go-spacemesh#1189]
# Overview / Motivation

Inside `Synchronise` we try to get the current layer from the database, if any block from the layer hashes is missing in the database, we request the whole layer from our neighbors. (we might ask for the whole layer even if we miss one block)

# The Task

# Implementation Notes

maybe `GetLayer` should return id list for the missing blocks ?

# Contribution Guidelines
Important: Issue assignment to developers will be by the order of their application and proficiency level according to the tasks complexity. We will not assign tasks to developers who have'nt introduced themselves on our Gitter [dev channel](https://gitter.im/spacemesh-os/Lobby)

1. Introduce yourself on go-spacemesh [dev chat channel](https://gitter.im/spacemesh-os/Lobby) - ask our team any question you may have about this task
2. Fork branch `develop` to your own repo and work in your repo
3. You must document all methods, enums and types with [godoc comments](https://blog.golang.org/godoc-documenting-go-code)
4. You must write go unit tests for all types and methods when submitting a component, and integration tests if you submit a feature
5. When ready for code review, submit a PR from your repo back to branch `develop`
6. Attach relevant issue to PR

**Comment by almogdepaz** [comment]
correct me if im wrong but we only fetch all of the block ids since we look in the db/pool before each block request
