### ISSUE TITLE
known blocks don't get processed by tortoise

### ISSUE THREAD

**Issue by y0sher** [spacemeshos/go-spacemesh#1190]
# Overview / Motivation

when running `getLayerFromNeighbors` we return a block slice, we don't add the block to the slice if `AddBlockWithTxs` failed, even if it was failed because of the block was already in the db. which means tortoise will miss that block and panic.

# The Task
we need to catch the "already exists in database" error gotten by GetFullBlocks
and add the block tho blockArr (the layer we are going to process) before continuing to the next block 

# Implementation Notes
TODO: Add links to relevant resources, specs, related issues, etc...

# Contribution Guidelines
Important: Issue assignment to developers will be by the order of their application and proficiency level according to the tasks complexity. We will not assign tasks to developers who have'nt introduced themselves on our Gitter [dev channel](https://gitter.im/spacemesh-os/Lobby)

1. Introduce yourself on go-spacemesh [dev chat channel](https://gitter.im/spacemesh-os/Lobby) - ask our team any question you may have about this task
2. Fork branch `develop` to your own repo and work in your repo
3. You must document all methods, enums and types with [godoc comments](https://blog.golang.org/godoc-documenting-go-code)
4. You must write go unit tests for all types and methods when submitting a component, and integration tests if you submit a feature
5. When ready for code review, submit a PR from your repo back to branch `develop`
6. Attach relevant issue to PR

**Comment by almogdepaz** [comment]
already exists error is now handled, late block handling will be add in #1284
