### ISSUE TITLE
tortoise concurrent access 

### ISSUE THREAD

**Issue by almogdepaz** [spacemeshos/go-spacemesh#1194]
# Overview / Motivation
it seem from the log that somehow we  ran 2 concurrent calls to tortoise 
we should investigate how that happened and avoid it 
tortoise is not thread safe!

# The Task
TODO: Clearly describe the issue requirements here...

# Implementation Notes
TODO: Add links to relevant resources, specs, related issues, etc...
fatal error: concurrent map read and map write

goroutine 2014059 [running]:
runtime.throw(0xe91317, 0x21)
    /usr/local/go/src/runtime/panic.go:608 +0x72 fp=0xc024c10810 sp=0xc024c107e0 pc=0x42e1f2
runtime.mapaccess1_fast64(0xd372a0, 0xc00030c330, 0x49be74e105ba9f57, 0x0)
    /usr/local/go/src/runtime/map_fast64.go:21 +0x195 fp=0xc024c10838 sp=0xc024c10810 pc=0x412a25
github.com/spacemeshos/go-spacemesh/tortoise.(*ninjaTortoise).updateCorrectionVectors.func1(0xc015b9dd40, 0x6ef45d86741b0322, 0xc015b9dd40)
    /go/src/github.com/spacemeshos/go-spacemesh/tortoise/ninja_tortoise.go:245 +0x1a9 fp=0xc024c11a48 sp=0xc024c10838 pc=0xc28749
github.com/spacemeshos/go-spacemesh/mesh.(*MeshDB).ForBlockInView(0xc00026ef00, 0xc00456c840, 0x99, 0xc019d466c0, 0x412c62, 0xde71a0)
    /go/src/github.com/spacemeshos/go-spacemesh/mesh/meshdb.go:146 +0x3c6 fp=0xc024c11b90 sp=0xc024c11a48 pc=0x885d36
github.com/spacemeshos/go-spacemesh/tortoise.(*ninjaTortoise).updateCorrectionVectors(0xc0002980c0, 0xc05345c76b, 0xfb, 0x99)
    /go/src/github.com/spacemeshos/go-spacemesh/tortoise/ninja_tortoise.go:261 +0xe4 fp=0xc024c11bf8 sp=0xc024c11b90 pc=0xc24df4
github.com/spacemeshos/go-spacemesh/tortoise.(*ninjaTortoise).handleIncomingLayer(0xc0002980c0, 0xc00caeace0)
    /go/src/github.com/spacemeshos/go-spacemesh/tortoise/ninja_tortoise.go:550 +0xc64 fp=0xc024c11ee0 sp=0xc024c11bf8 pc=0xc27764
github.com/spacemeshos/go-spacemesh/tortoise.(*Algorithm).HandleIncomingLayer(0xc0001d9350, 0xc00caeace0, 0xc0001a9380, 0xc0001a93a0)
    /go/src/github.com/spacemeshos/go-spacemesh/tortoise/algorithm.go:33 +0x61 fp=0xc024c11f10 sp=0xc024c11ee0 pc=0xc235b1
github.com/spacemeshos/go-spacemesh/mesh.(*Mesh).ValidateLayer(0xc0000e4ea0, 0xc00caeace0)
    /go/src/github.com/spacemeshos/go-spacemesh/mesh/mesh.go:194 +0xea fp=0xc024c11f90 sp=0xc024c11f10 pc=0x880c3a
github.com/spacemeshos/go-spacemesh/sync.(*Syncer).Synchronise.func1(0xc000288b60, 0xc01dc60a28, 0xc008b10000, 0xbb, 0xbb, 0xfc)
    /go/src/github.com/spacemeshos/go-spacemesh/sync/syncer.go:202 +0x79 fp=0xc024c11fb0 sp=0xc024c11f90 pc=0xc18ee9
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc024c11fb8 sp=0xc024c11fb0 pc=0x45df11
created by github.com/spacemeshos/go-spacemesh/sync.(*Syncer).Synchronise
    /go/src/github.com/spacemeshos/go-spacemesh/sync/syncer.go:201 +0xd2

**Comment by gavraz** [comment]
Explanation:
Synchronise calls ValidateLayer in a go routine:
		mu.Lock()
		go func(lyrToValidate types.Layer) {
			s.lValidator.ValidateLayer(&lyrToValidate) //run one at a time
			mu.Unlock()
		}(*lyr)

Assuming ValidateLayer takes time, the Synchronise function can return, the next tick will arrive,  synchronize will be called again and will call to ValidateLayer again so we have two calls running concurrently.
Note that the mutex is local to Synchronise func and hence will not hold the second call to Synchronise from calling ValidateLayer
