### ISSUE TITLE
Fetch server changes (bugs/additional features)

### ISSUE THREAD

**Issue by zalmen** [spacemeshos/go-spacemesh#1196]
***** THIS IS A PLACEHOLDER FOR SEVERAL REQUIREMENTS NEEDED TO BE HANDLED IN THE FETCH SERVER, IT SHOULD BE BROKEN DOWN TO SEVERAL ISSUES/BUGS****

1. System-wide, at any point in time, we shouldn't handle the same request more than once (no two pending request for the same data). 
2. If we get a request that was already successfully handled, we should return the reply immediately. 
3. Every response should be validated that it matches the request
4. (Might not be relevant) if the target peer has a partial answer it should return it and the requester should move to the next neighbor and request only what is missing.

**Comment by almogdepaz** [comment]
5. should allow managing peers by state
not syncing with outdated peers, blacklisting etc...

**Comment by almogdepaz** [comment]
@zalmen i think we should consider the tradeoff between passing redundant data on sync and making lots of requests, what  i can say is that sync works slower now that we added more requests to the flow
 of course we pass more data too i know but i think this pingpong where we try to avoid redundant data might be costing us time
