### ISSUE TITLE
Syncer to handle empty response case 

### ISSUE THREAD

**Issue by moshababo** [spacemeshos/go-spacemesh#1199]
# Overview / Motivation
When fetching from a peer layer hash / layer ids / block / txs / atxs / poet, the result might be empty (0 bytes), but this case isn't being checked and so a consecutive operation is failing, mostly the msg deserialization. In case of layer hash there's no deserialization and so the empty response is being assigned and triggers an attempt to fetch the empty layer hash block ids. 

# The Task
Handle the empty response case.
Optional: On the responding side, instead of returning an empty response, return a 4-bytes magic value (something like `0xF0F0F0F0`), to distinguish it from a faulty 0-bytes response.

**Comment by almogdepaz** [comment]
@moshababo 
we have some code duplication there, checking the nil response without doing it in each handler is preferable
