### ISSUE TITLE
Syncer to fetch layer block ids from list of peers per hash

### ISSUE THREAD

**Issue by moshababo** [spacemeshos/go-spacemesh#1200]
# Overview / Motivation
When fetching layer hashes from peers, only the last peer per hash is used to fetch the block ids. This means that the last peer can always block the node from fetching the block ids.

# The Task
Maintain list of peers per hash instead of one peer, and fetch the block ids from the list sequentially until receiving a response which matches the hash.

**Comment by almogdepaz** [comment]
we will run only late blocks separately for now and the kayer
