### ISSUE TITLE
Atx active set size on genesis epoch

### ISSUE THREAD

**Issue by moshababo** [spacemeshos/go-spacemesh#1203]
# Overview / Motivation
When publishing an atx and the target epoch is genesis, the active set size is set to 0.
This isn't the case when doing syntactic validation to the atx, which might expect a different active set size.

# The Task
Apply the same logic for a genesis epoch atx on both sides.

**Comment by noamnelke** [comment]
Not relevant since current genesis flow is temporary.

**Comment by barakshani** [comment]
Shouldn't this be fixed, or at least remain an open issue, until we change the flow?

**Comment by noamnelke** [comment]
Actually, I just checked and this is not true (maybe it was at some point).

The active set size is always calculated from the view, except in publication epoch 0, when the active set size is necessarily 0 (because there's no previous epoch to count in and the view is empty, too).

**Comment by barakshani** [comment]
What isn't true? The issue says that one may try to validate active set of epoch-0 atxs. Since it is possible that miners will publish their epoch-0 atx in epoch-1 (e.g. because they join late, or one of the poet is longer) there may be a mismatch where the atx declare 0 active set, but the view says differently.

**Comment by noamnelke** [comment]
It doesn't matter when the ATX is actually published, miners don't look at the current epoch when validating ATXs, they only look at the ATX's declared publication epoch (`PubLayerIdx`).

Specifically, the following code (hasn't changed from `develop` to the current PR) will prevent a view to be included in an epoch 0 ATX (remember that `pubEpoch` will stay 0 even if the ATX is published late):
```golang
	viewLayer := pubEpoch.FirstLayer(b.layersPerEpoch)
	var view []types.BlockID
	if viewLayer > 0 {
		var err error
		view, err = b.mesh.GetOrphanBlocksBefore(viewLayer)
		if err != nil {
			return fmt.Errorf("failed to get current view for layer %v: %v", viewLayer, err)
		}
	}
```
