### ISSUE TITLE
Research REPL library

### ISSUE THREAD

**Issue by avive** [spacemeshos/go-spacemesh#121]
#### Feature description
Recommend GO REPL library for use in this project.

#### Main Reason for adding this feature

We need to decide which GO REPL library to use for implement the [ Spacemesh REPL](https://github.com/spacemeshos/go-spacemesh/wiki/REPL).

To clarify, we do not need a REPL that allows interactive GO programming but rather a REPL that allows the user to interactively interact with the node using commands we define ourselves (see REPL wiki for more info). REPL may be a misleading name - perhaps an interactive shell app is more appropriate as most GO REPLs are designed to parse GOlang source code.

##### Evaluation criteria

1. Must be open source with MIT license
2. Flexibility and robustness (color, command completion, etc...)
3. Number of serious open issues that are not being fixed quickly. e.g. more than few weeks old. 
4. Major other GO apps that use the library
5. Number of library dependencies
6. Library binary size - the smaller the better
7. Users sentiment about the library - github comments, blog posts, etc...
8. Experience using it in another project.
9. Experiment and build a simple GO app with a REPL using the library - the best way to evaluate a library is to try to build something simple with it.
10. Documentation - are the maintainer helpful to use questions in issues? Is the library well documented?

**Comment by avive** [comment]
GO repl lib: https://github.com/motemen/gore

**Comment by y0sher** [comment]
Some candidates :
[go-prompt](https://github.com/c-bata/go-prompt)
[gosh](https://github.com/vladimirvivien/gosh)

**Comment by y0sher** [comment]
[go-prompt](https://github.com/c-bata/go-prompt)
seems like a good candidate for us, it has a lot of flexibility and nice auto completion features.
