### ISSUE TITLE
Implement REPL account commands

### ISSUE THREAD

**Issue by avive** [spacemeshos/go-spacemesh#122]
#### Feature description
Implement the account related commands in the Spacemesh REPL

#### Main Reason for adding this feature
Part of the core node functionality and the first time user experience.

Please go over the account related commands speced here: https://github.com/spacemeshos/go-spacemesh/wiki/REPL

Depends on #121

**Comment by avive** [comment]
The REPL / SMConsole should be started on node start. On first run it will guide the first time user experience defined here. https://github.com/spacemeshos/go-spacemesh/wiki/REPL .

All log entries should go to the app (and/or node) log files. Only error messages and important messages that we want the user to see (such as confirmation of a validation award) should be output to the REPL.

**Comment by lucasalcantara** [comment]
I'd like to work on it if no one is already working.

**Comment by y0sher** [comment]
Great! No one works on it yet!
Please check https://github.com/spacemeshos/go-spacemesh/issues/121 and help us decide on a REPL lib. Or start implementing using one of the candidates on the issue.

**Comment by lucasalcantara** [comment]
@y0sher I will use the go-prompt. I did some research but I think this one is more mature and works fine.

**Comment by y0sher** [comment]
Great so you can start working on it.
Please consider that as @avive has wrote in the REPL spec, the REPL should be one of many frontends the node will have but probably will be the only one that ships with the node itself.
Some features described in the spec might be missing in the node itself, you can still create the REPL frontend with mock functions that will be replaced once the node features will be implemented. 
The REPL should not implement any logic and only rely on services from the node.

have fun and feel free to share thoughts, questions and dilemmas here or on gitter while working on it.

**Comment by lucasalcantara** [comment]
@y0sher I noticed that on the method to create a new node you are returning an interface instead of the concrete type. I'd like to know if I can change it to return the concrete type since is a best practice in Go return the concrete type and I was thinking about to create a new interface in REPL with the commands (create, lock, unlock, etc) and receive it when I am starting the REPL.

**Comment by lucasalcantara** [comment]
@y0sher also another question. Where the variables that you mentioned in the issue #121 are saved? You said to read an ENV to echoing.

**Comment by zalmen** [comment]
From a duplicate issue on the same topic - 

Feature description
Recommend GO REPL library for use in this project.

Main Reason for adding this feature
We need to decide which GO REPL library to use for implement the Spacemesh REPL.

To clarify, we do not need a REPL that allows interactive GO programming but rather a REPL that allows the user to interactively interact with the node using commands we define ourselves (see REPL wiki for more info). REPL may be a misleading name - perhaps an interactive shell app is more appropriate as most GO REPLs are designed to parse GOlang source code.

Evaluation criteria
Must be open source with MIT license
Flexibility and robustness (color, command completion, etc...)
Number of serious open issues that are not being fixed quickly. e.g. more than few weeks old.
Major other GO apps that use the library
Number of library dependencies
Library binary size - the smaller the better
Users sentiment about the library - github comments, blog posts, etc...
Experience using it in another project.
Experiment and build a simple GO app with a REPL using the library - the best way to evaluate a library is to try to build something simple with it.
Documentation - are the maintainer helpful to use questions in issues? Is the library well documented?
