### ISSUE TITLE
Swallowing errors when calculating msg hash for "old messages"

### ISSUE THREAD

**Issue by noamnelke** [spacemeshos/go-spacemesh#1227]
`gossip.calcHash()` swallows all errors instead of returning them. This could result in accidentally treating new messages as old.

**Comment by ransonhobbes** [comment]
Is this the line in question?

https://github.com/spacemeshos/go-spacemesh/blob/3e065d23c30f25925f563f9b0ea6c8923af2db2a/p2p/gossip/protocol.go#L149

If yes, this seems to call directly into `sha256` which doesn't do any error handling. What sort of error is expected here?

**Comment by noamnelke** [comment]
No... The line in question no longer exists, closing.

If you're curious - this was it (`msghash.Write()` could return an error, which was ignored):
https://github.com/spacemeshos/go-spacemesh/blob/6678f4ea2089b8482ab774ac77e90a2025f02826/p2p/gossip/protocol.go#L23-L29
