### ISSUE TITLE
Set appropriate log levels for production/tests.

### ISSUE THREAD

**Issue by y0sher** [spacemeshos/go-spacemesh#124]
#### Expected behavior
We want console's stdout to show only really important informative messages, warnings and errors.
The rest of the message should be considered as Debug messages. written to log file but not shown in console unless running a test or declared as a flag beforehand.

limit the logging lib with `log.SetLevel(logging.INFO)` on either a test or a flag, change console log messages that are not critical for the user to see to `.Debug` instead `Info/Warning`.

#### Actual behavior
All messages are output to the console all the time.

#### Steps to reproduce the actual behavior
run any instance or test of the spacemesh.

**Comment by lucasalcantara** [comment]
is this issue still need to be done? If so I'd like to work on it.

**Comment by y0sher** [comment]
Sure go ahead please. We need to make sure logging is set to debug across the whole project.
save only super critical errors and information as info/error.
please post here if you have any questions.

**Comment by y0sher** [comment]
Now we set all log messages to `Debug` apart from app init messages.
I'm leaving this issue open for now to reference that we need to decide which messages we should present to the user.
