### ISSUE TITLE
Totroise never deletes first 4 layers

### ISSUE THREAD

**Issue by y0sher** [spacemeshos/go-spacemesh#1252]
# Overview / Motivation

`evictOutOfPBase` in `ninja_tortoise.go` evicts entries from the counting and voting maps of the tortoise, we shouldn't delete the entries that are less far away in the past then `hdist`.
though when running `evictOutOfPBase` we only check the the layer itself is smaller than `hdist` and then return. resulting in that (when `hdist=4`) we never delete layers 0-4.

code:
```go
func (ni *ninjaTortoise) evictOutOfPbase() {
	wg := sync.WaitGroup{}
	if ni.pBase.Layer() <= hdist {
		return
	}
```

# The Task

make sure we return only when the layer is within a distance of `hdist` (as `layer - hdist`) and not hdist itself.

# Implementation Notes
TODO: Add links to relevant resources, specs, related issues, etc...

# Contribution Guidelines
Important: Issue assignment to developers will be by the order of their application and proficiency level according to the tasks complexity. We will not assign tasks to developers who have'nt introduced themselves on our Gitter [dev channel](https://gitter.im/spacemesh-os/Lobby)

1. Introduce yourself on go-spacemesh [dev chat channel](https://gitter.im/spacemesh-os/Lobby) - ask our team any question you may have about this task
2. Fork branch `develop` to your own repo and work in your repo
3. You must document all methods, enums and types with [godoc comments](https://blog.golang.org/godoc-documenting-go-code)
4. You must write go unit tests for all types and methods when submitting a component, and integration tests if you submit a feature
5. When ready for code review, submit a PR from your repo back to branch `develop`
6. Attach relevant issue to PR

**Comment by almogdepaz** [comment]
wrong flow description, eviction starts from 0 and continues, the condition you see is to exit in the case where pbase-hdist < 0 so the layers we skipped are collected as soon as the condition is false, no bug.
