### ISSUE TITLE
tortoise deletes from a map concurrently without protecting

### ISSUE THREAD

**Issue by y0sher** [spacemeshos/go-spacemesh#1253]
# Overview / Motivation

on `ninja_tortoise` in `evictOutOfPbase` the code deletes from all the voting maps using a goroutine and a waitgroup. though these maps aren't protected in any way. they aren't supposed to be thread-safe so maybe just delete it serially? 

*NOTE*: this code actually works but I'm not sure why. maybe because they're all deleting a specific key?

# The Task
TODO: Clearly describe the issue requirements here...

# Implementation Notes
TODO: Add links to relevant resources, specs, related issues, etc...

# Contribution Guidelines
Important: Issue assignment to developers will be by the order of their application and proficiency level according to the tasks complexity. We will not assign tasks to developers who have'nt introduced themselves on our Gitter [dev channel](https://gitter.im/spacemesh-os/Lobby)

1. Introduce yourself on go-spacemesh [dev chat channel](https://gitter.im/spacemesh-os/Lobby) - ask our team any question you may have about this task
2. Fork branch `develop` to your own repo and work in your repo
3. You must document all methods, enums and types with [godoc comments](https://blog.golang.org/godoc-documenting-go-code)
4. You must write go unit tests for all types and methods when submitting a component, and integration tests if you submit a feature
5. When ready for code review, submit a PR from your repo back to branch `develop`
6. Attach relevant issue to PR

**Comment by almogdepaz** [comment]
not true, this happens at the end of update tables which is single threaded
evict is blocking so no concurrent access the only issue is tables that are accessed from outside and these tables have independent locks,
if we are on the subject its true that we don't evict from tgood
