### ISSUE TITLE
Change the way we select positioning ATX

### ISSUE THREAD

**Issue by noamnelke** [spacemeshos/go-spacemesh#1257]
We currently pick the ATX with the highest layer ID as a positioning ATX.

Once ticks are implemented, we should change the implementation of `updateTopAtxIfNeeded` to select the ATX with the highest epoch and if two ATXs have the same epoch -- the one with the highest tick count.

**Comment by barakshani** [comment]
what is the rationale?

**Comment by noamnelke** [comment]
answered offline

**Comment by barakshani** [comment]
The current implementation uses _topATX_ as PosATX, even if it is from the previous epoch. We should clarify on what conditions it is desired.

**Comment by moshababo** [comment]
@noamnelke still relevant?
