### ISSUE TITLE
Unify hashing algorithms

### ISSUE THREAD

**Issue by noamnelke** [spacemeshos/go-spacemesh#1275]
Our code uses at least 5 different hashing algorithms (`Sha256`, `Sha3`, `Keccak256`, `Shake128`, `FNV`). We should decide on a hashing algo and replace all the others in the codebase.

Let's use https://github.com/spacemeshos/sha256-simd ?

**Comment by wangyi-fudan** [comment]
Just mention wyhash, which is the fastest high quality conventional hash function.
https://github.com/wangyi-fudan/wyhash

**Comment by avive** [comment]
Blake3 should be considered as well https://github.com/BLAKE3-team/BLAKE3 @YaronWittenstein shared with me some nice benchmarks. @barakshani

**Comment by moshababo** [comment]
@noamnelke still relevant?

**Comment by countvonzero** [comment]
a decision was made in research call on Jan 19, 2023 to use blake3 for hashing. @dshulyak

**Comment by poszu** [comment]
> a decision was made in research call on Jan 19, 2023 to use blake3 for hashing. @dshulyak

@countvonzero would you mind summing up the rationale behind this decision?

**Comment by countvonzero** [comment]
basically we should use whatever hashing algo available thats most secure and fast. blake3 is chosenover blake2b due to higher security.

there were discussion about AVX2 or AVX 512 and it was decided either one would be fine, as upgrade btwn the two is compatible.
