### ISSUE TITLE
Clock synchronization

### ISSUE THREAD

**Issue by noamnelke** [spacemeshos/go-spacemesh#1287]
Our current solution is to verify the time with NTP, with some tolerance (10 seconds) and stop the node if it's above the threshold.

This solution has a few problems:

1. The tolerance is causing some problems in our test runs.
2. When users start running nodes this solution would force the user to keep their machine's clock accurate themselves. This is both cumbersome, and may conflict with the user's desires (what if I like to set my clock to 5 minutes ahead of time?).

There are two solutions that we've discussed, both require wrapping our use of the computer clock with something that can add an adjustment that we maintain:

1. The simpler solution is to measure our delta with NTP and add this delta to the internal clock.
2. The other is to measure the delta from our peers and take the median (bitcoin's solution).

I believe that, at least the first option, should be implemented before TN1.0 to prevent user friction and some issues arising from misaligned node clocks.

cc: @y0sher

**Comment by y0sher** [comment]
I agree with the last statement, though this should be tested thoroughly before releasing. until then maybe we can tighten the drift tolerance for our tests. (for real users one of the above given solutions is probably a must)

**Comment by barakshani** [comment]
see also https://github.com/spacemeshos/go-spacemesh/issues/1676

**Comment by avive** [comment]
Guys - is this really an important issue considering other bugs? I think that It is fair to assume that 90%+ of desktop users have clocks that auto sync with an ntp server such as msft and apple time servers. I think it is the default in win 10 pro and os x. It is hard to see how more than 10% of advanced users have sync off. It is really not too much to ask testnet smeshers to make sure their clocks are synced on the os level.

**Comment by avive** [comment]
fyi, I just installed win 10 pro and by default it is ntp synced w time.windows.com. 80% of users never change the defaults. I'm pretty sure it is like this in 10 home as well. However, I understand this is a problem with managed nodes that needs to be addressed.

**Comment by noamnelke** [comment]
@avive I don't understand your prioritization comment. This is not for `TN-F&F`, it's for `TN-1.0`.

I couldn't find anything definite, but found some indication that clocks could drift by up to 5 minutes without [special configuration](https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/configuring-systems-for-high-accuracy?tabs=MinPollInterval).

Also, while this is an edge-case, I see no reason to force users to keep their clocks sync'ed when it can [relatively] easily be fixed.

**Comment by avive** [comment]
ok - makes sense.

**Comment by moshababo** [comment]
@noamnelke still relevant?
