### ISSUE TITLE
Switch from urfave/cli to cobra

### ISSUE THREAD

**Issue by y0sher** [spacemeshos/go-spacemesh#129]
#### Feature description
 switch using [urfave/cli](https://github.com/urfave/cli) to [cobra](https://github.com/spf13/cobra).
It seems that by repo statics they're quite the same though cobra has some really nice projects using it.

Verify that Cobra supports these cli features that we need

- flags
- bind flags to variables ( default values )
- commands
- help 
- autocomplete 
- config file parsing (toml/yaml or other)

#### Main Reason for adding this feature
Some bugs with urfave/cli (loading config files), flexibility offered by cobra seems to attract great noticeable projects.

**Comment by avive** [comment]
Might make sense to use https://github.com/spf13/viper for config if we move to Cobra. Looks like Cobra supports all the features we need.

**Comment by eariassoto** [comment]
I can take this issue

**Comment by avive** [comment]
> I can take this issue
Great. The idea is to re-implement all existing CLI functionality using Cobra and Viper - we have already implemented quite a lot so please refer to the existing code.

> I suppose you want the config file to load the version, commit and branch variables. Is that correct?
No - we'd like these to be injected by make into the packaged binary - so these vars are really consts set at build-time - it should work today.

Are you on our dev talk Gitter channel? Please join us here https://gitter.im/spacemesh-os/Lobby

**Comment by avive** [comment]
Switch to viper for config files handlking as we move to cobra.

**Comment by samparsky** [comment]
@eariassoto What's the progress on this?

**Comment by avive** [comment]
@samparsky - nice of you to ask but I think @eariassoto didn't even start - we didn't hear from him for a while on this issue - let's give him one more day to respond JIC he started to work on this issue and otherwise you can go ahead and start. thanks!

**Comment by samparsky** [comment]
I have started work on this

**Comment by eariassoto** [comment]
Hi,
Sorry I didn't reply. I started with the change but got stuck with what to put in the config files. Better if someone else familiarized with how the CLI handles the configuration makes the change.

**Comment by samparsky** [comment]
@y0sher  @avive Going through the current implementation, I think the config package should be restructured and broken down. Currently it contains the app config and command line flags which is a bit confusing I think. 
 ----- 
My suggestion the command flags [(Flags)](https://github.com/spacemeshos/go-spacemesh/blob/master/app/config/flags.go) should be moved into a cmd package and the app config should be in a config package.

**Comment by y0sher** [comment]
Currently, config is all over the source code, some of it in `app/config`
and some of it under `p2p/nodeconfig` the last one in under `api/config`.
Any config value can be determined or by default value hardcoded, by config
file or with a command line flag.

I agree this should reconstructed, the file structue inside these folders
mentioned above is derived from examples we saw about `urfave/cli` , we
want to move to `cobra` to get a lighter and easier to understand
structure.

So go ahead and rearrange it (cmd folder sounds good and idiomatic go
structure).
Feel free to discuss/ask questions about the flags ,commands or anything
else.

Good job starting it, please don't hesitate to ping any of us if something
that we can help puts this on hold ( or just to talk in general :) .

**Comment by kanishkatn** [comment]
I am familiar with Cobra. I would love to help. Let me know ...

**Comment by y0sher** [comment]
Good job @samparsky !
