### ISSUE TITLE
p2p automation gossip tests should use message hashes

### ISSUE THREAD

**Issue by y0sher** [spacemeshos/go-spacemesh#1293]
# Overview / Motivation

We have the hash of the message printed on each `new_gossip_message` entry, we can use this hash to track down the relevant test messages instead of counting the initial number of messages and comparing which sometimes fails due to the slowness of indexing at elastic.

# The Task

this should include python code that can generate the message hashes generated at the node and look for the results in the logs.

# Implementation Notes
TODO: Add links to relevant resources, specs, related issues, etc...

# Contribution Guidelines
Important: Issue assignment to developers will be by the order of their application and proficiency level according to the tasks complexity. We will not assign tasks to developers who have'nt introduced themselves on our Gitter [dev channel](https://gitter.im/spacemesh-os/Lobby)

1. Introduce yourself on go-spacemesh [dev chat channel](https://gitter.im/spacemesh-os/Lobby) - ask our team any question you may have about this task
2. Fork branch `develop` to your own repo and work in your repo
3. You must document all methods, enums and types with [godoc comments](https://blog.golang.org/godoc-documenting-go-code)
4. You must write go unit tests for all types and methods when submitting a component, and integration tests if you submit a feature
5. When ready for code review, submit a PR from your repo back to branch `develop`
6. Attach relevant issue to PR

**Comment by lrettig** [comment]
I suspect this is no longer relevant given the new test/logs infrastructure - @y0sher could you confirm? Thanks

**Comment by y0sher** [comment]
If we're not using logs I assume it's not relevant. Though if we're rewriting tests to use APIs and keeping this test, I rather it'll use hashes like mentioned in the issue and not quantity.

**Comment by lrettig** [comment]
Cool, will let @AmitShaul and @sudachen figure it out. Thanks!
