### ISSUE TITLE
Nodes does not behave the same in hare eligibility under genesis flow

### ISSUE THREAD

**Issue by gavraz** [spacemeshos/go-spacemesh#1299]
The function validateRole in MessageValidation doesn't take the safe layer into consideration.
It checks IsGenesis on the layer gets false and then fails to GetIdentity even though the safe layer is in genesis.

Solutions:
1. Either insert GetIdentity to oracle.Eligible method
2. Or check IsGenesis also for the safe layer

**Comment by countvonzero** [comment]
not sure which codepath is being referred to.

> The function validateRole in MessageValidation doesn't take the safe layer into consideration.

this doesn't sound true.

validateRole in MessageValidation currently uses this function
https://github.com/spacemeshos/go-spacemesh/blob/e8951dc1476a37e90a3b89e589c7b66537a142e5/hare/eligibility/oracle.go#L297

which does take safe layer into consideration. all the calculation of safe layers ins done in `actives()`, which is definitely invoked (twice) when validating a role.
