### ISSUE TITLE
Finish node discovery features

### ISSUE THREAD

**Issue by avive** [spacemeshos/go-spacemesh#13]
- Comprehensive tests for the dht/kad protocol and swarm nodes discovery.
- Test connection to 5 random node on startup using bootstrap node

**Comment by samparsky** [comment]
@avive @y0sher I would like to jump on this, can what are the test scenarios?

**Comment by y0sher** [comment]
Kademlia bootstapping and node discovery is now implemented. 
now we have an hard limit about how much nodes we must have connected to have it `bootstrapped` what we really want is putting this limit only on filling the routing table. and letting the node run even with one node connected while in background trying to acquire more connections.

**Comment by y0sher** [comment]
this will be continued in #339
