### ISSUE TITLE
Hare broker does not handle more than one CP

### ISSUE THREAD

**Issue by barakshani** [spacemeshos/go-spacemesh#1304]
When one consensus process is running, and a new consensus process starts, the broker ignores messages that belong to the previous CP: "message does not belong to this round and is not an early msg".

**Comment by gavraz** [comment]
Update: to my understanding, this issue is not caused by a bug in the broker but by a bug in message validation.
Messages from "future" iterations are not passing validation.
#1326 fixes this bug.
