### ISSUE TITLE
Replace inhouse 'assert' with 'testify'

### ISSUE THREAD

**Issue by y0sher** [spacemeshos/go-spacemesh#131]
[testify](https://github.com/stretchr/testify) is a widely used testing set of packages that exposes an API similar to what we have at `assert` and more. 

I think we shouldn't maintain our own assertion lib as long we don't have any special testing needs.  

to complete this issue - 
- Remove assert package from go-spacemesh
- import add `testify` to our vendor list.
- replace usages by assert across our testing files if needed.

**Comment by samparsky** [comment]
@y0sher Interested on working on this

**Comment by y0sher** [comment]
Okay, should be quite straight forward. @samparsky

**Comment by y0sher** [comment]
Done in #140 by @samparsky
