### ISSUE TITLE
eligibility beacon should use a confidence param bigger than hdist

### ISSUE THREAD

**Issue by almogdepaz** [spacemeshos/go-spacemesh#1311]
# Overview / Motivation
hdist basically defines the the amount of layers that pbase can get stuck before self healing
we should make sure the confidence param is bigger than hdist to avoid fatal errors

# The Task
maybe its better to use hdist+1 as the confidence

**Comment by barakshani** [comment]
confidence parameter should be about the size of the tortoise window, as written in https://github.com/spacemeshos/go-spacemesh/issues/1056

**Comment by lrettig** [comment]
Will handle as part of work on self-healing
