### ISSUE TITLE
fetchLayerBlockIds should return a map if possible

### ISSUE THREAD

**Issue by gavraz** [spacemeshos/go-spacemesh#1369]
fetchLayerBlockIds(m map[string]p2p.Peer, lyr types.LayerID) ([]types.BlockID, error)
Returns a slice. It is possible that we can simply return a map.
We should check the usage of fetchLayerBlockIds and prefer a map over a slice if possible.

**Comment by almogdepaz** [comment]
no need for this, code base has changed to fit the slice return value
