### ISSUE TITLE
Config bugs filesystem, solution: Pass config structs instead of using hardcoded values

### ISSUE THREAD

**Issue by y0sher** [spacemeshos/go-spacemesh#138]
#### Expected behavior

Every constructor that requires config information will receive a config struct by parameter.

Edit: Labeled as a bug because it messes up filesystem location in tests.
We've setup `filesystem` helpers that should help create a dedicated folders for tests and be removed afterwards, though the use of a global config messes this up. we resulted in limiting parallel testing to make this have less impact on us while developing. Making filesystem work for a specific configuration will probably solve it. 

#### Actual behavior

In some places like `p2p`and `api` we use hardcoded values from `ConfigValues` initialized structs.

We moved to using `cobra` in https://github.com/spacemeshos/go-spacemesh/pull/135 , this is what's left to make CLI and config loading more tied to good practices.

**Comment by kanishkatn** [comment]
Hi,

I would love to pick this up.

**Comment by y0sher** [comment]
this was done already mostly other than some small p2p files and the ntp code. though there is still some minor work. @kanishkatn , sorry if this fell between the chairs. your more than welcome to try this now or some other issue.
