### ISSUE TITLE
NodeId.Key should be of type PublicKey

### ISSUE THREAD

**Issue by gavraz** [spacemeshos/go-spacemesh#1391]
NodeId.Key holds PublicKey.String()
PublicKey.String() returns BytesToHex - which means it is not the real public key
That could cause bugs if validation will be attempted with this "public key"

Moreover, NodeId.Key should be of type PublicKey and not just a string. That will help us avoid such issues.

**Comment by lrettig** [comment]
closing in favor of #2269
