### ISSUE TITLE
Syntactic validation of blocks relies on context

### ISSUE THREAD

**Issue by gavraz** [spacemeshos/go-spacemesh#1392]
Syntactic validation of blocks checks in the DB if the atx exist. That could change between nodes depending on their context and hence the validation result may change between nodes.

We should discuss how we want to fix this issue.

@noamnelke - I briefly described it since we will need to thoroughly discuss this issue prior to implementation. Anyway, if you have something to add - feel free.

**Comment by antonlerner** [comment]
nodes do not start receiving gossip blocks before they are fully synced with all atxs of peers
