### ISSUE TITLE
actives func in Hare oracle is not concurrency-safe

### ISSUE THREAD

**Issue by gavraz** [spacemeshos/go-spacemesh#1395]
Generally, actives function is not concurrency-safe.
In the node's flow it is possible that we enter actives from multiple distinct flows concurrently.
It is not handled by any lock but we should further investigate the implication and decide what we want to do.
I feel that even if there are no implications of high significance we should use a lock.

**Comment by jonZlotnik** [comment]
https://github.com/spacemeshos/go-spacemesh/blob/0cb3732b0796ed442366f39ef8cf3909a0c2b48d/hare/eligibility/oracle.go#L416-L425

Seems to have already been solved?
I propose we close this issue and create a new issue if a performance bottleneck ever reveals itself.

**Comment by jonZlotnik** [comment]
Granted, this `lock` should probably be separated into a `vrfMsgLock` and `activesLock`
