### ISSUE TITLE
Block votes on a layer with no Hare results

### ISSUE THREAD

**Issue by barakshani** [spacemeshos/go-spacemesh#1428]
If an instance of the Hare protocol never finishes, all (future) blocks would be abstain about their validity. We need, at some point, to formulate an opinion about such blocks.

One why if doing so, is to explicitly vote about these block after hdist layers - if the Hare protocol does not terminate within hdist-1 layers, when we generate blocks in the next layer (after hdist layers) we explicitly vote about them according to some predetermined rule.

See also: https://github.com/spacemeshos/go-spacemesh/issues/1427

**Comment by almogdepaz** [comment]
@barakshani can we close ?
