### ISSUE TITLE
Update new cli and config setup in Wiki.

### ISSUE THREAD

**Issue by y0sher** [spacemeshos/go-spacemesh#145]
We changed a to a new cli setup and config in https://github.com/spacemeshos/go-spacemesh/pull/135 by @samparsky.

current wiki page we have about config - https://github.com/spacemeshos/go-spacemesh/wiki/config

We need to update the wiki corresponding to the new changes. 
it will be great if @samparsky can take it or anyone else that is familiar with `cobra` and `viper`.

**Comment by y0sher** [comment]
generally, the help page should be enough. but it'll be nice if we provide some examples. though most parameters will be pre-configured in releases.

**Comment by moshababo** [comment]
Obsolete.
