### ISSUE TITLE
Active set size calculation is too slow

### ISSUE THREAD

**Issue by gavraz** [spacemeshos/go-spacemesh#1468]
Active set size calculation takes about 30 seconds.
The 30s have been witnessed on a 7-layer epoch automation test. The calculation was initiated by the Hare eligibility oracle.
It is too long and we are still not sure what is the cause for the long calculation. It doesn't seem likely at all, especially not for a 7-layer epoch.
We should:
1. Investigate the cause for the long calculation - maybe with a DB snapshot?
2. Consider what is the impact of the slow calculation (Hare, Blocks)
3. Think of a solution.

Please note that this issue had a bigger impact before we fixed
1. Double calculation of active set size in hare eligibility.
2. no optimization for calculating active set size beforehand.

**Comment by antonlerner** [comment]
We've found that cache size for atxs was 20, will change to 600, this would take roughly 50mb in memory since we store the entire atx in cache. to resolve this we should perform some more optimisations on how we store and fetch atxs. @almogdepaz , @gavraz please share related issues here as well if there are any.

**Comment by gavraz** [comment]
Partially related - the separation of atx header should reduce the size of the atx in the memory (also in the cache).

**Comment by gavraz** [comment]
@antonlerner - who owns this issue?
@barakshani - what is the status of this issue? How long does it take to calc?
@noamnelke - ATX header separation is merged?

**Comment by barakshani** [comment]
on normal behavior it is about 50-150ms. I see few seconds from time to time. Don't know yet why.

**Comment by antonlerner** [comment]
> on normal behavior it is about 50-150ms. I see few seconds from time to time. Don't know yet why.

I'm closing this issue since we've already introduced 2 optimisations that seem to work. if issue persists we'll re open and investigate
