### ISSUE TITLE
Write a design document describing DHT and node discovery

### ISSUE THREAD

**Issue by zalmen** [spacemeshos/go-spacemesh#147]
Write a design documents describing the architecture of the DHT module and node discovery flows. The doc should include the following:
- HL modules (packages) structures with exported api for each module.
- Modules dependencies graph.
- Code flows for common use cases

Done criteria-
- Document is approved and published on the project's wiki
- Add issues for all known issues under #146

**Comment by y0sher** [comment]
Done
