### ISSUE TITLE
Hare pre round start time

### ISSUE THREAD

**Issue by antonlerner** [spacemeshos/go-spacemesh#1477]
Hare pre-round round is dependent on the call to eligibility (IsEligibile may be blocking).
There is an optimization that makes the call to IsEligible beforehand. It is still, conceptually possible that the pre-round round will be delayed because of this blocking behavior. We should check and send the pre-round message in a goroutine and allow the func to continue.

In addition, according to @barakshani , the mentioned optimization might be problematic since it happens while blocks are arriving (during "hare delay").
We should also make this optimization even before the hare delay so it won't collide with other work of the node.

**Comment by gavraz** [comment]
@barakshani please add your input to the second point about the optimization.

**Comment by gavraz** [comment]
Was fixed in:
Hare no termination (#1480)
* Vote to layer, refactored getVotes
* Added concurrent limit and iterations limit to hare config
* Switched back GetResult to receive single param
* Impl non-consensus termination
* Wait for one more epoch in late nodes test
