### ISSUE TITLE
Implement Dolev-Strong's byzantine agreement protocol

### ISSUE THREAD

**Issue by zalmen** [spacemeshos/go-spacemesh#149]
A byzantine agreement is an agreement achieved among multiple nodes with the following results:
1. Agreement- All honest nodes agree on the same value.
2. Validity- If the sender is honest, then all honest nodes will agree on its value. 

Dolev-Strong (DS) in a synchronous byzantine agreement that can handle up to n-2 faulty nodes. DS has rather high round complexity (number of faulty processors plus one) and therefore the main purpose of this epic is to implement DS in order to benchmark it and validate that it complies with our spec.

In the Spacemesh protocol DS is a suggested algorithm used for reaching agreement among all honest nodes regarding *who* are the nodes participating in recent layers, this agreement is also called "semi-permissioned" committee-selection (SPCS). The basic idea is that every node that created a block in that layer, upon receiving M blocks in that layer, will create M instances of DS as a receiver and one instance as a sender. It is possible that the node will receive messages on unknown instances (in case the node never received the block that was created by the instance's sender), in such case the node will ad-hoc create a DS instance and participate in that instance as instructed by DS. At the end the node will merge all outputs from all DS instances.

References -
Dolev-Strong's original paper -
https://github.com/spacemeshos/go-spacemesh/raw/develop/research/DS-byzantine%20agreement.pdf
Dolev-Strong recommended variant by Kumaresan -
https://github.com/spacemeshos/go-spacemesh/raw/develop/research/DS%20by%20Kumaresan.pdf

Done Criteria -
- A design document describing the protocol that was implemented and the implementation architecture.
- A tested implementation of DS protocol ready for benchmarking

**Comment by CSNoyes** [comment]
Is this being implemented as an alternative to Mostefaoui et al.'s  “Signature-free asynchronous binary byzantine consensus with t < n/3, O(n^2) messages, and O(1) expected time" referenced in "Tortoise and Hares Consensus?"?
