### ISSUE TITLE
PoET does not include all miners in the membership proof

### ISSUE THREAD

**Issue by barakshani** [spacemeshos/go-spacemesh#1492]
Nodes register to the PoET, they print:
challenge submitted to PoET proving service (PoET id: f2faab4ce2abd0cdfb35e029f2a4c3bd1f4117ac48b1f9e8db0044c038a4b94a, round id: 8788)

Later they get the PoET proof, but are not included in it:
cannot create atx in epoch 2: cannot create Nipst: not a member of this round (poetId: f2faab4ce2abd0cdfb35e029f2a4c3bd1f4117ac48b1f9e8db0044c038a4b94a, roundId: 8788)

In addition, if this happens, the miner should remove this NIPST immediately, instead of try again next layer (and outputting the same error)

**Comment by moshababo** [comment]
Closing this although the bug was not found. If it happens again, please reopen.
