### ISSUE TITLE
peers get stuck replying to peer requests on long running networks

### ISSUE THREAD

**Issue by almogdepaz** [spacemeshos/go-spacemesh#1517]
# Overview / Motivation
in a long running network it seems that a new miner causes strange behavior  to connected peers 

# The Task
Fix 

# Implementation Notes
TODO: Add links to relevant resources, specs, related issues, etc...

# Contribution Guidelines
Important: Issue assignment to developers will be by the order of their application and proficiency level according to the tasks complexity. We will not assign tasks to developers who haven't introduced themselves on our Gitter [dev channel](https://gitter.im/spacemesh-os/Lobby)

1. Introduce yourself on go-spacemesh [dev chat channel](https://gitter.im/spacemesh-os/Lobby) - ask our team any question you may have about this task
2. Fork branch `develop` to your own repo and work in your repo
3. You must document all methods, enums and types with [godoc comments](https://blog.golang.org/godoc-documenting-go-code)
4. You must write go unit tests for all types and methods when submitting a component, and integration tests if you submit a feature
5. When ready for code review, submit a PR from your repo back to branch `develop`
6. Attach relevant issue to PR

**Comment by almogdepaz** [comment]
@barakshani @y0sher we can add the info about this here

**Comment by almogdepaz** [comment]
[logs.txt.zip](https://github.com/spacemeshos/go-spacemesh/files/4015806/logs.txt.zip)
the bug is in the release tick between layer 155 and 156 in the logs (notice the log times)

**Comment by barakshani** [comment]
@almogdepaz you meant to reference the log file to issue https://github.com/spacemeshos/go-spacemesh/issues/1654, right?

**Comment by avive** [comment]
@barakshani plz add more info

**Comment by barakshani** [comment]
Miners that we get synced from also send messages over gossip (hare messages, blocks, atxs; in addition they relay messages, but we don't keep track of that at the moment). When we get synced from our peers, we cause them - sometimes - to send gossip messages late/ with delay. They write in the logs that they send the message on time (if it is a block or an atx we see that they also get their message on time) but the rest of the network starts getting the message with a delay that varies from several seconds to minutes.
This behaviour even happens about 10-20 minutes after the sync process has finished.

**Comment by almogdepaz** [comment]
this was mitigated by randomly choosing peers to sync with, still didn't get to the bottom of this since its very hard reproducing.

**Comment by lrettig** [comment]
possibly related: #1868
