### ISSUE TITLE
instrument and trace performance critical tasks

### ISSUE THREAD

**Issue by y0sher** [spacemeshos/go-spacemesh#1518]
# Overview / Motivation

The Spacemesh protocol by itself is quite complicated with multiple systems running concurrently. the `go-spacemesh` implementation is quite similar,  multiple mission-critical (for protocol health) tasks are running at the same time, heavier instrumentation and trace will help us identify bottlenecks and areas that might be potentially leaking or affecting protocol performance. 

# The Task

## Design
* Identify critical points to measure. 
    * critical metrics to be exported 
    * decide on critical functions to measure
* Decide on tracing/metric exporting method.
* Choose the visualization or consuming method for different metrics and measures.

## Implement 
  * Measure the list of metrics[from design ] with Prometheus(?)
  * Measure the list of functions [ from design ] with go execution tracer or opentracing.
  * Create infrastructure to collect and visualize/consume all metrics/measurements. 

# Implementation Notes
TODO: Add links to relevant resources, specs, related issues, etc...

# Contribution Guidelines
Important: Issue assignment to developers will be by the order of their application and proficiency level according to the tasks complexity. We will not assign tasks to developers who haven't introduced themselves on our Gitter [dev channel](https://gitter.im/spacemesh-os/Lobby)

1. Introduce yourself on go-spacemesh [dev chat channel](https://gitter.im/spacemesh-os/Lobby) - ask our team any question you may have about this task
2. Fork branch `develop` to your own repo and work in your repo
3. You must document all methods, enums and types with [godoc comments](https://blog.golang.org/godoc-documenting-go-code)
4. You must write go unit tests for all types and methods when submitting a component, and integration tests if you submit a feature
5. When ready for code review, submit a PR from your repo back to branch `develop`
6. Attach relevant issue to PR

**Comment by y0sher** [comment]
## Design
* Identify critical points to measure. 
    * critical metrics to be exported 
    * decide on critical functions to measure

### Critical Points to measure 
 * time consumption of P2P message pipe.
 * traversing active set size, performing signature validations
 * think about: (store time to db, sync requests, responses)
 * TODO: insert more

### Decide on tracing/metric exporting method.
   * Trace with go tracer. (todo: maybe through opencensus opentracing)
   * export metrics with prometheus (todo: maybe through expvar ? )

### Choose the visualization or consuming method for different metrics and measures.
  * Currently we show metrics and logs analysis using Grafana. (which consumes metrics on prometheus server and elasticsearch server)
  * TODO: trace collection and visualization

**Comment by gavraz** [comment]
What about the max number of hops in p2p?
Size of channels (buffers) in p2p?
All we talked about a few days ago should be written here right?

We also need an easy way to record messages and build a db from these messages or any tool that will help us build UT that uses real data (preferably generated and up to date data).

**Comment by y0sher** [comment]
yes we can start expanding here and move to a wiki later.  I'll add what we talked about soon. 
about your second point, do you mean for all messages? like record a whole network content and replay with mocked time or something ?
if you comment more ideas about instrumentation methods or specific modules critical sections I'll add it up to a bigger doc.

**Comment by gavraz** [comment]
Recording data is one solution. The goal is to have data generated for UT (and on-demand for specific new cases we want to look into). We should think about it more, I know one sentence is not enough to describe it.

**Comment by y0sher** [comment]
Note: please let's differentiate implemented metrics and metrics that we're thinking its worth collecting. I encourage everyone to post both of them in (different formats) and I'll try to compile everything eventually.
# P2P 

## existing metrics 
`spacemesh_p2p_peers` { type = (outbound|inbound) }  total connected peers
`spacemesh_p2p_peer_recieve_bytes` { peer = publickey } total bytes read ( by peer) 
`spacemesh_p2p_peer_send_bytes` { peer = publickey } total bytes read ( by peer)
`spacemesh_p2p_total_gossip_messages` { protocol = protocol_name, type = (old|new) } total gossip messages recieved
`spacemesh_p2p_addrbook_size` - number of peers in discovery addrbook

## needed metrics and notes
- Monitor protocol queues in p2p.
- think about more gossip metrics
- monitor the time a message spends in different places in p2p

**Comment by almogdepaz** [comment]
### Tortoise
### existing metrics

- 	pbaseCount    
- 	processedCount
- 	blockVotes     
- 	validBlocks    
- 	invalidBlocks 

### needed metrics and notes

-    time to run handleLayer

**Comment by almogdepaz** [comment]
### Sync

### existing metrics
  
### needed metrics and notes

- mesure time to fetch avg block request
- mesure time to fetch avg tx batch
- mesure time to fetch avg atx batch
- mesure time to validate and store  avg block
- mesure time to validate and store avg tx
- mesure time to validate and store avg atx

**Comment by lrettig** [comment]
Is this distinct from telemetry? (#1964) CC @avive

**Comment by lrettig** [comment]
Closing in favor of #1964
