### ISSUE TITLE
Sending multiple transaction with consecutive nonce fails

### ISSUE THREAD

**Issue by antonlerner** [spacemeshos/go-spacemesh#1525]
# Overview / Motivation
When we try to run a test and send multiple transactions with running nonce, somehow, in the app_test, the last transaction with nonce 24 is received first by the node causing the new tests to fail.

This only happens in travis, @y0sher , maybe it is related to how the network is implemented in the app_test? can you think of another reason?

@noamnelke , do you think we should allow incorrect nonce to wait in the tx pool?

# The Task
TODO: Clearly describe the issue requirements here...

# Implementation Notes
TODO: Add links to relevant resources, specs, related issues, etc...

# Contribution Guidelines
Important: Issue assignment to developers will be by the order of their application and proficiency level according to the tasks complexity. We will not assign tasks to developers who haven't introduced themselves on our Gitter [dev channel](https://gitter.im/spacemesh-os/Lobby)

1. Introduce yourself on go-spacemesh [dev chat channel](https://gitter.im/spacemesh-os/Lobby) - ask our team any question you may have about this task
2. Fork branch `develop` to your own repo and work in your repo
3. You must document all methods, enums and types with [godoc comments](https://blog.golang.org/godoc-documenting-go-code)
4. You must write go unit tests for all types and methods when submitting a component, and integration tests if you submit a feature
5. When ready for code review, submit a PR from your repo back to branch `develop`
6. Attach relevant issue to PR

**Comment by noamnelke** [comment]
Interesting... We originally decided that we wouldn't allow it for simplicity reasons.

I assume that humans making transactions won't encounter this issue, as they will probably be slower than network propagation. However, when scripts create transactions (e.g. withdrawals from an exchange) this can definitely happen and it's not great at all.

Since I really want to re-think the way transaction processing happens, I think it's best to not invest time in fixing this issue, but I'm open to discuss it, if you disagree.

The main issue I have with simply allowing transactions with any nonce in the mempool is that we don't have any mempool evacuation/obsolescence policy in place, meaning that transactions that enter the mempool and don't go into a block - will stay there forever, possibly causing it to explode.

**Comment by antonlerner** [comment]
> Interesting... We originally decided that we wouldn't allow it for simplicity reasons.
> 
> I assume that humans making transactions won't encounter this issue, as they will probably be slower than network propagation. However, when scripts create transactions (e.g. withdrawals from an exchange) this can definitely happen and it's not great at all.
> 
> Since I really want to re-think the way transaction processing happens, I think it's best to not invest time in fixing this issue, but I'm open to discuss it, if you disagree.
> 
> The main issue I have with simply allowing transactions with any nonce in the mempool is that we don't have any mempool evacuation/obsolescence policy in place, meaning that transactions that enter the mempool and don't go into a block - will stay there forever, possibly causing it to explode.

It depends on whether the wallet must wait for tx confirmation before issuing a new one, if it does then we can assume txs will be sent separatly, but if the wallet allows sending of nultiple txs we cant assure they will reach a certain node in the same order
@IlyaVi please verify that the wallet can send out multiple tx for same account in same layer
@y0sher please verify that txs can arrive in an unordered fashion via gossip

**Comment by noamnelke** [comment]
Wait, there's no problem sending many transactions from an account in the same layer, as long as you wait a few seconds between them, allowing them to propagate.

The question to @IlyaVi, then isn't if the wallet allows sending many transactions per layer (I assume it does), but if there's any way to send a batch of transactions all at once (e.g. by listing many target accounts or something). I assume the answer to that is no.

@y0sher Is there any reason to believe propagation will take more than a few seconds in most cases?

BTW, as long as a few nodes receive the TXs in the right order, there's a high likelihood that it won't affect confirmation time, even if the rest of the network doesn't get them at all.

**Comment by antonlerner** [comment]
@noamnelke  waiting a couple of seconds does not guarantee same order of sent gossip messages to all nodes

**Comment by noamnelke** [comment]
A human composing a transaction realistically takes closer to 20-30 seconds, which should be enough to propagate to most of the network. Again, it's enough to have a subset get the TXs, but I think that in most cases, even with a 5-10 second gap between TXs, most nodes will receive them in order.

Convince me otherwise.

**Comment by antonlerner** [comment]
Noam these are made up numbers. I think relying on users "slowness" and network propagation time to be better is simply planning to fail... there is a reason for this mini "load" test, it tests not a common but possible case for consecutive txs. and txs will fail if this will not be fixed.

**Comment by y0sher** [comment]
whenever you `Broadcast` a new message it’s passed to the protocol for verification, it will be inserted into the propagation routine only after the protocol validated it. as a result, the order of propagation is the order of validation. This happens across all nodes and might affect the order of messages. without even taking network into consideration. 
we can assume that all nodes will get all and the same messages by a certain time, but to maintain an exact order we would probably need a completely different gossip protocol. thus I do believe the tx protocol should have some tolerance for that. 
on a side note: I think supporting rapidly increasing nonces to the same account shouldn't be our aim (at least not short term), but resiliency to let the miner and network keep going should.

**Comment by IlyaVi** [comment]
Right now there is no way to send transactions in a batch, everything is sequential - there is an API call for nonce for each transaction, then TX structure is composed, signed and sent to node. Final step is getting approval from node in form of TX id. Thus the question is if node advances nonce each time it receives new transaction

**Comment by antonlerner** [comment]
> Right now there is no way to send transactions in a batch, everything is sequential - there is an API call for nonce for each transaction, then TX structure is composed, signed and sent to node. Final step is getting approval from node in form of TX id. Thus the question is if node advances nonce each time it receives new transaction

No. the node sends the approval before advancing nonce. it does only syntactic validation for messages before sending approval. 

this means that potentially a user could create consecutive transactions

**Comment by noamnelke** [comment]
> the node sends the approval before advancing nonce

This is actually something that slipped through the cracks, there was supposed to be an issue for using the projector in the `GetNonce` and `GetBalance` gRPC calls. I've created this issue now: https://github.com/spacemeshos/go-spacemesh/issues/1529
