### ISSUE TITLE
Indicate on bootstrap failure after X tries so wallet will know

### ISSUE THREAD

**Issue by y0sher** [spacemeshos/go-spacemesh#1544]
# Overview / Motivation

currently, you are required to be routable (forward a UDP port) in order to connect as a home miner to a network. though the bootstrap process is retying 10 times and then quits and goes on to gossip with the bootstrap node. we should return and quit or somehow indicate that we're unable to recv incoming udp messages and redirect the user to educational material about NATs, firewalls and port-forwarding.

# The Task
TODO: Clearly describe the issue requirements here...

# Implementation Notes
TODO: Add links to relevant resources, specs, related issues, etc...

# Contribution Guidelines
Important: Issue assignment to developers will be by the order of their application and proficiency level according to the tasks complexity. We will not assign tasks to developers who haven't introduced themselves on our Gitter [dev channel](https://gitter.im/spacemesh-os/Lobby)

1. Introduce yourself on go-spacemesh [dev chat channel](https://gitter.im/spacemesh-os/Lobby) - ask our team any question you may have about this task
2. Fork branch `develop` to your own repo and work in your repo
3. You must document all methods, enums and types with [godoc comments](https://blog.golang.org/godoc-documenting-go-code)
4. You must write go unit tests for all types and methods when submitting a component, and integration tests if you submit a feature
5. When ready for code review, submit a PR from your repo back to branch `develop`
6. Attach relevant issue to PR

**Comment by avive** [comment]
If we keep the node routability requirement for f&f then this is just one case of #1662 . I hope we can get rid of the routability requirement for f&f as it creates a sub-optimal user experience.

**Comment by avive** [comment]
@y0sher - we were thinking about using the new /v1/nodestatus function to monitor the # of connected neighbors (peers in the response) and just display an error message about network issues if it stays below peersMin for n constant minutes. I believe this is good enough solution to resolve this issue for TNFF: #1662 - please close this issue if you agree.

**Comment by y0sher** [comment]
#1662 kinda handles this.
