### ISSUE TITLE
contextual validity not found on block under pbase

### ISSUE THREAD

**Issue by almogdepaz** [spacemeshos/go-spacemesh#1545]
# Overview / Motivation
this occurred  during an aws testnet run

![ds.PNG](https://images.zenhubusercontent.com/5bc359c853778662c5af1793/babfc58f-e877-486c-87db-dc60de02344c)

and it shouldn't be possible 

# The Task
TODO: Clearly describe the issue requirements here...

# Implementation Notes
TODO: Add links to relevant resources, specs, related issues, etc...

# Contribution Guidelines
Important: Issue assignment to developers will be by the order of their application and proficiency level according to the tasks complexity. We will not assign tasks to developers who haven't introduced themselves on our Gitter [dev channel](https://gitter.im/spacemesh-os/Lobby)

1. Introduce yourself on go-spacemesh [dev chat channel](https://gitter.im/spacemesh-os/Lobby) - ask our team any question you may have about this task
2. Fork branch `develop` to your own repo and work in your repo
3. You must document all methods, enums and types with [godoc comments](https://blog.golang.org/godoc-documenting-go-code)
4. You must write go unit tests for all types and methods when submitting a component, and integration tests if you submit a feature
5. When ready for code review, submit a PR from your repo back to branch `develop`
6. Attach relevant issue to PR

**Comment by barakshani** [comment]
a bit more info: the block arrives as a late block. Possibly it is a very late block, so when it arrives it is already below pbase. However, it should be checked that indeed it cannot happen to late blocks that are above pbase on time of arrival

**Comment by almogdepaz** [comment]
we should save such a block as contextualy invalid at the moment of arrival, this will provide cleaner behavior.
