### ISSUE TITLE
don't panic when block from hare result not found  

### ISSUE THREAD

**Issue by antonlerner** [spacemeshos/go-spacemesh#1547]
# Overview / Motivation
currently node panics when a block found in hare results is not in nodes database 
# The Task
remove the panic, replace with error, send nodes view in created block and not hare result set. 

# Implementation Notes
TODO: Add links to relevant resources, specs, related issues, etc...

# Contribution Guidelines
Important: Issue assignment to developers will be by the order of their application and proficiency level according to the tasks complexity. We will not assign tasks to developers who haven't introduced themselves on our Gitter [dev channel](https://gitter.im/spacemesh-os/Lobby)

1. Introduce yourself on go-spacemesh [dev chat channel](https://gitter.im/spacemesh-os/Lobby) - ask our team any question you may have about this task
2. Fork branch `develop` to your own repo and work in your repo
3. You must document all methods, enums and types with [godoc comments](https://blog.golang.org/godoc-documenting-go-code)
4. You must write go unit tests for all types and methods when submitting a component, and integration tests if you submit a feature
5. When ready for code review, submit a PR from your repo back to branch `develop`
6. Attach relevant issue to PR

**Comment by noamnelke** [comment]
@antonlerner I thought this was my task (I was assigned)... Not a big deal since I didn't work on it, but I guess letting me know that you're on it would be a good idea, in general.

**Comment by noamnelke** [comment]
closed by mistake - re-opening
