### ISSUE TITLE
recover from invalid ATX

### ISSUE THREAD

**Issue by antonlerner** [spacemeshos/go-spacemesh#1551]
# Overview / Motivation
Currently, an ATX is not tested for validity when publishing into network. 
it is then refrenced by the next ATX created, thus invalidating the next ATX as well.

# The Task
Validate the ATX when creation is complete, if ATX is invalid (investigate) and re run process.

# Implementation Notes
TODO: Add links to relevant resources, specs, related issues, etc...

# Contribution Guidelines
Important: Issue assignment to developers will be by the order of their application and proficiency level according to the tasks complexity. We will not assign tasks to developers who haven't introduced themselves on our Gitter [dev channel](https://gitter.im/spacemesh-os/Lobby)

1. Introduce yourself on go-spacemesh [dev chat channel](https://gitter.im/spacemesh-os/Lobby) - ask our team any question you may have about this task
2. Fork branch `develop` to your own repo and work in your repo
3. You must document all methods, enums and types with [godoc comments](https://blog.golang.org/godoc-documenting-go-code)
4. You must write go unit tests for all types and methods when submitting a component, and integration tests if you submit a feature
5. When ready for code review, submit a PR from your repo back to branch `develop`
6. Attach relevant issue to PR

**Comment by barakshani** [comment]
See https://github.com/spacemeshos/go-spacemesh/issues/1061 and https://github.com/spacemeshos/go-spacemesh/issues/1204

**Comment by noamnelke** [comment]
## Suggested solution
Implement a listener on the ATX Pool, such that, after publishing an ATX, the ATX Builder can wait until it hits the mempool.

If this wait times out (5 seconds should be enough, based on short discussion with @y0sher), the ATX publication fails and is retried in the next layer without updating the `prevAtx`.

This solution avoids validating the ATX twice, while also ensuring a "hand-off" to the mempool. When we implement free-standing ATXs (v0) we'll have to make the mempool persistent and synced meaning that a successful hand-off to the mempool is all we need to ensure that the ATX will be available to other miners.

**Comment by antonlerner** [comment]
I prefer to validate the atx twice since it's a once in an epoch operation. also, a timeout is almost never the best solution as it is likely to fail sometimes.
also this will allow you to discard the current atx and start over in case the old one fails validation.

**Comment by noamnelke** [comment]
As mentioned above, ensuring that the ATX hit the mempool is a better solution to ensure that the broadcast succeeded. A syntactically valid ATX can still not be sent, if for example, the node crashes at that point.

Starting over is what should happen at this point, anyway.

**Comment by antonlerner** [comment]
it is not since the published atx will always hit the creating node first. there is no guarantee that other nodes have received it

**Comment by noamnelke** [comment]
As mentioned above:
> When we implement free-standing ATXs (v0) we'll have to make the mempool persistent and synced meaning that a successful hand-off to the mempool is all we need to ensure that the ATX will be available to other miners.

**Comment by noamnelke** [comment]
I'm not ruling out validating the ATX **if the broadcast times out** and logging the result.

I initially set a 10 second timeout, but @y0sher believes that a 5 second timeout is enough to never happen outside of extreme circumstances.

**Comment by noamnelke** [comment]
Actually, I think the behaviour in case of a timeout should be:

1. Validate ATX, if invalid - clear state and start over.
2. If valid - wait another 15s.
3. If it still didn't hit the mempool - panic.

**Comment by antonlerner** [comment]
the alternative is implementing an atx sync right?
