### ISSUE TITLE
Have p2p struct as the internal orchestrator instead of Swarm

### ISSUE THREAD

**Issue by zalmen** [spacemeshos/go-spacemesh#156]
TODO: point to the required API in the design doc

**Comment by zalmen** [comment]
- [ ] Create internal `p2p` struct instead of Swarm that holds all the components, identity
- [ ] Expose static API out of the p2p package and set init() to create a base state for that

Move event loop into p2p:
- [ ] Incoming message flow - move Demuxer into p2p struct and redirect into it all incoming messages arriving from the net component
- [ ] Incoming and outgoing flows - Handle all creation and parsing of the messages Metadata header (including message signing)

**Comment by y0sher** [comment]
This was resolved as we decided to not use the `static` api and just create a single `p2p` service in the main process and pass it to protocol to use. it is still called `swarm` internally for the `p2p` package.
