### ISSUE TITLE
add / kill nodes, check atxs's active set and subsequently #eligible blocks

### ISSUE THREAD

**Issue by antonlerner** [spacemeshos/go-spacemesh#1561]
# Overview / Motivation
add / kill nodes, check atxs's active set and subsequently #eligible blocks

# The Task
interesting test scenarios:
- [ ] boot 300 nodes in epoch 1, make sure they create an ATX, at start of epoch 2 kill 100 nodes. make sure less blocks than needed created
- [ ] boot 200 nodes in epoch 1, boot extra 100 nodes in epoch 2, make sure each node of the 300 has created block in epoch 3, and that number of blocks hasn't exceeded the required number of blocks per layer  / epoch
- [ ] other scenarios?

# Implementation Notes
TODO: Add links to relevant resources, specs, related issues, etc...

# Contribution Guidelines
Important: Issue assignment to developers will be by the order of their application and proficiency level according to the tasks complexity. We will not assign tasks to developers who haven't introduced themselves on our Gitter [dev channel](https://gitter.im/spacemesh-os/Lobby)

1. Introduce yourself on go-spacemesh [dev chat channel](https://gitter.im/spacemesh-os/Lobby) - ask our team any question you may have about this task
2. Fork branch `develop` to your own repo and work in your repo
3. You must document all methods, enums and types with [godoc comments](https://blog.golang.org/godoc-documenting-go-code)
4. You must write go unit tests for all types and methods when submitting a component, and integration tests if you submit a feature
5. When ready for code review, submit a PR from your repo back to branch `develop`
6. Attach relevant issue to PR

**Comment by barakshani** [comment]
this issue is addressed here https://github.com/spacemeshos/go-spacemesh/issues/1754
