### ISSUE TITLE
Refactor Net module to contain all aspects of (secured/non-secured) connection maintenance 

### ISSUE THREAD

**Issue by zalmen** [spacemeshos/go-spacemesh#157]
TODO: point to the p2p design doc

- [ ]  Move Handshake protocol into net for creating secured connection.
- [ ] Decouple handling of wire protocol (e.g. `delimited`) from the Connection struct and write a wire format interface to make is modular.
- [ ] When creating a new connection, pass the incoming message channel on which p2p is listening for new messages (with metadata)
- [ ] Make dial and listen transport agnostic.

**Comment by y0sher** [comment]
was done in #174
