### ISSUE TITLE
Fix logs

### ISSUE THREAD

**Issue by barakshani** [spacemeshos/go-spacemesh#1570]
- **ALL** log messages regarding messages from p2p (not local things) should include the sender's `node_id`.

- Fix bytes representations to something readable:
`Failed sending HARE_PROTOCOL msg [123 129 185 230 148 211 148 26 48 31 95 93] to`

- In the log
`could not get result for layer in range`
there is
`"error":"no result for the requested layer"`
The word _error_ should not appear

- Block id is now a short string/id of 5 characters -- causes too collisions (in the logs) -- should be longer (12 char. ?)

- "got new ATX" should include all possible information: similar to the info in "ATX published!" + other ATX fields (in particular `epoch_id').

- fix JSON in `starting build atx in epoch %v` and `re-entering atx creation in epoch %v`

- late hare messages (late preround / "contextually invalid message") should include the node_id that sent the message. "contextually invalid" is not a good name - should be "late" / "not in time" (if too early)

- we have
`sending message failed %!(EXTRA *service.DataMsgWrapper=&{true 6 1 [113 169 217 46 19 216 93 89 35 103 13 132 9 97 7 74 149 179 217 161 81 4 131 209 229 113 105 88 151 40 90 48]}, string= error: , *errors.errorString=connection was closed)`
as well as
`peer responded with nil to poet request DFjCnmocNHoa3Kyd16LWQpFTTcRZThP1CS6vuB8WvFEj%!(EXTRA []uint8=[113 169 217 46 19 216 93 89 35 103 13 132 9 97 7 74 149 179 217 161 81 4 131 209 229 113 105 88 151 40 90 48])`
should fix the presentation to something comprehensible (in all relevant places)
(see also:
`handle atx request {atx_ids %!s(zapcore.FieldType=15) %!s(int64=0) [ca1cfd21703c8ed26655722c3da2f37a009ec7aeabe2131140498422af57514a b1a56aa5afc2d523f7d1c907c88bd579ecaa29d5dbfaf947cbc9d06d84c19a67 d5b4af7d28cf9df9d8ef568e843a7544cd5a78d5a1760ee91971441d851a61c9 789885c3ac2307cad568ca9fa70de707dcb434b8353fe923f396cd1180ba8647 6c34150b8a2bd843246185c3b8f84a2f15424493ce4608c0ed25426db941026a  ] <nil>}`)

- `Reward calculated` appears twice in each layer

- Fix `atx size %!s(int=18956)%!(EXTRA log.Field={atx_id 15 0 f6f9c <nil>})`. It is better if this is part of the "ATX published!" log

- Add `epoch_id` to "I've created a block"

- unfamiliar atx was requested (id: %s), fix `%s`

- Add duration to "finished PoST execution"

- Any log about the initial post creation / proof root etc.?

- the function `CalcActiveSetSize` should print the calculated active set size. Can write it under `done calculating active set size`

- Fix the `%s` and `<nil>` here `handle atx request {atx_ids %!s(zapcore.FieldType=15) %!s(int64=0) [361ee3710cf0c78cf84b23367dfb986d3ef9bc2b0076b2ac7fe54e86fafb890a] <nil>}`

- `block created` and `block received` should have associated ATX in short string.

- `already synced for layer` appears every 10 seconds. Consider the benefit of printing it.

- In the message `Failed sending newBlock msg [22 91 102 90 183 144 70 218 165 121 166 12] to 6S3sSsvzYv4kb2oQLsbCHae2xS5GtLKU6JvTCMMfG6uP, reason=connection was closed` the peer name is not the correct peer we failed sending the message to.

- add `epoch_id` to the `release tick` log.

- Blocks coming by fetching (as opposed to gossip) should have all the logs as in `got new block`. Currently some logs are under the `start handle block` log (in the `handleBlock()` function).

********
For dashboard purposes:
- `got new atx` should have longer ids than 5 characters (atx_id, _sender_id etc.) to prevent collisions and displaying inaccurate information.

**Comment by noamnelke** [comment]
@lrettig if you're working on logs then you should be aware of this change I made a couple of months ago: https://github.com/spacemeshos/go-spacemesh/pull/1808

It makes many of our custom types implement the `LoggableField` interface which allows us to just include a variable in the log message and it will be formatted in a way that makes sense. I haven't converted any of the existing logs to use this mechanism, but we should do it gradually, as we update these logging statements. Let me know if you need help with this.

**Comment by lrettig** [comment]
@noamnelke thanks for the heads up! That's exactly what I've been doing in #1952 - see for instance https://github.com/spacemeshos/go-spacemesh/pull/1952/files#diff-fbc8f466cd0cde2afe76fa37ca7ee514R174
