### ISSUE TITLE
A gossip message is not sent again ONLY to the sender

### ISSUE THREAD

**Issue by gavraz** [spacemeshos/go-spacemesh#1575]
The longer a message is waiting to be broadcasted in the queue the more likely it is that the message will be sent to neighbors who have already sent us the message (because it is more likely that during the queue time our neighbors will send us that message).
On dequeue, we send to all neighbors except the original sender. We should be able to check if the message should be sent to each of the neighbors prior to sending the message.
It is possible that in addition to knowing if we should send the message to each peer, we will want to have a separate queue for each peer.

We should think about it more thoroughly when the time comes and decide what and how to implement it.

**Comment by lrettig** [comment]
Might be solved by the broker described in #1911

**Comment by lrettig** [comment]
Related: #1157
