### ISSUE TITLE
DHT as a self-contained module

### ISSUE THREAD

**Issue by zalmen** [spacemeshos/go-spacemesh#159]
TODO: point to p2p design doc

DHT module should be responsible for all discovery related protocols.
- [ ] All Bootstrap and FineNode related flows should be handled within the DHT package
- [ ] The kademlia routing table is missing the mechanism to check whether a peer is alive when the kbucket is full and replace it if not.
- [ ] Now we have an hard limit about how much nodes we must have connected to have it bootstrapped what we really want is putting this limit only on filling the routing table. and letting the node run even with one node connected while in background trying to acquire more connections.

**Comment by y0sher** [comment]
Done
