### ISSUE TITLE
Ensure we have logs of state root

### ISSUE THREAD

**Issue by noamnelke** [spacemeshos/go-spacemesh#1591]
- [x] Log global state root whenever it's updated
- [x] Log layer hash (concatenation of sorted block ids + prev. layer hash) every time pbase passes it
- [x] Ensure automation tests validate that all nodes have the same mesh at the end of the test
- [x] Fix #1547

**Comment by noamnelke** [comment]
@barakshani you agree with how I defined the task?

**Comment by barakshani** [comment]
For the second bullet, it is better to have a hash for the entire mesh (instead of independent layers). Check our App Test.

**Comment by noamnelke** [comment]
I don't think the `app_test` does what you think it does...

We only compare the `IntermediateRoot` which is global state trie root. This global state trie only contains data about accounts, not blocks, ATXs or even individual transactions. It's definitely not affected by any contextually invalid blocks or other data that doesn't change account balances or nonces (counters).

Maintaining a hash of the entire state may prove inefficient to do, which is why I suggested storing the hash of each layer (sha256 of concatenated block ids + previous layer hash) when pbase passes it. This can be incrementally maintained relatively easily and provide the ability to compare the entire state up to any given layer.

**Comment by gavraz** [comment]
@noamnelke 
Fixing #1547 will remove the panic and replace it with an error. This means we won't know if two nodes have different mesh.
Hence, as part of this issue that validates that all nodes have the same mesh, we think it is good to also handle #1547. Meaning these two issues are unified.

**Comment by gavraz** [comment]
Also, please make sure that our automation tests include validation that all nodes have the same mesh at the end of the test.
