### ISSUE TITLE
Group all domain structures (e.g. Node) in a single package

### ISSUE THREAD

**Issue by zalmen** [spacemeshos/go-spacemesh#161]
All domain related data structures should be in a single package (consider having it in the base p2p package) which has no internal dependencies.  

- [ ] Refactor 'node' package to be identity and move all identity related inside. Expose creating nodes functions.
- [ ] Create a Node struct  - a basic struct that implements these methods base on a PublicKey and IP address. 
- [ ] Create LocalNode struct that extends the Node struct and holds the local node's credentials as well.

**Comment by y0sher** [comment]
Done :)
