### ISSUE TITLE
Use the PoET version mentioned in `go.mod` for automation runs

### ISSUE THREAD

**Issue by noamnelke** [spacemeshos/go-spacemesh#1621]
The current implementation uses the latest `develop`, instead we should extract the PoET version from `go.mod` and use that.

**Comment by lrettig** [comment]
We ran into issues with poet version again today after https://github.com/spacemeshos/poet/pull/105 was merged yesterday (my fault). We put into place a temporary fix in #2128 where we pinned a specific poet build: https://github.com/spacemeshos/go-spacemesh/commit/e353ccc393eda807411ef001015b2d3e8dabf4fb#diff-7002836ab7b8ee5645f5352721e0a15f9dc5eeac359a716460926725f2be4d72

However we need a more permanent solution. Note that this will also rely on changes on the poet side: https://github.com/spacemeshos/poet/issues/106

**Comment by moshababo** [comment]
@dshulyak still relevant?

**Comment by lrettig** [comment]
It's still relevant: there's still a poet version pinned in tests context:

https://github.com/spacemeshos/go-spacemesh/blob/ffc0c927d0d3e96dce55597cba2da8a54bcfc4e6/systest/testcontext/context.go#L32

Which doesn't necessarily match the version pinned in `go.mod`

**Comment by dshulyak** [comment]
it was updated recently. but it may lag behind periodically as those changes are usually independent. maybe we should enforce during review to keep version in go.mod and version in tests in sync. maybe it is not important though as long as they are compatible
