### ISSUE TITLE
Investigate Hash12, Hash32 usage and performance

### ISSUE THREAD

**Issue by gavraz** [spacemeshos/go-spacemesh#1626]
Hash12/32 is used widely in the system and attached to IDs like ATX id and block id. We should investigate how it is used and prefer immutability.
Performance should be put as a first prio. In addition, we should consider using a code generator for these types.

**Comment by noamnelke** [comment]
> we should consider using a code generator

Why? A code generator almost always produces less efficient code than hand-tweaked code.

**Comment by gavraz** [comment]
Hash12 and Hash32 basically use the same code. The only diff is by the constant. A code generator will simply create a file for each type with the same code and sub X with 12, 32 or whatever other numbers we find needed. I don't understand why it would be less efficient.

**Comment by noamnelke** [comment]
I see. If that's what you meant by code generator (something like [Genny](https://github.com/cheekybits/genny) for generics) then I agree.
