### ISSUE TITLE
slow block validation under stress 

### ISSUE THREAD

**Issue by barakshani** [spacemeshos/go-spacemesh#1637]
We have experienced, in several occasions, that under some stress it takes too much time to finish block syntactic validation and writing the block to the database.

We have seen it in gossip and also during sync. More logs are needed to see where it gets stuck.

This situation happens in the stress sync test, see layers 696-697

<img width="737" alt="Screen Shot 2019-12-29 at 1 04 52 PM" src="https://user-images.githubusercontent.com/35497694/71556149-58d5ce00-2a3d-11ea-8566-786f06672888.png">

where the highlighted block is stuck for 20 seconds.

<img width="1109" alt="Screen Shot 2019-12-29 at 1 00 34 PM" src="https://user-images.githubusercontent.com/35497694/71556159-6b500780-2a3d-11ea-92d3-5fbf0e02c840.png">

**Comment by moshababo** [comment]
Obsolete.
