### ISSUE TITLE
API for getting config

### ISSUE THREAD

**Issue by noamnelke** [spacemeshos/go-spacemesh#1638]
This would allow adding a node to the network by only providing it an IP address of a single existing node, and having it query for all other params.

**Comment by avive** [comment]
@Rami-Kasterstein @noamnelke - I'm not sure what's the status of it but you can reopen my PR which has added this to the API as a possible solution: https://github.com/spacemeshos/go-spacemesh/pull/1664

**Comment by noamnelke** [comment]
@ilans are you on this?

It seems that every person that looks at this has a different solution in mind. You've implemented one, I've implemented another, Jeff has another idea and I think that @ilans has a fourth solution that he didn't explain to me.

Bottom line, I think it's not important enough which solution we choose to be worth this much attention, so I gracefully retreat from my position on it.

I think that it's best that @ilans delivers this (and decides on the solution), since it's essentially a devops issue and he'll have to maintain it.

**Comment by avive** [comment]
We had a meeting about this today and @ilans believe that the way to do it is via the API - so I will open my PR and get it ready for review. I will assign you as reviewer.
