### ISSUE TITLE
Test p2p node discover, p2p messages, gossip

### ISSUE THREAD

**Issue by zalmen** [spacemeshos/go-spacemesh#164]
Test all functionality related to DHT node discovery and p2p messages based on an approved test plan. 
This epic also includes all automation issues that are required for running the test plan.

Done criteria:
- All QA cycles are passing besides bugs that aren't considered as blockers (below certain majority level - TBD).

**Comment by avive** [comment]
Sorry, didn't meant to close this issue.

**Comment by lrettig** [comment]
@y0sher are all of these already being tested by our existing p2p system test?

**Comment by y0sher** [comment]
Well, test plan was more elaborative than what haa been done so far. Currently we have happy flow tests. This issue doesn't represent this but we need more adversarial tests like dropping nodes/messages in the middle of the test and understanding the impact of it on propagation delay and cover.
