### ISSUE TITLE
Ctrl-C won't kill the node when running

### ISSUE THREAD

**Issue by y0sher** [spacemeshos/go-spacemesh#1657]
# Overview / Motivation

we want the node to gracefully shutdown when users hit the Ctrl-C button. though we've noticed that in some situations it does kill the node and in other it doesn't.

# The Task

investigate occurrences where the node fails to quit and find the dangling code that keeps running.

# Implementation Notes

usually when running a home miner and connecting to a network this will be the case. generally when hitting CTRL-C at first stages of booting up it would probably work normally.

# Contribution Guidelines
Important: Issue assignment to developers will be by the order of their application and proficiency level according to the tasks complexity. We will not assign tasks to developers who haven't introduced themselves on our Gitter [dev channel](https://gitter.im/spacemesh-os/Lobby)

1. Introduce yourself on go-spacemesh [dev chat channel](https://gitter.im/spacemesh-os/Lobby) - ask our team any question you may have about this task
2. Fork branch `develop` to your own repo and work in your repo
3. You must document all methods, enums and types with [godoc comments](https://blog.golang.org/godoc-documenting-go-code)
4. You must write go unit tests for all types and methods when submitting a component, and integration tests if you submit a feature
5. When ready for code review, submit a PR from your repo back to branch `develop`
6. Attach relevant issue to PR

**Comment by noamnelke** [comment]
The existing ATX Builder only checks for the stop signal before starting a go routine that builds a new ATX. The process of creating an ATX includes waiting for PoET, so it could be a long time until it stops from when the signal is received. This is one of the many issues #1619 resolves.

Of course, it may not be the only offender.

**Comment by lrettig** [comment]
Anecdotally, I've noticed this issue while syncing, but it doesn't seem to be an issue if my node is fully synced.

**Comment by lrettig** [comment]
Pretty sure this has been addressed!
