### ISSUE TITLE
Excessive memory allocation in poet proof verify function

### ISSUE THREAD

**Issue by barakshani** [spacemeshos/go-spacemesh#1658]
similar to https://github.com/spacemeshos/go-spacemesh/issues/1617, it seems that we allocate unneeded memory in the merkle tree proof verification, regarding the poet proof.
See the fix in https://github.com/spacemeshos/post/pull/34

**Comment by moshababo** [comment]
@noamnelke i'll be working on this soon.

**Comment by noamnelke** [comment]
Oh, good that you told me, I was planning on doing it today. No worries, though, I'll just pick something else.
