### ISSUE TITLE
Replacement to AWS - long-running testing infrastructure

### ISSUE THREAD

**Issue by barakshani** [spacemeshos/go-spacemesh#1666]
We need a new environment to run long-running networks, with potentially many miners.

This environment should allow:
- About 1500 miners
- Miners in multi regions
- Multiple PoET servers
- Multiple poet gateways and bootstrap nodes
- Good machine for a long-running poet, with sufficient RAM and disk space
- Enough disk space per miner for mesh data
- Init factory
- Add / remove miners (ideally specifying which miner to remove)
- Add / remove poet (should allow to specify the poet_id)

Need to consider how to update miners

**Comment by lrettig** [comment]
@narayanprusty please have a glance at this. I think we've accomplished all of this using GCP, and this can be closed. Please let us know if you think anything is still pending here. Thanks!
