### ISSUE TITLE
Tortoise panic when restarting a Node

### ISSUE THREAD

**Issue by barakshani** [spacemeshos/go-spacemesh#1671]
After restart, a persistent node panicked running the Tortoise:

`{"L":"INFO","T":"2020-01-06T21:08:13.875Z","N":"31476.post         ","M":"execution: start executing 1 files, parallelism degree: 1\n","node_id":"31476"}
{"L":"INFO","T":"2020-01-06T21:08:13.875Z","N":"00000.defaultLogger","M":"json API listening on port 9090"}
{"L":"INFO","T":"2020-01-06T21:08:13.875Z","N":"h895zseHr3shKG2xhiAZRMH9XpbNDT4BM4XiKNzik5c","M":"Bootstrap: starting with 1 sized table"}
{"L":"INFO","T":"2020-01-06T21:08:13.875Z","N":"00000.defaultLogger","M":"grpc API listening on port 9091"}
{"L":"INFO","T":"2020-01-06T21:08:13.877Z","N":"31476.mesh         ","M":"Validate layer 94","node_id":"31476"}
{"L":"INFO","T":"2020-01-06T21:08:13.877Z","N":"31476.trtl         ","M":"Tortoise update tables","node_id":"31476","layer_id":94,"n_blocks":33}
{"L":"INFO","T":"2020-01-06T21:08:14.415Z","N":"31476.trtl         ","M":"found minimal good layer 93, 4165714335","node_id":"31476"}
{"L":"ERROR","T":"2020-01-06T21:08:14.426Z","N":"31476.trtl         ","M":"Fatal: goroutine panicked. Stacktrace: goroutine 220 [running]:\nruntime/debug.Stack(0x0, 0xc00013ef88, 0x4d13d4)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0xa7\ngithub.com/spacemeshos/go-spacemesh/log.Log.Panic(0xc000292a80, 0xc0003041f0, 0xc0066281e0, 0x47, 0x0, 0x0, 0x0)\n\t/go/src/github.com/spacemeshos/go-spacemesh/log/zap.go:41 +0x26\ngithub.com/spacemeshos/go-spacemesh/tortoise.(*NinjaTortoise).addPatternVote.func1(0x30216fdcb0b206ea, 0x13de6a6f1fb9e83e, 0xd21d44f550372a45, 0x4af7f22d7801f38b)\n\t/go/src/github.com/spacemeshos/go-spacemesh/tortoise/ninja_tortoise.go:435 +0x9a2\ngithub.com/spacemeshos/go-spacemesh/tortoise.(*NinjaTortoise).handleIncomingLayer(0xc0001cbce0, 0xc00516b3a0)\n\t/go/src/github.com/spacemeshos/go-spacemesh/tortoise/ninja_tortoise.go:572 +0x5ea\ngithub.com/spacemeshos/go-spacemesh/tortoise.(*Algorithm).HandleIncomingLayer(0xc003cddf00, 0xc00516b3a0, 0x0, 0x0)\n\t/go/src/github.com/spacemeshos/go-spacemesh/tortoise/algorithm.go:56 +0xb6\ngithub.com/spacemeshos/go-spacemesh/mesh.(*Mesh).ValidateLayer(0xc000578120, 0xc00516b3a0)\n\t/go/src/github.com/spacemeshos/go-spacemesh/mesh/mesh.go:170 +0xf0\ngithub.com/spacemeshos/go-spacemesh/sync.(*Syncer).Synchronise(0xc00017e780)\n\t/go/src/github.com/spacemeshos/go-spacemesh/sync/syncer.go:293 +0x3e1\ngithub.com/spacemeshos/go-spacemesh/sync.(*Syncer).getSyncRoutine.func1()\n\t/go/src/github.com/spacemeshos/go-spacemesh/sync/syncer.go:192 +0x6d\ncreated by github.com/spacemeshos/go-spacemesh/sync.(*Syncer).run\n\t/go/src/github.com/spacemeshos/go-spacemesh/sync/syncer.go:207 +0x226\n","node_id":"31476"}
{"L":"PANIC","T":"2020-01-06T21:08:14.426Z","N":"31476.trtl         ","M":"block ea06b from layer 93 has no explicit voting, something went wrong ","node_id":"31476"}`

Looks like it has a similar cause as https://github.com/spacemeshos/go-spacemesh/issues/1593
[Note that the Node seems to be running Post (first line) for some reason]

**Comment by almogdepaz** [comment]
@barakshani it would be great if we have a full log of this issue or a way to reproduce

**Comment by barakshani** [comment]
We encountered a similar problem, only that instead of the error message above, we got something about failure of XDR

**Comment by lrettig** [comment]
Ran into this error just now, running using the smapp GUI on OS X. Full log: https://gist.github.com/lrettig/38294598448b67032f378970096f8cea

Here's what I saw in the frontend:

```
Error: Command failed: /Applications/Spacemesh.app/Contents/node/go-spacemesh --grpc-server --json-server --tcp-port 7513 --config '/Users/lanerettig/Library/Application Support/Spacemesh/config.toml' --coinbase 0xf08f67f9a5c968025e241627625c0cb909c39ab8b52898b68e484ce4fa5006d2 --start-mining --post-datadir '/Users/lanerettig/post' -d '/Users/lanerettig/Library/Application Support/Spacemesh/spacemeshtestdata/' >> '/Users/lanerettig/Library/Application Support/Spacemesh/spacemesh-log.txt'
panic: block 2c432 from layer 149 has no explicit voting, something went wrong 

goroutine 225 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0000f1600, 0x0, 0x0, 0x0)
	/Users/ilya/go/pkg/mod/go.uber.org/zap@v1.10.0/zapcore/entry.go:229 +0x546
go.uber.org/zap.(*SugaredLogger).log(0xc0002fe208, 0x604, 0xc0001981e0, 0x48, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/ilya/go/pkg/mod/go.uber.org/zap@v1.10.0/sugar.go:234 +0x100
go.uber.org/zap.(*SugaredLogger).Panicf(...)
	/Users/ilya/go/pkg/mod/go.uber.org/zap@v1.10.0/sugar.go:159
github.com/spacemeshos/go-spacemesh/log.Log.Panic(0xc00028bce0, 0xc0002fe208, 0xc0001981e0, 0x48, 0x0, 0x0, 0x0)
	/Users/ilya/go/src/github.com/go-spacemesh/log/zap.go:42 +0x14a
github.com/spacemeshos/go-spacemesh/tortoise.(*NinjaTortoise).addPatternVote.func1(0x1a4b6812ee2e432c, 0xe962ff911fcfccf, 0xc080bbc1ed)
	/Users/ilya/go/src/github.com/go-spacemesh/tortoise/ninja_tortoise.go:444 +0x9f2
github.com/spacemeshos/go-spacemesh/tortoise.(*NinjaTortoise).handleIncomingLayer(0xc0002f0a80, 0xc0066b5600)
	/Users/ilya/go/src/github.com/go-spacemesh/tortoise/ninja_tortoise.go:566 +0x71d
github.com/spacemeshos/go-spacemesh/tortoise.(*Algorithm).HandleIncomingLayer(0xc004e788a0, 0xc0066b5600, 0x0, 0x0)
	/Users/ilya/go/src/github.com/go-spacemesh/tortoise/algorithm.go:55 +0xc8
github.com/spacemeshos/go-spacemesh/mesh.(*Mesh).ValidateLayer(0xc00010c2c0, 0xc0066b5600)
	/Users/ilya/go/src/github.com/go-spacemesh/mesh/mesh.go:209 +0xf9
github.com/spacemeshos/go-spacemesh/sync.(*Syncer).handleNotSynced(0xc00010c420, 0x96)
	/Users/ilya/go/src/github.com/go-spacemesh/sync/syncer.go:355 +0xca
github.com/spacemeshos/go-spacemesh/sync.(*Syncer).Synchronise(0xc00010c420)
	/Users/ilya/go/src/github.com/go-spacemesh/sync/syncer.go:318 +0x448
github.com/spacemeshos/go-spacemesh/sync.(*Syncer).getSyncRoutine.func1()
	/Users/ilya/go/src/github.com/go-spacemesh/sync/syncer.go:211 +0x6d
created by github.com/spacemeshos/go-spacemesh/sync.(*Syncer).run
	/Users/ilya/go/src/github.com/go-spacemesh/sync/syncer.go:232 +0x234
```

**Comment by lrettig** [comment]
Full `config.toml` contents:

```
[main]
genesis-time = "2020-02-04T07:06:06+00:00"
layer-duration-sec = "300"
layer-average-size = "30"
layers-per-epoch = "6"
genesis-active-size = "50"
poet-server = "35.231.54.161:50002"
sync-request-timeout = "20000"
hdist = "7"

[p2p]
network-id = "1"

[p2p.swarm]
bootstrap = true
randcon = "8"
bootnodes = ["spacemesh://6Q5oLe7rARVfFeekrzy9qjPDcA9csTLnkQ9aZp64wYf4@34.73.217.215:7513"]

[api]

[time]

[post]
post-space = "1048576"

[reward]
base-reward = {abs = "50000000000000"}

[hare]
hare-round-duration-sec = "30"
hare-committee-size = "30"
hare-max-adversaries = "14"
hare-exp-leaders = "5"
hare-wakeup-delta = "30"
hare-limit-iterations = "10"

[hare-eligibility]
eligibility-confidence-param = "25"
eligibility-epoch-offset = "0"

[logging]
app = "info"
post = "info"
stateDb= "info"
state = "info"
store = "info"
poetDb = "info"
meshDb = "info"
trtl = "info"
atxDb = "info"
block-eligibility = "info"
mesh = "info"
sync = "info"
block-oracle = "info"
hare-oracle = "info"
hare = "info"
block-builder = "info"
block-listener = "info"
poet = "info"
nipst = "info"
atx-builder = "info"
hare-beacon = "info"
```

**Comment by lrettig** [comment]
Much shorter log, same issue: https://gist.github.com/lrettig/67f815daed6f0a373e53f881cbdfcf80

Steps to reproduce:
- Start running the Spacemesh OS X app
- Quit it
- `rm -rf ~/spacemesh ~/spacemeshtestdata ~/post`
- Rerun it

App screenshot:
![image](https://user-images.githubusercontent.com/3316532/73785975-641bc800-4766-11ea-8380-65cf1e6cc0a3.png)
![image](https://user-images.githubusercontent.com/3316532/73785989-6a11a900-4766-11ea-88b3-fa4630219d8a.png)

**Comment by almogdepaz** [comment]
@lrettig that recreation flow is a bit strange, if you deleted spacemeshtestdata which basically holds all our node databases, you shouldn't have any prior mesh related data so the node should start from scratch.
from the log is looks like you are trying to recover from layer 149

**Comment by almogdepaz** [comment]
ok @lrettig 's recreation flow allowed me to figure this out, basically we dont pass the datadir param whan running with the app which causes all data folders to be written to home.
running with -d ~/spacemesh/data/ fixes this

**Comment by avive** [comment]
To clarify, I get this error after restarting the node w/o deleting any local data files between the runs. 
The app passes the data folder (-d param) to the node when it starts it on each new app session.
I'm going to share full logs of a repo case here next time it happens.
