### ISSUE TITLE
atx builder and block builder started even when StartMining is false

### ISSUE THREAD

**Issue by y0sher** [spacemeshos/go-spacemesh#1680]
# Overview / Motivation

we added StartMining flag and gRPC call to start mining, it start the `StartPost` function which creates a post init. though even when this flag is not passed the `atxBuilder` and `blockBuilder` and created and started which results in many errors when trying to mine and even checking commitment of other blocks. 

# The Task
TODO: Clearly describe the issue requirements here...

# Implementation Notes
TODO: Add links to relevant resources, specs, related issues, etc...

# Contribution Guidelines
Important: Issue assignment to developers will be by the order of their application and proficiency level according to the tasks complexity. We will not assign tasks to developers who haven't introduced themselves on our Gitter [dev channel](https://gitter.im/spacemesh-os/Lobby)

1. Introduce yourself on go-spacemesh [dev chat channel](https://gitter.im/spacemesh-os/Lobby) - ask our team any question you may have about this task
2. Fork branch `develop` to your own repo and work in your repo
3. You must document all methods, enums and types with [godoc comments](https://blog.golang.org/godoc-documenting-go-code)
4. You must write go unit tests for all types and methods when submitting a component, and integration tests if you submit a feature
5. When ready for code review, submit a PR from your repo back to branch `develop`
6. Attach relevant issue to PR

**Comment by avive** [comment]
So, when a node is managed by the app, it will get started on first run w/o the start-mining being set and only later an api call to StartMining will be made. So it seems that this issue is critical to fix before f&f otherwise we'll get many app issues for users which they don't know about and can't fix.

**Comment by antonlerner** [comment]
I tried to reproduce with `StartMininig = false` on AppTest and could not, please re open with relevant logs if this happens again
