### ISSUE TITLE
Only a node's latest ATX can be retrieved, preventing block eligibility check

### ISSUE THREAD

**Issue by noamnelke** [spacemeshos/go-spacemesh#1682]
When calculating block eligibility for an epoch we need the ATX from the previous epoch. Under normal conditions, since eligibility is calculated at the start of the first layer, the latest ATX will be from the previous epoch, allowing the node to calculate its block eligibility.

If, for some reason, an ATX is published before eligibility is successfully calculated, the miner will never be able to get the relevant ATX in order to calculate block eligibility, since the newer ATX will be its latest.

Since the eligibility cache isn't persistent, this can happen if the node publishes an ATX and then restarts in the same epoch. It will not be able to determine eligibility for blocks in the remainder of the epoch.

**Comment by barakshani** [comment]
https://github.com/spacemeshos/go-spacemesh/issues/1083 may be related
