### ISSUE TITLE
Debug mode from command line

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#1686]
# Overview / Motivation

To run go-spacemesh with debug mode enabled so I can see all debug output when running on the command line.

# The Task

Add a command line flag (e.g., "-v" or "-debug" or something) that shows me all debug output.

# Implementation Notes

It seems like right now the only way to enable debug mode is by changing the code and recompiling.

# Contribution Guidelines
Important: Issue assignment to developers will be by the order of their application and proficiency level according to the tasks complexity. We will not assign tasks to developers who haven't introduced themselves on our Gitter [dev channel](https://gitter.im/spacemesh-os/Lobby)

1. Introduce yourself on go-spacemesh [dev chat channel](https://gitter.im/spacemesh-os/Lobby) - ask our team any question you may have about this task
2. Fork branch `develop` to your own repo and work in your repo
3. You must document all methods, enums and types with [godoc comments](https://blog.golang.org/godoc-documenting-go-code)
4. You must write go unit tests for all types and methods when submitting a component, and integration tests if you submit a feature
5. When ready for code review, submit a PR from your repo back to branch `develop`
6. Attach relevant issue to PR

**Comment by lrettig** [comment]
@y0sher please take a look and let me know if I'm missing something obvious here. If not I'd be happy to work on this as it would make the rest of my work easier :) Thanks

**Comment by y0sher** [comment]
for the `node` executable we have configuration available for each module, checkout `config.toml` it has every modules' severity. it can be changed from there or using a gRPC call. the exception is the p2p logger which I'm working to add there. 
currently we don't have this using cli flags but it should be quite easy, if you want to go on and do it just check `cmd/node/node.go` and `cmd/root.go` you'll have to add the cli flags in `cmd/root.go` and they'll be loaded into the executable. 
I guess you can also add a -v or -debug flag that will switch all of them over to debug.
