### ISSUE TITLE
Local testnet guide

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#1691]
# Overview / Motivation

We want to make it as easy as possible for developers to run `go-spacemesh` locally and fire up a local, private testnet.

# The Task

At minimum, add documentation on how to fire up a local, mining node (along with required infrastructure such as a poet server). Add instructions on configuring a bootstrap node, then connecting other nodes to it.

**Comment by lrettig** [comment]
When I run `go-spacemesh` locally using a similar set of params to the ones we're using for Barak's testnet, it just spins forever with the below output. How do I get my node to act as a bootstrap node, and to begin smeshing?

Command:

`> go-spacemesh --tcp-port 7513 --coinbase 0x1234 --poet-server 127.0.0.1:50002 --post-space 1048576 --test-mode --start-mining --randcon 8 --layer-duration-sec 180 --hare-wakeup-delta 30 --hare-round-duration-sec 30 --layers-per-epoch 7 --eligibility-confidence-param 25 --eligibility-epoch-offset 0 --layer-average-size 120 --genesis-active-size 200 --hare-committee-size 80 --hare-max-adversaries 39 --sync-request-timeout 60000 --post-labels 100 --max-inbound 12 --genesis-time 2020-01-15T21:46:12+00:00 -d ~/spacemeshtestdata/`

Logs:

```
{"L":"ERROR","T":"2020-01-15T18:10:12.071-0500","N":"beb8a.blockBuilder ","M":"failed to check for block eligibility","node_id":"beb8a","layer_id":29,"error":"cannot calc eligibility, not synced yet"}
{"L":"INFO","T":"2020-01-15T18:10:12.071-0500","N":"beb8a.sync         ","M":"start synchronize","node_id":"beb8a"}
{"L":"INFO","T":"2020-01-15T18:10:12.071-0500","N":"beb8a.atxBuilder   ","M":"cannot create atx : not synced","node_id":"beb8a"}
{"L":"INFO","T":"2020-01-15T18:10:12.071-0500","N":"beb8a.sync         ","M":"Node is out of sync setting gossip-synced to false and starting sync","node_id":"beb8a"}
{"L":"INFO","T":"2020-01-15T18:10:12.071-0500","N":"beb8a.sync         ","M":"syncing layer","node_id":"beb8a","current_sync_layer":1,"last_ticked_layer":29}
{"L":"INFO","T":"2020-01-15T18:10:12.071-0500","N":"beb8a.sync         .peers        ","M":"now connected","node_id":"beb8a","n_peers":0}
{"L":"INFO","T":"2020-01-15T18:10:12.071-0500","N":"beb8a.sync         ","M":"could not get layer 1 from neighbors could not get layer hashes from any peer","node_id":"beb8a"}
{"L":"ERROR","T":"2020-01-15T18:10:42.075-0500","N":"beb8a.hare         ","M":"No blocks for consensus on layer 29 could not retrive layer = 29 blocks ","node_id":"beb8a"}
{"L":"INFO","T":"2020-01-15T18:13:12.069-0500","N":"00000.defaultLogger","M":"release tick","event":true,"layer_id":30}
{"L":"INFO","T":"2020-01-15T18:13:12.069-0500","N":"beb8a.atxBuilder   ","M":"cannot create atx : not synced","node_id":"beb8a"}
```

**Comment by avive** [comment]
https://testnet.spacemesh.io/#/local - I think it is up-to-date @moshababo - but the page is currently not linked from anywhere in the guide.

**Comment by lrettig** [comment]
This is now much easier thanks to https://github.com/spacemeshos/local-testnet. Closing.
