### ISSUE TITLE
Can't run tests on windows 10 pro

### ISSUE THREAD

**Issue by avive** [spacemeshos/go-spacemesh#1712]
# Overview / Motivation
Can't test go-spacemesh on windows 10 pro

# The Task
Fix `make test` errors.

# Repro steps
- Install win 10 pro dev deps.
- Run make install and make build
- Try `make test`

Result:
```
 C:\dev\go-spacemesh> make test
process_begin: CreateProcess(NULL, bash -c "if [ \"$TRAVIS_PULL_REQUEST\" == \"false\" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi", ...) failed.
scripts\win\genproto.bat
Generating protobuf for C:\dev\go-spacemesh\api\pb\api.proto
Generating protobuf for C:\dev\go-spacemesh\merkle\pb\node.proto
ulimit -n 500; go test -timeout 0 -p 1 ./...
process_begin: CreateProcess(NULL, ulimit -n 500; go test -timeout 0 -p 1 ./..., ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [test] Error 2
```

Expected: being able to run the tests.

**Comment by avive** [comment]
likely cause is `ulimit -n 500;` not being a valid shell command.

**Comment by avive** [comment]
Several tests also fail when running via `go test -timeout 0 -p 1 ./...`

**Comment by moshababo** [comment]
What's the priority of this task?

**Comment by avive** [comment]
it has no assigned milestone yet. It is not 0.1 for sure - but it should def be fixed for open source reediness.

**Comment by lrettig** [comment]
Just checked, this is still an issue

**Comment by moshababo** [comment]
@lrettig still relevant?

**Comment by lrettig** [comment]
Haven't tested on windows for a while but I think no one has complained about this recently
