### ISSUE TITLE
Verify mesh sync time against rollout plan requirements

### ISSUE THREAD

**Issue by avive** [spacemeshos/go-spacemesh#1724]

**Comment by almogdepaz** [comment]
latests run with my poor internet connection at home show 2.25 sec average per layer, the mark we where aiming for is 2 sec. the sync times for managed nodes  are much faster so the limitation is probably my connection.

**Comment by avive** [comment]
On my fast connection my current sync ratio is 1:77, meaning 1 sec to sync 77 secs of mesh but we aim for at least double that like what you write above. e.g. 1:150 which is 2 secs per a 5 minutes layer (300 secs) but I understand from @barakshani that this run is not sync-optimized.

**Comment by almogdepaz** [comment]
the latest run has 3 minute layers, thats why talking about time per layer gives better perspective (we already calculated that we need 2 sec for the f&f ). 
anyway im gonna test without bls to make sure the internet is the bottleneck. if its the connection theres not much we can do for the f&f besides changing params...

**Comment by avive** [comment]
Let's close once we confirm 1:75 sync rate ~2 hours for 1 week of data

**Comment by barakshani** [comment]
Sync time is about 3-4 seconds per layer on average, which is about 1.5-2 hours per week of growing mesh.

These numbers are without (or with very few) transactions. The reason that transaction may cause a slow sync time is not fetching the transactions, but updating the state according to them.

**Comment by avive** [comment]
We need to profile with transactions to figure out if we need to do further optimizations for 0.1.

**Comment by barakshani** [comment]
See https://github.com/spacemeshos/go-spacemesh/issues/1817
