### ISSUE TITLE
No neighbors after node reinstall - PONG w diff pub key

### ISSUE THREAD

**Issue by avive** [spacemeshos/go-spacemesh#1742]
1. Run a go-spacemesh node on your computer.
2. Stop the node, remove all local data and start a new node from the same computer.

Result:
Bootstrap will not return any neighbors, preventing the node from syncing.

Log: 
`2020-01-28T12:32:07.991+0200	WARN	8g1iYjSFZSUfFwf8Kw7Ypab2ZVvjfViwtg4GHsbujFbP	Peer spacemesh://5Q1zNLu36UmFPWoaJKtPXAhbCFuNiNVrVuzRq6LWQDKY@34.73.217.215:32788 didn't response to protocol queries - err:got pong with different public key
2020-01-28T12:32:07.991+0200	INFO	8g1iYjSFZSUfFwf8Kw7Ypab2ZVvjfViwtg4GHsbujFbP	Bootstrap : 54 try gave 0 results`

Expected: Bootstrap to return neighbors to new node so it can sync. 

@y0sher

**Comment by noamnelke** [comment]
I guess a node dialing in from same ip and port should overwrite the previous record?
