### ISSUE TITLE
Bootstrap is blocking the startup sequence

### ISSUE THREAD

**Issue by zalmen** [spacemeshos/go-spacemesh#175]
The startup sequence for the p2p layer should be -
1. create p2p
2. register protocols
3. run bootstrap in the background

**Comment by y0sher** [comment]
`swarm` now has `Start` which starts bootstrap in a non-blocking way but enables to block with the `waitForBoot() error` func. this can be replaced with a `chan` (or `Context`) in the future to enable the client to decide how much to wait.
