### ISSUE TITLE
Wrong API response to submit new tx when node is not synced

### ISSUE THREAD

**Issue by avive** [spacemeshos/go-spacemesh#1755]
1. Submit a tx on a node that is not synced yet.
2. Result is that the tx was broadcasted ok but the the tx is not broadcasted.

Expected: Return a result that tx can't be broadcasted because the node is not synced yet.

Once the sync status API is working, we'll disable new tx submission until the node is synced but we should still fix this on the api correctness level.

**Comment by avive** [comment]
1. Submit a tx on a node that is not synced yet.
2. Result is that the tx was broadcasted ok but the the tx is not broadcasted.
Expected: return a result that tx can't be broadcasted because the node is not synced yet.

**Comment by avive** [comment]
We will block execution of new transactions in the app if the node is not yet synced soon so this is a low priority issue. Not for F&F

**Comment by moshababo** [comment]
Obsolete.
