### ISSUE TITLE
Support an http end point with config.toml for f&f and 0.1 prod env.

### ISSUE THREAD

**Issue by avive** [spacemeshos/go-spacemesh#1776]
Similar to http://nodes.unruly.io/ on GC so clients can auto-easily configure their node to the current running network params. It will also be nice to have it on https and not on http.

**Comment by noamnelke** [comment]
I disagree. We should include the `config.toml` with the correct params, including bootnodes and poet addresses with the distribution.

**Comment by avive** [comment]
We are going to bundle one but having this end points will allow us to update the f&f test with a new genesis in case we need to know within the 2 weeks test so we should ideally have both. Otherwise, if for some reason we need to start a new genesis for f&f - we have to ask them to download and reinstall a new app instead of just restarting the app to join...

**Comment by noamnelke** [comment]
Restarting the app having the side effect of deleting all your data and changing the network you're running... Sounds like a terrible user-experience.

What if I want to keep running the old network? How do I indicate that? Or can the Spacemesh company overrule my decision and dictate what I run on my computer?

Downloading a new version for a new network, or at the very least downloading a new config file and manually deleting previous data sounds very reasonable to me, considering that we're asking users to stop running a version of the network and start running a completely new network.

Ideally (not for F&F), the app should support multiple networks, like many crypto wallets do, so you can switch back-and-forth between networks (e.g. mainnet <-> testnet).

**Comment by avive** [comment]
Noam is right about concerns of external testers, we want this feature to enable easier internal q&a of closed and f&f as w/o this feature we need to package, distribute and install a new app installer for every new genesis.

**Comment by avive** [comment]
We also want this endpoint to be on https and not http as soon as possible.
