### ISSUE TITLE
Active set size cache key should include epoch in addition to view hash

### ISSUE THREAD

**Issue by noamnelke** [spacemeshos/go-spacemesh#1778]
## The issue
While the calculation of the active set size is dependent on the requested epoch, the cache is per view, regardless of the epoch.

## Possible consequences
This could allow an attacker to maliciously create an ATX that includes a view it knows would be in validators' caches, but with a different epoch.

This could allow one to use a larger active set size than the view-epoch combination actually have, and/or to break up consensus between validators who have the view cached and those who don't.

<details>
<summary>Relevant code</summary>

https://github.com/spacemeshos/go-spacemesh/blob/4722feddb698b7a19596b689b751a5ebcb44bcf1/activation/atxdb.go#L255-L266
</details>

**Comment by moshababo** [comment]
@noamnelke still relevant?
