### ISSUE TITLE
move `delimited` inside `p2p/net/wire`

### ISSUE THREAD

**Issue by y0sher** [spacemeshos/go-spacemesh#178]
## Expected behavior

`delimtied` is a `wire.Formatter` implementation, it should be inside `p2p/net/wire`.

- [ ] - Move `delimited` inside the `p2p/net/wire` (`/delimited`) package

## Contribution Guidelines
1. Introduce yourself on go-spacemesh [dev chat channel](https://gitter.im/spacemesh-os/Lobby) - ask our team any question you may have about this task
2. Fork branch `develop` to your own repo and work in your repo
3. You must document all methods, enums and types with [godoc comments](https://blog.golang.org/godoc-documenting-go-code)
4. You must write go unit tests for all types and methods when submitting a component, and integration tests if you submit a feature
5. When ready for code review, submit a PR from your repo back to branch `develop`

**Comment by dhyon** [comment]
I guess this issue's as good as any to start with.
