### ISSUE TITLE
Packet weirdness

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#1782]
I've been packet sniffing using wireshark and I noticed two strange things today:

1. The supplied tcp-port (the one supplied via `--tcp-port` and entered into the GUI) is only used a very small number of times during the initial bootstrap, then never again:

![image](https://user-images.githubusercontent.com/3316532/73790442-7863c300-476e-11ea-83bc-b1fe6b234572.png)

(In this case, see that only 16 of > 100k packets used this port - this log is from a full sync)

2. All of the data seems to be exchanged with a single peer:

![image](https://user-images.githubusercontent.com/3316532/73790876-3be49700-476f-11ea-91a8-ab05afc1eb59.png)
![image](https://user-images.githubusercontent.com/3316532/73790818-20798c00-476f-11ea-95b4-c44b42db3962.png)

**Comment by y0sher** [comment]
I think that makes sense. you use the listening port for the discovery sequence during the bootstrap (over udp).
After that you initiate TCP connections to collected peers, TCP will allocate a new source port for each connection as the listening port is occupied listening.

**Comment by lrettig** [comment]
That explains no. 1 but not no. 2 - @y0sher any idea why all of the data would be exchanged with a single IP address?

**Comment by moshababo** [comment]
Obsolete.
