### ISSUE TITLE
Data collection and APIs for 0.2 projects

### ISSUE THREAD

**Issue by avive** [spacemeshos/go-spacemesh#1792]
- Design and implement mesh data collections and data APIs based on various 0.2 clients requirements (dashboard, explorer, rewards program)
- Interface between teams working on the 0.2 clients / projects which require data.

**Comment by lrettig** [comment]
Note to self: talk to @noamnelke and @antonlerner about indexes and data as part of the architecture design.

**Comment by lrettig** [comment]
@avive I don't think there's a distinct task here - I think this is encapsulated in the work we're already doing in https://github.com/spacemeshos/product/ and https://github.com/spacemeshos/api/ and https://github.com/orgs/spacemeshos/projects/11, and the go-spacemesh work can be tracked under #1764 - can we close this one?

**Comment by avive** [comment]
Yes.
