### ISSUE TITLE
No neighbors after restart

### ISSUE THREAD

**Issue by avive** [spacemeshos/go-spacemesh#1793]
1. run a node. 
2. machine got disconnected from the network over-night 
3. Reconnected to network - address book error in the log - bootstrap shut down by signal.
4. Restarted node - now I'm getting ping timeouts from all the nodes I'm trying to connect with - can't sync. 
5. Bootstrap starts to give 0 new results to node. 

Expected: bootstrap to recover when network outage ends (at least after node restart) and nodes not to give ping timeouts so node is able to sync.

**Comment by avive** [comment]
[spacemesh-log.txt 3.zip](https://github.com/spacemeshos/go-spacemesh/files/4176595/spacemesh-log.txt.3.zip)

**Comment by lrettig** [comment]
@avive has this recurred? Can we close this?
