### ISSUE TITLE
more logs in block builder / listener

### ISSUE THREAD

**Issue by barakshani** [spacemeshos/go-spacemesh#1797]
When a block is published, the "I've created a block" log contains block_id, layer_id, #tx, #atxs, view_size, votes_size and AssATX.

All of this information should also appear in the "got new block" log. At the moment this log only contains block_id and layer_id. In addition, it should also include the `sender_id`, which is the node_id of the miner that created the block.

If possible, both logs above should also include the proof_counter.

_After_ testing, this changes should be applied to the `closed_tn` branch.

**Comment by noamnelke** [comment]
`sender_id` is non-trivial. While validating the block we fetch the associated ATX and it's only found there, but there are all kinds of edge cases where we don't reach that point, so I don't want to wait before logging that we received the block until we know the miner id.

Two options:
1. You look up the ATX received log that matches the associated ATX of the block and find it there.
2. I log a separate message after fetching the ATX like "block id XX atx fetched, miner id: XX".

Let's agree to do 1?

**Comment by barakshani** [comment]
why not using the output from the public key extraction?
Have a look at the same field in "got new atx", I believe that this is what we do there.

**Comment by barakshani** [comment]
We should also have epoch_id under "I've created a block", and ideally also under "got new block"

**Comment by noamnelke** [comment]
I can add it to "block received", but I don't have `LayersPerEpoch` in the block builder, so I can't add it there easily.

Is it ok only in "block received"?

**Comment by barakshani** [comment]
Yes, it is enough for receiving the block.

**Comment by barakshani** [comment]
Seems that the the Associated ATX field actually gives that latest ATX, which may actually give eligibility for blocks one epoch after the published block's publication index 

Similar issue to https://github.com/spacemeshos/go-spacemesh/issues/1682

**Comment by noamnelke** [comment]
We validate that the ATX's target epoch matches the block's publication epoch:
https://github.com/spacemeshos/go-spacemesh/blob/c017a4489eee24ff1bd2c6e430c723dbbb4a1239/oracle/blockeligibilityvalidator.go#L104-L120
