### ISSUE TITLE
Fees are distributed to miners even if the transaction can't be applied

### ISSUE THREAD

**Issue by noamnelke** [spacemeshos/go-spacemesh#1798]
When calculating miners' rewards, fees from all transactions in contextually valid blocks are summed up and distributed to miners. Some transactions may not end up being executed (due to wrong nonce, insufficient balance or even non-existing account), but the fee in them still gets distributed.

This can be trivially abused to inflate the money supply.

**Comment by avive** [comment]
We have lots of work on this area and the currently implemented solution is obviously lacking in many ways and you didn't even mention smart contract transactions. Even with the restricted set of smart contract transactions - we only know the fee range in advance, but we can't compute how much the tx fee will cost be in practice until we execute them on the current global state.

In my mind this is one of the core cryptocurrency design issues that we must address in the coming weeks that is not resolved yet. 

Specifically - I can't see how tx fees can be distributed separately form the state transition function itself. In my view, we can only distribute tx fees to smesher for a layer after the state transition function ran on that layer and determined which coin and smart contract transactions are valid, and how much gas was actually spent in each smart contract transaction. So, the tx fee reward is just computed in the wrong time and place in the code. It should be applied to a layer after the STF was actually executed and the STF should sum the tx fees for that layer based on each tx execution.
 
@lrettig @barakshani @tal-m @iddo333

**Comment by lrettig** [comment]
> we only know the fee range in advance, but we can't compute how much the tx fee will cost be in practice until we execute them on the current global state

This is troubling. Why not?

> I can't see how tx fees can be distributed separately form the state transition function itself

Agree here - this seems dangerous to me for a bunch of reasons. Maybe the solution is to create some sort of "holding account" that collects all of the fees in a given layer, as the transactions in that layer are applied to the global state. Then, "at the end" of that layer, the contents of that "holding account" are distributed to the miners, in some sort of second, independent state transition.

**Comment by avive** [comment]
> This is troubling. Why not?

The halting problemo :-)

**Comment by lrettig** [comment]
> The halting problem

We can't know for sure, but we _can_ "estimate." You can't know for sure in Ethereum for the same reason, but wallets like Metamask still calculate an estimated gas cost (see [estimategas](https://web3js.readthedocs.io/en/v1.2.6/web3-eth.html#estimategas)).

Also, this is much less of an issue if the language is decidable like [clarity](https://docs.blockstack.org/core/smart/overview.html). Even if the entire language isn't, individual hardcoded smart contracts could be.

**Comment by avive** [comment]
won't this issue be fixed by the needed 0.2 tx processing code and new rewards scheme?

**Comment by noamnelke** [comment]
I hope it will, this is why nobody's fixing it for now.
