### ISSUE TITLE
Update global state with TXs once hare terminates

### ISSUE THREAD

**Issue by barakshani** [spacemeshos/go-spacemesh#1805]
When the Hare protocol terminates on layer j, if the global state is updated to layer j-1, we update it according to the blocks in the Hare output set. If not, we wait until all (open) Hare consensus processes in previous layers terminate, then we update the state, after updating layer j-1.

Possibly, the logic was already applied here: https://github.com/spacemeshos/local-testnet/issues/10

**Comment by antonlerner** [comment]
Currently Hare consensus processes can run simultaniously, up to `hdist` consensus processes. 
For V2 of the protocol, we will heavily rely on hare consensus and update global state when hare is terminated
To do so, we need to implement some new features to hare consensus process.
- [ ] Implement event for consensus process termination
- [ ] implement receiver function that listens to hare termination and updates state in consecutive order
- [ ] test new mechanism and edge cases
Important note: this will change the logic of state update and will not update state if our assumptions are broken and hare does not terminate, and will basically freeze global state forever.
@gavraz @barakshani please review and add you comments

**Comment by barakshani** [comment]
A small comment: it is true that it makes sense to run at most `hdist` CPs, however the `hare-iteration-limit` is an independent parameter, so it may be bigger.

For you note at the end, sure, it is also the case with the Tortoise. Research works on a more robust Hare. Future tasks (not under this epic) will include assertion by the Tortoise, and reversion of the state in case the Tortoise outputs a different state (set of contextually valid blocks).
