### ISSUE TITLE
Crash after node restart

### ISSUE THREAD

**Issue by avive** [spacemeshos/go-spacemesh#1806]
This is repro every single time with the current node from develop and the GC env which is also running it.

1. Start a node - remember which port you set.
2. Stop it and start again - use the same port.
Result: crash.
Expected: don't crash and sync.

OS X.

Logs attached.

[spacemesh-log.txt.zip](https://github.com/spacemeshos/smapp/files/4188569/spacemesh-log.txt.zip)

2020-02-11T23:40:41.641+0200	ERROR	7715d.mesh         	Fatal: goroutine panicked. Stacktrace: goroutine 1 [running]:
runtime/debug.Stack(0xc0008c3480, 0xc0002ee000, 0x587a6d0)
	/usr/local/Cellar/go/1.13.5/libexec/src/runtime/debug/stack.go:24 +0x9d
github.com/spacemeshos/go-spacemesh/log.Log.Panic(0xc0002a5da0, 0xc00035d140, 0xc00035d130, 0x4b04aca, 0x2b, 0xc0030cff00, 0x2, 0x2)
	/Users/avive/dev/go-spacemesh/log/zap.go:44 +0x26
github.com/spacemeshos/go-spacemesh/mesh.NewRecoveredMesh(0xc0000db600, 0x4c6aa80, 0xc0000cd900, 0xc0000bff00, 0x4c6ac40, 0xc0008c33c0, 0x4c51000, 0xc0003bc630, 0x4c50fc0, 0xc0002b4de0, ...)
	/Users/avive/dev/go-spacemesh/mesh/mesh.go:136 +0x101e
github.com/spacemeshos/go-spacemesh/cmd/node.(*SpacemeshApp).initServices(0xc00025c360, 0xc000394a00, 0x40, 0xc0003780c0, 0xc0, 0xc0, 0x4c70e20, 0xc0000ea780, 0x7ffeefbffcfd, 0x45, ...)
	/Users/avive/dev/go-spacemesh/cmd/node/node.go:502 +0x187e
github.com/spacemeshos/go-spacemesh/cmd/node.(*SpacemeshApp).Start(0xc00025c360, 0x53096e0, 0xc0001a0d00, 0x0, 0xd)
	/Users/avive/dev/go-spacemesh/cmd/node/node.go:864 +0xe19
github.com/spacemeshos/go-spacemesh/cmd/node.glob..func1(0x53096e0, 0xc0001a0d00, 0x0, 0xd)
	/Users/avive/dev/go-spacemesh/cmd/node/node.go:91 +0x211
github.com/spf13/cobra.(*Command).execute(0x53096e0, 0xc0000ca010, 0xd, 0xd, 0x53096e0, 0xc0000ca010)
	/Users/avive/dev/go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:766 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x53096e0, 0xc000000180, 0xc000163f50, 0x4007c1f)
	/Users/avive/dev/go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:850 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/avive/dev/go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:800
main.main()
	/Users/avive/dev/go-spacemesh/main.go:23 +0xac
	{"node_id": "7715d"}
2020-02-11T23:40:41.641+0200	PANIC	7715d.mesh         	cannot load state for layer 2, message: leveldb: not found	{"node_id": "7715d"}

**Comment by avive** [comment]
The panic is at: 

2020-02-11T23:40:41.641+0200	PANIC	7715d.mesh         	cannot load state for layer 2, message: leveldb: not found	{"node_id": "7715d"}

**Comment by almogdepaz** [comment]
@antonlerner  fixed this https://github.com/spacemeshos/go-spacemesh/pull/1809
