### ISSUE TITLE
Error getting layer from database on App start

### ISSUE THREAD

**Issue by barakshani** [spacemeshos/go-spacemesh#1807]
Miner was synced, smashed all day long. I've started and closed and restarted the App several times. Finally got an error message.

See:
<img width="425" alt="Screen Shot 2020-02-12 at 4 06 11 AM" src="https://user-images.githubusercontent.com/35497694/74300960-2c121780-4d5a-11ea-9946-a5da12783642.png">

**Comment by almogdepaz** [comment]
@barakshani got more logs? tried recreateing but couldn't...

**Comment by barakshani** [comment]
Closing this issue since the App did not delete the old files from a previous testing network -- it is too weird of a case to debug.
