### ISSUE TITLE
Pass ip addresses only as net.Addr

### ISSUE THREAD

**Issue by y0sher** [spacemeshos/go-spacemesh#181]
# Overview / Motivation
Around the `p2p` packages we pass, return or store `address`/`Address()` in a string format. it should represent an IP address of a node. passing it as a string makes room for errors (passing vs not passing a port) or wrong format IPs. 
We want to change all mentions of ip addresses to be in a `net.Addr` format.

# The Task
- [ ] Replace all getters of addresses with `net.Addr`
- [ ] Replace all function parameters with `net.Addr`
- [ ] Modify UT accordingly

# Contribution Guidelines
1. Introduce yourself on go-spacemesh [dev chat channel](https://gitter.im/spacemesh-os/Lobby) - ask our team any question you may have about this task
2. Fork branch `develop` to your own repo and work in your repo
3. You must document all methods, enums and types with [godoc comments](https://blog.golang.org/godoc-documenting-go-code)
4. You must write go unit tests for all types and methods when submitting a component, and integration tests if you submit a feature
5. When ready for code review, submit a PR from your repo back to branch `develop`

**Comment by dhyon** [comment]
I'll take this one.

**Comment by y0sher** [comment]
Good, keep in mind all of the work is around the `p2p` package where we use IP addresses. we want to represent these addresses with the common struct used by the golang std lib (`net.Addr`) which is basically a representation for 4 bytes. currently we're passing around strings and stuff like that and then break them up to IP and Ports.

**Comment by y0sher** [comment]
done by our contributor @dhyon ! 👍 thanks
