### ISSUE TITLE
Hare Test_multipleCPs may end up with empty proposal

### ISSUE THREAD

**Issue by gavraz** [spacemeshos/go-spacemesh#1813]
# Overview / Motivation
Noam run Test_multipleCPs with non-intersecting sets.
The result was that we got termination with an empty set but on the other hand no "preround ended with empty set".
This result is unexpected and should be investigated.
In addition @barakshani - should we be able to terminate with an empty set?

# The Task
Recreate and investigate this issue.
Also, add a UT with the empty set scenario which asserts the expected result according to Barak.

**Comment by barakshani** [comment]
Yes, an empty set is a set (and a valid output).
