### ISSUE TITLE
Build process and environment

### ISSUE THREAD

**Issue by zalmen** [spacemeshos/go-spacemesh#182]
This epic covers the basic requirements of our dev (local) environment and build (remote) environment. 
The basic environment should contain:
1. Automated process to fetch all dependencies (currently all dependencies are part of our repository)
2. Automated process to auto-generate all updated protobuf code  
3. Create a docker image for our build environment

**Comment by lrettig** [comment]
I think our current Makefile and the existing scripts satisfy these requirements. Please reopen if I've missed anything.
