### ISSUE TITLE
Fetch all code dependencies 

### ISSUE THREAD

**Issue by zalmen** [spacemeshos/go-spacemesh#183]
We want to strip down the repository from unrelated code,
At this moment all our dependencies are in the `vendor` directory. 
In order to be able to remove it we have to smoothly automate the building and dependency downloading process. we want to do it using `make`

All the dependencies are written in the `vendor/vendor.json` file.

- [ ] - Make sure `vendor.json` is up to date with our dependencies. 
- [ ] - automate installing `govendor` and running `govendor sync` using `make`, before building.
- [ ] - make sure the process satisfies all the project dependencies. 
- [ ] - Remove the dependencies packages directories from the repository.

**Comment by zalmen** [comment]
@noamnelke is this issue still relevant?

**Comment by noamnelke** [comment]
Nope, fixed by go-modules. Closing.
