### ISSUE TITLE
Run tortoise 30 seconds into the layer

### ISSUE THREAD

**Issue by barakshani** [spacemeshos/go-spacemesh#1834]
Today the tortoise is being fed on a layer's tick with blocks from the previous layer. In addition, late blocks are considered "late" (not for hare) only if they are published not within their layer timeframe.

Since all honest blocks should arrive within delta time (propagation limit = 30 seconds) from the layer's tick, we can let the tortoise eat blocks after delta time. All other blocks should be considered late.

The benefit is that we get confirmation 4:30 minutes earlier compared to today, and also classify late blocks correctly.

Note that Hare CPs start exactly after 30 seconds, so we should consider this before implementing.

**Comment by almogdepaz** [comment]
#1860

**Comment by almogdepaz** [comment]
lets wait with the whole hare cp thing till we have proof its a problem

**Comment by barakshani** [comment]
Done https://github.com/spacemeshos/go-spacemesh/pull/1860
