### ISSUE TITLE
wrong layer hash

### ISSUE THREAD

**Issue by almogdepaz** [spacemeshos/go-spacemesh#1835]
# Overview / Motivation
in a run of the late_nodes test one of the miners had an incorrect layer hash

# The Task
find cause and fix

# Implementation Notes
http://kibana.spacemesh.io/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now%2Fw,mode:quick,to:now%2Fw))&_a=(columns:!(M,layer_id,layer_hash),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'4c63e6a0-45c9-11ea-beeb-55f7b675b2db',key:kubernetes.namespace_name,negate:!f,params:(query:hilec,type:phrase),type:phrase,value:hilec),query:(match:(kubernetes.namespace_name:(query:hilec,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'4c63e6a0-45c9-11ea-beeb-55f7b675b2db',key:layer_id,negate:!f,params:(query:17,type:phrase),type:phrase,value:'17'),query:(match:(layer_id:(query:17,type:phrase))))),index:'4c63e6a0-45c9-11ea-beeb-55f7b675b2db',interval:auto,query:(language:lucene,query:'%22new%20layer%20hash%22'),sort:!(T,desc))

# Contribution Guidelines
Important: Issue assignment to developers will be by the order of their application and proficiency level according to the tasks complexity. We will not assign tasks to developers who haven't introduced themselves on our Gitter [dev channel](https://gitter.im/spacemesh-os/Lobby)

1. Introduce yourself on go-spacemesh [dev chat channel](https://gitter.im/spacemesh-os/Lobby) - ask our team any question you may have about this task
2. Fork branch `develop` to your own repo and work in your repo
3. You must document all methods, enums and types with [godoc comments](https://blog.golang.org/godoc-documenting-go-code)
4. You must write go unit tests for all types and methods when submitting a component, and integration tests if you submit a feature
5. When ready for code review, submit a PR from your repo back to branch `develop`
6. Attach relevant issue to PR

**Comment by barakshani** [comment]
Main issue is that we get:
`received syntactically invalid ATX e5484: could not calculate active set for ATX e5484 leveldb: not found`
It is not clear what's the cause for this error. In a later stage during the test the miner succeeds in calculating the active set (so it finds the atx in the database)

The layer hash issue is just subsequent:
`failed to validate block: failed to validate e5484 could not calculate active set for ATX e5484 leveldb: not found`

So far we have encountered this bug only in this test.

**Comment by almogdepaz** [comment]
@barakshani im on it
