### ISSUE TITLE
Use an ephemeral ed25519 key pair until mining starts

### ISSUE THREAD

**Issue by moshababo** [spacemeshos/go-spacemesh#1836]
# Improvement proposal
When node starts, it needs an `ed25519` key pair, of which its pubic key is used as the node id.

This id is also used for the PoST initialization, and so its private key was previously designed to be saved among the PoST files - when the data was generated for nodes beforehand (the `init-factory` tool). 

For this reason, when launching a node without mining, it creates the id and persist its private key _inside_ the default PoST datadir. When user starts mining it may chose a different path, so the private key file need to be copied. Other option is to persist the private key on the node's datadir (distinct from the PoST datadir), but this creates an issue for the `init-factory` tool and requires changes to the test infra (and may create future problems when a similar tool will be used by end-users, and not just by managed nodes).

AFAIK committing to the id is done only in the PoST initialization. If so, it will be possible to use an ephemeral id until then, so that if the node restarts, it will create a different one. Only once the node starts mining, the id private key will be saved - in the PoST datadir. 

**This is viable only if non of the services which are using the id or its derivatives is persisting it or relaying on that in any way.**

**Comment by y0sher** [comment]
imo sounds legit, what about not using a key at all and generating one only when initializing mining ? 
edit: ephemeral key might be easier to implement since some services might need that key to check eligibility (which will always result in no-eligibility in that case).

**Comment by avive** [comment]
don't use ephemeral ids if possible. It will make debugging very hard if nodes switch ids while they are running. I think this option makes most sense: `For this reason, when launching a node without mining, it creates the id and persist its private key inside the default PoST datadir. When user starts mining it may chose a different path, so the private key file need to be copied.`

**Comment by moshababo** [comment]
Some other services are using it, and even if we'll eliminate that, it might be needed for logging/monitoring purposes.

**Comment by moshababo** [comment]
> don't use ephemeral ids if possible. It will make debugging very hard if nodes switch ids while they are running

Node id won’t be changed when it starts mining - it will only be persisted. It will be changed only if the node **restarts** before mining started.

Having the App being able to copy the file means that it need to discover the PoST datadir default path. It also means that this dir will be created before mining started (not a big deal IMO). Also, it leaves the node buggy, since it's relying on a fix in a higher-level (and so whoever uses the node without the App is exposed to this bug). This is why I see this only as a temporary workaround, and not as a solution.

**Comment by avive** [comment]
Let's try to step back and agree on the higher level requirements:

1. Node id should never change once created when the node starts for the first time on a system unless the user deletes the Spacemesh data folder and starts the node again. In that case, when node starts - it is a brand new node.

2. Any files created by the node for persistence should always be created in the sm data folder and never outside of it.

3. User should be able to specify post data file location in any location on his system that he has read/write permissions to and has sufficient space for the post size commitment (e.g 4GB for f&f and 0.1).

**Comment by barakshani** [comment]
Why do you need 4 if you have 1?
anyway I agree with 4 but not with 1. in fact, before mining starts there is no requirement to generate a node_id. it's just a technical issue in our implementation.

**Comment by avive** [comment]
But it is a huge change as the node tries to sync before mining starts in closed_tn - which id are you going to get before mining? How are we going to be able to correlate in the logs between the temp id and the one created after mining starts? You are right about 4 - removing.

**Comment by barakshani** [comment]
Are we trying to agree on high-level requirement or got back to the ground (whether it's a change or not is irrelevant through the high-level glasses)?

Practically, home users have a single log file, so it is already correlated.
