### ISSUE TITLE
Verified Layer lags behind

### ISSUE THREAD

**Issue by barakshani** [spacemeshos/go-spacemesh#1838]
When layer j+1 starts we start "processing" layer j, by running the Tortoise on it (then update state etc., if pbase advances). Therefore, when our last synced layer is k, our VerifiedLayer is k-1.

There are 2 issues:
1. The App shows a difference of 3, instead of 1 (k and k-3)
2. There is a new change in the code where it seems that the miner processes layers with a delay of one layer.

For point 2, the following screenshots are from the running testnet, where we compare old miners to a new one (with the new code):
- Layer hash is computed one layer late (5 minutes after the rest)
<img width="1362" alt="Screen Shot 2020-02-19 at 12 54 54 PM" src="https://user-images.githubusercontent.com/35497694/74927075-a63c3f00-53df-11ea-8ec5-f80086c2d524.png">

- New state root is also computed one layer late, also there are 2 logs of "new state root" for some reason
<img width="1367" alt="Screen Shot 2020-02-19 at 12 54 38 PM" src="https://user-images.githubusercontent.com/35497694/74927232-e4d1f980-53df-11ea-9343-da2439b77449.png">

**Comment by barakshani** [comment]
Looking at the code in `grpc_server.go`, we see that in fact the "verified layer" is "latest layer in state" (`VerifiedLayer: s.Tx.LatestLayerInState().Uint64()`) which means that point 1 above is fine: we are verifying k-1, p_base is k-2, and the latest layer in state is indeed k-3.

Point 2 above should still be addressed.

**Comment by avive** [comment]
@barakshani  Does this issue cover the case we see where the verified layer lags 10-15 layers behind the tip? If not - we need another issue for this observed bug that we see in some f&f clients.

**Comment by barakshani** [comment]
No, but as far as I know a fix for what you are talking about is part of this PR https://github.com/spacemeshos/go-spacemesh/pull/1785. I don't know if the solution is tested. It is not merged into `closed_tn` yet.
