### ISSUE TITLE
Auto-generate Protobuf code

### ISSUE THREAD

**Issue by zalmen** [spacemeshos/go-spacemesh#184]
Our build process should be able to automagically generate protobuf code for all recently updated Protobuf files.

**Comment by y0sher** [comment]
check `.travis.yml` and the `ci` folder.

**Comment by y0sher** [comment]
looks like these are the best options,

https://github.com/src-d/proteussrc-d/proteus
https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/code-generator
https://github.com/NYTimes/openapi2proto
https://github.com/dedis/protobuf
