### ISSUE TITLE
Code readiness

### ISSUE THREAD

**Issue by avive** [spacemeshos/go-spacemesh#1840]
## Goal
Enable new developers to understand current implementation of the main Spacemesh components in code across all major go code repos (go-spacemesh, poet, post, etc...)

## Main epic tasks
1. Code-doc all code according to go-doc conventions. (see https://blog.golang.org/godoc-documenting-go-code). This command locates all missing go-doc comments in a dir: `golint ./...`  (1,840 issues in go-spacemesh)
2. Fix errors reported when running `godoc` on go-spacemesh
2. Remove commented and dead code from all active branches.
3. Create github issues from each TODO comments (there are 288 of them in go-spacemesh)
4. Remove outdated TODO comments.
5. Fix all `go vet ./...` reported issues in all the major go repos.

## Secondary tasks
1. Fix all typos in comments - go-land can easily find them: code-> inspect code -> whole project.
2. Fix non-idiomatic go issues - go-land code analysis might be useful here.
3. Fix all golint issues.

**Comment by avive** [comment]
References: https://pkg.go.dev/mod/github.com/spacemeshos/go-spacemesh?tab=packages
See missing synopsis for top-level packages...

**Comment by avive** [comment]
![image](https://user-images.githubusercontent.com/96002/76109365-95ddb400-5fdc-11ea-94d3-8dac7d7df935.png)

**Comment by avive** [comment]
Current health check on branch develop go-spacemesh:
1. go lint issues: 1386 (including go-doc errors)
2. go vet issues: 29
3. goland inspection (code-> inspect code -> whole project) -> typos (most are false positives) + code style issues.
4. Packages with missing go-doc synopsis: https://pkg.go.dev/github.com/spacemeshos/go-spacemesh?tab=subdirectories. How do we find all go-doc issues?
5. TODOs cleanup - 306 TODOs

POET Issues:
1. Goland inspector - 26 code style issues.
2. go lint issues: 5
3. go vet issues: 3
4. todos: 12
5. Missing go docs for packages: https://pkg.go.dev/github.com/spacemeshos/poet?tab=subdirectories
6. Missing go docs for main module: https://pkg.go.dev/github.com/spacemeshos/poet?tab=doc

**Comment by noamnelke** [comment]
Current status of `go-spacemesh`:

1. `golint` issues: 0
2. `go vet` issues: 0
3. GoLand still reports some issues, but nothing critical IMO. The main reason I don't want to invest in fixing these is that there's no way (that I know of) to validate this in CI.
4. I think all packages have a synopsis now, but it will only be updated [here](https://pkg.go.dev/github.com/spacemeshos/go-spacemesh?tab=subdirectories) once we make a major release (it looks at the latest tag).
5. @antonlerner will run a tool to create an issue for each TODO and cross reference the issue and code comment. We'll then prioritize the issues ongoingly.

Do we want to close this issue? @avive

**Comment by avive** [comment]
1. On `develop` I get these for `golint ./...`:
```
aembp:go-spacemesh avive$ golint ./...
activation/poet.go:71:2: redundant if ...; err != nil check, just return error instead.
activation/post.go:36:2: redundant if ...; err != nil check, just return error instead.
api/http_server.go:31:2: redundant if ...; err != nil check, just return error instead.
api/config/genesis.go:31:2: redundant if ...; err != nil check, just return error instead.
cmd/hare/oracle_client.go:120:2: don't use leading k in Go names; var kInBytes should be inBytes
cmd/integration/server.go:101:2: redundant if ...; err != nil check, just return error instead.
eligibility/fixedoracle.go:157:2: don't use leading k in Go names; var kInBytes should be inBytes
eligibility/fixedoracle.go:199:2: don't use leading k in Go names; var kInBytes should be inBytes
mesh/meshdb.go:132:2: redundant if ...; err != nil check, just return error instead.
mesh/meshdb.go:484:2: redundant if ...; err != nil check, just return error instead.
miner/block_builder.go:210:30: should drop = nil from declaration of var votes; it is the zero value
p2p/gossip/protocol_test.go:296:31: should drop = nil from declaration of var pk; it is the zero value
p2p/net/network_test.go:91:19: should drop = nil from declaration of var c; it is the zero value
sync/requests.go:232:2: redundant if ...; err != nil check, just return error instead.
sync/syncer.go:574:2: redundant if ...; err != nil check, just return error instead.
```

2. Super nice!
3. ok.
4. Let's wait until it refresh and do minor changes if needed.
5. @antonlerner  believes we should keep them in the code as future refactoring notes and not create issues out of them.

**Comment by avive** [comment]
It is amazing to see the nice progress we had on this project!

**Comment by noamnelke** [comment]
regarding 4: it doesn't refresh on it's own - only when we create a new tag that includes these changes.

**Comment by avive** [comment]
1. is fixed after golint update per @noamnelke suggestion.

**Comment by lrettig** [comment]
Well done guys - huge success

![Borat](https://media2.giphy.com/media/l2YWmzOpaGK0b0TZK/giphy.gif)

**Comment by avive** [comment]
We now wait to see how go-spacemesh will look on https://pkg.go.dev/github.com/spacemeshos/go-spacemesh?tab=subdirectories - the docs are generated when the next tag will be created.

**Comment by noamnelke** [comment]
Worth noting that not all packages have a synopsis yet.

![image](https://user-images.githubusercontent.com/776358/79199682-024e9d00-7e3e-11ea-945c-39e2939f1c06.png)

Are we content with this situation or do we want to make a last effort and fill in the blanks?

**Comment by avive** [comment]
We want to fill-in the blanks - this is a leftover from this project that was supposed to be done.
