### ISSUE TITLE
Improve nodestatus api

### ISSUE THREAD

**Issue by avive** [spacemeshos/go-spacemesh#1841]
Add the following useful data to the response of /v1/nodestatus:
- Smesher ID.
- Last known root state hash and layer number of the state.
- Go-spacemesh semantic version. e.g 0.1.13
- Go-spacemesh branch and commit hash (as displayed on the start of a node in the console).
- Network ID.

**Comment by avive** [comment]
@lrettig - part of api refactoring we need to discuss

**Comment by lrettig** [comment]
Will handle in #1764 - this has already been factored into the API design
