### ISSUE TITLE
GPU-Post write to disk

### ISSUE THREAD

**Issue by gavraz** [spacemeshos/go-spacemesh#1843]
# Overview / Motivation
We want to integrate GO-Post with GPU-Post. The way they will communicate is by files on disk.
In the repository GPU-Post we should implement a function that writes the results to disk.

# The Task
1. Discuss and verify this proposed solution (communicating through the disk) with **Aviv**.
2. Check out the implementation of GPU-Post.
3. Implement the missing parts to write the results to disk (in GPU-Post repo, C).

**Comment by moshababo** [comment]
Obsolete.
