### ISSUE TITLE
Call GPU-Post from GO-Post

### ISSUE THREAD

**Issue by gavraz** [spacemeshos/go-spacemesh#1844]
# Overview / Motivation
A part of the integration we should make the call to GPU-Post from GO-Post.
We decided that unless other issues arise, we will use CGO for this integration (the other option is using a GRPC server).

# The Task
Integrate GO-Post and GPU-Post using CGO.

**Comment by avive** [comment]
We would like the POST process (with GPU support) to be independent of go-spacemesh so it can be used by different clients and be more easily testable therefore there's no need to use CGO. What needs to be designed is the inter-process communication channel between go-spacemesh and the gpu-post-init process in a way that supports other clients to communicate with the POST process and POST needs to be built as a stand-alone process for all 3 supported OSes. @noamnelke @moshababo

**Comment by avive** [comment]
What is GPU-POST and what is GO-POST?
High-level what we want for POST is to have a standalone process with an interface that can be used by other clients such as go-spacemesh. The process should use the gpu-post c-library internally. 
@noamnelke @moshababo

**Comment by moshababo** [comment]
Obsolete.
