### ISSUE TITLE
Check Cross-OS compatibility of GPU-Post go-binding

### ISSUE THREAD

**Issue by gavraz** [spacemeshos/go-spacemesh#1846]
# Overview / Motivation
GPU-Post is going to be go-binded to GO-Post. We should make sure that using cgo to do that does not break any cross-os compatibility.

# The Task
After #1844 is done, make sure we can compile GO-Post on the various OSs we support (Linux, Mac, Windows).

**Comment by moshababo** [comment]
Obsolete.
