### ISSUE TITLE
CPU fallback strategy

### ISSUE THREAD

**Issue by gavraz** [spacemeshos/go-spacemesh#1847]
# Overview / Motivation
GPU-Post implements also a CPU fallback in case there is no GPU.
GO-Post has a few optimizations implemented, hence, it could be that falling back to the CPU implementation in GPU-Post is not better.

# The Task
1. Compare GPU fallback performance to the one in GO-Post.
2. In case that we prefer our implementation, make sure GPU-Post supports "letting you know" before falling back to CPU calculations and make sure we use our implementation.
3. It is possible that we should make some optimizations in GPU-Post fallback. We should speak to shababo to understand if it is what we want when we better understand this issue.

**Comment by moshababo** [comment]
Obsolete.
