### ISSUE TITLE
New PoST proof

### ISSUE THREAD

**Issue by barakshani** [spacemeshos/go-spacemesh#1855]
Need to implement https://github.com/spacemeshos/research/issues/37, once finalised.

**Comment by moshababo** [comment]
@barakshani  Is it ready for implementation?

**Comment by barakshani** [comment]
No.
Ideally this issue, or the one referenced above, will contain content for implementation.

**Comment by moshababo** [comment]
Closed by https://github.com/spacemeshos/post/pull/39.
