### ISSUE TITLE
Verifying Tortoise

### ISSUE THREAD

**Issue by barakshani** [spacemeshos/go-spacemesh#1856]
Consider implementing a verifying version of the tortoise, that only counts blocks that are inline with the Hare results. In quiet times that would be sufficient, and efficient. As a fallback we would need to run the current Tortoise implementation.

**Comment by almogdepaz** [comment]
not sure i understand the benefits of implementing this, the current tortoise is not a bottleneck at "quiet times" and preforms rather well.

**Comment by barakshani** [comment]
See relevant part here: https://github.com/spacemeshos/research/issues/33
