### ISSUE TITLE
wrong global state after restart

### ISSUE THREAD

**Issue by barakshani** [spacemeshos/go-spacemesh#1876]
We had 3 managed miners that suddenly restarted (VM crash?). They load the global state from the db, but the layer_id is off by one; see screenshot below.
In addition, their _layer_hash_ is also incorrect. Probably for the same reason.

![bad_state](https://user-images.githubusercontent.com/35497694/76159293-84ed8980-6127-11ea-86c1-b4487dff757f.PNG)

**Comment by antonlerner** [comment]
@noamnelke , could it be because of this code, where layer hash is persisted only after all layers have been pushed to state?:
```
func (m *Mesh) pushLayersToState(oldPbase types.LayerID, newPbase types.LayerID) {
	for layerId := oldPbase; layerId < newPbase; layerId++ {
		l, err := m.GetLayer(layerId)
		if err != nil || l == nil {
			// TODO: propagate/handle error
			m.With().Error("failed to get layer", log.LayerId(layerId.Uint64()), log.Err(err))
			break
		}
		m.AccumulateRewards(l, m.config)
		m.PushTransactions(l)
		m.logStateRoot(layerId)
		m.setLayerHash(l)
		m.setLatestLayerInState(layerId)
	}
	m.persistLayerHash()
}
```

**Comment by noamnelke** [comment]
I don't think it would make a difference if the `m.persistLayerHash()` was at the end of the loop. If there are more layers to push to the state and the loop isn't done yet, then you may get more layers to be persisted, but not all of them (since you didn't complete the loop).

What we need here is to process layers in a transaction, so we either persiste the entire update or none of it (and then we'll process it right after recovery).

**Comment by antonlerner** [comment]
I believe this is thee cause for the bug, do you agree?

**Comment by noamnelke** [comment]
I haven't looked at the entire code flow, but iirc (and this code snippet supports that) there's no tight control of state transitions. I.e. if a node crashes during a state transition it may end up with an invalid state.

This is not a small fix like moving the `m.persistLayerHash()` one line up. It's a change that may require changing some of the flows in the state transition and atomically persisting more granular statuses for recovery (in each database we'll need to store up to what point that particular database was updated).

I'm not 100% sure about how this should work - designing an airtight solution requires digging in the code a bit to understand the limitations.
