### ISSUE TITLE
No rewards after 49 hours

### ISSUE THREAD

**Issue by yaelmhoffman** [spacemeshos/go-spacemesh#1878]
The app has synced successfully and been running for over 49 hours, but without the user receiving any rewards.
[spacemesh-log.zip](https://github.com/spacemeshos/go-spacemesh/files/4303807/spacemesh-log.zip)

**Comment by avive** [comment]
@barakshani - is this due to being on the wrong side of the fork? Logs attached.

**Comment by barakshani** [comment]
yes. they publish an atx but it is, as well as their subsequent blocks, invalid

**Comment by avive** [comment]
Not relevant anymore in net id 113.
