### ISSUE TITLE
Can't connect to the P2P network

### ISSUE THREAD

**Issue by yaelmhoffman** [spacemeshos/go-spacemesh#1881]
A red bar appears in the app telling the user that they can't connect to the P2P network, requiring them to manually adjust firewall settings and port forwarding. 
![20200303_135813904_iOS](https://user-images.githubusercontent.com/56118594/76216848-fc034a80-6219-11ea-9a19-6e05f51db06f.jpg)
[spacemesh-log-Natko.zip](https://github.com/spacemeshos/go-spacemesh/files/4306772/spacemesh-log-Natko.zip)

**Comment by avive** [comment]
@yaelmhoffman - We need logs. Possible? W/o logs we can assume this is an end user p2p config issue but not do much about it - the app is supposed to report when the node can't connect to the p2p network so it is kind of a feature....

**Comment by y0sher** [comment]
It seems by the logs that indeed the users fails to get responses from the nodes it tries to contact. though this issue lacks context and reproduction methods. as when I run the node I don't get this issue, meaning we need to know more about the user's configuration - firewall used or any other network constraints.

**Comment by avive** [comment]
> It seems by the logs that indeed the users fails to get responses from the nodes it tries to contact. though this issue lacks context and reproduction methods. as when I run the node I don't get this issue, meaning we need to know more about the user's configuration - firewall used or any other network constraints.

thank you - we'll try to get this information from the user.

**Comment by avive** [comment]
This should be fixed in 0.0.6.
