### ISSUE TITLE
Red bar error: restart app

### ISSUE THREAD

**Issue by yaelmhoffman** [spacemeshos/go-spacemesh#1882]
Red bar telling user to restart the app, but restarting doesn't fix the problem. 
<img width="1034" alt="Screen Shot 2020-03-03 at 12 29 18 PM" src="https://user-images.githubusercontent.com/56118594/76217437-17bb2080-621b-11ea-9771-200aa1fb1347.png">
[spacemesh-log.txt.zip](https://github.com/spacemeshos/go-spacemesh/files/4306827/spacemesh-log.txt.zip)

**Comment by y0sher** [comment]
As far as I can tell, the logs show as the node is working properly, p2p is initialized and connected to gossip, we sync and tortoise runs as it should be.
this indicates either an error with the app or and error with the API exported from the node to the app. @IlyaVi @avive

**Comment by avive** [comment]
We should log api responses and timeout on api responses) that trigger the app error bars in the app.

**Comment by avive** [comment]
This should be fixed in 0.0.6 - it was just too aggressively displayed on startup.
