### ISSUE TITLE
Fix contacts features

### ISSUE THREAD

**Issue by yaelmhoffman** [spacemeshos/go-spacemesh#1888]
The contacts features of the app are not working.

**Comment by avive** [comment]
Contacts screen issues:
1. Valid addresses are rejected as invalid.
2. Create button is white and is hardly visible over light grey background - get better color with more contrast from designer and use it. Maybe even a big green or purple button?

<img width="1340" alt="Screen Shot 2020-03-29 at 6 14 26 PM" src="https://user-images.githubusercontent.com/96002/77852791-275dd180-71e9-11ea-9dcb-8a1481ed4ad6.png">

In transaction log screen, trying to create contract from an address fails - error box - address is invalid. In addition, auto-filled address is missing canonical 0x prefix.

**Comment by shibe-dev** [comment]
@avive i'm working on this issue from https://github.com/spacemeshos/smapp/issues/515. i've fixed the "address is invalid" error when creating contacts from the contacts tab (error shown in your screenshot), but i'm unsure what you mean by "In transaction log screen, trying to create contract from an address fails - error box - address is invalid". Can you elaborate what you mean by the "transaction log screen"/steps to reproduce this error?

**Comment by avive** [comment]
Yes. Here's the repro case:
1. Expand a transaction in the transaction log.
2. Click on the contract purple icon near the address which is not your wallet address in the transaction.
A purple 'create new contact' area is displayed. 
3. Enter a nickname for the new contact and click 'create'

Result: Address is invalid red error popover.
Expected: Contact to be created.

<img width="1392" alt="Screen Shot 2020-05-28 at 10 33 13 AM" src="https://user-images.githubusercontent.com/96002/83112327-ac247900-a0ce-11ea-90fc-e6f6cd959757.png">
