### ISSUE TITLE
Fork in test_kill_node

### ISSUE THREAD

**Issue by antonlerner** [spacemeshos/go-spacemesh#1892]
## Description
when running test kill node, we see that one miner has a different layer hash than the others, this is due to it failing to get validation result for block `0122f` 
miner is `sm-client-vfk1j-tlwlm-6c96767f57-s4tdz`
deployment `vfk1j `

here you can see this block has been processed:
<img width="883" alt="Screen Shot 2020-03-11 at 18 12 27" src="https://user-images.githubusercontent.com/21037839/76438767-1a0cae80-63c4-11ea-82b7-04e41ca70de5.png">

then we see that contextual validity is not found for this block

<img width="1217" alt="Screen Shot 2020-03-11 at 18 15 31" src="https://user-images.githubusercontent.com/21037839/76439045-7cfe4580-63c4-11ea-949f-3238e9abdcc2.png">

and the different layer hash that follows
<img width="1230" alt="Screen Shot 2020-03-11 at 18 19 06" src="https://user-images.githubusercontent.com/21037839/76439320-e4b49080-63c4-11ea-9471-17e5dc5db0db.png">

**Comment by antonlerner** [comment]
pbase seems to be stuck
http://kibana.spacemesh.io/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now%2Fw,mode:quick,to:now%2Fw))&_a=(columns:!(M,kubernetes.pod_name,current_sync_layer,layer_id,layer_hash),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'6126dfe0-5d3c-11ea-beeb-55f7b675b2db',key:kubernetes.pod_name,negate:!f,params:(query:sm-client-vfk1j-tlwlm-6c96767f57-s4tdz,type:phrase),type:phrase,value:sm-client-vfk1j-tlwlm-6c96767f57-s4tdz),query:(match:(kubernetes.pod_name:(query:sm-client-vfk1j-tlwlm-6c96767f57-s4tdz,type:phrase))))),index:'6126dfe0-5d3c-11ea-beeb-55f7b675b2db',interval:auto,query:(language:lucene,query:'%22vfk1j%22%20%26%26%20%2234dcb.trtl%22'),sort:!('@timestamp',asc))

**Comment by barakshani** [comment]
I had a look at the logs:
Layer 4 blocks have a very long propagation delay (more than 30 seconds); I haven't checked the cause of it.
P_base isn't really stuck, but because the miner doesn't get all layer 4 blocks on time, it does not advance p_base before it needs to know the contextual validity (I'm guessing for the Hare beacon). Once enough layer 4 blocks are received, p_base does advance.

**Comment by barakshani** [comment]
The fork is caused by this issue https://github.com/spacemeshos/go-spacemesh/issues/1893

**Comment by moshababo** [comment]
Obsolete.
