### ISSUE TITLE
Private key of faucet account in config

### ISSUE THREAD

**Issue by ghost** [spacemeshos/go-spacemesh#1903]
## Description
This is not a safest way, to store faucet (tap) private key

## Affected code
https://github.com/spacemeshos/go-spacemesh/blob/0cd25ae79d4935a1d1d31b0620c6f12abe46627e/tests/tx_generator/config.py#L4

**Comment by avive** [comment]
@antonlerner @AmitShaul - we should get the tap private key out of the codebase and use a new key pair for the 2 tap accounts before deploying the new testnet because several marketing programs such as the store can't be launched while any user can get any amount of smesh.

**Comment by avive** [comment]
@noamnelke said he's going to look into it - what we need is to test genesis accounts config for testnets and use one in the next testnet genesis. So the accounts in the code will still be used for testing but will not be used in open networks which will use their own genesis config file.

**Comment by ghost** [comment]
@avive 
https://github.com/spacemeshos/go-spacemesh/blob/develop/api/config/genesis.go#L70
`Address: 0xe77910b4419a4ee0f1d5483d7dd3b5b6b6922ee9 balance: 100000.0000000004 SMH`

**Comment by noamnelke** [comment]
@c29r3 Thanks for reporting this issue.

In the next testnet we're going to hardcode different tap accounts (and keep the private keys, well... private) until we get to implementing #2004.
