### ISSUE TITLE
PoET list of members to be hashed instead of constructing Merkle tree from

### ISSUE THREAD

**Issue by moshababo** [spacemeshos/go-spacemesh#1905]
## Description
The PoET service currently broadcasts proofs containing the ordered list of its members. This list is  provided instead for a distinct Merkle proof per member, since all membership proofs will eventually be needed on the network.
Despite that, the list is being used to construct a Merkle tree, for deriving a root which is used as the PoET input (the "statement"), instead of just being hashed.

## TODO
* Refactor PoET service to hash the list instead of constructing a Merkle tree
* Refactor PoET validation in `go-spacemesh` to calc root by hashing the list instead of constructing a Merkle tree

This would be a breaking change to the protocol (older proofs would turn invalid).

## Affected code
https://github.com/spacemeshos/poet/blob/55497a2dff28585f361a7e832600a04e0ec65862/service/round.go#L324
https://github.com/spacemeshos/go-spacemesh/blob/develop/activation/poetdb.go#L166

**Comment by moshababo** [comment]
@noamnelke any thoughts?

**Comment by dshulyak** [comment]
this was changed elsewhere
