### ISSUE TITLE
GRPC does not return "amount"

### ISSUE THREAD

**Issue by ghost** [spacemeshos/go-spacemesh#1908]
## Description
API does not return `amount` if you specify amount=0 when sending transaction

## Steps To Reproduce
1. Send transaction with amount = 0
![image](https://user-images.githubusercontent.com/52304443/76977277-2a81d380-6946-11ea-9dd8-c98ec37278d5.png)
2. Convert ID transactions to byte array
`list(bytearray.fromhex("b0f1e86eacca71e35dec42fe2e8001443d7f4aa153f347123c2368860d27a40a"))`
3. Check tx info
`curl -s http://localhost:9090/v1/gettransaction -H "Content-Type: application/json" -d '{"id":[176, 241, 232, 110, 172, 202, 113, 227, 93, 236, 66, 254, 46, 128, 1, 68, 61, 127, 74, 161, 83, 243, 71, 18, 60, 35, 104, 134, 13, 39, 164, 10]}' | jq .`
![image](https://user-images.githubusercontent.com/52304443/76978521-dc6dcf80-6947-11ea-905d-b04d5b50be25.png)

4. There is no info about sended amount

## Expected Behavior
```
{
  "txId": {
    "id": "sPHobqzKceNd7EL+LoABRD1/SqFT80cSPCNohg0npAo="
  },
  "sender": {
    "address": "afed9a1c17ca7eaa7a6795dbc7bee1b1d992c7ba"
  },
  "receiver": {
    "address": "afed9a1c17ca7eaa7a6795dbc7bee1b1d992c7ba"
  },
  "amount": "0",
  "fee": "1",
  "status": "PENDING"
}
```

## Environment
Please complete the following information:
 - OS: Linux, Ubuntu 18.04
 - Node Version: 0.19.5

**Comment by avive** [comment]
Shouldn't a coin transaction always have an amount of 1 or more smidge? What is the benefit of having 0 amount coin transactions? @noamnelke @antonlerner

**Comment by ghost** [comment]
Same situation with `fee` and `gas`. it’s technically possible to send a transaction with `fee` = 0  
![image](https://user-images.githubusercontent.com/52304443/79122581-b4378c00-7da0-11ea-8037-39ec82ad1a45.png)
Transaction ID: `9d86abae9746165c5eea7441114c606fe4c9fbc497c1922e54e78cf42cabcce3`
But i'm not sure, that this transaction will be confirmed

**Comment by noamnelke** [comment]
@c29r3 The reason zero-value fields are "missing" from the raw response from the API is that the response is serialized using [Protobuf](https://developers.google.com/protocol-buffers) before being converted to JSON and Protobuf encodes zero-value and missing fields the same way. The API response's missing fields should be interpreted as zeros by the caller.

@avive We currently don't impose a minimum fee for transactions. We may want to do this to reduce spam transactions in mainnet. If an entity chooses to send a 0 amount transaction and pay the required fee for it, I see no reason to have rule that artificially disallows it. An example of how it could be useful: one could come up with a riddle whose answer is a Spacemesh address. To register solving the riddle one must send an empty transaction to that address. What's the benefit of enforcing a minimum amount in that scenario (so long as the transaction pays the required fee)?

**Comment by avive** [comment]
I don't understand the logic behind 0 tx fees - it has to be 1 smidge - the smallest unit. Otherwise, DOSing the tx pool and filling the mesh blocks with valid txs has 0 cost.

**Comment by noamnelke** [comment]
I don't think 1 "smidge" is enough to discourage spam transactions. I think the minimum should be higher.

In case what I wrote wasn't 100% clear - I'm NOT advocating allowing zero-fee transactions, but I do think we should allow zero-**amount** transactions (that was the example I gave).
