### ISSUE TITLE
client version is checked against hardcoded version

### ISSUE THREAD

**Issue by y0sher** [spacemeshos/go-spacemesh#1918]
## Description

we have a simple version matching mechanism in p2p that is meant to make sure we only work with backward compatible versions. we compare the versions during handshake. though we've started updating version numbers, the actual version we use to comparing is stored under `p2p/config/params.go`  

the version there is still set to `0.0.1`

## Expected Behavior

version is updated according to version bumps we do with the node so the comparing will actually be effective.

**Comment by avive** [comment]
I think that ideally there should be a build flag - min supported client version which defaults to the currently built version so backward compatibility can be set at build time.
