### ISSUE TITLE
Change cli flag names to be identical to config

### ISSUE THREAD

**Issue by y0sher** [spacemeshos/go-spacemesh#192]
#### Expected behavior
CLI flag names are identical to config variable names.

#### Actual behavior
CLI flags are configured with `Cobra` @ `/app/cmd/root.go` with old names

The CLI flags name in `app/cmd/root.go` should be changed to the same names as in the config that can be found in the `config.toml` file or the structs tag names in each `config` package.

**Comment by samparsky** [comment]
@yosher I can work on this
