### ISSUE TITLE
ATX data availability

### ISSUE THREAD

**Issue by antonlerner** [spacemeshos/go-spacemesh#1925]
## Description
When receiving an ATX without the NIPST refrence found in db, we should fetch it from neighbour

check out `handleGossipAtx` in `block_builder.go`

**Comment by dshulyak** [comment]
The relevant code is currently in this file https://github.com/spacemeshos/go-spacemesh/blob/c7da63aff0731dcf8337699c61136ccf6460a798/activation/atxdb.go#L736-L789
