### ISSUE TITLE
Bootstrap will continue trying even after exit signal

### ISSUE THREAD

**Issue by y0sher** [spacemeshos/go-spacemesh#194]
#### Expected behavior
When using a interrupt signal (CTRL+C) to stop the node. it will stop all processes and quit.

#### Actual behavior
When bootstrap fails the node retries bootstrapping. (that way we can spin up multiple nodes at the same time and let them bootstrap). but the CTRL+C signal won't stop the bootstrap process and the program will keep running.

#### Steps to reproduce the actual behavior
Set `bootstrap` to `true` and insert a random (not working) bootnode. 
build and run. try CTRL+C.

**Comment by mestorlx** [comment]
@y0sher just submitted PR #215 with a possible solution.
will appreciate some feedback
