### ISSUE TITLE
Add instructions on running godoc to README

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#1947]
## Description

As part of #1840 we need to "Fix errors reported when running godoc on go-spacemesh." I have no idea how to "run godoc on go-spacemesh." When I run `godoc` on the commandline, I get very confusing output that talks about an HTTP server:

```
> godoc help
Unexpected arguments. Use "go doc" for command-line help output instead. For example, "go doc fmt.Printf".
usage: godoc -http=localhost:6060
```

**Comment by lrettig** [comment]
It seems like the command I want to run is something like `godoc -analysis=type,pointer` -- but this runs for all of the packages in my $GOROOT, and runs forever. @avive let me know if I'm missing something obvious here.

cf. https://golang.org/lib/godoc/analysis/help.html, https://godoc.org/golang.org/x/tools/cmd/godoc

**Comment by avive** [comment]
Just run this to see all go-doc related errors: `golint ./...`

**Comment by lrettig** [comment]
Okay, so by godoc you meant golint? If so then I misunderstood and I guess we can close this :)
