### ISSUE TITLE
Check if caching base58 encoded string of the private key binary data is worthwhile

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#1949]
## Description

The `String()` function in `crypto/keys.go` used to use caching. It was removed in https://github.com/spacemeshos/go-spacemesh/commit/64f61d6beb6df9fe489403b28b8a80f98007b58a#diff-e14633a61c8dceca5cef1638df656895L155 (not sure why). Should we add it back?

## Affected code

Related files (optionally with line numbers): 

TODO from https://github.com/spacemeshos/go-spacemesh/blob/c2d52d462ceaad0c587a3333c290d1db031d67aa/crypto/keys.go#L12

**Comment by moshababo** [comment]
Obsolete.
