### ISSUE TITLE
Use sha3 as library

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#1950]
## Description

The golang.org/x/crypto/sha3 code (https://github.com/golang/crypto/tree/master/sha3) was brought into go-spacemesh in https://github.com/spacemeshos/go-spacemesh/pull/327/commits/70926561919ec9c5acab3e8f02aacef95382f185. I'm not completely sure why. None of the code has been touched since then (https://github.com/spacemeshos/go-spacemesh/commits/develop/crypto/sha3).

Can we go back to using this as a library?

## Affected code
`crypto/sha3/**`

This issue appears in commit hash: c2d52d462ceaad0c587a3333c290d1db031d67aa

**Comment by avive** [comment]
@antonlerner

**Comment by avive** [comment]
@noamnelke - what do you think?

**Comment by lrettig** [comment]
If there are no objections here, I'll take care of this. Assuming we haven't touched the library, it should be quite simple to just switch back to importing it. If we have, we can wrap just that portion.

**Comment by noamnelke** [comment]
So actually... Why do we use sha3 at all?

I looked at the code usages and it looks like we only use it in code we copy-pasted blindly from Ethereum. Our other hashes are all sha256 (using our optimized library) and the api is identical so changing hashing algorithms would be trivial.

I suggest we use this opportunity to switch to `sha256-simd`.

@avive any objections?

**Comment by avive** [comment]
You should talk with @antonlerner - I think it is used as part of the usage of the Ethereum Trie in sm. So, he will know. I have no objection to use sha256-simd for all hashes.

**Comment by moshababo** [comment]
@lrettig still relevant?

**Comment by lrettig** [comment]
This was fixed in #3063
