### ISSUE TITLE
Constant coin issuance per layer

### ISSUE THREAD

**Issue by avive** [spacemeshos/go-spacemesh#1961]
## Description
We must ensure constant coin issuance per layer. Currently there's a Smidge remainder that is not distributed after the block reward per participating smeshers is calculated out of the layer total reward.

## Steps To Reproduce
Observe the logs of layer rewards computation. There's a reminder that is not distributed.

## Expected Behavior
Figure out how to distribute the reminder to one or more smeshers so the whole smidge reward is distributed - maybe some deterministic random function to reward it to one smesher?
Another idea - accumulate it in an account that is designated to dev fund for code contributions.

## Environment
All envs

**Comment by avive** [comment]
@tal-m @noamnelke @antonlerner  fyi

**Comment by noamnelke** [comment]
I'd also like to do something about it for esthetic purposes, but I don't think it's high priority - do you agree?

The solution that I like most is to roll this remainder over to the next layer. This way each layer has an infinitesimally small difference with other layers (nothing that an adversary can meaningfully benefit from), but this difference doesn't accumulate over time.

What mostly bothers me about the current situation is that it's not trivial to tell exactly how many coins are in existence at a given point without going all the way back to genesis and summing it up.

**Comment by avive** [comment]
It is not a high priority but needs to be done so I wrote this issue so we won't forget. Rolling the reminder to the next layer and assuming it was issued is a cool idea. I like it.

**Comment by moshababo** [comment]
@lrettig still relevant?

**Comment by lrettig** [comment]
This is not a separate issue. Will be handled as part of https://github.com/spacemeshos/pm/issues/5
