### ISSUE TITLE
GetTxIdsByAddress returns duplicate txids

### ISSUE THREAD

**Issue by ghost** [spacemeshos/go-spacemesh#1963]
## Description
Endpoint `v1/accounttxs` returns a lot of duplicated hashes

## Steps To Reproduce
1. `curl -s  http://localhost:9090/v1/accounttxs -H "Content-Type: application/json" -d '{"account": {"address":"0x4466d6ca8f57b87c59e9c52037c0b866018b806e"}}' | jq ."txs"`
![image](https://user-images.githubusercontent.com/52304443/77976386-87e23100-7305-11ea-9483-eb2758830b3b.png)

2. `curl -s  http://localhost:9090/v1/accounttxs -H "Content-Type: application/json" -d '{"account": {"address":"0x4466d6ca8f57b87c59e9c52037c0b866018b806e"}}' | jq ."txs" | jq 'unique'`
![image](https://user-images.githubusercontent.com/52304443/77976394-8f093f00-7305-11ea-9774-d3f25d1cd087.png)

## Environment
Please complete the following information:
 - OS: Linux, Ubuntu 18.04
 
 - Node Version: 0.1.8

**Comment by lrettig** [comment]
I'm pretty sure this isn't an API issue. This happened in the old API, and it happens in the new API too. The API calls 
`meshdb` `GetTransactionsByDestination` and `GetTransactionsByOrigin`, and `TxMempool.GetTxIdsByAddress`. While it's true that the API doesn't attempt to deduplicate the txids it gets, it seems unlikely that the same txid would be returned two or three times from these calls.

**Comment by dshulyak** [comment]
I fixed it some time ago
