### ISSUE TITLE
Telemetry

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#1964]
Opening a placeholder issue for this project and to begin collecting requirements. Telemetry will allow us to collect logs and events from nodes in a more structured fashion.

Reminder to self to talk to Yosher before working on this.

CC @ilans

**Comment by avive** [comment]
Please also talk with @IlyaVi about app-level error reporting.

**Comment by avive** [comment]
App Telemetry data should go to the app logs and be sent using the 3rd party telemetry solution. @ilya is going to decide on which solution to use. User must be able to opt-out from error and telemetry reporting via the settings.

**Comment by lrettig** [comment]
To recap what we discussed today: it's OPT-OUT for the testnet, OPT-IN for mainnet.

**Comment by lrettig** [comment]
I wasn't aware of this previously, but for comparison, geth has [built-in metrics](https://github.com/ethereum/go-ethereum/tree/master/metrics):

```
METRICS AND STATS OPTIONS:
  --metrics                           Enable metrics collection and reporting
  --metrics.expensive                 Enable expensive metrics collection and reporting
  --metrics.influxdb                  Enable metrics export/push to an external InfluxDB database
  --metrics.influxdb.endpoint value   InfluxDB API endpoint to report metrics to (default: "http://localhost:8086")
  --metrics.influxdb.database value   InfluxDB database name to push reported metrics to (default: "geth")
  --metrics.influxdb.username value   Username to authorize access to the database (default: "test")
  --metrics.influxdb.password value   Password to authorize access to the database (default: "test")
  --metrics.influxdb.tags value       Comma-separated InfluxDB tags (key/values) attached to all measurements (default: "host=localhost")
```
