### ISSUE TITLE
preround status optimization

### ISSUE THREAD

**Issue by gavraz** [spacemeshos/go-spacemesh#1965]
We made optimization to the size of status messages. Instead of sending the preround certificate as in the original article, we count on the fact that preround messages will arrive no later than the following round, hence each participant is expected to be able to find proof of status messages at the end of the status round.

Thi optimization required a few tweaks like moving status message validation to the end of the round (instead of instantly) and doing union over preround messages from the same sender. Both are not trivial from the security aspect and actually expose us to some attacks (like a union of messages that can grow bigger and bigger).

The research team was not intimidated nor worried about the implications of that optimization. Dr. Barak & Gavrad were concerned about it.

A follow up to this optimization is a wider optimization. The certificate of preround messages is no special and it can be done also for SVP and commit certificate. 

IMO, this should be thoroughly considered and analyzed by the research time before proceeding. I do recommend that we do find some way to optimize the size of Hare messages. Graphene is or just using IDs of messages are also good candidates.

**Comment by lrettig** [comment]
@jonZlotnik curious to get your take on this once you've had a chance to consider it
