### ISSUE TITLE
Transactions issue

### ISSUE THREAD

**Issue by avive** [spacemeshos/go-spacemesh#1979]
## Description
Unexpected response from node api regarding a transcation.

## Steps To Reproduce
1. Call /v1/accounttxs to view this account transactions:
```{
  "startLayer" : 0,
  "account": {
  	"address": "0x40a21738d8a48805d390ffa1473b5ec24236b4f1"
  }
}
```
Results:
```
{
    "txs": [
        "0xc4a6b6fe19548d96f2342d056f7bf860d4390def04807756759f2360832d66cf",
        "0xce49b7e6ba7a0390c975cef440538a1bdef789a58688f245a08e35a5f9201b3a",
        "0x9e183718f45a38fc1dba02f4eb36edb98f6ca60c87008ace93c68b9be67c0cfd",
        "0xc4a6b6fe19548d96f2342d056f7bf860d4390def04807756759f2360832d66cf",
        "0xce49b7e6ba7a0390c975cef440538a1bdef789a58688f245a08e35a5f9201b3a",
        "0x9e183718f45a38fc1dba02f4eb36edb98f6ca60c87008ace93c68b9be67c0cfd",
        "0xc4a6b6fe19548d96f2342d056f7bf860d4390def04807756759f2360832d66cf",
        "0xce49b7e6ba7a0390c975cef440538a1bdef789a58688f245a08e35a5f9201b3a",
        "0x9e183718f45a38fc1dba02f4eb36edb98f6ca60c87008ace93c68b9be67c0cfd",
        "0xc4a6b6fe19548d96f2342d056f7bf860d4390def04807756759f2360832d66cf",
        "0xce49b7e6ba7a0390c975cef440538a1bdef789a58688f245a08e35a5f9201b3a",
        "0x9e183718f45a38fc1dba02f4eb36edb98f6ca60c87008ace93c68b9be67c0cfd"
    ],
    "validatedLayer": "6258"
}
```
2. Call /v1/gettransaction on ANY of these transactions.

## Behavior
```
{
    "error": "transaction not found, id: 71ee3d6fb7ba6daedad37f7473def971e7f8e34e77f1ad5b75e7fbf3d6b9f3af",
    "message": "transaction not found, id: 71ee3d6fb7ba6daedad37f7473def971e7f8e34e77f1ad5b75e7fbf3d6b9f3af",
    "code": 2
}
```

## Expected Behavior
Return txs data.

## Environment
Please complete the following information:
 - OS: OS X
- Env: open testnet 
- Node version: 0.1.9
- Account: 0x40a21738d8a48805d390ffa1473b5ec24236b4f1 with node v0.1.9.

## Additional Resources
- This postman collection might be useful: https://www.getpostman.com/collections/a184456e0302cadf34e7

**Comment by antonlerner** [comment]
It seems that transactions were processed by node correctly,
```
{"L":"INFO","T":"2020-04-06T15:49:20.020Z","N":"1e2ac.state        ","M":"transaction processed","node_id":"1e2ac","transaction":"<id: ce49b, origin: 0xaFEd9, recipient: 0x40A21, amount: 99999, nonce: 1792, gas_limit: 20, fee: 50>"}
```
 @noamnelke  can you check API call is good?

**Comment by avive** [comment]
The app is not getting these transactions as well. The I'm trying to get the tx info is via
/v1/gettransaction with post json of:
`{
  "id": "9e183718f45a38fc1dba02f4eb36edb98f6ca60c87008ace93c68b9be67c0cfd"
}`

**Comment by noamnelke** [comment]
That's because you're not using the API correctly. The `/v1/gettransaction` endpoint accepts a byte array as TXID.

E.g.:
```json
{
	"id": [196, 166, 182, 254, 25, 84, 141, 150, 242, 52, 45, 5, 111, 123, 248, 96, 212, 57, 13, 239, 4, 128, 119, 86, 117, 159, 35, 96, 131, 45, 102, 207]
}
```

To convert a hex string to a byte array, in python3 run this (remember to remove the `0x` in the beginning):
```python
[int(x) for x in bytearray.fromhex('c4a6b6fe19548d96f2342d056f7bf860d4390def04807756759f2360832d66cf')]
```

**Comment by noamnelke** [comment]
BTW, inconsistencies in our wallet API is something Ilya and I are aware of, making the API consistent in the format of values like addresses should be part of the overhaul I have in mind.

**Comment by avive** [comment]
@IlyaVi - so this issue is back to you: I don't see these transactions in the app. I only see 3 txs in the log.

**Comment by noamnelke** [comment]
@avive this is not a `go-spacemesh` issue (until new evidence is presented) so I'm closing this issue and you can open a new one in `smapp`.

**Comment by avive** [comment]
ok

**Comment by avive** [comment]
@lrettig - I think we want to make sure that we canonical tx ids in the updated api and not byte arrays which are very caller unfriendly. It fooled me because all most other methods accept hex strings as valid ids.
