### ISSUE TITLE
Archive mode

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#1985]
Archive mode runs a node in a mode where _all intermediate database states_ are stored.

Alternatively, "normal" mode could include a "garbage collector" that's on by default and discards these intermediate states, so that "archive mode" means "no gcmode."

**Comment by avive** [comment]
I think that we defeintly want to well define this. Here's a possible mini spec:
1. Add network param to the config file which indicates how many layers from the current layer a full node should keep global state data which is not the accounts db.
2. If node is not an archive node, it should discard all of this state when a new layer is created (based on time). If an archive node, don't delete this data - ignore this param. When data is deleted, also delete any indexes and views created exclusively from this data. What is called garbage collection above.
3. Add flag to startup node as archive node or full node.

I think this should suffice as a good first implementation. I think that additional issues we'll need to consider for full / archive node will only materialzie when we implement fully the STF and the new incentive scheme. I can't think about anything else beyond what's specified above right now.

**Comment by lrettig** [comment]
> implement fully the STF and the new incentive scheme

The "layers_to_keep" param should definitely be longer than the number of layers used in the lookback calculation for rewards.

**Comment by lrettig** [comment]
@avive what about stuff that's not exactly global state data, e.g., event logs? It might be helpful here to create a table with _all_ of the classes of data in question and the retention criteria/plan for each.

**Comment by moshababo** [comment]
@lrettig still relevant?

**Comment by lrettig** [comment]
Yes, but there's no imminent dev task so this issue can be closed. We'll define the spec for this soon.
