### ISSUE TITLE
make the queue generic

### ISSUE THREAD

**Issue by salvatore63** [spacemeshos/go-spacemesh#1986]
/develop/sync/fetch_queue
queue       chan []types.Hash32     //types.TransactionID

**Comment by noamnelke** [comment]
Hey @salvatore63, thanks for taking an interest in Spacemesh!!

I agree with what you did in this issue and PR, but I will close them for now until we do a more concentrated effort to accompany all of our code todos with matching issues (that should have a specific format).

Please don't let this disparage you from making future contributions! I highly recommend joining our Discord and coordinating with us there before your next contribution: https://discord.gg/7xxJp8E (look for me in the `dev_discussion` room).
