### ISSUE TITLE
chore: swarm config params

### ISSUE THREAD

**Issue by avive** [spacemeshos/go-spacemesh#20]
#### Feature description

Make all swarm config values command-line and config-file modifiable. Look at `SwarmConfigValues` - right now the values are hard-coded.

#### Reasons for adding this feature
This feature will allow us to more easily test swarm features.

**Comment by y0sher** [comment]
urfave/cli should load everything pretty smooth even from config files. tough it has an open issue about parsing u/int(64) and duration types, maybe we should use another toml parser (probably the one used by cli anyway) ? 
reference to issue : https://github.com/urfave/cli/issues/599

**Comment by avive** [comment]
i think we should go w the cli parser for now and cast from ints. We should also decide toml vs. yaml and provide some demo config file. for duration i guess we can receive inputs in float or int rperesntijg secs and cast to duration.

**Comment by y0sher** [comment]
I discovered that to use the cli parsing feature flag names must be single names 
(eg: "tcp" instead of "tcp, t" which enables multiple command line applications to the command)
Anyway you'll see a pr soon. I can use some advices about making the code more tidy, generic.

**Comment by avive** [comment]
Perhaps parsing the config file ourselves as you suggest and just updating matched flag values is the way to go as it looks like the cli bug is open for almost a year.
