### ISSUE TITLE
Data backup system for testnet swag store

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2002]
We need a way to back up testnet state, and possibly roll back the state in case of an issue, before we launch the swag shop.

**Comment by avive** [comment]
My thoughts on this task that the backup agent can be just client of the new api and that rolling back state is a bit over ambitious and we shouldn't try to have it now. So, in case of open testnet death event, we have all of the account balances at the time of death in an external db, and we can use it for at least rewards entitlements but users won't be able to purchase things with the store once this data testnet died. 

Here's a away to allow app users to restore their balances on a new testnet without restoring the whole state.
1. User backs up his tn1 wallet.
2. User join tn2 via the app and restores his tn1 wallet from backup.
3. User can request us to send him his old tn1 balance by signing a request using the wallet sign text feature. Heb basically proves to us that he has the private key of that wallet.
4. Tap operator sends him the amount of smesh he had at time of death...

This is clunky and manual but may suffice for up to say 100 top users who will want to redeem their old testnet coin on a new testnet.

**Comment by lrettig** [comment]
Could be a fun issue for a community contributor to work on, now that the API implementation is coming along. Adding Help Wanted tag.
