### ISSUE TITLE
Handle SIGTERM gracefully

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2003]
I noticed that sending a SIGTERM (using the `kill` command) causes the node to immediately exit, without even printing any message to the log. Can we trap this and handle it the same way we handle a SIGINT (ctrl-c)?

**Comment by moshababo** [comment]
@lrettig still relevant?

**Comment by lrettig** [comment]
Yes. We're gracefully handling `SIGINT`:

https://github.com/spacemeshos/go-spacemesh/blob/2e58ca2817765c4f7e7c2c9f7968a76d643ce285/cmd/base.go#L87-L89

but not `SIGTERM` (which, e.g., docker sends). This can lead to data corruption.

This is definitely doable, see: https://www.rudderstack.com/blog/implementing-graceful-shutdown-in-go/
