### ISSUE TITLE
Move genesis account configuration to config file

### ISSUE THREAD

**Issue by noamnelke** [spacemeshos/go-spacemesh#2004]
## Background
As highlighted in #1903, the default node configuration creates pre-loaded tap accounts for testing (whose private keys must be in the code). In an open testnet we don't want these accounts to exist.

It's currently possible to configure the pre-loaded accounts via the `GenesisConfPath` in the configuration, which should point to a file containing this configuration. This makes it technically harder to control.

## Required changes
The pre-loaded tap accounts should be configurable using the main `config.toml`.

### Inline tables in TOML
Including a list of objects in a TOML file doesn't have to be very hard. The TOML documentation lists the following option at the end of the section on [Array of Tables](https://github.com/toml-lang/toml#user-content-array-of-tables):
```toml
points = [ { x = 1, y = 2, z = 3 },
           { x = 7, y = 8, z = 9 },
           { x = 2, y = 4, z = 8 } ]
```

---

Of course the node doesn't require any particular format for config files, other than TOML, JSON and any other common format is supported.

**Comment by avive** [comment]
1. Can we move to support only json config files and not worry about toml specific issues? With spacecraft there's no toml config files anymore only json anyhow.
2. We need to decide if the genesis config which is going to include all the pre-configured svm smart wallets instances to be deployed on genesis, and tap accounts for testnets, is going to part of the single config.json file or a separate genesis.json config file that is provided to the node via a cli param. That data will be a large set for mainnet so it might be easier to manage in a separate file.

**Comment by noamnelke** [comment]
> 1. Can we move to support only json config files and not worry about toml specific issues? With spacecraft there's no toml config files anymore only json anyhow.

The node doesn't care about the format, so we don't need to do anything in that regard. The only problem right now is that the genesis config is in a separate config file, we just need to move it into the main one.

> 2. We need to decide if the genesis config which is going to include all the pre-configured svm smart wallets instances to be deployed on genesis, and tap accounts for testnets, is going to part of the single config.json file or a separate genesis.json config file that is provided to the node via a cli param. That data will be a large set for mainnet so it might be easier to manage in a separate file.

I don't know. It's currently in a separate file, so we can just keep it that way. We could make it optionally included, but I don't like that direction - we should use the same code paths for tests and production.

What I do think we should separate into two separate config files is the network/consensus config (params that all users of the same network should have in common: e.g. net id, minimum post space, etc.) vs. the local config (anything configurable by the user: e.g. folders, allocated PoST space, etc.).

**Comment by avive** [comment]
So what are the tasks that should be done to resolve this issue? Likely a good first issue for contributors here.

**Comment by avive** [comment]
> What I do think we should separate into two separate config files is the network/consensus config (params that all users of the same network should have in common: e.g. net id, minimum post space, etc.) vs. the local config (anything configurable by the user: e.g. folders, allocated PoST space, etc.).

@noamnelke - do you still want to have 2 config files? One for user settings and one for network-wide config? Isn't it enough to have a Node section in the config file with local node config? I think it will be good to avoid extra complexity and just use sections. 

One config file with 2 sections is simpler than having to deal with 2 config files with 1 section each IMO.

**Comment by noamnelke** [comment]
I'm confident that separating the config that's shared for the entire network from the config that each node operator sets for themselves will save us from many future issues.

I don't know if this will convince you, but btcd has a [config with user-params](https://github.com/btcsuite/btcd/blob/master/config.go) that references the "[chain config](https://github.com/btcsuite/btcd/tree/master/chaincfg)" (from a separate file).

Geth goes a step further and has separate config files for the [node](https://github.com/ethereum/go-ethereum/blob/a1f16bc74c7efb593db2982c92222d1e4a201c25/node/config.go#L53), [miner](https://github.com/ethereum/go-ethereum/blob/a1f16bc74c7efb593db2982c92222d1e4a201c25/miner/miner.go#L44), [metrics](https://github.com/ethereum/go-ethereum/blob/a1f16bc74c7efb593db2982c92222d1e4a201c25/metrics/config.go#L20) and [network (eth config)](https://github.com/ethereum/go-ethereum/blob/a1f16bc74c7efb593db2982c92222d1e4a201c25/eth/ethconfig/config.go#L121). In addition to all of these, it has a [params package](https://github.com/ethereum/go-ethereum/tree/master/params) with many hard-coded values used in the node (not sure why these are separate from the configs).

Separation of config files will make it easier to ensure that a user uses the correct network config - you could compare the hash of the file or the entire file contents without having to sift through user settings, some of which will be private, making sharing of the file harder/more dangerous.

I'm confident that we need _at least_ two files. We need to decide if we can benefit from splitting the "network config" into even more files, like geth. I actually like that approach.

**Comment by noamnelke** [comment]
On second thought I think I understand the motivation for hard-coded params that are separate from the config. If changing a param may not be supported by the code or the supported bounds are interdependent and hard to validate - it shouldn't be configurable. I haven't validated that this is the sort of params that geth puts in the params package, but we can consider something like what I described.

We can consider implementing this when we implement config validation, which is actually way overdue!

**Comment by avive** [comment]
Ok, so let's have `net.config` for the network config (immutable, easy to compute hash of deserialized json or similar) and `user.config` (or `node.config`) for providing user config values that override the node's sensible defaults such as node's post config. BTW, I think btc and eth configs jave limited value as references because the user experience for both is overly complicated IMO. Geth is notoriously hard to properly configure by node operators.

**Comment by dshulyak** [comment]
@noamnelke @avive so we can just close this (and https://github.com/spacemeshos/go-spacemesh/issues/2493) issue?

**Comment by avive** [comment]
> @noamnelke @avive so we can just close this (and #2493) issue?

Please clarify: why should we close these issues? We still want to support genesis accounts via a config file. Has this feature been implemented and merged to develop already?

**Comment by dshulyak** [comment]
There is an option to provide --genesis-conf. It allows setting initial accounts for genesis. This issue was about merging that config with the general node config. But i thought that the consensus is to keep two separate configs (one is kinda immutable, and one for general settings).

**Comment by avive** [comment]
I think there's a slight confusion here. The genesis account are part of consensus and therefore needs to be in the network config file. The user node settings are separate and should be in their own file. @noamnelke - correct me if I misunderstood but I thought we agreed that all genesis params should go into network.config and this include genesis accounts. I hope this is clearer.

**Comment by noamnelke** [comment]
Yes, @avive is correct here. We should add the genesis account config to the normal config (the single config we have right now) and later we'll want to separate user/node config from network/consensus config. Possibly, we'll also want the smeshing config (e.g. allocated space and coinbase account) and metrics reporting config (only if it's more than an endpoint, e.g. if we allow configuring what to report) separately (I think this would be a huge improvement).
