### ISSUE TITLE
Amounts in transactions sent in CLIWallet don't line up

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2006]
## Description

I'm sending testnet transactions from one smesher to another and running into some strange issues.

## Steps To Reproduce
- Fire up a testnet smesher
- Let it collect rewards
- Extract its account to use with CLIWallet (this tool can help: https://github.com/DaveAppleton/smesh2cli)
- Load the account in CLIWallet and send the balance to another account

## Issues

1. The account `Balance` showing up in CLIWallet seems to be wrong. See lines 50, 85, 86, 103, 118, and 149 in [this gist](https://gist.github.com/lrettig/a1bdcb22281c7c0b80b69d8b2185184a).
    - Line 50: original balance: 373743971890559
    - Lines 85, 86: I sent 100 smidge and paid 1 gas
    - Line 103: 373743971890559 - 101 = 373743971890458 (this amount looks correct)
    - Line 118: attempting to send entire balance and pay 1 gas (373743971890457 + 1)
    - Line 149: 379258815704992: the smesher received some more rewards - but the balance I just sent wasn't subtracted!
1. The amount showing up in the app on the receiver side is wrong (could be a UI issue? cf. https://github.com/spacemeshos/smapp/issues/483)

## Expected Behavior

Expected the amounts to add up :)

## Environment
Please complete the following information:
 - OS: Linux
 - Node Version: 0.1.9+4812339036139219b1aeeb6101e7866924e2d974
 - App Version (if applicable): 0.0.7
 - CLIWallet v0.0.1 (https://github.com/spacemeshos/CLIWallet/releases/tag/v0.0.1)

**Comment by lrettig** [comment]
Here's another pair:

```
> Balance:  380184741630917
> Nonce:  2
> Public key: 0x7082fa3f0db0b54c6afee03d91e0dd7590b8f659f586f48c2cd983fe6c9770d9
$ tx
> Transfer coins from local account to another account.
<APP> INFO 049 17:20:55.070 ▶ request: http://localhost:9090/v1/nonce, body: { "address": "0x91e0dd7590b8f659f586f48c2cd983fe6c9770d9"}
<APP> INFO 04a 17:20:55.071 ▶ response body: {"value":"2"}
<APP> INFO 04b 17:20:55.071 ▶ request: http://localhost:9090/v1/balance, body: { "address": "0x91e0dd7590b8f659f586f48c2cd983fe6c9770d9"}
<APP> INFO 04c 17:20:55.071 ▶ response body: {"value":"380184741630917"}
$ Enter or paste destination address: 0xC881B52CBa8AfC1C70fc28bD6DAaAFBAA7Bd975c
$ Enter amount to transfer in Smidge (SMD): 37925881570499299999999999999
$ Use default gas price (1 Smidge)? (y/n) y
> Transaction summary:
> From:   0x91E0dD7590b8f659F586f48C2cd983fE6c9770D9
> To:     0xC881B52CBa8AfC1C70fc28bD6DAaAFBAA7Bd975c
> Amount: 37925881570499299999999999999
> Gas:    1
> Nonce:  2
$ Confirm transaction (y/n): y
<APP> INFO 04d 17:21:19.422 ▶ request: http://localhost:9090/v1/submittransaction, body: { "tx": [0,0,0,0,0,0,0,2,200,129,181,44,186,138,252,28,112,252,40,189,109,170,175,186,167,189,151,92,0,0,0,0,0,0,0,100,0,0,0,0,0,0,0,1,0,0,0,0,255,255,255,255,133,148,147,56,182,78,251,95,193,31,31,126,186,40,231,141,121,221,62,197,168,99,228,101,54,230,100,30,200,173,106,50,40,220,75,86,236,108,212,228,194,123,214,153,158,131,86,172,141,208,54,94,239,84,218,56,87,197,164,176,231,12,75,10]}
<APP> INFO 04e 17:21:19.476 ▶ response body: {"value":"ok","id":"edb991cb295a9b8060d4671d417c22ab36393dd5b6bb0d3569e2f25a21aeb622"}
> tx submitted, id: edb991cb295a9b8060d4671d417c22ab36393dd5b6bb0d3569e2f25a21aeb622
$ info
<APP> INFO 04f 17:21:31.219 ▶ request: http://localhost:9090/v1/nonce, body: { "address": "0x91e0dd7590b8f659f586f48c2cd983fe6c9770d9"}
<APP> INFO 050 17:21:31.220 ▶ response body: {"value":"3"}
<APP> INFO 051 17:21:31.220 ▶ request: http://localhost:9090/v1/balance, body: { "address": "0x91e0dd7590b8f659f586f48c2cd983fe6c9770d9"}
<APP> INFO 052 17:21:31.220 ▶ response body: {"value":"380180446663621"}
> Local alias:  bar
> Address:  0x91e0dd7590b8f659f586f48c2cd983fe6c9770d9
> Balance:  380180446663621
> Nonce:  3
> Public key: 0x7082fa3f0db0b54c6afee03d91e0dd7590b8f659f586f48c2cd983fe6c9770d9
```

The actual tx amount appears to be 380184741630917 - 380180446663621 = 4294967296 or 4.2B smidge or ~0.004 SMH which lines up with what I see in the app on the receiver - but where did this number come from?

This may be a bug in CLIWallet.

**Comment by avive** [comment]
I see the same thing - when you attempt to send a large amount with CLIWallet - the actual transaction amount is set to 4294967296 smidge. It is not clear if this is a go-spacemesh or a CLIwallet issue without proper investigation.

**Comment by noamnelke** [comment]
This is a CLIWallet issue. I've explained on the issue there how we should fix it. Closing this.

https://github.com/spacemeshos/CLIWallet/issues/12#issuecomment-630348517
