### ISSUE TITLE
Account DB

### ISSUE THREAD

**Issue by zalmen** [spacemeshos/go-spacemesh#201]
A KV store holding the state of all accounts. The DB should support access to accounts data as it was at any point in history (block? layer? TBD).

Account {
  - Public key
  - Nonce
  - Balance
}

Exposed API:
- SetAccount(public key, Account) // will create new entry if no such key
- GetAccount(public key, point in history) -> Account/Null

Open questions:
- What defines a "point in history"? Block number? Layer number?

**Comment by antonlerner** [comment]
https://github.com/spacemeshos/go-spacemesh/wiki/Global-State

**Comment by zalmen** [comment]
@antonlerner, do you have any additional work to do on the Account DB? Are there any known issues that will require fixing/optimizing?
