### ISSUE TITLE
Сrash - block dfdf6 from layer 2307 has no explicit voting

### ISSUE THREAD

**Issue by ghost** [spacemeshos/go-spacemesh#2010]
## Description

Faucet node crashed. It trying to find peers in a few minutes and then crashes.
## Steps To Reproduce
1. Start node

## Environment
Please complete the following information:
 - OS: Ubuntu 18.04
 
 - Node Version: 0.1.9+4812339036139219b1aeeb6101e7866924e2d974
 

![image](https://user-images.githubusercontent.com/52304443/80920070-19feae80-8d76-11ea-93d0-e3f9f0140ef7.png)

![image](https://user-images.githubusercontent.com/52304443/80920076-2256e980-8d76-11ea-956c-e8590ac20262.png)

## Full log
[log.txt](https://github.com/spacemeshos/go-spacemesh/files/4570972/log.txt)

**Comment by y0sher** [comment]
hi, thanks for reporting, your logs indicate that you did have 5 peers connected when it crashed. this looks like a sync error, will look into it. also it seems that the layer we got the panic on was already synced, means it might be related to recovery and persistence, if you could provide previous logs it will be very helpful.

**Comment by ghost** [comment]
> if you could provide previous logs it will be very helpful.

@y0sher 
https://drive.google.com/open?id=12nBkba01QAwcyCuJALvvJxw-Lrr5HT17
From May 01 00:00:37 to May 03 18:27:25

**Comment by y0sher** [comment]
ok thanks! that really helped. form the logs I could extract that at some point you had problems with with writing permissions which resulted in errors when trying to add objects to leveldb.
there are a lot of lines like the following one -
``` 
a375d.sync         .blockFetchQueue        failed to add pending for Block f105e could not add bl f105e to database open sm_data/mesh/blocks/031012.log: permission denied        {"node_id": "a375d"}
```
this means we are not handling these errors on the best side and the database got corrupt. we will have to investigate further in order to solve this situation in the future by stopping the node and requiring to fix the permissions. 

for now try fixing your permissions, remove the existing database files and re-sync.

**Comment by ghost** [comment]
> for now try fixing your permissions

@y0sher 
I don’t understand what there might be a problem with permissions - the node is run as root. Btw, this is second time when i got corrupted DB

**Comment by y0sher** [comment]
`open sm_data/mesh/blocks/031012.log: permission denied` this is an error from the operating system, it could be caused by many reasons. 
what kind of storage are you using ?

**Comment by ghost** [comment]
> what kind of storage are you using ?

200 GB SSD. But it is virtual private server, i don't know exact ssd model
```
hdparm -Tt /dev/sda

/dev/sda:
 Timing cached reads:   12356 MB in  1.99 seconds = 6195.23 MB/sec
 Timing buffered disk reads: 558 MB in  3.00 seconds = 185.91 MB/sec
```

Not sure exactly what could have affected, but delays are pretty significant
![image](https://user-images.githubusercontent.com/52304443/81003699-ef832300-8e53-11ea-81d4-cd98b4c63752.png)

**Comment by antonlerner** [comment]
replaced by verifying tortoise #1856
