### ISSUE TITLE
to do integration testing

### ISSUE THREAD

**Issue by salvatore63** [spacemeshos/go-spacemesh#2013]
for   block_listener_test.go

**Comment by noamnelke** [comment]
Hey @salvatore63,

As I explained in [this comment](https://github.com/spacemeshos/go-spacemesh/issues/1986#issuecomment-621021588), we want to make a concentrated effort to convert code TODOs to issues, but those issues will have a specific format. Creating these issues now isn't very helpful, so I'm closing this for now.

Thanks again for taking an interest, see you on Discord 😉
