### ISSUE TITLE
Use `p2p.Peers` in `gossip.Protocol`

### ISSUE THREAD

**Issue by y0sher** [spacemeshos/go-spacemesh#2017]
## Description

We implemented the peer event handling code in `gossip.Protocol` before we wrote `p2p.Peers`, so there's much duplication there. we want to reduce that by making `gossip.Protocol` use the `p2p.Peers` struct to get informed about connected peers.

## Affected code
- `p2p.Peers`
- `p2p.gossip.Protocol`

## Notes:
this might require refactoring `p2p.Peers` to a different package (under `p2p`) to prevent a dependency cycle.

**Comment by anton-kuklin** [comment]
Will work on it
