### ISSUE TITLE
Transaction Processor 

### ISSUE THREAD

**Issue by zalmen** [spacemeshos/go-spacemesh#202]
Transaction processor:
Process incoming transactions and update current state.

Input -
Set of unsorted transactions with a mutual context (layer?)

Output -
A sorted list of accepted transactions and a sorted list of rejected transactions.

Use-cases -
- The TP should sort incoming transactions. 
- The TP should ignore duplicate transactions.
- The TP should reject syntactically invalid transactions (i.e. bad signature, bad format, etc.)
Foreach transaction:
- Execute the transaction using the accounts DB api:
  - Reduce amount and fee from sender and update nonce.
  - Increase amount to receiver (create one if non-existing) 
- Reject transaction with insufficient balance, invalid nonce.
  
Open questions -
- What is the basic structure that defines a point in history for which queries can apply? Block? Layer? 
- How do we grant the miners the transaction fee and miner reward?

**Comment by antonlerner** [comment]
https://github.com/spacemeshos/go-spacemesh/wiki/Global-State
