### ISSUE TITLE
Wallet balance stuck for 3 weeks despite rewards coming in

### ISSUE THREAD

**Issue by yaelmhoffman** [spacemeshos/go-spacemesh#2029]
The user has been running the smesher continuously, and rewards have been coming in, but the wallet balance doesn't change.

Logs:
https://drive.google.com/open?id=1E_tlWjFgG-8TTJ8Fh8STRpD4T-uZqoXd

Screenshots:
![Screenshot 2020-05-21 at 20 29 55](https://user-images.githubusercontent.com/56118594/82736419-5ba9c600-9d32-11ea-90ad-50a903cfd83f.png)
![Screenshot 2020-05-20 at 18 15 16](https://user-images.githubusercontent.com/56118594/82736420-5d738980-9d32-11ea-97d7-114c884f7ffa.png)

**Comment by avive** [comment]
Global state fork?

**Comment by avive** [comment]
@yaelmhoffman - are there additional reports like this or is the only user who experiences this issue?

**Comment by lrettig** [comment]
my smesher also stopped reporting rewards a while ago. and another user is reporting issues now in #bug_reports: https://discordapp.com/channels/623195163510046732/691261757921951756/713813426014650418

**Comment by y0sher** [comment]
@lrettig, you report something different, the above issues says you can see rewards coming but balance won't update..

anyway I can see many bad stuff in these logs, it can't validate hare messages and blocks even though he's synced. we need to look more thoroughly to understand exactly what happened.
though I can tell that from the beginning he starts with preloaded peers though none of them answer, so maybe the whole case is trying to run on older data. for now, delete all spacemesh data, p2p and mesh and try again.

**Comment by lrettig** [comment]
> @lrettig, you report something different, the above issues says you can see rewards coming but balance won't update..

I'm not sure whether I'm still getting rewards or not - let me know if I should investigate what's happening to my smesher

**Comment by lrettig** [comment]
Confirmed that I'm still receiving rewards, and my balance is being updated, but the rewards are not being displayed in the app - which leads me to believe it's a frontend issue

**Comment by avive** [comment]
Should be addressed in the latest app release - there's still the known duplicated transactions issue. This is likely not reproducible with the latest app release. Can you please ask this guy to install the latest app on the new network and report if he's still seeing this issue?
