### ISSUE TITLE
Parameterize two log statements relating to eligibility

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2042]
First:

> `Jun 22, 2020 @ 09:57:59.000 | asked for eligibility for epoch 385 (cached: 384)`

Second:

> `Jun 22, 2020 @ 12:42:59.001 | miner 7f994 found eligible for 0 blocks in layer 2343`

All of the numerical values here (epoch numbers, block eligibility count, layer number, and miner ID) should be broken out as params with their own log labels.

See similar work done in #1952 

Per @AmitShaul and @ilans, these log statements aren't currently being used for testing and are safe to modify

In case it's helpful, these logs can be viewed on Kibana: http://104.197.58.135:5601/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15h,to:now))&_a=(columns:!(sm.M,name),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:sm,key:name,negate:!f,params:(query:devnet45-miner-0-30),type:phrase),query:(match_phrase:(name:devnet45-miner-0-30)))),index:sm,interval:auto,query:(language:kuery,query:'sm.M:%22found%20eligible%20for%22'),sort:!())

**Comment by lrettig** [comment]
Here's an example of the kind of change that needs to be made:

https://github.com/spacemeshos/go-spacemesh/pull/1952/files#diff-a8d1aea5cc21c9a6122f8091d2aba940

**Comment by moshababo** [comment]
Obsolete.
