### ISSUE TITLE
Add db indices for ATX

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2064]
See e.g.:

https://github.com/spacemeshos/go-spacemesh/blob/bb63ec70d3d9f7ace9a8c08f755af6d7e0fdafac/api/grpcserver/mesh_service.go#L160-L172

This is required by the API. We don't currently have any way to look activations up by layer, or by coinbase. We should add indices for one or both of these.

**Comment by brusherru** [comment]
Outdated?
Seems it is working, I've just retrieved my activations by coinbase.

**Comment by lrettig** [comment]
It works but it's still brute force in the current version of the code. This issue is not outdated:

https://github.com/spacemeshos/go-spacemesh/blob/556e4da8c7bf1a649cff5ecd64b0aebde7949047/api/grpcserver/mesh_service.go#L120-L152

**Comment by lrettig** [comment]
Hi @countvonzero, why was this closed? It doesn't appear to have been completed and the ugly, brute force code is still there, which appears to be the cause of #5006

**Comment by countvonzero** [comment]
it is closed because when this issue is opened, we are using leveldb. 

the title said "Add db indices for ATX". what does that mean? add what index?
why do we want to index atx by layer? why can this only be solved by indexing db?
 
please let #5006 stand and close this issue. i don't see how this issue help. lets focus on the memory problem described there and find a solution. it doesn't have to be solved by db.

**Comment by lrettig** [comment]
Thanks for providing context. I wrote the underlying code in a naive, brute force fashion, where it loops over every single ATX in order to filter on layer and coinbase. I don't think this task is specific to any particular database (and the title could probably be clearer). It looks like this code hasn't been updated. Also, there's still a link to this issue in the code; if this issue is being closed as no longer relevant, the TODO comment in the code should also be removed:

https://github.com/spacemeshos/go-spacemesh/blob/52949ec1a32b8698577578e67be4cdf0cc34056e/api/grpcserver/mesh_service.go#L125-L155

We can continue to work on this in #5006

**Comment by lrettig** [comment]
Follow up in linked issue
