### ISSUE TITLE
Log does not need to output to logfile

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2065]
These params are ignored by the function. This change was made in #1323, but this still needs to be cleaned up.

https://github.com/spacemeshos/go-spacemesh/blob/61eafeeb2a9e3ec785113cf8284eec8bf8ef6ee9/log/log.go#L127-L129

In fact AFAICT all of the functionality for logging to a file is not used anywhere (except in the log tests).

**Comment by stuartwk** [comment]
Is this just a matter of removing the function params then cleaning up the instances where it's called? If so, I can clean this up.
