### ISSUE TITLE
Remove time.Sleep from tests

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2067]
## Description
We use `time.Sleep` throughout our tests while e.g. waiting for a goroutine or service to spin up. In general this isn't a great idea because it's fragile, and also because it slows down the tests quite a bit. Most or all of these Sleep statements can probably be replaced with concurrency tools like channels, waitgroups, mutexes, etc.

See one example of such a fix here: 9bc6794f29f7bb7d0deab7aae2870af2c11adae1

## Affected code
Many tests, grep for `time.Sleep`

**Comment by u5surf** [comment]
@lrettig I would like to try to this issue

problematic case is e.g. 
https://github.com/spacemeshos/go-spacemesh/blob/b49a23f5d839f0d2d24b5b4f34f2fd372eeb97e8/cmd/sync/sync_test.go#L24

**Comment by lrettig** [comment]
Welcome to give it a shot! Not sure how much experience you have with concurrency in go but it would be great practice. I haven't analyzed this test in depth so I can't explain exactly what's going on here or how I'd fix it, but at a glance, it looks like the syncer should notify a channel every time it processes a layer, and the test should pass after 20 layers have been processed, or fail if the 20 secs passes first instead.

**Comment by lrettig** [comment]
Here's another good example: https://github.com/spacemeshos/go-spacemesh/commit/4f35f7b7e899788bfbd945aff3abd507ed4f54c3

**Comment by lrettig** [comment]
Another example: #2422
