### ISSUE TITLE
Add db index for reward smesher ID

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2068]
For the API we need to know which smesher and coinbase received each reward (https://github.com/spacemeshos/api/blob/ff4a9a6b913a23a83cf07a0a7b4b7c16605ce9c0/proto/spacemesh/v1/types.proto#L100-L107). Right now, we can find rewards by account that received the reward but there is no smesher ID or coinbase attached to it:

https://github.com/spacemeshos/go-spacemesh/blob/61eafeeb2a9e3ec785113cf8284eec8bf8ef6ee9/mesh/meshdb.go#L436

Similar to #2064

**Comment by noamnelke** [comment]
specifically the coinbase is known, because that's how we retrieve the reward in the first place, so we could just fill that in

**Comment by lrettig** [comment]
The account that received the reward is the coinbase - we may want to rename this, depending how we ultimately design incentives and rewards (as smoothing makes the concept of a "coinbase" account seem slightly off) - but, as Noam pointed out, we do have this data and indeed this is how it's currently indexed. We do _not_ currently store SmesherId in the database. So the scope of this issue is:

- add SmesherId to the [Reward type](https://github.com/spacemeshos/go-spacemesh/blob/fdcff23bf731ca495672129ba8b05fb110da189d/common/types/transaction.go#L129-L134) (other code may need to change; be sure to update existing tests and/or add a test for this)
- store it in the database when rewards are calculated and stored
- make sure it's returned by [meshdb.GetRewards](https://github.com/spacemeshos/go-spacemesh/blob/61eafeeb2a9e3ec785113cf8284eec8bf8ef6ee9/mesh/meshdb.go#L436-L461)
- surface it [in the API code](https://github.com/spacemeshos/go-spacemesh/blob/e0c08c459b12edbfba126a2a2453962a5076e7f9/api/grpcserver/globalstate_service.go#L124-L144)
- add a database index from smesher ID -> reward (or reward ID)
- use it to finish implementing `SmesherRewardStream` and `SmesherDataQuery` in `api/grpcserver/globalstate_service.go`

**Comment by sidsankhe** [comment]
Currently, the database does not take into account that a single Coinbase could be associated with multiple SmesherIDs. When writing the transaction rewards to the database, the key is of the form `reward_<coinbase>_<layerID>`, and the reward struct is for a specific Coinbase and SmesherID. Since multiple SmesherIDs could share a Coinbase, we cannot differentiate between different rewards with the same Coinbase but different SmesherIDs with this current key-scheme. Therefore, we are extending the primary database key to be of the form `reward_<coinbase>_<smesherID>_<layerID>`. In order to perform efficient look-ups of rewards by SmesherIDs, we will have to add a secondary key of the form `reward_<smesherID>_<coinbase>_<layerID>` that points to the primary key, and then the lookup becomes a two-step process, but we can do this via the prefix-matching that LevelDB offers.

**Comment by lrettig** [comment]
@avive, API-related question regarding database indices and sort order of rewards: Sid pointed out that, if we refactor the DB index for reward along the lines described above, we can no longer guarantee that rewards (per-smesher, or per-coinbase) will be returned from the API in order of layer. They'll be returned in order of `(smesherID, layer)` (when querying by coinbase) or `(coinbase, layer)` (when querying by smesherID). In other words, if one smesher has rewards accumulated to multiple coinbases, the rewards will come out of the database grouped by coinbase; and if one coinbase has accumulated rewards from multiple smeshers, they'll come out of the database grouped by smesher.

The question is, how important is it that we be able to return rewards (by coinbase, or by smesher) strictly sorted by layer?

**Comment by avive** [comment]
I think it is okay and clients can sort the data as they like once they have it quite easily. However, doesn't all of this pending on whether we are going to have epoch-wide rewards smoothing? if there's smoothing then the reward amount is per epoch and not tied to specific layers. So, for example, if I smeshed in 3 layers in an epoch and got 1 SMH reward for that epoch then can we assume 1/3 SMH per layer?

**Comment by lrettig** [comment]
You're right, but there's still a layer associated with each reward - in the case of epoch smoothing, it would become the layer at which the reward is calculated, or paid, or vests, something along those lines. We have yet to figure out exactly how this will work, but I think the question I asked here remains the same. We'll just make sure this is clearly documented.

**Comment by noamnelke** [comment]
Why not make it `reward_<coinbase>_<layerID>_<smesherID>` and `reward_<smesherID>_<layerID>_<coinbase>`?

Or, if we only have endpoints for rewards by coinbase or by smesher and there's no need for internal differentiation (other than by layer) then we can just have `reward_<coinbase>_<layerID>` and `reward_<smesher_id>_<layerID>` with a sum inside.
