### ISSUE TITLE
Standardize rewards type

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2069]
We use the type `big.Int` to store rewards, but everywhere else, including in the log statement at the bottom of this chunk, and in the API code, we use uint64. Can the reward amount ever be negative? If not, can we harmonize this type and move it all to uint64?

https://github.com/spacemeshos/go-spacemesh/blob/b49a23f5d839f0d2d24b5b4f34f2fd372eeb97e8/mesh/mesh.go#L691-L714

**Comment by neysofu** [comment]
Resurrecting this just to document that we're set on using `uint64`. This decision seems to be final.

https://github.com/spacemeshos/go-spacemesh/issues/2718#issuecomment-941092617
