### ISSUE TITLE
api-phase8 build error

### ISSUE THREAD

**Issue by AndrewAR2** [spacemeshos/go-spacemesh#2070]
## Description
When trying to build go-spacemesh branch 'api-phase8', the error is thrown:
```
events/reporter.go:294:3: cannot use make(chan *types.Layer) (type chan *types.Layer) as type chan NewLayer in field value
```
## Steps To Reproduce
`go build` or `make build`

**Comment by lrettig** [comment]
Good catch, thanks :) Fixed in https://github.com/spacemeshos/go-spacemesh/pull/2061/commits/dad50a3303cb5263c67ab7250c6b77a8c45f4dac. Please try building again!

**Comment by AndrewAR2** [comment]
Now it works! Thank you!!!
