### ISSUE TITLE
Optimize offset handling for API Query endpoints

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2073]
## Description

The *Query endpoints in the API accept an optional Offset parameter, which allows them to return paginated results. The naive way to handle this is to recalculate all of the possible data to be returned, then just return it starting from the offset - this is how it's implemented today. Obviously, this is inefficient and we can do better.

One possibility is to cache the original lookup results. A better option would be to allow each of the underlying queries to also accept an offset and maxresults params, though I'm not sure how easy it would be to add support for this to the database.

## Affected code

https://github.com/spacemeshos/go-spacemesh/blob/aa7eb73e121e7746de3468d1a365523dc729e3fb/api/grpcserver/globalstate_service.go#L134-L152

**Comment by dshulyak** [comment]
Unfortunately design of the offset is completely bugged, collection must be ordered by the offset key. This is not going to work if offset is set to some random integer, that has nothing to do with a collection order. For example collection is ordered by layer id - layer id is a good offset. Integer is a good offset only if collection is ordered by autoincremented id, which is usually the case with common backend applications.

**Comment by lrettig** [comment]
How is the collection in the DB ordered now?

**Comment by dshulyak** [comment]
accounts? lexicographically
