### ISSUE TITLE
Implement app events

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2074]
Opening as a placeholder to implement support for smart contract (app) events. This could not be implemented in the API since go-spacemesh does not support this yet:

https://github.com/spacemeshos/go-spacemesh/blob/aa7eb73e121e7746de3468d1a365523dc729e3fb/api/grpcserver/globalstate_service.go#L301-L308

CC @YaronWittenstein

**Comment by dshulyak** [comment]
i will actually close this. when the time comes it will be tracked elsewhere (svm probably)
