### ISSUE TITLE
api-phase9 build error

### ISSUE THREAD

**Issue by AndrewAR2** [spacemeshos/go-spacemesh#2079]
## Description
When trying to build go-spacemesh branch 'api-phase9', the error is thrown:
```
cmd/node/node.go:726:3: undefined: startService
cmd/node/node.go:729:3: undefined: startService
cmd/node/node.go:732:3: undefined: startService
```

## Steps To Reproduce
`go build` or `make build`

**Comment by lrettig** [comment]
Sorry about that, this was the result of a merge conflict, resolved in https://github.com/spacemeshos/go-spacemesh/pull/2071/commits/8ea2e0fd5c013ecca730852bd3c9d88147e3850a

Thanks for the heads up :)
