### ISSUE TITLE
Go version check script fails on MacOS X

### ISSUE THREAD

**Issue by divan** [spacemeshos/go-spacemesh#2097]
## Description
The `./scripts/check-go-version.sh` which is run by Makefile, doesn't check Go version properly on MacOS X. In my case I have latest Go (1.14.6) installed, while script throws error saying Go 1.14+ is required.

## Steps To Reproduce
1. find Macbook
2. git clone go-spacemesh develop branch
3. run `make`
4. See error: `Go 1.14+ is required (vgo.version.go1.14.6 darwin/amd64 is installed at /usr/local/go/bin/go)`

## Expected Behavior
Go version is checked correctly, no error is shown, exit code 0.

## Environment
 - OS: MacOS X 10.15.5 Catalina 
 - Shell: GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)

## Additional Resources 
This bug seems to be due to the differences between default MacOS X `sed` and GNU sed. One of the solutions would be to use different tool – `gsed` from the [`gnu-sed`](https://formulae.brew.sh/formula/gnu-sed) package and check for the correct platform in the script. Another one would be rewriting semver parsing code in a way that doesn't use `sed`.

**Comment by lrettig** [comment]
Hi @divan, thanks for opening this issue and the PR. Both BSD sed and GNU sed appear to be working for me in macOS 10.15:

```
> go version | sed 's/go version go\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\).*/\1 \2 \3/'
1 14 6
> go version | gsed 's/go version go\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\).*/\1 \2 \3/'
1 14 6
> sw_vers -productVersion
10.15.6
> gsed --version
gsed (GNU sed) 4.8

```

Perhaps there's something else in your environment that's causing this issue?

**Comment by divan** [comment]
Hmm, it turns out it's not a sed issue, but regexp's one. It works correctly only for Go versions that do have patch number.

```
$ echo "go version go1.14.6 darwin/amd64" | sed 's/go version go\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\).*/\1 \2 \3/'
1 14 6
$ echo "go version go1.14 darwin/amd64" | sed 's/go version go\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\).*/\1 \2 \3/'
go version go1.14 darwin/amd64
```
So in my case I had currently active installation of Go version 1.14 (without patch numbers), thus the script was failing.

One of the solutions is to modify regexp to parse Go versions without patch number correctly. Another one is to use a proposed solution (https://github.com/spacemeshos/go-spacemesh/pull/2098) which doesn't use sed and regexps.

**Comment by lrettig** [comment]
I think this is my fault. Reverting this change might fix it!

https://github.com/spacemeshos/go-spacemesh/pull/2052/files#diff-4bda0207ee3bbd1b352c7fc15cccc589

**Comment by divan** [comment]
To me the less moving parts in the script the better, but whatever you prefer.
