### ISSUE TITLE
API account counter issue

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2104]
## Description
Calling `GlobalStateService.Account` returns the actual account counter (nonce) (along with balance) from global state. However, this is _not_ the counter value that should be included in a newly-submitted tx. For a new tx, the system expects the counter to match the _projected_ counter value returned by `TransactionProcessor.GetProjection`, which factors in pending transactions:

https://github.com/spacemeshos/go-spacemesh/blob/1c818789facf0e7219feb7d8d5737ce6b6776835/mesh/meshdb.go#L576-L584

If a client naively reads account data from the API, then tries to submit a tx, it will fail as a result.

CC @noamnelke @avive, would appreciate your input on this.

## Steps To Reproduce
1. Call `GlobalStateService.Account`
2. Submit a new, valid tx to `TransactionService.SubmitTransaction` using the account counter you just got. If there are any pending txs from this sender, it will fail.

## Expected Behavior
I see a few options:

- return projected counter and balance instead of current values from global state - probably a bad idea
- add a new API endpoint to get _projected_ account data
- add projected data to the existing account API endpoints

**Comment by noamnelke** [comment]
The old api had `GetNonce` and `GetBalace` endpoints which returned projected values.

I agree that it can be confusing to get an account info without the projected values. I think that from an api-consumer perspective it's best to get those values as part of the existing account endpoints, in addition to the "final" data from the state. Any reason not to do it that way?

**Comment by lrettig** [comment]
I agree. I'll update the API to add projected as well as current state values.

**Comment by lrettig** [comment]
The API has been updated. I'm adding support for the latest API release in #2133 which should take care of this.
