### ISSUE TITLE
Update tx generator script to work with devnet

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2105]
We want to use this to generate a bunch of tx data in the devnet that will flow through to the dashboard and explorer. This script was written to run inside a kubernetes environment, and it needs some modification to run outside this environment and to talk to a specific node on a specific port. It also needs updating to work with the new GRPC API.

#2185 should be done first

**Comment by lrettig** [comment]
This is blocking on #2133.

**Comment by lrettig** [comment]
This is no longer blocking on anything. It's not a strict dependency but it would be nice to work on this along with #2185.

**Comment by moshababo** [comment]
@lrettig still relevant?

**Comment by lrettig** [comment]
Nope, not even sure if this still exists
