### ISSUE TITLE
Create basic fetch mechanism

### ISSUE THREAD

**Issue by antonlerner** [spacemeshos/go-spacemesh#2108]
## Description
Create a basic fetch mechanism capable of sending  a hash and receiving a response in a form of a byte buffer. 
The received buffer can be validated with a special callback function

The fetch mechanism needs to have a cache of requests, so that multiple requests for same data will not be performed

Fetch mechanism must include meta data to hint the other peer where to fetch data from

The mechanism must be efficient in a way that requests will be split to multiple peers

**Comment by hoenirvili** [comment]
This should be a stand-alone package inside go-spacemesh or this should be integrated further into an api?
