### ISSUE TITLE
Fix missing newTx test function

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2117]
There are several lingering references to this function, here is one of them:

https://github.com/spacemeshos/go-spacemesh/blob/efa7538ba4fbb4ea90be43c827233a580c736e19/state/tx_pool_test.go#L33

It was removed in #2011 / efa7538ba4fbb4ea90be43c827233a580c736e19 and based on the diff it looks like it was supposed to be replaced by `mesh.NewSignedTx`.

CC @antonlerner

**Comment by moshababo** [comment]
Seems to be outdated.
