### ISSUE TITLE
Errors attempting to sync with different protocol version

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2122]
## Description
If I connect to a running network and try to sync a node that's running a different build than the one the network is running, I get very strange, cryptic errors - e.g., deserialization errors trying to read the block data provided by peers.

Expected behavior is that the initial sync/p2p handshake would fail and there would be a clear error message about the mismatch in protocol versions. Nodes running incompatible protocol versions should detect this immediately and not try to exchange any messages - ideally they would not even peer with one another.

Of course this raises the question, what exactly defines a protocol version? We may need to manually hardcode this each time it changes - but at the very least, it should change when message or serialization format change, and probably when consensus rules change too. (Nodes with incompatible config flags should also not try to talk to one another. This would be easier to compare programmatically, if we're not already doing that.)

**Comment by y0sher** [comment]
#87 is open for long time. we haven't done anything major in this since we haven't released a backward compatible version yet. currently we only exchange the ClientVersion and disconnect when it's different. but this has to be updated manually with every version to actually affect something.

**Comment by lrettig** [comment]
Thanks, I'll close in favor of #87 and we can take the conversation there.
