### ISSUE TITLE
Node panics on restricted network

### ISSUE THREAD

**Issue by avive** [spacemeshos/go-spacemesh#2132]
## Description
Node panics during initial sync.

## Steps To Reproduce
Start node on restricted network (@avive please provide more details on what the restrictions are, if possible).

## Expected Behavior
Node should finish syncing and stay up to date.

## Environment
Please complete the following information:
 - OS: OS X, iMac.
 - Node Version:  0.1.13

## Additional Resources 
[logs.zip](https://github.com/spacemeshos/go-spacemesh/files/5146008/logs.zip)

**Comment by avive** [comment]
Turns out an office Internet connection was the issue and once user switched to a different network everything works fine.

**Comment by lrettig** [comment]
It would still be good to know what's going on here. Took a look at the logs, the node seems to be connecting and syncing properly but there are a few errors that keep appearing:

```
WARN	ticker	skipping tick since we missed the time of the tick by more than the allowed threshold	{"threshold": "500ms"}
ERROR	clock	could not notify subscribers	{"message": "missed tick time by more than the allowed threshold", "missed": 0}
ERROR	c6c8b.hare         	Error contextually validating message	{"node_id": "c6c8b", "msg_type": "Status", "sender_id": "f3873", "current_k": 1, "msg_k": 0, "layer_id": 413, "message": "incorrect round"}
WARN	c6c8b.hare         	encountered late PreRound message	{"node_id": "c6c8b", "sender_id": "1d2f5", "layer_id": 433}
ERROR	c6c8b.blockBuilder 	transaction origin does not exist	{"node_id": "c6c8b", "transaction": "<id: 6ca46, origin: 0xC4EAB, recipient: 0x077cB, amount: 4294967295, nonce: 0, gas_limit: 100, fee: 1>", "tx_id": "6ca46", "origin": "0xC4EAB"}

```

Also @avive regarding the behavior of the smapp, don't you think that the Spacemesh logo spinning forever is an issue? Why would that happen, if the node is connected and syncing? What explains this, from the app log?

```
[2020-08-29 09:12:00.505] [error] In nodeManager, in startNode, error is: Error: Command failed: "/Applications/Spacemesh.app/Contents/node/go-spacemesh" --grpc-server --json-server --tcp-port 7153 --config "/Applications/Spacemesh.app/Contents/config/config.json" -d "/Users/yasuomi.takeda/Library/Application Support/Spacemesh/node-data" >> "/Users/yasuomi.takeda/Library/Application Support/Spacemesh/spacemesh-log.txt"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7c pc=0x432ea97]

goroutine 1 [running]:
net/http.(*Server).Shutdown(0x0, 0x4c8c480, 0xc000136010, 0x0, 0x0)
	/usr/local/Cellar/go/1.14.5/libexec/src/net/http/server.go:2698 +0x57
github.com/spacemeshos/go-spacemesh/api.(*JSONHTTPServer).Close(0xc009c78160, 0x0, 0x4b0a9d9)
	/Users/avive/dev/go-spacemesh/api/http_server.go:31 +0x96
github.com/spacemeshos/go-spacemesh/cmd/node.(*SpacemeshApp).stopServices(0xc000334480)
	/Users/avive/dev/go-spacemesh/cmd/node/node.go:679 +0x8bc
github.com/spacemeshos/go-spacemesh/cmd/node.(*SpacemeshApp).Cleanup(0xc000334480, 0x5402f20, 0xc000320180, 0x0, 0x8, 0x0, 0x0)
	/Users/avive/dev/go-spacemesh/cmd/node/node.go:290 +0x7a
github.com/spacemeshos/go-spacemesh/cmd/node.glob..func1(0x5402f20, 0xc000320180, 0x0, 0x8)
	/Users/avive/dev/go-spacemesh/cmd/node/node.go:94 +0x23e
github.com/spf13/cobra.(*Command).execute(0x5402f20, 0xc000138010, 0x8, 0x8, 0x5402f20, 0xc000138010)
	/Users/avive/dev/go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:766 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x5402f20, 0xc000000180, 0xc0001d1f78, 0x4007d3f)
	/Users/avive/dev/go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:850 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/avive/dev/go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:800
main.main()
	/Users/avive/dev/go-spacemesh/main.go:23 +0xac
```

**Comment by avive** [comment]
It is going to be very hard to reproduce this. @y0sher looked at the node logs and claim he sees nothing bad there.

**Comment by avive** [comment]
The node panic looks like an exception in cleanup. Might be worth ensuring that an error on closing the jsonhttpserver doesn't panic the node... @y0sher .

**Comment by lrettig** [comment]
@avive my main question here is about smapp, not go-spacemesh:

> don't you think that the Spacemesh logo spinning forever is an issue? Why would that happen, if the node is connected and syncing? What explains this, from the app log?

**Comment by avive** [comment]
It is fairly rudimentary - the logo currently keeps spinning until it can connect to the local node. This is about to change soon due to the new startup experience flows and the new features. Current code doesn't handle well the case that smapp can never connect to the node. In the updated startup flow (See https://product.spacemesh.io/#/smapp_wallets_flows), the node is started only in some cases and we need to handle app and node communications errors better for sure. So I don't think that it is worth fixing this rare issue for now because the whole flow is going to be updated very soon (in a matter of weeks). We also don't have evidence that this issue is common.

**Comment by noamnelke** [comment]
@avive this kind of issue description is more suitable to the SMApp repo. The issue is that the SMApp fails to display a proper error message to the user. When the node panics, the SMApp must display the panic message to the user and direct them to report the issue along with a shortcut to the logs folder on their machine.

The issue in this repo should not include any details on the UI (e.g. spinning logo). You could post an issue saying something like "node panics with message X" and attach the logs. Sorry for being strict about this, but irrelevant details like how the SMApp handles the panic confuse and distract from the node issue.

**Comment by noamnelke** [comment]
I've edited the description and title of this issue to make it more suitable for this repository.

**Comment by avive** [comment]
This is clearly a go-sm node issue - you can see the flags that smapp uses to start it in lane's comment. There is no other magic. I assume it will panic in a similar way if started via terminal on a restricted network. Smapp handling of node error should be a a separate issue and I will open one to handle node crashes but this issue is about the node panic on restricted network. Cool?

**Comment by noamnelke** [comment]
The problem was with the previous title and description. I'm not saying there's no issue at all. See how I phrased it in comparison to how it was before.

**Comment by lrettig** [comment]
Opened https://github.com/spacemeshos/smapp/issues/575 to track the frontend issue - @noamnelke thanks for sorting out the metadata on this side!

**Comment by lrettig** [comment]
No pending task here afaict
