### ISSUE TITLE
Can't get balance or nonce for genesis accounts on Testnet

### ISSUE THREAD

**Issue by avive** [spacemeshos/go-spacemesh#2145]
## Description
API methods nonce and balance return account doesn't exist for genesis accounts. Due to this issue, we can't fund the community tap or test transactions on the network before a smesher gets a reward.

## Rerpo
1. Sync a full node on open testnet net-id 118.
2. From the terminal (or via any api client such as CLIWallet) try to get balance or nonce of one of the genesis accounts via the api:

```
curl -d '{"address": "0x1"}' 'localhost:9090/v1/balance'
```

## Result:
{"error":"account does not exist","message":"account does not exist","code":2}

## Expected Behavior
API to return correct genesis account balance.

## These should be the genesis account for an open testnet:
0xc4eabd379d646beb6e065934cf7e9de59f8d43e7
0x18cd748bd82496c4341aad3e66930c855349aa48
0x1

The log file indicated the genesis accounts were created as expected:

```
2020-09-17T21:33:11.743+0300	INFO	99e36.app          	Genesis account created: 0x1, Balance: %!s(uint64=100000000000000000)	{"node_id": "99e36"}
2020-09-17T21:33:11.743+0300	INFO	99e36.app          	Genesis account created: c007a95dc5b50c3ebbb8ff6bc4eabd379d646beb6e065934cf7e9de59f8d43e7, Balance: %!s(uint64=100000000000000000)	{"node_id": "99e36"}
2020-09-17T21:33:11.743+0300	INFO	99e36.app          	Genesis account created: 9707fd32f9e96a72c4fa1b0f18cd748bd82496c4341aad3e66930c855349aa48, Balance: %!s(uint64=100000000000000000)	{"node_id": "99e36"}
```

**Comment by lrettig** [comment]
I'm testing this while syncing a node. It seems like the error happens while the node is syncing - but at some point it goes away, as my fully-synced nodes work fine.

```
lane@smesh-dev-nyc-5:~$ curl -d '{"address": "0x1"}' 'localhost:9090/v1/balance'
{"value":"100000000000000000"}
```

**Comment by lrettig** [comment]
I don't know what's causing this or when the error goes away - it does NOT appear to be when the node has synced past the first or second epoch, nor when it's fully synced - but eventually the error does go away. However, I'm inclined to ignore it since the new API seems to work fine immediately after the node first boots up:

```
smesh-dev-nyc-6:~$ curl localhost:19093/v1/globalstate/account -d '{"account_id": {"address": "AAAAAAAAAAAAAAAAAAAAAAAAAAE="}}'
{"account_wrapper":{"account_id":{"address":"AAAAAAAAAAAAAAAAAAAAAAAAAAE="},"balance":{"value":"100000000000000000"}}}
```

**Comment by lrettig** [comment]
@avive I'm in the process of removing the old API anyway in #2131, can we just switch to the new API instead of trying to fix this?

**Comment by avive** [comment]
I don't know - it depends if there are any tests / devops services that depend on it - I think Spacecraft 3.0 relies on api 1.0 to work properly and possibly some api tests. @noamnelke - btw, I've tried this many times and again just now - on a synced net id node 118 /v1/balance and /v1/nonce  for built-in test genesis account 0x1 return account doesn't exist.

**Comment by lrettig** [comment]
Pending #2131, tests will no longer rely on the old API, and spacecraft also should not. I'm going to mark this issue as resolved by that PR, let me know if you disagree.
