### ISSUE TITLE
Document how to run multiple smeshers

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2147]
We've had a few community questions on this. We should document best practices for doing this - how to run multiple nodes on one machine, resource requirements when doing this, how to set the ports correctly, logging, using VMs, how to use the same coinbase and see the rewards accrue in the app, any other networking considerations, etc. We should explain that this won't be terribly helpful longer term once you can configure any amount of storage space, but it should be documented anyway since some folks will inevitably want to run multiple nodes/have multiple identities.

From Discord:

> how do I spawn multiple copies of the app with a single wallet?
> you can't currently spawn multiple smeshers with a single app, but you can run as many as you want from the command-line. instructions are here: https://github.com/spacemeshos/go-spacemesh#joining-spacemesh-tweedledee-testnet-net-id-118
> just make sure they each get a different port, datadir, and post datadir `--tcp-port $x -d $y --post-datadir $z`
> and, if you run the GRPC/JSON APIs, you need to give those different ports too
> also you can pass in the same `--coinbase` address to each, and use the address that you set up in the smapp application, so that you'd see your rewards accrue in the app

**Comment by avive** [comment]
The best path for this as far as wallets are concerned is to use CLIWallet (api client) with  the `server` param to connect to the json-http api 0.1 of any node on same machine or over the network (host:port). It defaults to localhost:9090 - which is the default json-http api interface for a local running node. All of this should be of course better documented. I can add a page to the testnet guide about running a full node without smapp and outline multiple nodes per machine scenario with a caveat that this is not needed once variable post is supported.

We also don't have support yet in CLIWallet for smeshing and it doesn't make sense to add it as we migrate to api 2.0 for that. So smeshing setup needs to be described via node cli flags for now - like we explain in the go-sm repo readme...

**Comment by avive** [comment]
There's also Anton's video about how to join the testnet with a go-sm node without smapp: https://www.youtube.com/watch?v=mqbSeCTYRaY

**Comment by lrettig** [comment]
I think https://github.com/spacemeshos/local-testnet does this well. Closing, let me know if you disagree.
