### ISSUE TITLE
Add test name to logger output for tests

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2150]
When reading the output of tests, such as in CI (travis/github actions), it's very difficult to tell which test produced which log lines. Some tests are very verbose. Sometimes a test fires off a goroutine which continues to output even after the test has ended ([example](https://travis-ci.org/github/spacemeshos/go-spacemesh/jobs/729699754)). It would be very helpful to add the name of the test to each log line as additional context (when running inside a test).

**Comment by devamanv** [comment]
@lrettig I am a first time contributor and would like to work on this issue. Please help me get started and assign the issue to me.

**Comment by lrettig** [comment]
Hi @amanviitb, nice to meet you, you are more than welcome to contribute and take on this task. Would you mind starting by proposing a plan of attack, and letting me know if you have any questions? If you're not already on our Discord, you can join at http://chat.spacemesh.io/ and we can discuss via direct message there as well (look for me in the `#dev_discussion` channel!).
