### ISSUE TITLE
Remove "travis timeout" patches

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2170]
## Description
There are several patches in tests that are intended to address an issue with travis CI (deprecated in #2165) that should no longer be needed under GitHub Actions. A couple of them are visible here (and there may be others):

- https://github.com/spacemeshos/go-spacemesh/pull/2165/commits/f68d33862ca7878f2f3aafc76e7ef13929043831#diff-79678d10f0e157689bf0df3adbd13d4a7d668326cbaf7a62ee4ef8b5497ff636
- https://github.com/spacemeshos/go-spacemesh/pull/2165/commits/f68d33862ca7878f2f3aafc76e7ef13929043831#diff-b4ede24417d57b1c277ce8f79d071570753a3e59742c3f757577ef87e24c72a5

We should remove these patches now that we're using GH Actions (assuming of course that doing so doesn't break anything)

## Affected code
Various test code

This issue appears in commit hash: 4d27c598a63f28b478dd803abb6002f8a93452cb

CC @noamnelke

**Comment by moshababo** [comment]
@lrettig still relevant?

**Comment by lrettig** [comment]
Don't think so, these appear to have been removed
