### ISSUE TITLE
GitHub Actions not triggering on push without changes

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2179]
Opening this to document a strange issue that @noamnelke discovered today. It appears that, when we `bors try` a PR and the tests fail, then we `bors try` again, GH Actions fails to trigger the `push` workflow the second time if there are no changes to the code. I confirmed that making a tiny, superficial change to the code causes it to work again. It appears that Actions has an optimization where, if there's a subsequent push to the same branch with no change to the code, it doesn't run again. I can't find this documented anywhere, but it may be an issue with bors and flakey tests.

Bors sort of doesn't play nice with Actions so this is not terribly surprising.

At the very least we should understand what's going on and make sure it's documented. We should consider workarounds, too. Random ideas:

- cause the relevant workflow to make a superficial commit to the source branch if a push to staging fails (e.g., a file that tracks the last commit hash or something)
- use a different branch name for each try (e.g., `staging-XXXXXX` where `XXXXXX` is derived from the time, source branch, latest commit hash, or something) - most workflows support wildcards in branch names so this might work
- "force" a workflow to run using the GH API
- make bors smart enough to _rerun_ the previous workflow instead of creating a new push

**Comment by lrettig** [comment]
Oddly enough this does not appear to be a problem for `bors merge`, which happily reruns all of the actions in `staging`. It's only an issue for `bors try`/the `trying` branch - not the end of the world since we can always manually rerun in Actions.

**Comment by moshababo** [comment]
@lrettig still relevant?

**Comment by lrettig** [comment]
Not sure. No one has complained about this recently AFAIK. We can investigate later if it happens again.
