### ISSUE TITLE
Store account state root internally as byte array

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2194]
It's currently stored as a string. It should be stored as a bytearray, and only converted to a string when printed:

https://github.com/spacemeshos/go-spacemesh/blob/8a072181bfe2633d2a90461deb29627c1283706e/common/types/account_state.go#L15

**Comment by avive** [comment]
Note that internally in the db, a hash is stored and not a string. So this issue is about modifying MultipleAccountsState to store bytes instead of a string.

**Comment by buck54321** [comment]
Have you considered a `type HexBytes []byte` that implements `json.Marshaler` and `json.Unmarshaler` to use hex (with or without the `0x`?) in the JSON encoding, as opposed to the base-64 encoding that is the default for the `json` package?

**Comment by moshababo** [comment]
Obsolete.
