### ISSUE TITLE
handle late blocks in verifying tortoise 

### ISSUE THREAD

**Issue by y0sher** [spacemeshos/go-spacemesh#2202]
## Description

handling late blocks in verifying tortoise. should also design how to handle them.

## Affected code

verifying tortoise

**Comment by lrettig** [comment]
@y0sher right now all late blocks are passed into tortoise as they arrive. I proposed a different architecture in #2415. Wondering if you had something more specific in mind here. (Or should we close this issue in favor of that one?)

**Comment by lrettig** [comment]
Will follow up on this in #2552
