### ISSUE TITLE
differentiate between not terminated hare and terminated with empty set in tortoise and sync

### ISSUE THREAD

**Issue by y0sher** [spacemeshos/go-spacemesh#2203]
## Description

with the verifying tortoise we are now syncing on hare results (aka vote input vector) and using them for verifying. 
we need to be able to differentiate between not terminated hare and terminated with empty set in both, 
if terminated with empty set we should know to vote against every block in that layer
if not terminated we abstain until terminated.

currently we always act as if the hare was not terminated and abstain on all blocks when we get empty set from sync or hare itself.

## Affected code
- hare
- tortoise
- sync

This issue appears in commit hash: 

Related files (optionally with line numbers):

**Comment by lrettig** [comment]
To rephrase this slightly, a node needs to be able to vote explicitly neutral inside a block with respect to the contents of a layer (while waiting for hare to finish, before hare surpasses the max number of iterations). After hare terminates (if it terminates), the node should vote according to the hare for up to `hdist` layers, after which point it should vote according to the tortoise instead (per @tal-m).

**Comment by antonlerner** [comment]
Until hare does not finish: we will vote neutral for the layer
When hare finishes: 
if it finishes with an empty set:
Vote negative (TBD: discuss on research forum @tal-m, @moshababo )
otherwise: vote according to hare result

**Comment by lrettig** [comment]
Right now, there is no way to vote neutral. A neutral vote or lack of a vote (see [this change](https://github.com/spacemeshos/go-spacemesh/commit/6a9bfe49302ffa97c4595c88414ca5c02c8f111c)) is counted in tortoise as _an explicit vote for layer zero_ which is not what we intend.

Also, I'm not sure whether we currently distinguish in hare between a hare CP that ends successful with an empty set, and a hare failure, when getting votes [here](https://github.com/spacemeshos/go-spacemesh/blob/efa7538ba4fbb4ea90be43c827233a580c736e19/miner/block_builder.go#L220).
