### ISSUE TITLE
Automate releases

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2207]
It shouldn't be too hard to automate builds using the new CI setup. This has already been set up in https://github.com/spacemeshos/gpu-post/.

needs #2205

**Comment by noamnelke** [comment]
I think builds should be triggered when we create a tag (not on every merge to `develop`).

A build should push an image to Dockerhub (we should separate this part from the `tag-and-build` command in the makefile).

It should also build binaries for all platforms and attach them as artifacts to a draft release (that we can then manually release by just clicking a button).

We can use [this tool](https://goreleaser.com/quick-start/) for the job, or at least steal some of their source code... I like their automatic release notes--at least as a basis for manual editing.

**Comment by lrettig** [comment]
there's also https://github.com/marketplace/actions/automatic-releases and a bunch of other tooling available

**Comment by noamnelke** [comment]
Yeah, there are many tools that auto generate changelogs, doesn't matter to me which one we use.

**Comment by lrettig** [comment]
Done in #2223
