### ISSUE TITLE
[v0.1.17] | layer has no explicit voting

### ISSUE THREAD

**Issue by ghost** [spacemeshos/go-spacemesh#2211]
## Description
Tap node reboots endlessly after update to version `v0.1.17`

## Steps To Reproduce
1. Update to version v0.1.17
2. Download the latest configuration file
3. See error  
```
2020-11-25T00:51:39.832+0100        PANIC        17018.trtl                 block 03342caf00 from layer 631 has no explicit voting, something went wrong         {"node_id": "17018d13f904381725b99a393dd03a03b992bfc2a6dadabd6ef945a88ab75434"}
Nov 25 00:51:39 start_daemon.sh[7604]: panic: block 03342caf00 from layer 631 has no explicit voting, something went wrong
```

## Environment
Please complete the following information:
 - OS: Linux, Ubuntu 18.04
 
 - Node Version: `v0.1.17+5f1237a7ee06884d55712faf04655b064fe49225`
 

## Additional Resources 

![image](https://user-images.githubusercontent.com/52304443/100166984-00b67e80-2ecf-11eb-85dd-59431373fd47.png)

## LOGS  
[tap-node-log.tar.gz](https://github.com/spacemeshos/go-spacemesh/files/5593604/tap-node-log.tar.gz)

**Comment by lrettig** [comment]
Thanks for reporting this. It's probably the same issue as in #2088 (and the other issues linked there).

**Comment by antonlerner** [comment]
replaced by #1856
