### ISSUE TITLE
add database indices for atxs to index them by layer

### ISSUE THREAD

**Issue by shibe-dev** [spacemeshos/go-spacemesh#2217]
## Description
Currently, activations are indexed by atxID as well as by coinbase address. As the number of layers grows, searching for a specific activation transaction gets more and more inefficient (the API implementation uses a getter GetATXsByCoinbase). Adding database indices to index atxs by layer would increase efficiency. [See similar issue/fix here](https://github.com/spacemeshos/go-spacemesh/pull/2176)

## Affected code
Getter appears in api/mesh_service.go, implementation should be added in activation/atxdb.go

**Comment by moshababo** [comment]
Obsolete.
