### ISSUE TITLE
Remove timestamp field from block header

### ISSUE THREAD

**Issue by noamnelke** [spacemeshos/go-spacemesh#2225]
## Description
The block header contains a `Timestamp` field, which is set, but never read.

It’s problematic to use it anywhere since it’s un-vetted, one can plaster any timestamp that serves them onto anything.
Since we’re not doing anything with this field we may as well call it “arbitrary 8 bytes that the miner can fill with whatever they please”.

## Affected code
https://github.com/spacemeshos/go-spacemesh/blob/f76c8b99427a4a9f559da87fced6cf5aa3219266/common/types/block.go#L124-L133

**Comment by avive** [comment]
why not remove it and save some bytes per stored tx?

**Comment by krishnaindani** [comment]
Hi, Is this issue available? If so I would like to try working on this.

**Comment by noamnelke** [comment]
@avive Removing the field is what this issue is about, see title.

@krishnaindani Sure! Feel free to submit a pull request.

**Comment by krishnaindani** [comment]
Thanks @noamnelke . I will get started and submit the pr

**Comment by krishnaindani** [comment]
I see the block header defined [here](https://github.com/spacemeshos/go-spacemesh/blob/develop/common/types/block.go#L130) and used [here](https://github.com/spacemeshos/go-spacemesh/blob/develop/miner/block_builder.go#L286).  I only see these two places to remove the field. Am I understanding correctly?

**Comment by noamnelke** [comment]
Yes, looks that way.

**Comment by krishnaindani** [comment]
> Yes, looks that way.

Just wanted to cross check. Thanks. I have created the pr.

**Comment by krishnaindani** [comment]
I have added a PR for this issue. Can someone check if the PR looks good or if I need to update anything there? Thanks in advance.
