### ISSUE TITLE
Add -race flag to tests and fix data races

### ISSUE THREAD

**Issue by nkryuchkov** [spacemeshos/go-spacemesh#2226]
## Description
Neither unit tests, nor system tests use the `-race` flag. Using it would enable Go's race detector and let us find some existing data races easily. As a result of a read/write operation is undefined in case of a data race, they might cause some unexpected behavior.

I ran unit tests with the flag, and there are many races in multiple packages.

This issue appears in commit hash: 
`f790a44`

Related files (optionally with line numbers): 
https://github.com/spacemeshos/go-spacemesh/blob/develop/Makefile#L137
https://github.com/spacemeshos/go-spacemesh/blob/develop/Makefile#L142
https://github.com/spacemeshos/go-spacemesh/blob/develop/Makefile#L142
https://github.com/spacemeshos/go-spacemesh/blob/develop/Dockerfile#L31

**Comment by y0sher** [comment]
@nkryuchkov this will be really helpful though a lot of the races we have are originated in races with mocks and simulators I hope we can take advantage of the `-race` flag without putting too much work into synchronizing mocks..

**Comment by nkryuchkov** [comment]
Logs of `ulimit -n 9999; go test -race -timeout 0 -p 1 ./...`:
[dataraces.log](https://github.com/spacemeshos/go-spacemesh/files/5808461/dataraces.log)

**Comment by nkryuchkov** [comment]
https://github.com/spacemeshos/go-spacemesh/pull/2608 fixes most of the data races. However, some data races in tests still need to be fixed. Later, the `-race` flag needs to be enabled.
