### ISSUE TITLE
Some rewards are not sent by the api

### ISSUE THREAD

**Issue by avive** [spacemeshos/go-spacemesh#2228]
Looks like not all rewards are sent via the api for a layer. See logs here: https://github.com/spacemeshos/explorer-frontend/issues/102 . This what causes the under-reporting of rewards in dash and explore.

**Comment by avive** [comment]
I ran some more tests.
Layer 4804 on TN 122 had 45 blocks. See: https://stage-explore.spacemesh.io/layers/4804/blocks . GlobalStateService GlobalStateStream returned only 32 rewards events via `grpcurl -d '{"globalStateDataFlags": 2}' -plaintext localhost:9092 spacemesh.v1.GlobalStateService.GlobalStateStream`. So we are def missing some rewards in the stream.

**Comment by lrettig** [comment]
CC @sidsankhe who's working on how rewards are stored (and indexed) in the database as part of #2068. We never figured out the cause of this issue, whether it was happening inside the API or the DB. Let's wait and see if everything is working after #2068 is done, the new API is fully implemented, and we've finished implementing whatever reward scheme we ultimately land on (#421).

**Comment by moshababo** [comment]
@brusherru still relevant?

**Comment by lrettig** [comment]
Was probably handled in #2068
