### ISSUE TITLE
[BUG]Syncing the mesh... Error

### ISSUE THREAD

**Issue by tyevlag** [spacemeshos/go-spacemesh#2264]
2021-01-19T23:18:20.504+0800	ERROR	00000.defaultLogger	GRPC GetBalance returned error msg: account does not exist, address c17cb093064256a4c470813550969c9e8dcc5b72
2021-01-19T23:18:20.504+0800	INFO	00000.defaultLogger	not reporting error as buffer is full: {GRPC GetBalance returned error msg: account does not exist, address c17cb093064256a4c470813550969c9e8dcc5b72 goroutine 279 [running]:
runtime/debug.Stack(0xc007d98210, 0xc007d98210, 0xc007c19440)
	C:/hostedtoolcache/windows/go/1.14.13/x64/src/runtime/debug/stack.go:24 +0xa4
github.com/spacemeshos/go-spacemesh/cmd/node.(*SpacemeshApp).setupLogging.func1(0x2, 0xbff9dbef1e12a520, 0x4f874d2d5, 0x1bb9aa0, 0x11096c0, 0x13, 0xc000040150, 0x6c, 0x0, 0x0, ...)
	D:/a/go-spacemesh/go-spacemesh/cmd/node/node.go:303 +0x49
go.uber.org/zap/zapcore.(*hooked).Write(0xc0001bb800, 0x2, 0xbff9dbef1e12a520, 0x4f874d2d5, 0x1bb9aa0, 0x11096c0, 0x13, 0xc000040150, 0x6c, 0x0, ...)
	C:/Users/runneradmin/go/pkg/mod/go.uber.org/zap@v1.15.0/zapcore/hook.go:65 +0xa2
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00013f810, 0x0, 0x0, 0x0)
	C:/Users/runneradmin/go/pkg/mod/go.uber.org/zap@v1.15.0/zapcore/entry.go:216 +0x11e
go.uber.org/zap.(*SugaredLogger).log(0xc007c19770, 0xc000472002, 0x113a6c3, 0x46, 0xc007c19930, 0x1, 0x1, 0x0, 0x0, 0x0)
	C:/Users/runneradmin/go/pkg/mod/go.uber.org/zap@v1.15.0/sugar.go:234 +0x107
go.uber.org/zap.(*SugaredLogger).Errorf(...)
	C:/Users/runneradmin/go/pkg/mod/go.uber.org/zap@v1.15.0/sugar.go:148
github.com/spacemeshos/go-spacemesh/log.Log.Error(0xc0001bd740, 0x113a6c3, 0x46, 0xc007c19930, 0x1, 0x1)
	D:/a/go-spacemesh/go-spacemesh/log/zap.go:32 +0x10e
github.com/spacemeshos/go-spacemesh/log.Error(...)
	D:/a/go-spacemesh/go-spacemesh/log/log.go:118
github.com/spacemeshos/go-spacemesh/api.SpacemeshGrpcService.GetBalance(0xc0001fac40, 0x2383, 0x12c9c60, 0xc00017c6c0, 0x2979a060, 0xc0001a0a00, 0x12e7420, 0xc00007ab40, 0xc00025d200, 0x12d50a0, ...)
	D:/a/go-spacemesh/go-spacemesh/api/grpc_server.go:134 +0x41b
github.com/spacemeshos/go-spacemesh/api/pb._SpacemeshService_GetBalance_Handler(0x10e4c40, 0xc00006cc30, 0x12d1020, 0xc007d98090, 0xc0005163c0, 0x0, 0x12d1020, 0xc007d98090, 0xc00016c1e0, 0x42)
	D:/a/go-spacemesh/go-spacemesh/api/pb/api.pb.go:2148 +0x21e
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001fac40, 0x12dff00, 0xc0006c5b00, 0xc00012ad00, 0xc0006ad2c0, 0x1b935b0, 0x0, 0x0, 0x0)
	C:/Users/runneradmin/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x511
google.golang.org/grpc.(*Server).handleStream(0xc0001fac40, 0x12dff00, 0xc0006c5b00, 0xc00012ad00, 0x0)
	C:/Users/runneradmin/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd04
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0006c0040, 0xc0001fac40, 0x12dff00, 0xc0006c5b00, 0xc00012ad00)
	C:/Users/runneradmin/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xa8
created by google.golang.org/grpc.(*Server).serveStreams.func1
	C:/Users/runneradmin/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x20b
 error}

**Comment by noamnelke** [comment]
@lrettig is this normal behaviour? I'm referring to the `not reporting error as buffer is full` part.

**Comment by lrettig** [comment]
"GRPC GetBalance returned error msg: account does not exist" message is coming from the old API, and the "not reporting error as buffer is full" ERROR isn't really an error. Old API was removed and the error was downgraded to DEBUG in #2131 (which code isn't included in the running testnet).

**Comment by lrettig** [comment]
@tyinsomnia thanks for pointing this out! These issues have already been fixed but the fix isn't included in the running testnet--it will be included in a future testnet release.

**Comment by lrettig** [comment]
For the record, this is still appearing in the latest testnet release because smapp is still using the old API. When smapp is upgraded to use the new API, we can remove the old API from the testnet builds and the error will go away.
