### ISSUE TITLE
Look into tags for disabling API services

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2266]
@moshababo points out that https://github.com/lightningnetwork/lnd uses golang tags to enable/disable certain RPC services. Look into how this works and the pros/cons of this approach (versus just compiling everything in and enabling/disabling with CLI flags/config as we do now).

**Comment by noamnelke** [comment]
Having to rebuild the node for different configurations seems unreasonable to me.

Trying to think of services for which it makes sense:
- Testing/debugging endpoints that we'll never use in production and we want to prevent someone accidentally enabling them.

I honestly started this bulleted list thinking I can come up with at least one more service where this makes sense, but couldn't. I don't even see a big advantage for the first bullet over a simple config flag. Would love to hear if you think I'm missing something.

**Comment by lrettig** [comment]
API services can be enabled/disabled in config file and on command line
