### ISSUE TITLE
NodeID should contain a single ed25519 key

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2269]
## Description
Right now, NodeID contains two keys, an edwards public key used for signing and a BLS-derived key used for VRF. We want to collapse these down to a single ed25519 key.

In future we may want to allow the node operator to rotate the signing key, but for now we're only allowing a single key that cannot be changed.

Replace BLS with a library that implements the scheme described [here](https://community.spacemesh.io/t/research-agenda-2020-08-10/104/5). There's more background info in [this thread](https://community.spacemesh.io/t/need-for-two-keys-in-nodeid/139).

## Affected code
- Initialization code in cmd/node.go
- NodeID struct and all code that uses it
- SmesherID (derived from NodeID) and all code that uses it

This issue appears in commit hash: 35432834b1bcc8aa4110e033c9d4e2e9701bc7d7

## Related issues

Replaces #1391 
Obviates #936

**Comment by dshulyak** [comment]
ecvrf is implemented in oasis's library https://github.com/oasisprotocol/curve25519-voi/blob/master/primitives/ed25519/extra/ecvrf/ecvrf.go . we should use it.

also we should replace our library with oasis library, as it is superior both in quality and in performance, also it is being used in puiblic blockchains (tendermint and oasis). it may require changing it slightly to support public key recovery as it is not implemented.
