### ISSUE TITLE
Sync protocol implementation

### ISSUE THREAD

**Issue by almogdepaz** [spacemeshos/go-spacemesh#227]
implement sync protocol.

**Comment by zalmen** [comment]
Does this issue cover both the cases where the node is the "client" and when the node is the "sever" of the sync process?

**Comment by zalmen** [comment]
Does this issue cover both the cases where the node is the "client" and when the node is the "sever" of the sync process?

**Comment by almogdepaz** [comment]
@zalmen  no i think i'll open another issue just for that
