### ISSUE TITLE
Support for obtaining the Layer Computed for Rewards

### ISSUE THREAD

**Issue by sidsankhe** [spacemeshos/go-spacemesh#2275]
## Description

Currently, there is no way to get the LayerComputed field, i.e. the layer in which a reward was computed. Support needs to be added for this, because the Rewards API endpoints need this information. 
## Affected code

This issue appears in commit hash: 

Related files (optionally with line numbers):

**Comment by avive** [comment]
Doesn't this need to wait until the new rewards scheme is finalized because rewards might not be for a specific layer but for example the number of blocks submitted in an epoch? @lrettig

**Comment by lrettig** [comment]
Yup. All these related issues are tracked with the rewards tag here, we'll work through them all as we figure out how rewards are going to work.

**Comment by dshulyak** [comment]
What this field even means? Layer where reward is computed is the layer where block with that reward was applied

**Comment by lrettig** [comment]
@dshulyak we considered rewards designs where we do epoch-wide smoothing of rewards, and/or reward maturation, where a reward "computed" in layer `m` is paid (and spendable) in layer `m+n`. We're going with a simpler reward scheme for now, without either of these, so this isn't needed for now. Thanks for asking.

**Comment by poszu** [comment]
@lrettig, should `layer_computed` field be removed from `message Reward` in proto definition then? https://github.com/spacemeshos/api/blob/7fbc096071e0d3bf7f1feffbc5de8661276dc6af/spacemesh/v1/types.proto#L81

**Comment by lrettig** [comment]
@poszu yes it can be removed for now. If and when we introduce a more sophisticated reward scheme we can revisit this design.
