### ISSUE TITLE
Collect local logs and zip when node crashes

### ISSUE THREAD

**Issue by antonlerner** [spacemeshos/go-spacemesh#2277]
When a Node crashes for a user we should pack the relevant logs to make sure they are not re written, this will also make reporting issues a lot easier for us

when a node panics or exits abruptly we should have a method that packs the logs to a known location

**Comment by avive** [comment]
I think that @lrettig opened an issue recently regarding log rotation. q: why should the logs be re-written? They are always appended and always in one place? I don't think we even had a user that didn't find his logs when we asked him for it. There's a button in smapp settings top open the logs folder as well. Also - don't we want the telemetry feature that @sudachen has been working on to at least report panics with some logs back to the mothership if user's telemetry is opted-in?

**Comment by avive** [comment]
The common solution for getting users logs in case of a crash this is to ask the user to submit a crash report back to the telemetry server and include his logs in the report + the panic but the logs are currently too big after short time to be uploaded.

**Comment by lrettig** [comment]
It's here: https://github.com/spacemeshos/smapp/issues/680

Seems to me most of this log management stuff belongs in smapp, not go-spacemesh.

**Comment by moshababo** [comment]
@lrettig still relevant?

**Comment by lrettig** [comment]
Yes, there was a discussion about this in slack recently: https://spacemesh.slack.com/archives/C89QJJY3G/p1656319462621179
