### ISSUE TITLE
Add contextual validity bit to block data structure

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2304]
When a new block is received, the node should record, in the block data structure, whether the block was received on time or not, i.e., whether or not it's contextually valid. This will be used by both hare and tortoise in voting. Note that blocks should (obviously) not be marked late/contextually invalid if the node is not currently fully synced.

**Comment by dshulyak** [comment]
This is covered under https://github.com/spacemeshos/go-spacemesh/issues/3003
