### ISSUE TITLE
Increase hdist

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2306]
Right now, this is set to 5 in the default config, and we've been running with it set to 10 in the testnets. However, according to @tal-m, it should be closer to 200. This increases our robustness against hare attacks, since honest nodes will explicitly vote neutrally until hare has terminated or failed completely, and we need a big enough window for honest votes to accumulate and override dishonest votes against a pattern while honest nodes continued to wait for hare.

**Comment by moshababo** [comment]
@lrettig still relevant?

**Comment by lrettig** [comment]
Yes, this will be part of mainnet parameterization
