### ISSUE TITLE
Layer.Activations in API now contains active set

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2314]
Right now, `Layer.activations` in `MeshService` contains the union of the _active set_ for the blocks in that layer:

https://github.com/spacemeshos/go-spacemesh/blob/ac474c937735a11a6e0c954c06a7688c8f7fcff7/api/grpcserver/mesh_service.go#L303-L326

But the active set consists of activations from the previous epoch. Do we want this to contain the union of activations pointed to by blocks in the current layer? Or something else?

(Note that this _may_ have changed recently due to #2237, I'm not certain.)

**Comment by avive** [comment]
High-level we want to know in epoch n about each smesher that is going to be eligible to smesh in epoch n+1 and this is the data set for the 'active smeshers' info-graphics we display for users in dash and explore.

**Comment by lrettig** [comment]
Right, but the problem is, we have no "epoch" data type in the API, and it doesn't make sense to associate activations with layers, since in fact activations are associated with epochs. I think we should remove them from layers entirely to prevent the sort of confusion we're seeing now. Will PR this. They can be read directly from blocks for now.

**Comment by moshababo** [comment]
@lrettig still relevant?

**Comment by lrettig** [comment]
Probably not (see linked API issue)
