### ISSUE TITLE
v0.1.26, failed when syncing to altitude 1214

### ISSUE THREAD

**Issue by bananooo-zhang** [spacemeshos/go-spacemesh#2315]
## Description
In ubuntu system, when I synced to 1214 altitude, it stopped syncing. This state has lasted for 24 hours

![image](https://user-images.githubusercontent.com/61408588/110269168-18d58800-7ffe-11eb-99fe-96a2fb32d940.png)

**Comment by bananooo-zhang** [comment]
The problem seems to be solved. I deleted the spacefile file and restarted the synchronization, and then it succeeded.
It should be a fork or other problem during the synchronization process, it is recommended to optimize

**Comment by lrettig** [comment]
Thanks for the bug report, @bananooo-zhang, I'm glad to hear the problem resolved itself!
