### ISSUE TITLE
cant find account in web explore

### ISSUE THREAD

**Issue by bananooo-zhang** [spacemeshos/go-spacemesh#2319]
this is my account, 0xdC413F3e95B1E4D57c47FfBcc4b6e889A1903C86,have 60+ smd
![image](https://user-images.githubusercontent.com/61408588/110443774-42260f00-80f7-11eb-8476-e0e1b740f31e.png)

but in this link, i cant find my account
https://explorer-126.spacemesh.io/

**Comment by avive** [comment]
I see it here after searching for it via the explorer search bar: 
https://explorer-126.spacemesh.io/accounts/0xdC413F3e95B1E4D57c47FfBcc4b6e889A1903C86
Note that we have a known issues in rewards in explorer but you can see your balance.
Q: what did you do to search? Did you try using the explorer search bar?

**Comment by bananooo-zhang** [comment]
> I see it here after searching for it via the explorer search bar:
> https://explorer-126.spacemesh.io/accounts/0xdC413F3e95B1E4D57c47FfBcc4b6e889A1903C86
> Note that we have a known issues in rewards in explorer but you can see your balance.
> Q: what did you do to search? Did you try using the explorer search bar?

https://www.loom.com/share/2ae31be9b75b4aa891596a68ea120255
i make a video，pls watch，maybe i setp is wrong？
