### ISSUE TITLE
Accessing logs for system tests run locally

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2330]
If I run system tests locally, right now, the process of finding and accessing the logs is very complicated. I have to run `kubectl get service -n <your namespace>` to figure out the IP where kibana is running -- and kubectl doesn't work for me, it gives me an error: `Unable to connect to the server: stopped after 10 redirects`. If I want the logs to be preserved, and not deleted after a successful run, I have to [manually change a test config file](https://spacemesh.slack.com/archives/C89QJJY3G/p1615472029173000).

Is all of this documented somewhere? Can it be made easier?

**Comment by moshababo** [comment]
Obsolete.
