### ISSUE TITLE
Return true current sync layer in API

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2333]
In #2299 we patched the API to return the current (tip) layer rather than statically returning the first layer of the third epoch as the current layer. But this still isn't really accurate. What we really want is for the API to instead return the latest _synced_ layer. This information is currently not exposed to the API, but it could be, and it definitely lives in the sync code somewhere, since sync prints log lines like these:

```
2021-03-14T22:04:13.399+0300    INFO    bfda3.sync              syncing layer   {"node_id": "...", "current_sync_layer": 67, "last_ticked_layer": 3375}
```

The `NodeService.Status` should return the latest _synced_ layer (not latest layer in state) during genesis (and maybe always.)

**Comment by dshulyak** [comment]
Latest synced layer is stored as a ProcessedLayer in the validator, so we can just read it (note that ProcessedLayer+1 might be *current* layer that is being synced, but definitely not *latest*).

@lrettig can you elaborate why would we want to use it during genesis? as I understand your comment is still valid
```
// We cannot get meaningful data from the mesh during the genesis epochs since there are no blocks in these
// epochs, so just return the current layer instead```

**Comment by lrettig** [comment]
> @lrettig can you elaborate why would we want to use it during genesis? as I understand your comment is still valid

`NodeService.Status` returns three layer values:

https://github.com/spacemeshos/go-spacemesh/blob/631d56f11c25aa36074e84fbbf5879fd504cf32b/api/grpcserver/node_service.go#L81-L83

While syncing genesis layers, the intuitive thing that should happen here is that `SyncedLayer` and `VerifiedLayer` should both be set to the most recently synced layer. There's no state, no blocks, nothing to process or verify during genesis (i.e., all of these layers are "zero layers" from the perspective of syncer).

`TopLayer` should be set to the _current layer height_ (based on time), as it is now.

Right now, the code sets `VerifiedLayer` and `SyncedLayer` to equal `TopLayer`. From the perspective of the user, this is confusing, since it seems like the node is already at layer 575 (the final genesis layer) when it first launches, and then gets stuck at this layer for a while.

Does this make sense?

**Comment by dshulyak** [comment]
thank you, it makes more sense now. since there are no blocks during genesis we will update the synced layer, but not layer in state. and during non-genesis layer in state will be updated because of this condition ([ref](https://github.com/spacemeshos/go-spacemesh/blob/9116d1fd4f6f4fadef986d12212a938a62f87e97/mesh/mesh.go#L272-L291). i was somewhat confused about it
