### ISSUE TITLE
Rewards API not returning any rewards

### ISSUE THREAD

**Issue by sidsankhe** [spacemeshos/go-spacemesh#2353]
## Description

The new changes to the rewards API result in 0 rewards being returned for all calls to the API. This could be a problem with writing to the database.
## Environment
Please complete the following information:
 - OS: 
 
 - Node Version: 
 
 - App Version (if applicable):

**Comment by lrettig** [comment]
This is a duplicate of #2228, let's handle it there as there's already more context there.
