### ISSUE TITLE
blocks, tortoise: merge for/against exceptions into a single list, vote neutral on layers instead of blocks

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2369]
As described in https://github.com/spacemeshos/SMIPS/issues/2, the initial version of verifying tortoise includes three explicit lists of exception votes:

```
Block {
   Base_Block: <block_id>
   For_Exception_List: [<block_id>, <block_id>, <block_id>...] // List of blocks I vote For and Base_Block doesn't
   Against_Exception_List: [<block_id>, <block_id>, <block_id>...] // List of blocks I vote Against and Base_Block doesn't
   Neutral_Exception_List: [<block_id>, <block_id>, <block_id>...] // List of blocks I vote neutral and Base_Block doesn't or blocks that just come after Base_Block.
}
```

As discussed on the R&D call with Tal this week, we can optimize this in a few ways:

- blocks only ever vote neutral on an entire layer, never on individual blocks in a layer (and only in the case where they're still waiting for a Hare result for that layer). So there's no need to list individual block ids in the neutral list, just layer IDs.
- the For and Against exception lists can be collapsed down to a single list. For any block on this list, the block's vote is implicitly the _opposite_ of the base block's vote.

Regarding neutral votes in the base block, by default a block citing it should also be considered to vote neutral for the same layers, unless the block includes _any_ explicit for or against votes for _any_ blocks in that layer (this may already be how things work, I'm not sure)

CC @y0sher, @sudachen 

Addendum: a block does not need to encode an explicit vote _for_ its base block, this can be made automatic and implicit. ([discussion](https://spacemesh.slack.com/archives/C89QJJY3G/p1635846350093700))

**Comment by lrettig** [comment]
Related: in block fast validation, make sure the exception lists are valid (i.e., don't contain contradictions), and invalidate a block if they do:

https://github.com/spacemeshos/go-spacemesh/blob/9d3a379994e3652eb0378d2cc555588bba91005e/blocks/blocks.go#L153-L159

**Comment by dshulyak** [comment]
should also incorporate https://github.com/spacemeshos/go-spacemesh/issues/2674 when this will be implemented
