### ISSUE TITLE
MeshService AccountMeshDataQuery method error

### ISSUE THREAD

**Issue by avive** [spacemeshos/go-spacemesh#2372]
## Description

API returns an error just after a transaction was received by the node for submission to mem-pool.

## Steps To Reproduce

1. Submit a transaction to your local node from a client and note your account_address.
2. Call MeshService.AccountMeshDataQuery(account_address, <transaction_flag>) to get all transactions for that account.

Result: api returns rpc error: code = Internal desc = error retrieving tx data

## Expected Behavior

Expected: return all mesh transactions and no error.

Now wait few minutes and try again - you'll get no error.
Hypothesis: there must be some internal state where the transaction is not yet in the mem pool or in a block where the transaction causes an error in the node.

## Environment
go-spacemesh develop branch 
go1.16.3 darwin/amd64

**Comment by lrettig** [comment]
Not sure what's going on under the hood here, but in any case I agree it should not produce an error - even if there are no transactions, you should just get an empty list or null result

**Comment by moshababo** [comment]
@brusherru still relevant?
