### ISSUE TITLE
GlobalStateService AccountDataQuery Method Issue

### ISSUE THREAD

**Issue by avive** [spacemeshos/go-spacemesh#2376]
## Steps To Reproduce

Call `GlobalStateService::AccountDataQuery()` for an account that got past rewards on TN NetId 28 with the account_data_flags set to ACCOUNT_DATA_FLAG_REWARD == 2. . e.g.

```bash
curl -d '{
    "filter": {
        "accountId" : {"address": "aDZwegxgjUtqd9STdv54sBPR3BU="},
        "account_data_flags": 2
    }
}' https://api-json-28.spacemesh.io/v1/globalstate/accountdataquery
```

## Actual Behavior
Empty results set.

## Expected Behavior
Get all rewards awarded to this address..

## Environment
TN Id 28 Node (managed by smapp release on os X)

## Note
GlobalStateService.AccountDataStream returns rewards events for this coinbase account 0x6836707a0c608d4b6a77d49376fe78b013d1dc15

**Comment by moshababo** [comment]
@brusherru still relevant?
