### ISSUE TITLE
Add to automation readme instructions for running systests locally

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2382]
Re: tests/README.md

In addition to what's in this doc, I had to do the following to run tests locally:

- install pipenv
- `cd tests/`
- `pipenv install`
- `pipenv shell`
- download/generate a gcloud service account credentials file
- set `GOOGLE_APPLICATION_CREDENTIALS=/path/to/credentials_file.json`

Also note that the command to run tests only works from inside the `tests/` subdirectory.

CC @AmitShaul

**Comment by moshababo** [comment]
Obsolete.
