### ISSUE TITLE
Streaming apis implementation can miss sending data to clients

### ISSUE THREAD

**Issue by avive** [spacemeshos/go-spacemesh#2384]
## Description
As the streaming api is currently implemented, there can be multiple consumers for a single go channel of events created by the event reporter.  For example, in the globalState service implantation, there will be a consumer of data from the reporter's singleton rewardsChannel, per subscribed client, per one of the 3 streaming methods that use this channel - GlobalStateStream, SmesherRewardStream and AccountDataStream. 

This will cause an issue where for example, not all rewards events will be sent to all registered clients in the case that two or more clients are registered to receive rewards using any of the 3 implemented streaming methods, or even  when only client is registered on two or more of the streams because the first select loop which will receive the event from the channel will consume it.

We need to implement pub-sub here to support multiple producers and multiple consumers pattern.

**Comment by avive** [comment]
This issue will block testnet 0.2 release because Smapp uses the grpc streams to fetch user data. @IlyaVi @lrettig @moshababo

**Comment by avive** [comment]
I think that go grpc uses blocking i/o and sending a message to a stream is not supported from different go routines. We don't want to block the node on sending data to slow clients over a network connection. This means that Reporter needs to be able to receive data from sources in node in a non-blocking way but internally, send the data blocking to all client streams.

**Comment by avive** [comment]
Repro steps:
1. Subscribe with 1 grpc client such as grpcurl to the globalState service GlobalStateStream method to receive rewards.
2. Wait until node performs rewards calculation for a layer.
3. Observe that you'll only get a subset of the rewards data items in the client but not all of them for a layer.

@moshababo

**Comment by avive** [comment]
I have an outline of a solution that uses pub sub for rewards that can be applied on all reported streaming data. @sidsankhe takes over working on this issue.

**Comment by lrettig** [comment]
Outline of fix (see #2389):
- modify reporter to use pubsub-style interface (rather than a single, singleton channel per stream, create a new channel for each subscriber - same as ticker does). allow subscriber to specify channel buffer size.
- remove `blocking` arg/property from reporter struct. reporting an event should _never_ block and writes to all channels should be non-blocking.

CC @sidsankhe

**Comment by avive** [comment]
Is this fully resolved?

**Comment by lrettig** [comment]
> Is this fully resolved?

Nearly, pending a few tweaks in the linked PR, see https://github.com/spacemeshos/go-spacemesh/pull/2389#pullrequestreview-680144825
