### ISSUE TITLE
Drop peers after failing to send messages to them

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2385]
## Description
I'm seeing ~200k/hr p2p warnings about "failed sending" messages from the managed testnet nodes (see screenshot below). This happens when a node tries to propagate a gossip message to a peer, and fails. I think this error is happening so often because nodes never drop peers after such an error. Ideally, a node should drop a peer--in the case of connection not found in cpool, probably right away, and replace it with a healthy peer.

## Affected code

https://github.com/spacemeshos/go-spacemesh/blob/a3ba021480a2aa5ed9b88d9d2c1f62dbddf7c1f1/p2p/gossip/protocol.go#L145

This issue appears in commit hash: v0.1.29, a3ba021480a2aa5ed9b88d9d2c1f62dbddf7c1f1

Related files (optionally with line numbers): 

![image](https://user-images.githubusercontent.com/3316532/115275524-e4caa800-a10f-11eb-8053-817654d8e580.png)

**Comment by dshulyak** [comment]
So in the codebase if writer fails https://github.com/spacemeshos/go-spacemesh/blob/develop/p2p/net/conn.go#L285-L297 it will notify switch https://github.com/spacemeshos/go-spacemesh/blob/develop/p2p/switch.go#L217-L218 which will call Disconnect. We definitely don't need to add another disconnect in the protocol, as this mechanism already exists.

But there is probably something wrong with it, the code didn't change much between https://github.com/spacemeshos/go-spacemesh/commit/a3ba021480a2aa5ed9b88d9d2c1f62dbddf7c1f1 and current develop.

**Comment by dshulyak** [comment]
For reads there is similar code flow that will propagate notifications and close connection if reader failed.
One suspicious part is https://github.com/spacemeshos/go-spacemesh/blob/develop/p2p/switch.go#L687-L696

Notification is actually non-blocking so if there were a lot of disconnects (more than 30) and peer manager goroutine wasn't scheduled to run some events might get dropped. And this will result in the behaviour that you are seeing (connection in cpool doesn't exist, but peer manager is not updated properly).

**Comment by dshulyak** [comment]
I experimented with the change https://github.com/spacemeshos/go-spacemesh/pull/2490 on a devnet with 50 nodes. By disconnecting multiple peers periodically. "expired peer" log was consistently observed, but never "failed sending". 

I assume that the issue is fixed. It is still possible that sometimes "failing sending" will be observed because peers are not updates synchronously when the connection is dropped, but it won't be at a reported rate.
