### ISSUE TITLE
LayerID type should protect against overflow

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2414]
## Description
Int types in golang [do not panic on overflow](https://stackoverflow.com/questions/54605650/arithmetic-on-uint8-int8) and instead wrap around. Internally, our LayerID type is stored as a uint (see also #2082). In practice this means that if you inadvertently subtract layer x from layer y, where x > y, you'll get a very large layer as a result (the opposite could happen if adding two very large layers, but this is less likely).

It is of course possible to add checks to every bit of layer arithmetic, but this is dangerous and error-prone. It would be safer if the LayerID type did not wrap an integer type, as it does now, and therefore did not natively allow arithmetic operations. Instead, the type should implement basic safe math functions such as Add, Sub, Comp, Inc, Dec, etc. that prevent overflow and wrap around (or panic if it's attempted).

## Affected code
common/types/block.go LayerID type, and everything that relies on it
many places that perform layer arithmetic, e.g., the new Tortoise code

This issue appears in commit hash: e36cb051371df4e3a35c4b3e91f9e6fe5e49e527

**Comment by noamnelke** [comment]
`LayerID` already supports the add operation, but unfortunately it's not consistently used. I agree with the solution in this issue (hiding the underlying integer to control arithmetic operations).

https://github.com/spacemeshos/go-spacemesh/blob/e36cb051371df4e3a35c4b3e91f9e6fe5e49e527/common/types/block.go#L71-L74

**Comment by lrettig** [comment]
Yes, but @noamnelke note that even this operation doesn't prevent overflow/wraparound

**Comment by noamnelke** [comment]
I know, but since it's a method rather than an operation performed directly on the underlying number, it's trivial to add this protection there.
