### ISSUE TITLE
Async/on-demand tortoise

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2415]
Right now, tortoise receives data in several ways:

- when Hare finishes processing a layer, its output is sent to `tortoise.HandleIncomingLayer` via `mesh.ValidateLayer`
- when a layer is received via sync, the same thing happens
- when a late block arrives via sync or gossip, it's sent individually into `tortoise.HandleLateBlocks`

All of these are currently handled synchronously: e.g., the syncer is waiting for tortoise to finish running and processing the new layer before it continues syncing.

The tortoise should be totally asynchronous. It should be a separate, autonomous "background process" in its own goroutine (like the hare broker). All incoming data should be buffered on channels, and the caller should never wait for it to finish. This would have a few advantages:

- easier to process incoming blocks and layers in batches (especially useful for late blocks, see #2412). This is the main motivation for this change. The way in which tortoise processes data should not be tightly coupled to the messages it receives about new blocks and layers.
- architecturally, it makes more sense: there's no reason hare, mesh, or syncer should block on tortoise. It makes the API simpler.
- makes it a bit simpler to rerun the verifying tortoise from scratch periodically, on its own schedule (without worrying about blocking data providers), or to trigger tortoise once in a while when an accounting of the voting weight of incoming blocks requires it

No block data should be passed directly into tortoise (this was done already in #2400). Tortoise should just receive notifications that new data is waiting to be processed. The API should basically just be:

- new incoming layer
- late block received

**Comment by lrettig** [comment]
Here's another way of conceptualizing the tortoise. It's an expensive operation that only _needs_ to run:

- when we construct a new block, so that the votes in the block are accurate and up to date (this is the most important)
- once every so often, perhaps on demand (and totally regardless of block creation), so that the user knows they're seeing the most up to date, valid state (especially if they're running an application, or sending transactions, that rely on this information)
- periodically, from genesis, to recheck historical vote/weight accounting

Right now, we run tortoise very often, every time we get new layer data (from sync or gossip), or a single late block, so that we always have the most up to date information on the contextual validity of historical blocks and layers. 

Self-healing makes tortoise an even more expensive operation, so this is a good time to revisit this question and this design.

**Comment by dshulyak** [comment]
tortoise is a non-blocking (e.g. it doesn't have to wait for anything) and not an expensive operation. It also needs to be completed asap when a new layer is available, as we only apply tx to the state after the tortoise verifies blocks.

rerun definitely needs to be async, but it is somewhat unrelated to general interface, and it was made async in some of the changes lately. 

the proposed change definitely doesn't enable anything new, maybe it has arguable pro that hare will be non-blocking, but i don't see it as important.

> easier to process incoming blocks and layers in batches (especially useful for late blocks, see Process late blocks in batches #2412). This is the main motivation for this change.

late blocks will be processed based on notification from mesh state sync, which will trigger rerun in background. 

>  architecturally, it makes more sense: there's no reason hare, mesh, or syncer should block on tortoise. It makes the API simpler.

each hare instance runs in its own goroutine. conceptually it makes sense that it triggers tortoise after it is completed. tortoise takes ms to complete. if verified layer was stuck for some time it will take longer, but still neglible amount of time compared to hare.

>  makes it a bit simpler to rerun the verifying tortoise from scratch periodically, on its own schedule

it is already runs in a separate goroutine.

**Comment by dshulyak** [comment]
I don't think that we will implement it. The concurrency model for the tortoise is good enough, and i don't see good reasons to change it.
