### ISSUE TITLE
Can't connect to p2p network - Ubuntu 20.04

### ISSUE THREAD

**Issue by JoJ123** [spacemeshos/go-spacemesh#2425]
## Description
After following each step of the installation & setup guide for Ubuntu 20.04 the 4GB file was created, but after I start the application I'm getting after a few minute the red alert: "Can't connect to p2p network"

Port 7153 is forwared in the router.

## Environment
Please complete the following information:
 - OS: Ubuntu 20.04
 - App Version (if applicable):  Latest

**Comment by GreatV** [comment]
Testnet 129 is officially dead.

**Comment by JoJ123** [comment]
@GreatV Oh what does it mean exactly?

**Comment by GreatV** [comment]
> @GreatV Oh what does it mean exactly?

Just wait for new Testnet release, and try again.

**Comment by mauro-miatello** [comment]
same here
it connects, stay online some minutes and then goes offline

**Comment by mauro-miatello** [comment]
it seems working with Testnet 132 Build v0.1.38, but it's at the same point since 48h (1894/2572) and no log / messages of what it's doing
