### ISSUE TITLE
Per-cluster weak coin for healing

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2428]
## Description

Right now, self-healing relies on a weak coin that's generated _per layer_ (see #2393). This should really be per cluster, not per layer. Quoth @tal-m:
> note that whenever we say "layer" for self-healing, we actually need to use "cluster", where a cluster is a set of enough layers that they have 800 blocks in total (in expectation). So if layer size is 50, a cluster would be 16 layers. For layer size 200, a cluster is 4 layers.
> There should really be one coin per cluster, and all blocks in a cluster should vote the same way (depending only on the blocks they received by the start of the cluster).
>  This is because for 50 blocks, if q=1/3 there's a pretty good probability that there will be a dishonest majority.

## Affected code

This issue appears in commit hash: #2393 (not merged yet)

Related files (optionally with line numbers): 
- hare/preroundtracker.go
- hare/hare.go
- etc.

**Comment by moshababo** [comment]
@dshulyak still relevant?

**Comment by dshulyak** [comment]
i will doublecheck with Tal if he still considers improvements to weak coin as useful
