### ISSUE TITLE
Implement blocking, threadsafe routing table.

### ISSUE THREAD

**Issue by y0sher** [spacemeshos/go-spacemesh#244]
Currently `dht.RoutingTable` is implemented using a big select loop to synchronize all actions on its contents, to prevent deadlocks we use buffered channels, though with this approach we cannot ensure our action was finished when its returns. this can be achieved by switching to non-buffered channels. but it might deadlock and for sure block other actions.

We want to re-implement routing table in a way that it will be easy to test, all it will work in a blocking way. but it should also be thread safe.

**Comment by zalmen** [comment]
@y0sher, is it still relevant? Do you expect to address this as part of the MS-2.0 work?
