### ISSUE TITLE
AccountNonce does not keep up with more than 1tx/5sec

### ISSUE THREAD

**Issue by andreivcodes** [spacemeshos/go-spacemesh#2443]
## Description

`Transaction incorrect counter or insufficient balance` when sending many transactions.

## Steps To Reproduce
1. Query the network for AccountNonce using GlobalStateServiceClient -> stateProjected.counter
2. Create a new transaction
3. Push it to TransactionServiceClient
4. Repeat at a rate higher than 1tx / 5seconds

## Expected Behavior

Transaction is added to mempool

## Actual Behavior
It works for a while, but not consistently. The lowest latency I could find which consistently works is 1tx / 5s. 
When the network does not keep up with AccountNonce increment, grpc outputs

`GrpcError (gRPC Error (code: 3, codeName: INVALID_ARGUMENT, message: Transaction incorrect counter or insufficient balance, details: [], rawResponse: null))`

**This was easily reproduced on 02/06/2021 but it looks like today, 03/06/2021, even 10tx/s work fine. I'm not sure if this was fixed already or it is just a coincidence.**

**Comment by moshababo** [comment]
Obsolete.
