### ISSUE TITLE
Api Regression in go-sm v0.1.36

### ISSUE THREAD

**Issue by IlyaVi** [spacemeshos/go-spacemesh#2446]
## Description
Node Service: 
Status query and Status stream don't return any data after sending query and activating stream.
Error stream dies immediately after activation with error message "14 UNAVAILABLE: No connection established"

AccountMeshDataStream, AccountDataStream close immediately after activation with end of stream event.

Nice to have:
AccountMeshDataQuery, AccountDataQuery to return empty dataset/array when no historic data exist per requested wallet instead of nil.

## Steps To Reproduce
run latest go-sm and try to establish stream clients for a fresh wallet

## Expected Behavior
Described previously

## Environment
Please complete the following information:
 - OS: 
 Mac OS
 - Node Version: 
v0.1.36

**Comment by avive** [comment]
> Nice to have: AccountMeshDataQuery, AccountDataQuery to return empty dataset/array when no historic data exist per requested wallet instead of nil.

what do you mean by nil? For AccountDataQueryResponse you should get total_results = 0 and an empty set of account_item. Maybe your grpc client is returning nil when a repeated field has 0 items?

**Comment by IlyaVi** [comment]
> what do you mean by nil? For AccountDataQueryResponse you should get total_results = 0 and an empty set of account_item. Maybe your grpc client is returning nil when a repeated field has 0 items?

I'm getting 'undefined' at the app as response

**Comment by avive** [comment]
> > what do you mean by nil? For AccountDataQueryResponse you should get total_results = 0 and an empty set of account_item. Maybe your grpc client is returning nil when a repeated field has 0 items?
> 
> I'm getting 'undefined' at the app as response

So it is def an issue we should fix and not a nice to have - when there are no results total_results should return to  0 and the results array should just be zero items.

**Comment by lrettig** [comment]
@IlyaVi I just tested all of these streams against the v0.1.36 code and I'm unable to recreate any of these errors. Everything appears to be working fine. I tried a fresh checkout, and I also tried the compiled binary. I tried without a config file, and with the 131 config file. I'm testing using `grpcurl` and note also that I've been running this against running nodes for all of the recent testnets, without issue. Maybe the issue is higher up in the stack somewhere?

**Comment by avive** [comment]
It is not exactly the same issue but related - one of the top users issues with smapp is lack of visibility regarding the managed hidden node status. Is the feature that the node will return an error via a stream to smapp complete in all cases that node panics? This way Smapp can display the error and enable the restart node button in the network screen.

**Comment by avive** [comment]
@IlyaVi - is this still an issue?
