### ISSUE TITLE
Harmonize time types in config

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2448]
## Description
Right now, we express time in different ways in different modules/sections of the config, e.g.:

```
        "main": {
                "layer-duration-sec": 300,
                "sync-request-timeout": 60000
        },
        "p2p": {
                "conn-keepalive": "48h",
                "dial-timeout": "1m",
                "response-timeout": "60s",
                "session-timeout": "15s"
        },
        "time": {
                "default-timeout-latency": "10s",
                "max-allowed-time-drift": "10s",
                "refresh-ntp-interval": "30m"
        }
```

Harmonize all of these so they all use a common format, e.g., milliseconds, or strings like "10s".

## Affected code

This issue appears in commit hash: f9e4a4b39d8d170c7d5696bd9e12cdac5aaf4360

**Comment by neodied** [comment]
I'd like to get my feet wet with contributing to open source projects and this seems like a decent, simple starting point.

@lrettig mind if I try to tackle this?

**Comment by lrettig** [comment]
@neodied go for it! This one is a good starting point, it should be fairly straightforward. My gut feeling is that, rather than using ms (at first glance it isn't immediately obvious what "60000" means) we should use the string format, e.g., "60s".
