### ISSUE TITLE
design and suggest ways to implement node loading from existing state

### ISSUE THREAD

**Issue by AmitShaul** [spacemeshos/go-spacemesh#2469]
## Description
in order to save time for developers to test their code we'd like to make the tests run time shorter.
one way of doing so is to load spacemesh nodes from a certain state, this means we don't have to wait for this state to be formed - which is time consuming.
for example today we run tests from setup stage, which means we start the network and wait for genesis process to finish.
currently no action happens at the first two epochs, nodes just wait until the third epoch (epoch number 2) to start creating blocks and process transactions.
this setup stage can be skipped if recorded once and loaded for each test (each test that uses the same config as the recorded config).

## TODO:
explore possible ways of implementing this solution.

**Comment by avive** [comment]
That will be amazing and very useful for local-net for dev scenarios. Right now, every time I change code in the node and I want to test it in a local network, I need to restart a local note with an updated local node image, wait until epoch 3 to test transactions and `normal` consensus behavior. Even with extreme short epochs and layers, I need to wait ~45 minutes which is quite bad. Being able to restore a local-net from persisted state after updating node version is going to be very useful for local spacemesh dev in the future. So I think this task should be extended (perhaps in phase II?) to load a Spacemesh network from persisted state. also, PoET persistence / restore should be considered as part of local-net state restore....
