### ISSUE TITLE
Hare inbound gossip message processing delays

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2478]
## Description
Nodes are taking as long as a minute to receive inbound Hare gossip messages and report them as valid (after which they're gossiped on to other peers).

I can't tell exactly what's going on under the hood without full debug logs. It could be an issue with the Hare broker priority queue, message validation, or something else. I suspect it's happening during the Hare broker `eventLoop`.

## Environment
Please complete the following information:
 - OS: Linux
 - Node Version: v0.1.41

## Additional Resources 
![image](https://user-images.githubusercontent.com/3316532/123186844-02e1bb00-d467-11eb-9174-803aad81651d.png)
from https://testnet-kibana.spacemesh.io/goto/29beacaf0fe3b5c3757deed8d6f8788a

**Comment by lrettig** [comment]
Dug a bit deeper using debug logs:

![image](https://user-images.githubusercontent.com/3316532/123360706-c59b2d00-d53b-11eb-9b82-0635e6b20aae.png)
full data: 
[hare backlog (1).csv](https://github.com/spacemeshos/go-spacemesh/files/6713146/hare.backlog.1.csv)
[hare backlog.csv](https://github.com/spacemeshos/go-spacemesh/files/6713147/hare.backlog.csv)
from https://testnet-kibana.spacemesh.io/goto/91ecf641e57a09491279144a2f4d0d67

The hare broker is getting stuck somewhere in here:

https://github.com/spacemeshos/go-spacemesh/blob/3645848f68a00d8b96f348402d61dbdb97b2db09/hare/broker.go#L232-L269

It seems like it's either the eligibility validator or the `newMsg` call. Both of these rely on the Hare oracle, which does use a mutex. And there's one or two other parallel hare goroutines also using the Hare oracle from the main consensus process code in algorithm.go, including:

https://github.com/spacemeshos/go-spacemesh/blob/3645848f68a00d8b96f348402d61dbdb97b2db09/hare/algorithm.go#L286-L303

But I can't find any blocking calls that would cause it to get stuck for as long as 60 secs.

**Comment by dshulyak** [comment]
there is a graph traversal function that may do many reads from disk and it is executed while holding the exclusive lock in the oracle https://github.com/spacemeshos/go-spacemesh/blob/100d5ce178bc90721492c605a365b4efe59a6518/activation/atxdb.go#L248-L274. i don't understand why i can't find the log line "done calculating active set size" with timings in the elastic. the text of log has changed between 0.1.41 and current version, but i can't find either.

**Comment by lrettig** [comment]
@dshulyak you were right:

`done calculating active set size | atxDb | 1m13.812238934s`

Here it is in the live testnet logs: https://testnet-kibana.spacemesh.io/goto/48b95795d097bdd1cabca9d825b3ca93

**Comment by lrettig** [comment]
Each node only needs to calculate this once per epoch, but it takes a very long time (then it's cached). This explains why the issue only pops up sporadically.

As a quick workaround, we could trigger the calculation before it's needed, run it concurrently and cache it. But I think we need to understand why this is so slow (I/O, I suppose) and speed it up.

**Comment by lrettig** [comment]
Here's a workaround: https://github.com/spacemeshos/go-spacemesh/pull/2481/commits/377e908b03babfc9d7bbd489fb20ff11f706027f

I'll PR this into develop as well but need to rework it, as testnet and develop have diverged.

**Comment by dshulyak** [comment]
I would also like to profile that graph traversal function to understand how it can take 1m.

**Comment by dshulyak** [comment]
On devnet 0.2 it takes between 5-10 ms to compute this value:
![Screenshot from 2021-08-06 13-11-39](https://user-images.githubusercontent.com/1964576/128495323-87d27186-fcb7-41b3-824e-f027fb716d8c.png)

**Comment by dshulyak** [comment]
Let's close it I guess. I will make sure to monitor a larger testnet to see if latency is still acceptable.
