### ISSUE TITLE
Create a spacemesh network test in testground

### ISSUE THREAD

**Issue by y0sher** [spacemeshos/go-spacemesh#2504]
## Motivation

The testground testing framework developed by Protocol Labs (ipfs,filecoin) has developed quite fast since we started developing spacemesh, it now has most of the features we need if not more, it might be easier to migrate to testground instead of recreating all this logic; it even supports injecting latency and other adversary testing methods. 

it can run locally on docker or on a k8s cluster, the only thing is we might need to set up our own none-managed k8s cluster. @narayanprusty or @valar999 could probably help setting this up.

@daonb might be able to migrate the first transaction test since he's been fiddling with it for a while now.

**Comment by daonb** [comment]
This is going to be fun.  I'll start working on the test_transaction case.

Regarding the the setup, I really like the [init pattern](https://link.medium.com/HxQySlYjFhb). Instead of a main controller we'll use short-lived containers running next to each node, bringing it to life when the enviornement is ready.

**Comment by daonb** [comment]
I want to start with a simplified version of test_transaction:

The test starts after genesis and then creates a tab account with 50 Mesh. It then waits for the network to synchronize and transfers 5 Mesh to a new regular account. After sync it validates the transfer and issues a new transfer from this new account to another new account, waits for sync and validates.

That's all. I've remove more transfers and random accounts as it probably belongs in a different test.

**Comment by y0sher** [comment]
I'm not familiar with init containers, lets try to stick to the way testground does it, there are some great references for test plan on `lotus` (filecoin client) and in `libp2p/tesplans`.
No problem to simplify the test in order to get it running quickly, but keep in mind breaking similar tests into smaller tests won't be so cost-effective, setting up a whole network for each small test will be expensive in time and $$$. Anyway for the purpose of checking if testground fits our needs you can make it as simple as possible.

**Comment by daonb** [comment]
testground give us test plans that are made of one or more test cases. All test cases in the plan share the same network and setup run once per plan. 

Here's the [first test plan](https://github.com/daonb/go-spacemesh/blob/testground/plans/mining/main.go) for your review.
