### ISSUE TITLE
Create devops infrastructure for testground

### ISSUE THREAD

**Issue by y0sher** [spacemeshos/go-spacemesh#2510]
## Description

We recently found `testground` , a framework that might service all out testing needs, including local tests of multiple nodes and even running a scaled environment on k8s. 

In order to test the k8s approach and run big tests we'll need to create the required infrastructure, machines and permissions. testground isn't using a managed k8s like eks or gke. 

@valar999 please dive into testground and create the required devops infra to run it.

**Comment by valar999** [comment]
Now it supports only AWS. I will try it first.
