### ISSUE TITLE
Propose new CI build solution

### ISSUE THREAD

**Issue by noamnelke** [spacemeshos/go-spacemesh#2514]
# Motivation
We currently perform builds locally and upload them to Dockerhub, where the CI pulls from to run system tests. The same process is used for running testnets. This has never been a problem thanks to Go's cross compilation - developers were able to create builds for all platforms, regardless of the platform they're developing on.

Now that we start using CGO in order to support GPU-PoST and later SVM the build process becomes more involved, with dependencies that are not trivial to keep in sync on different platforms. Building binaries for different platforms than the platform they're being built on is also a challenge.

# High level solution
The "industry standard" is to create builds remotely as part of the CI process. We should consider all the different use-cases that are in use at Spacemesh and design a process that will support them. The high-level idea is to spin up machines running different platforms and create each platform's binary on a development machine running that platform. We should consider how we make the artifacts available to the next steps in the CI flow, how artifacts from other repositories (in other languages) are referenced and pulled, etc.

**Comment by moshababo** [comment]
@noamnelke still relevant?
