### ISSUE TITLE
Use more efficient algorithm for rescoring good blocks after healing

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2522]
## Description
Right now, we use a very naive algorithm to rescore which blocks should be marked as "good" blocks, on the basis of new information, after self-healing successfully heals one or more layers:

https://github.com/spacemeshos/go-spacemesh/blob/e09b148deab77f05ceab52ae8b7495adfc5102aa/tortoise/verifying_tortoise.go#L874-L892

Basically, it rescores every block in every intervening layer, from the first healed layer up to the top layer. This is quadratic, if not worse.

This [research forum thread](https://community.spacemesh.io/t/effficient-vote-encoding-encoding-checkpoints-for-efficient-tortoise-verification/72) contains ideas on how we can do this more efficiently. We should be able to achieve an algorithm that is linear in the number of healed blocks/layers.

## Affected code

This issue appears in commit hash: e09b148d

Related files (optionally with line numbers): tortoise/verifying_tortoise.go

**Comment by lrettig** [comment]
Tal: it's critical to have this for genesis because it requires passing and storing additional information (that we wouldn't otherwise have)

**Comment by dshulyak** [comment]
For this specific issue we don't need more efficient algorithm. With recent optimizations rerun of 4000 layers takes ~40 seconds. Most of the bottlenecks that are left are related to the number of votes that we have. So once we switch to unified content block rerun will be blazingly fast. Rescoring blocks is a part of rerun and in this particular case, we will never rescore blocks for 4000 layers, at most for 2000 in mainnet.  

We may need a more efficient algorithm for the rerun, it will take around ~30minutes to rerun a mesh after it was up for a year. But this needs to be re-evaluated after the unified content block is introduced.

**Comment by dshulyak** [comment]
I consider it optimized and sufficiently good based on latest data.
