### ISSUE TITLE
Duplicated results in MeshService.AccountMeshDataQuery

### ISSUE THREAD

**Issue by avive** [spacemeshos/go-spacemesh#2530]
Repro: 
```bash
grpcurl -d '{"filter" : {"accountId":{"address":"uo8EjA4XCaFWQpCuz1xr6vihXhw="}, "accountMeshDataFlags":1}, "minLayer":{"number":0},"maxResults":0, "offset":0}' api-34.spacemesh.io:443 spacemesh.v1.MeshService.AccountMeshDataQuery
```

Result: 8 results of 2 duplicated transactions.
Expected: 2 results, one for each unique transaction.

**Comment by lrettig** [comment]
This is an implementation issue, not a design issue. Transferring to go-spacemesh

**Comment by avive** [comment]
clients can easily filter results by tx id but there may be a deeper issue here such as same tx in multiple layers or save transaction in multiple blocks in same layer. Another good reason to add tx layer id to this api results.

**Comment by dshulyak** [comment]
Keys are stored in a very error-prone way. This is an example of getTransactionDestKeyPrefix keys, that are generated with this function:

```go
func getTransactionDestKeyPrefix(l types.LayerID, account types.Address) []byte {
	str := "a_d_" + account.String() + "_" + strconv.FormatUint(l.Uint64(), 10)
	return []byte(str)
}
```

Then, if I create 4 transactions in layers 2,20,21,22 this is how keys will look like:

```
a_d_0xA7f6282fA5323a9dc0035024Ddf689F1A50FFA6b_20_0xf2d4e41d955e5699b37d217d31dc36c1bfa1f48216edb710161d13f3cc0ce1bf
a_d_0xA7f6282fA5323a9dc0035024Ddf689F1A50FFA6b_21_0x0f352dd46f0e87a97ded043de33204ad0d6166a3e16c610eb19886dfe1633ea9
a_d_0xA7f6282fA5323a9dc0035024Ddf689F1A50FFA6b_22_0x28fc6b62ebe5e4327b49e2bbe5209fe316eb2e5bc58f5be049f5827b876c4233
a_d_0xA7f6282fA5323a9dc0035024Ddf689F1A50FFA6b_2_0x68a09d64fa0f07b342448949070fa1e5cebe8c434739526432db9aa43bb8671b
```

When we are scanning for this address 0xA7f6282fA5323a9dc0035024Ddf689F1A50FFA6b starting at layer 2 we will traverse all these keys. So, if we are doing queries from layers 2 till 22, we will find every transaction multiple times (https://github.com/spacemeshos/go-spacemesh/blob/develop/api/grpcserver/mesh_service.go#L248-L257)

**Comment by dshulyak** [comment]
I changed code in that module slightly while working on this issue https://github.com/spacemeshos/api/issues/153. So I will propose a fix for this as well.
