### ISSUE TITLE
Flag remoteNodeManagement

### ISSUE THREAD

**Issue by valar999** [spacemeshos/go-spacemesh#2537]
## Description
Add boolean flag to config remoteNodeManagement with default value of false.
Only accept write methods (methods that modify node) in NodeService from localhost unless flag is set to true.

Blocks https://github.com/spacemeshos/ws-ops/issues/25

**Comment by dshulyak** [comment]
Usually private and public servers are just running on different sockets (e.g. private only on localhost). Based on an attached issue we should split our single API servers into two. Doing checks based on a source and a variable sounds quite hacky in the API.

**Comment by moshababo** [comment]
@lrettig any thoughts?

**Comment by lrettig** [comment]
Agree with @dshulyak, this should not be a flag. It should either be different API services, or two entire API servers running on two different ports/interfaces.
