### ISSUE TITLE
Weight tortoise votes based on beacon correctness

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2540]
## Description

Right now, we calculate the weight of votes in tortoise in a straightforward fashion, based only upon the weight of the voting block's ATX:

https://github.com/spacemeshos/go-spacemesh/blob/ab0616c6b700a3585ac2e9e33dd879cc1cda27a7/tortoise/verifying_tortoise.go#L489-L500

Per @tal-m, we need to take a couple of other factors into consideration:

- beacon correctness
- whether the ATX was received on time

> For verifying tortoise, we can be more conservative --- we don't count votes with an incorrect beacon value (i.e., different from ours for that epoch) or votes with ATXs that weren't received on time (unless we're syncing, in which case we expect everything to be late). So those just have weight 0.
> For self-healing, we do need to count all valid votes, but we "postpone" votes with a bad beacon. This means that if the current epoch is i, then votes with an incorrect beacon in epochs i-k,...,i have 0 weight, but for votes in epochs < i-k we ignore the beacon and give them full weight. (k is a parameter that for now I think we can set to 1)
> I was talking about the tortoise beacon. This is the one used for block eligibility.

See threads in Slack [here](https://spacemesh.slack.com/archives/CG91F13C7/p1625681189049600)

Note that we _do_ store ATX timestamps, which are used by the tortoise beacon to validate timely ATXs. However, we do not associate tortoise beacon values with blocks and their votes, so this association needs to be created somehow.

Requires #2541, #2542, #2544

## Affected code

This issue appears in commit hash: ab0616c6b700a3585ac2e9e33dd879cc1cda27a7

Related files (optionally with line numbers): tortoise/verifying_tortoise.go

**Comment by lrettig** [comment]
Per https://github.com/spacemeshos/go-spacemesh/issues/2544#issuecomment-877864416, we should only consider beacon correctness here, not ATX validity.

CC @dshulyak, @tal-m

**Comment by dshulyak** [comment]
@countvonzero could you please confirm that it was implemented with https://github.com/spacemeshos/go-spacemesh/commit/9c8b62c01095445d7e3c06faeb37b3803b92456d ?

**Comment by countvonzero** [comment]
> @countvonzero could you please confirm that it was implemented with [9c8b62c](https://github.com/spacemeshos/go-spacemesh/commit/9c8b62c01095445d7e3c06faeb37b3803b92456d) ?

yes. it's implemented in the said commit. tho the approach is slightly different. instead of using zero weight for K layers, it's simply not considering the voting blocks with the wrong beacons for K layers

**Comment by dshulyak** [comment]
Sounds the same to me)
