### ISSUE TITLE
Store tortoise beacon value in blocks

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2541]
## Description
Tortoise beacon is used to determine eligibility for blocks but the beacon value is not stored explicitly in blocks. Per @tal-m, 

> It [the beacon value] appears explicitly only in the first block of every epoch
> A block with an incorrect beacon value isn't syntactically invalid --- it's valid, but its vote is postponed. It should still be gossiped and stored (and its votes should be counted once they are old enough).

This is required by self-healing

## Affected code
miner/block_builder.go
blocks/blockoracle.go

This issue appears in commit hash: 50268fc6c8aa7205c8a5c5d573f17cf7956084df

CC @nkryuchkov

**Comment by nkryuchkov** [comment]
Implemented in https://github.com/spacemeshos/go-spacemesh/pull/2826/files#diff-8ac542d4d1c25da9711b531b91af36b77f933bfb13f6fdc47cf86f15f35bc1a3R278
