### ISSUE TITLE
Replace dynamic XDR codec with more efficient encoding

### ISSUE THREAD

**Issue by antonlerner** [spacemeshos/go-spacemesh#2545]
## Description
Currently we use dynamic encoding / decoding of our structs we should move to use statically defined .x files that describes the structs primitive types for better performance.

**Comment by avive** [comment]
i think that the time to implement this for transactions encoding should probably be on or after the new tx model (based on account abstraction) is implemented in the node which we need to do for 0.3.

**Comment by dshulyak** [comment]
Is there a library that can generate golang code from .x files?

**Comment by dshulyak** [comment]
I suggest we tackle it before MN, current xdr library is not optimal and we should check if xdr using .x files will address its issues. If not we should switch to other options (cbor, flatbuffers, maybe something else).

**Comment by moshababo** [comment]
Pending https://github.com/spacemeshos/go-spacemesh/issues/2686.
