### ISSUE TITLE
tortoise: provide API to trigger rerun

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2551]
## Description
We need to occasionally trigger a rerun of verifying tortoise to account for new information that may have accumulated for old layers that slipped outside the tortoise window. It's unlikely, but theoretically possible that enough new information (e.g., newly-arrived ATXs or blocks from the other side of a network split) may have arrived that might change the tortoise opinion about block/layer validity.

Right now, we do the Simplest Possible Thing and just trigger a full rerun from genesis every once in a while, but this is highly inefficient:

https://github.com/spacemeshos/go-spacemesh/blob/cccc75614ab32d2bee8d31997706b00dbaf283a7/tortoise/verifying_algorithm.go#L157-L169

It would be better to account for the weight of newly received information, and trigger a rerun only when that weight is high enough to possibly cross the threshold of changing tortoise opinion.

Some other things to figure out (with placeholder TODOs in the code):

- should the rerun happen "in the background" in a separate goroutine? does it need to hold the tortoise mutex? related to #2415 
- how to handle errors

## Affected code
tortoise/verifying_algorithm.go
Possibly related to sync: CC @countvonzero 

This issue appears in commit hash: e13b3aa467335aef4d3552348ef929f419f72e94

**Comment by moshababo** [comment]
@dshulyak still relevant?
