### ISSUE TITLE
Don't rerun verifying tortoise every time a late block arrives

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2552]
## Description

We've always rerun the full tortoise algorithm every time we receive a late block, in order to update vote counts and other block data. Per @tal-m, we don't actually need to do this anymore with verifying tortoise for two reasons:

1. Late blocks should not be considered honest (and the verifying tortoise only counts honest blocks)
2. If our assumptions hold, a late block will not change the verifying tortoise opinion anyway

Tal said:

> the verifying tortoise works at layer resolution; processing blocks separately would negate the efficiency optimization that takes it from quadratic to linear. If we already processed the layer for that block, the verifying tortoise doesn't need to process the block at all (since honest blocks shouldn't arrive late, and the verifying tortoise only needs to count honest blocks).

See [this thread](https://spacemesh.slack.com/archives/CG91F13C7/p1626053930107300) on slack.

Self-healing _does_ count all blocks (it has no notion of "honest" blocks or blocks received on time) but it doesn't need to explicitly run every time a block arrives late. (When it does run, it will see blocks that were added to the mesh.) What's more, we trigger a full rerun of verifying tortoise from scratch once in a while (see #2551), which will factor in late blocks as needed.

Related: #2412, #2415, #2551

## Affected code
tortoise/*
sync, mesh code that passes block data to tortoise

This issue appears in commit hash: e13b3aa467335aef4d3552348ef929f419f72e94

**Comment by dshulyak** [comment]
This was changed lately, we don't count late block until rerun. In future, i assume it will be accelerated with mesh state sync.
