### ISSUE TITLE
Publishing Global state tree root

### ISSUE THREAD

**Issue by antonlerner** [spacemeshos/go-spacemesh#258]
As written in design doc:

In order to allow all nodes to know if their state is accurate, a global state root hash must be published on the blockmesh. The published root hash must be derived from a state which is surely in consensus between all nodes, this state can be derived only by processing blocks and transactions from previous layers which accumulated enough positive votes to be considered irreversible. This period of layers will be decided is called the “Global state threshold”. Each node will publish its own state tree root hash on a block that's being mined alongside an aggregated hash of all transactions that were applied to receive the published root.
Each node must compare its root hash to the root published on the mesh, if the local nodes root hash differs from published root hash it must revert to the last root hash that was consistent with the hash published on the mesh and replay the transactions since. TO REVIEW: It probably would need to invalidate all blocks received from since and re- request them from peers.
TODO: if different blocks have different root hashes in them, which is the correct one? What is the expected behaviour in such case?

**Comment by zalmen** [comment]
@antonlerner, does your first comment above still stands? Are we going to publish the state root in the block header? If no, can we close this issue? Also, look at [#256](https://github.com/spacemeshos/go-spacemesh/issues/256 ) and check if it's still relevant (same topic)

**Comment by antonlerner** [comment]
Since state is not required to be consistent between all nodes at all times we chose currently not to publish root state currently and rely on tortoise mesh consistency for correct state.
