### ISSUE TITLE
Block validation failure due to wrong tortoise beacon

### ISSUE THREAD

**Issue by nkryuchkov** [spacemeshos/go-spacemesh#2582]
## Description

The `TestMultiNode` test may fail because of the `block eligibility check failed - err tortoise beacon eligibility VRF validation failed` error on one of the nodes. This error is logged because this node has a tortoise beacon that is different from tortoise beacons on other nodes. The failure happens almost never on a PC/laptop, sometimes in CI, very often on a Raspberry Pi.

## Steps To Reproduce
1. Run `TestMultiNode` multiple times on a slow machine until it fails

## Expected Behavior

`TestMultiNode` always passes, there are no `block eligibility check failed - err tortoise beacon eligibility VRF validation failed` errors in logs

## Environment
Please complete the following information:
Slow machines like RPi, sometimes CI, but may appear on faster machines.

## Additional Resources 

TBD

**Comment by lrettig** [comment]
I'm still seeing this happen nearly all the time when running app tests in the `healing` branch, even with this fix. Attaching a sample log.

[testlog15-bad.txt.gz](https://github.com/spacemeshos/go-spacemesh/files/6979313/testlog15-bad.txt.gz)

**Comment by lrettig** [comment]
@nkryuchkov see also this failure: https://github.com/spacemeshos/go-spacemesh/runs/3317849384?check_suite_focus=true

**Comment by lrettig** [comment]
More recent runs are working. I wonder if something in #2649 fixed this. Will close for now unless it recurs again.
