### ISSUE TITLE
Make error -  macOS / M1

### ISSUE THREAD

**Issue by avive** [spacemeshos/go-spacemesh#2586]
## Description
setup_env.sh fails on systems with M1 cpu.

## Steps To Reproduce
Run make on v0.1.44. Note that there's no error in develop branch.
 
## Expected Behavior
Make to build the go-spacemsh binary 

## Environment
 - OS: macOS
 - Node Version: v0.1.44.

## Additional Resources 

```
>make
./setup_env.sh
fetching https://github.com/protocolbuffers/protobuf/releases/download/v3.6.1/protoc-3.6.1-osx-arm64.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9  100     9    0     0     16      0 --:--:-- --:--:-- --:--:--    16
extracting...
Archive:  protoc.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of protoc.zip or
        protoc.zip.zip, and cannot find protoc.zip.ZIP, period.
make: *** [install] Error 9
```

**Comment by noamnelke** [comment]
The testnet version is based on old code that still requires protobuf, which is no longer the case in `develop` (we no longer use protobuf there).

I'm closing this issue since this will get fixed when the testnet catches up. If you think this is urgent enough for a hotfix on the testnet - please reopen it.
