### ISSUE TITLE
Stream timesync error to RPC clients and add API to notify that the clock is correct

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#2593]
Per discussion in https://github.com/spacemeshos/SMIPS/issues/55.

We want to provide users of the smapp with timely notifications that the time is not sync, before node will be shutdown.
On such error user will have to fix the clock and notify the go-sm with another API call.

Once API call is received we assume that the system clock is adjusted and previous errors can be ignored. In future we can also drop peers that have invalid clock.

**Comment by avive** [comment]
Q: are we still going to check on startup drift related to average time from several NTP servers and crash the node if drift is too big and only notify via api if there's a drift while the node is running? Need to better understand how node behavior's going to change to think through the UI/UX implications.
@antonlerner @moshababo

**Comment by antonlerner** [comment]
I think that as per our discussion in the [SMIP](https://github.com/spacemeshos/SMIPS/issues/55 ) in case of a large time drift we will pause all miner operations and put out an error that miner cannot continue running until time drift is fixed. the implementation of halting all miner operations can be via killing it, but can be done in other ways

**Comment by dshulyak** [comment]
Streaming errors will be fixed as a part of https://github.com/spacemeshos/go-spacemesh/pull/2603

**Comment by dshulyak** [comment]
I will remove it from the current sprint. We are not going to add this API for now to keep things simple. Later we will keep things as they are or act based on feedback (if any).
