### ISSUE TITLE
Disable logs during test run

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#2598]
## Description

It is really hard to find out what test failed when there is a wall of text. Most of the time test output doesn't even fit in my terminal history and I can't find the test failure message. 

Logs might be necessary to debug the failure in some cases and we can keep them on CI, but there should be an option to disable them completely (reduce verbosity level).

Solution:
- Register a command line option to set a log level for tests
- Use common logger initializer across all tests

```go
var testLoglevel = flag.String("testlevel", "info", "")

func NewTestLog(testName string) Log {
     // set testLogLevel to a new logger with
}
```

**Comment by daonb** [comment]
I feel the pain but this is just an interim solution.

As a developer running tests I don't want to fiddle with CLI options. All I want is a short pass message when all is well and all the logs when it fails.

**Comment by dshulyak** [comment]
@daonb you will be able to get that with `go test ./...` (without any flags). I am pretty sure that the solution that I proposed works for all use cases (take a look at the change).
