### ISSUE TITLE
Use json array for grpc services items in config file

### ISSUE THREAD

**Issue by avive** [spacemeshos/go-spacemesh#2601]
## Motivation
The current specification of grpc services in the config file is using one string with a list of services. This is fragile and kind of the wrong type to have an array of data.

Current implementation:
```json
"api": {
		"grpc": "gateway,node,mesh,globalstate,transaction,smesher,debug"
	}
```
To see how fragile this is, try adding a space between array items in the string and start a node. It will panic.

Enhancement:

```json
"api": {
		"grpc-services": ["gateway",  "node" , "mesh", "globalstate", "transaction", "smesher", "debug"]
	}
```

This seems like a trivial change but one of the first things that newcomer devs to the project and technical testnet users are going to do is to look at the config file and it starts with something not that great...

**Comment by noamnelke** [comment]
Just to be clear, we don't actually parse the config ourselves or even require using JSON specifically (the default for the config is actually TOML) -- we use Cobra for that.

From skimming their documentation it looks like both formats (comma separated string and list of strings) are supported (I'm not 100% sure, though). Before we assign a dev to this task - can you please confirm that the format you want isn't actually supported today?

**Comment by avive** [comment]
confirmed as i wrote in the repro case above, adding space panics.

**Comment by avive** [comment]
I've verified this works: 
```json
"grpc": ["debug" ,"gateway","node","mesh","globalstate","transaction","smesher"]
``` 

So this issue should now be - update reference config files we provide for devnets and testnets to use good json.

**Comment by noamnelke** [comment]
@narayanprusty ☝🏻

**Comment by andres-spacemesh** [comment]
The config map is working correctly. Devnet-999 is using it at https://github.com/spacemeshos/Applications/blob/main/spacemesh-networks/devnet/999/config.yaml#L10
