### ISSUE TITLE
Rewards for account api error

### ISSUE THREAD

**Issue by avive** [spacemeshos/go-spacemesh#2606]
## Description
Querying for some managed miners rewards returns an api error.

## Steps To Reproduce
1. Run the unnamed/untagged 7/28 created devnet
2. Query GlobalStateService::AccountRewards() for account `0x8C99365feE31f1cEDB056A35D7f561584679ea3c`

Result: grpc error response.
Expected: Display account rewards.

Called with offset 0 and maxRresults 0.

Note that this is one of the managed miners addresses that has a balance due to rewards so there should be rewards for this account. If you need to repro interactively then use smrepl from the smesher-api branch or you can also repro with grpc-url. Also notes that rewards are fetched fine for other managed miner accounts so it only happens in some cases but not all.

```
$ state account
$ Enter an address: 0x8C99365feE31f1cEDB056A35D7f561584679ea3c
Address: 0x8C99365feE31f1cEDB056A35D7f561584679ea3c
Balance: 134.880360951726 SMH
Nonce: 0
Projected balance: 134.880360951726 SMH
Projected nonce: 0
Projected state includes all pending transactions that haven't been added to the mesh yet
$ 
```

How to repro:
```
>grpcurl -d '{"filter" : {"accountId":{"address":"jJk2X+4x8c7bBWo11/VhWEZ56jw="}, "account_data_flags":4}}' -plaintext localhost:9092 spacemesh.v1.GlobalStateService.AccountDataQuery
{
  "totalResults": 1,
  "accountItem": [
    {
      "accountWrapper": {
        "accountId": {
          "address": "jJk2X+4x8c7bBWo11/VhWEZ56jw="
        },
        "stateCurrent": {
          "balance": {
            "value": "152276432652715"
          }
        },
        "stateProjected": {
          "balance": {
            "value": "152276432652715"
          }
        }
      }
    }
  ]
}

>grpcurl -d '{"filter" : {"accountId":{"address":"jJk2X+4x8c7bBWo11/VhWEZ56jw="}, "account_data_flags":2}}' -plaintext localhost:9092 spacemesh.v1.GlobalStateService.AccountDataQuery
ERROR:
  Code: Internal
  Message: error getting rewards data
>
```

**Comment by avive** [comment]
This issue happened using a non-managed devnet node which joined the devnet and synced as the api provider.

**Comment by dshulyak** [comment]
I was able to reproduce this bug. Turns out it is not random at all. This is the stringified key `r_0x8C99365feE31f1cEDB056A35D7f561584679ea3c_714ecedf9616392cf83feb45988036ee1e3da31cb8285c616c1a62a9542b93698�T�v����ۧo�w���_��.�JPZu��_1001` for smesher rewards.

This key is generated as `str := string(getSmesherRewardKeyPrefix(smesherID)) + "_" + account.String() + "_" + l.String()`. Separator ( `_` ) that we are using is actually equal to one byte (95), so if this byte appears anywhere in String() it will cause this issue.

**Comment by avive** [comment]
i guess we need to check all similar db keys for this issue.

**Comment by dshulyak** [comment]
I agree. It is somewhat hard to spot such errors immediately. As a general rule we shouldn't use any sort of string concatenation or fmt.Sprintf for byte keys stored in a database.
