### ISSUE TITLE
No smeshing rewards

### ISSUE THREAD

**Issue by avive** [spacemeshos/go-spacemesh#2607]
## Description
1. Start a node w/o smeshing and sync on unnamed 0.2 devnet with genesis at 7/28 and sync
1. Use smrepl api client to setup pos, rewards address and start smeshing
1. Wait for more than 4 epochs

Result: No semshing rewards for the smesher id or for the rewards address are returned and rewards address balance is 0.
Expected: Start getting smeshing rewards to rewards address.

```
$ smesher status
Node is currently smeshing
$ post status
👍  Proof of spacetime data was created and is used for smeshing.
Proof of spacetime configuration:
  Data dir (relative to node or absolute): ./
  Date files: 1
  Compute provider id: 2
  Throttle when computer is busy: false
  Bits per label: 8
  Units: 2
  Labels: 2048
  Size (GiB): 1.9073486e-06
  Size (Bytes): 2048
$ smesher rewards-address
Rewards address is: 0x812E0B791364F81a23d67df0Ae9B9cD3B3e95016
$ smesher rewards
Smesher id: 0x2994b86a7ee7f80cc4f1299a88a30f488fa781faccbd14624bbe5f52ee5bc665
Total rewards: 0
$ account rewards 0x812E0B791364F81a23d67df0Ae9B9cD3B3e95016
Total rewards: 0
$ 
```

**Comment by dshulyak** [comment]
It looks like (from logs) that this smesher never sent any ATX's (or they weren't received by any managed node). As i understand this `0x2994b86a7ee7f80cc4f1299a88a30f488fa781faccbd14624bbe5f52ee5bc665` is atx_node_id, and `0x812E0B791364F81a23d67df0Ae9B9cD3B3e95016` is coinbase.

**Comment by avive** [comment]
one thing to check is if it was able to communicate with poet. Maybe poet only visible to managed nodes?

**Comment by dshulyak** [comment]
Poet is available.

**Comment by dshulyak** [comment]
We are not publishing atx unless node is synced. So this is pointless to test because sync can't finish for newly joined nodes in current devnet.

**Comment by avive** [comment]
understood. I will try to repro when new nodes can join a devnet.

**Comment by lrettig** [comment]
I suspect this is due to #2609, let's follow up there. If there is evidence that a node is fully synced and still not receiving rewards, reopen and we can investigate the issue separately.
