### ISSUE TITLE
Verified layer and synced layer gets stuck on 0.2 devnet

### ISSUE THREAD

**Issue by avive** [spacemeshos/go-spacemesh#2609]
Repro: Try to sync a node to devnet with genesis of 7/28.
Result: Verified layer is stuck at 166. Synced layer stuck at layer 245. Current layer is 428 as of report time.

```
$ status node
Node info:
Version: v0.0.0-unreleased
Build: d4270faff08c112a704d9e3beaefab7304eed919
API server: localhost:9092 (GRPC API 1.1). >> Insecure Connection. Use only with a local trusted server <<
Synced: false
Synced layer: 245
Current layer: 428
Verified layer: 166
Peers: 8
```

[log.txt.zip](https://github.com/spacemeshos/go-spacemesh/files/6898663/log.txt.zip)

**Comment by dshulyak** [comment]
This issue is outdated by now. We will reopen new if we see verified layer being stuck in new devnet.
