### ISSUE TITLE
Blocks are not produced because node goes out of sync

### ISSUE THREAD

**Issue by antonlerner** [spacemeshos/go-spacemesh#2610]
## Description
It seems that nodes go out of sync sometimes and not produce blocks at some layers

```2021-07-20T04:36:03.3731003Z 2021-07-20T04:32:24.107Z	INFO	bb576.sync         	setting layer 6 to zero-block	{"node_id": "bb5760ec4abb906c71caa5b6b039fde593651432686141a64ec39dfdd3b4a177", "module": "sync"}```
```2021-07-20T04:36:03.3741370Z 2021-07-20T04:32:24.107Z	ERROR	bb576.sync         	failed to set zero-block for layer	{"node_id": "bb5760ec4abb906c71caa5b6b039fde593651432686141a64ec39dfdd3b4a177", "module": "sync", "layer_id": 6, "errmsg": "layer has blocks", "name": "sync"}```

this error triggers the “not synced” state

Error is caused because we try to sync the current layer while accepting blocks from gossip, while we do that there is a race between synced and blocks received by gossip - if a block was received after we have synced layer with peers and received empty response it will error 

## Expected Behavior
Node should be synced all of the time
Node shouldn't go out of sync if an error is received when syncing current layer, maybe even not sync the current layer

## Environment
Please complete the following information:
 - OS: 
 
 - Node Version: 
 
 - App Version (if applicable):

**Comment by avive** [comment]
Is that what happened on the 7/28 devnet?
