### ISSUE TITLE
Flaky TestNIPostBuilderWithClients

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#2614]
## Description

--- FAIL: TestNIPostBuilderWithClients (1.43s)
    nipost_test.go:219: 
        	Error Trace:	nipost_test.go:219
        	            				nipost_test.go:187
        	Error:      	Received unexpected error:
        	            	builder: poet service is unstable: failed to get PoET service ID: Get "http://127.0.0.1:18551/v1/info": dial tcp 127.0.0.1:18551: connect: connection refused
        	Test:       	TestNIPostBuilderWithClients
    nipost_test.go:199: 
        	Error Trace:	nipost_test.go:199
        	            				panic.go:613
        	            				testing.go:741
        	            				nipost_test.go:219
        	            				nipost_test.go:187
        	Error:      	Received unexpected error:
        	            	failed to kill process: os: process already finished
        	Test:       	TestNIPostBuilderWithClients
--- FAIL: TestNewNIPostBuilderNotInitialized (1.24s)
    nipost_test.go:262: 
        	Error Trace:	nipost_test.go:262
        	Error:      	Received unexpected error:
        	            	builder: poet service is unstable: failed to get PoET service ID: response status code: 500, body: {"error":"service not started","code":2,"message":"service not started"}
        	Test:       	TestNewNIPostBuilderNotInitialized
    nipost_test.go:247: 
        	Error Trace:	nipost_test.go:247
        	            				panic.go:613
        	            				testing.go:741
        	            				nipost_test.go:262
        	Error:      	Received unexpected error:
        	            	failed to kill process: os: process already finished
        	Test:       	TestNewNIPostBuilderNotInitialized
FAI

## Steps To Reproduce
Runs unit tests. Fails periodically on https://github.com/spacemeshos/go-spacemesh/pull/2603 

## Environment

Ubuntu 20.04.1 LTS
go version go1.16.3 linux/amd64

**Comment by fasmat** [comment]
This test is flaky on ubuntu and mac OS.
 If executed on windows via github actions it never finishes and is canceled when the timeout is reached.
