### ISSUE TITLE
import and build go-spacemesh as a library for another project (testground)

### ISSUE THREAD

**Issue by y0sher** [spacemeshos/go-spacemesh#2618]
## Description

We want to test go-spacemesh within a testing framework like `testground`, one of the main features of this framework is you can just import your module and access it from a go-code like the was a unit test, this gives a lot of power in a distributed network.
 
## Changes

we need to create a dockerfile or a make command that enables importing go-spacemesh using `go get` within a docker.
preferably we will be able to do this with live code from a local repo or a remote branch. 

## Notes
this became a little bit harder since we introduced cgo and gpu-post..

**Comment by moshababo** [comment]
@y0sher to be closed?

**Comment by y0sher** [comment]
Pretty much done but not merged so we can close..
