### ISSUE TITLE
set genesis time when loading a preset network state

### ISSUE THREAD

**Issue by AmitShaul** [spacemeshos/go-spacemesh#2620]
## Description
when loading a preset node state the timing is different than when it was first recorded it.
this will cause nodes to fail since the whole network was "down" for that gap in time.
in order to prevent this "genesis time" can be set in a way that nodes won't notice the difference in time.

when starting a network with preset state genesis time should be set to (current time) - (the time took to record the state)
for example when recording two epochs with 4 layers per epoch and each layer is 30 seconds genesis time will be the current time - (30secs  * 4layers * 2epochs) = current time - 4 mins

## Update
apparently we already have a flag like that so this issue is not needed

**Comment by y0sher** [comment]
Adding a genesis-flag isn't needed but checking for compatibility of a different genesistime with the existing db is needed.
