### ISSUE TITLE
Implement tortoise beacon sync

### ISSUE THREAD

**Issue by nkryuchkov** [spacemeshos/go-spacemesh#2622]
## Description

Tortoise beacon sync should be implemented according to https://github.com/spacemeshos/SMIPS/issues/52

## Affected code

Tortoise beacon, sync

This issue appears in commit hash: 
`4b13d81196bb17698fba6312f81c0e54b8e73a76`

Related files (optionally with line numbers): 
TBD

**Comment by countvonzero** [comment]
breaking this down to the following issues:
- https://github.com/spacemeshos/go-spacemesh/issues/2809 beacon sync: record beacon in first block of epoch and use it to do syntactic validation
- https://github.com/spacemeshos/go-spacemesh/issues/2810 beacon sync: determine beacon value from blocks in the first K layers
- https://github.com/spacemeshos/go-spacemesh/issues/2811 beacon sync: hare uses synced beacon to determine "good" block
- https://github.com/spacemeshos/go-spacemesh/issues/2812 beacon sync: verifying tortoise never counts votes from block with incorrect beacon value
- https://github.com/spacemeshos/go-spacemesh/issues/2813 beacon sync: self-healing ignore votes from block with incorrect beacon for K layers

@moshababo
