### ISSUE TITLE
One slow (disconnected) peer will slow down everyone else

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#2647]
## Description

I was investigating broadcasting code flow (for the source of the problem of not delivered weak coins) and found that if a single peer is too slow and queue fills up it will slow down all delivery to other peers. 

In the gossip module we will iterate over all peers and block until the message is added to the queue of each peer. The current queue size is 250 messages. If single peer got disconnected but the socket is not yet terminated it will block for response-timeout (which is 60s by default and in majority of the configurations, which is also should be lower) and after that fail with deadline exceeded error.

## Steps To Reproduce

It can happen in a way that i described above, but i think it can be reproduced in a simpler way like: create two nodes, register gossip protocol, block in the handler instead of processing messages. Eventually, all queues must fill up and the peer on other side will be blocked on a send.

## Solution

Setup a buffer in bytes. For example 2mb for each outgoing queue. If this queue fills up disconnect a peer preemptively.
We have a configuration for max inbound and max outbound peers. By having these 2 (3) knobs we can control precisely how much memory p2p stack will be consuming in total.

## Expected Behavior

Single slow peer can't block everyone else.

**Comment by dshulyak** [comment]
cc @antonlerner @y0sher

**Comment by dshulyak** [comment]
Actually, this is not the reason why weak coin messages are not delivered on time. Otherwise, i will see this warning "connection: outbound send queue backlog".

**Comment by lrettig** [comment]
We have a series of old PRs that will likely address this issue:

- https://github.com/spacemeshos/go-spacemesh/pull/2435
- https://github.com/spacemeshos/go-spacemesh/pull/2450
- https://github.com/spacemeshos/go-spacemesh/pull/2463

See also #1868 (is it a duplicate?)

Will get these merged ASAP

**Comment by dshulyak** [comment]
This was addressed.
