### ISSUE TITLE
Refactor log.WithContext to minimize memory allocations

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#2657]
## Description

15% of all allocations in space and in objects is made by copying logger inside log.WithContext. This pattern is misused, if logger needs to be extended with some fields it must be copied once for the whole scope as in:

```go
clog := log.WithContext(ctx)
clog.Info(...)
clog.Debug(...)
```

And not

```go
clog.WithContext(ctx).Info(...)
clog.WithContext(ctx).Debug(...)
```

This will minimize amount of allocations but still not completely, because ctx is passed through the code and logger will have to be initialized in every separate method. We  need to find a way to avoid allocation but preserve ease of use. One way could is to use interface like:

```go
log.Info(..., log.Context(ctx))
```

log.Context will unpack session (or any other know fields) from context and print them without copying the logger. 

## Affected code

log.WithContext and every place it is used.

**Comment by dshulyak** [comment]
cc @lrettig

**Comment by dshulyak** [comment]
If we will use the approach with log.Context we can get log like:

```
logger.go:130: 2021-08-11T10:20:02.075+0300	INFO	test	{"context": {"session": "yyy", "request": "xxx"}, "name": ""}
```

I think this is good enough, the only question if elastic will be able to parse it correctly (https://www.elastic.co/guide/en/elasticsearch/reference/current/nested.html)

**Comment by lrettig** [comment]
Good idea. That works for me, assuming elastic can parse it!

**Comment by moshababo** [comment]
@dshulyak still relevant?
