### ISSUE TITLE
Fix tortoise memory leak if verified layer gets stuck

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2671]
## Description
If our assumptions hold, and self-healing works, the verified layer should not get stuck for very long in tortoise. However, if it does get stuck, we have a potential memory leak where the tortoise data structures will keep growing monotonically and will not be able to evict old layers. This is because the eviction window depends directly upon the last verified layer:

https://github.com/spacemeshos/go-spacemesh/blob/9d3a379994e3652eb0378d2cc555588bba91005e/tortoise/verifying_tortoise.go#L187-L204

We either need stronger guarantees about the maximum size that this window can reach, or else we need to take more aggressive steps to manage/bound memory usage here.

This issue appears in commit hash: 9d3a379994e3652eb0378d2cc555588bba91005e

**Comment by dshulyak** [comment]
It was noted in some discussion that we should evict from sliding window based on the Last layer, not Verified. It removes this potential leak.

**Comment by dshulyak** [comment]
I suggest we don't do anything about it. In current version the "leak" is still there, but it is manageable unless the tortoise is stuck for > 10 000 layers.
