### ISSUE TITLE
Cache block opinions in tortoise

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2672]
## Description
The tortoise relies upon the "local opinion" of blocks, which can depend upon several things depending on the age of the block's layer, whether or not it's been verified, and whether hare completed for the layer: counting votes in blocks, reading block contextual validity from meshdb, or reading the "input layer" (which may be received from hare, or from sync).

This operation can be very expensive, especially if it involves vote counting. We currently make no effort to cache this local opinion, nor any of the underlying data that it relies upon. This makes certain operations, such as rescoring "good" blocks after healing, very slow and expensive.

Devise a caching strategy that takes into account all of the moving parts (layer age, newly-arrived blocks and updated votes, hare results, etc.).

## Affected code
verifying_tortoise.go `layerOpinionVector`, `getBlockLocalOpinion`

This issue appears in commit hash: 9d3a379994e3652eb0378d2cc555588bba91005e

**Comment by dshulyak** [comment]
This was extensively profiled and the important part of this issue was addressed in https://github.com/spacemeshos/go-spacemesh/pull/2897 .
