### ISSUE TITLE
In Tortoise save and vote against blocks that exceed the max exception list size for DoS prevention

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2673]
## Description
Self-explanatory

## Affected code
https://github.com/spacemeshos/go-spacemesh/blob/9d3a379994e3652eb0378d2cc555588bba91005e/tortoise/verifying_tortoise.go#L595

This issue appears in commit hash: 9d3a379994e3652eb0378d2cc555588bba91005e

**Comment by countvonzero** [comment]
@lrettig @noamnelke please confirm that this issue is no longer applicable in the context of unified content block. we don't need to vote against contradictory ballot.

i think in this case we should black list the smesher that cast the vote

**Comment by dshulyak** [comment]
I am not sure regarding the unified content block, but this should be implemented in the block receiver. Every honest node should check if the block exceeds max exception limit, and if so drop it completely. This way it won't be included in the hare, and every node will vote against such block naturally. And i agree that we can also penalize smehser that produced this block, one we have that feature defined.

If the ballot can include exceptions i think this is still necessary for unified content block, why is it not?
