### ISSUE TITLE
Cache layer block IDs in tortoise

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2675]
## Description
Similar to #2672

## Affected code
https://github.com/spacemeshos/go-spacemesh/blob/9d3a379994e3652eb0378d2cc555588bba91005e/tortoise/verifying_tortoise.go#L1023-L1024

This issue appears in commit hash: 9d3a379994e3652eb0378d2cc555588bba91005e

**Comment by dshulyak** [comment]
Before caching anything lets benchmark and profile first. The code already very complicated in tortoise, caching stuff without a reason will not improve the situation.

**Comment by dshulyak** [comment]
Closing as this is not a bottleneck.
