### ISSUE TITLE
Cache votes for blocks in tortoise

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2676]
## Description
Similar to #2672

## Affected code
https://github.com/spacemeshos/go-spacemesh/blob/9d3a379994e3652eb0378d2cc555588bba91005e/tortoise/verifying_tortoise.go#L1033-L1034

This issue appears in commit hash: 9d3a379

**Comment by dshulyak** [comment]
This is not a bottleneck.
