### ISSUE TITLE
Properly set delta parameter in threshold calculation for block local opinion

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2677]
## Description
When calculating threshold _global_ opinion on blocks in old layers, delta represents the depth of the layer in question, behind the `last` layer for which tortoise has data. What should this value be when using global opinion in place of _local_ opinion for blocks in old, unverified layers? (For now we're using 1.)

## Affected code
https://github.com/spacemeshos/go-spacemesh/blob/9d3a379994e3652eb0378d2cc555588bba91005e/tortoise/verifying_tortoise.go#L1040-L1042

This issue appears in commit hash: 9d3a379994e3652eb0378d2cc555588bba91005e

**Comment by dshulyak** [comment]
What are the options? I feel like this needs more context, or should we just clarify it with research?

**Comment by lrettig** [comment]
Confirmed with @tal-m that delta should always be 1 in this case, i.e., we don't care about how old the layer in question is, we only care about the overall vote margin
