### ISSUE TITLE
Optimize tortoise block opinion data structure and vote counting algorithm

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2679]
## Description
This is done very naively today. It could probably be made much more efficient with better data structures: e.g., using matrix math.

Related issues that this could address: #2369, #2424, #2522, #2672, #2719

Things we need the block opinions data structure to do that it cannot currently:
- efficiently evict opinions on blocks older than a given layer (#2719)
- index into a block's opinions on blocks in a given layer (#2424)
- efficiently perform basic linear algebra/matrix math, e.g., sum all opinions of blocks in a given layer for a given block, or copy all of a block's opinions into another block's opinions vector

## Affected code
tortoise/verifying_tortoise.go

This issue appears in commit hash: 9d3a379994e3652eb0378d2cc555588bba91005e

**Comment by dshulyak** [comment]
@lrettig do i understand it right that 1 and 2 points will be addressed by https://github.com/spacemeshos/go-spacemesh/pull/2734 ?

as for

> efficiently perform basic linear algebra/matrix math, e.g., sum all opinions of blocks in a given layer for a given block, or copy all of a block's opinions into another block's opinions vector

do you have particular ideas on how it can be optimized now? or should we wait for UCB before attempting optimizations?

**Comment by dshulyak** [comment]
It looks like we are already close to a unified content block. The remaining task from this issue to simplify opinions data structure, we can tackle it as a part of https://github.com/spacemeshos/go-spacemesh/issues/2719 .
