### ISSUE TITLE
Does tortoise need to overwrite input vector after healing?

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2680]
## Description
After tortoise successfully heals a layer, it updates contextual validity in the database for the blocks in that layer:

https://github.com/spacemeshos/go-spacemesh/blob/9d3a379994e3652eb0378d2cc555588bba91005e/tortoise/verifying_tortoise.go#L1231-L1234

However, it does _not_ overwrite the existing input vector in meshdb (the output of hare, or received via sync). For old layers, tortoise only looks at contextual validity and not at the input vector:

https://github.com/spacemeshos/go-spacemesh/blob/9d3a379994e3652eb0378d2cc555588bba91005e/tortoise/verifying_tortoise.go#L1079-L1081

And we only heal old layers. So I think this isn't necessary.

**Comment by dshulyak** [comment]
Let's close this issue. I don't see any case when it can be necessary, and in general updating input vector that is produced by hare in tortoise is weird.
