### ISSUE TITLE
Priority queue length > 50

### ISSUE THREAD

**Issue by nkryuchkov** [spacemeshos/go-spacemesh#2681]
## Description

There're `outbound gossip message queue backlog` warnings in the devnet logs. They are caused by a priority queue length of 51, which is greater than 50.

## Expected Behavior

No such warning

**Comment by lrettig** [comment]
Likely addressed by #2450
But would also be good to know the underlying cause

**Comment by nkryuchkov** [comment]
The message disappeared, but the `p2p: outbound message queue is full, dropping peer` appeared:
![image](https://user-images.githubusercontent.com/24493220/135177208-369cbd84-1350-4a41-bb57-2fc5c75f46aa.png)

**Comment by dshulyak** [comment]
This code was replaced
