### ISSUE TITLE
`overwriting sessionID in context` warning

### ISSUE THREAD

**Issue by nkryuchkov** [spacemeshos/go-spacemesh#2684]
## Description

Seen on devnet. It happens in `WithSessionID`, when `curSessionID != sessionID`, but `sessionID` is always a unique value (`uuid.New().String()`, called from `WithNewSessionID`) which cannot be equal to `curSessionID`

**Comment by lrettig** [comment]
The idea behind this warning is to establish a link between the parent and child sessionID for debugging purposes. There's probably a cleaner way to do this. We could definitely change the wording and downgrade this from a warning to info.

**Comment by lrettig** [comment]
Fixed in https://github.com/spacemeshos/go-spacemesh/pull/2400/commits/45d5609cbc633d6799325b512ac1391e83ec70cc and https://github.com/spacemeshos/go-spacemesh/pull/2400/commits/dedfb19d5b140493afa1f5cd21ff332b10ff29aa
