### ISSUE TITLE
devnet: log "could not get contextual validity for block in list"

### ISSUE THREAD

**Issue by countvonzero** [spacemeshos/go-spacemesh#2695]
## Description

aggregated hash is calculated as part of setting processed layer, because it needs to be calculated in layer order.
as part of mesh.setProcessedLayer(layerN), it attempts to calculate the aggregated hash for layerN.

this is premature because when tortoise validates a layer N, it can only determine block validity for layer N-1. this is because to determine validity for a layer N you need votes from layers >N. hence this log.

## Steps To Reproduce
1. `make dockertest-late-nodes namespace=$YOUR_NAMESPACE dump=True`
2. go to kibana and looks for logs
`could not get contextual validity for block in list`

## Expected Behavior
`mesh.setProcessedLayer` should only calculate aggregated hash for layer whose block validity is determined.

**Comment by lrettig** [comment]
> mesh.setProcessedLayer should only calculate aggregated hash for layer whose block validity is determined.

In other words, only for layers that tortoise has already verified

**Comment by dshulyak** [comment]
@countvonzero @lrettig What are the consequences of this bug? Asking to better understand network health when i am seeing this log.

**Comment by countvonzero** [comment]
@dshulyak this bug is caused by calculating aggregated hash too eagerly (before blocks contextual validity is determined by tortoise)
aggregated hash is not yet used for anything yet so it's safe to ignore this log. but feel free to switch it to Debug log for now. i will change it together with fixing this issue.

**Comment by dshulyak** [comment]
@countvonzero i was looking at the logs related to https://github.com/spacemeshos/go-spacemesh/issues/2712

logs http://34.71.50.154:5601/goto/8dac1271d552c802ef2215c9aad86003 (pw in devnets channel)

the block passed tortoise validation, but it is not pushed to the state because contextual validity is not found in the database. as a consequence rewards are not accumulated and not saved.

is it related to the bug that you are working on, or it is a different one?

UPD: actually it is not related to this bug, just the log is the same

**Comment by lrettig** [comment]
That's odd. When the tortoise validates a layer it saves contextual
validity to the database!

**Comment by countvonzero** [comment]
what @lrettig said. at least in the develop branch, contextual validity is guaranteed after tortoise validate a layer.

but one thing worth noting is: @dshulyak at least in the develop branch.
after tortoise output `oldPbase` and `newPbase`, it only apply states up to `newPbase-1` layer. i don't understand why this is the case.

**Comment by lrettig** [comment]
This was recently fixed in the healing branch: https://github.com/spacemeshos/go-spacemesh/commit/1fa05a3af17c3778f0d53fc3f2f97cff032bda9e
