### ISSUE TITLE
Nil pointer dereference crash in StartSmeshing

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#2701]
## Description

One of the miners in my devnet failed with this stack trace:

```
{"L":"INFO","T":"2021-08-20T15:28:53.826-0400","N":"49d4f.post         ","M":"proving: generated proof after 1 iteration(s)","node_id":"49d4f8d36123bfffc23a6c3f8d74e3a6d97c20b918ab474ad8728eb3de49e5e6","module":"post"}
{"L":"INFO","T":"2021-08-20T15:28:53.826-0400","N":"49d4f.nipostBuilder","M":"finished Post execution","node_id":"49d4f8d36123bfffc23a6c3f8d74e3a6d97c20b918ab474ad8728eb3de49e5e6","module":"nipostBuilder","duration":"8.550212ms","name":"nipostBuilder"}
{"L":"INFO","T":"2021-08-20T15:28:53.826-0400","N":"49d4f.atxBuilder   ","M":"atx builder is stopped","node_id":"49d4f8d36123bfffc23a6c3f8d74e3a6d97c20b918ab474ad8728eb3de49e5e6","module":"atxBuilder"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa0c pc=0x473325]


github.com/nullstyle/go-xdr/xdr3.Marshal(...)
	/go/pkg/mod/github.com/nullstyle/go-xdr@v0.0.0-20180726165426-f4c839f75077/xdr3/encode.go:77
github.com/spacemeshos/go-spacemesh/codec.EncodeTo(0x124bb20, 0xc0060222a0, 0xef7600, 0xc0003def48, 0xc004fd51c0, 0x10efc3d, 0x4)
	/go/src/github.com/spacemeshos/go-spacemesh/codec/codec.go:19 +0x65
github.com/spacemeshos/go-spacemesh/codec.Encode(0xef7600, 0xc0003def48, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/spacemeshos/go-spacemesh/codec/codec.go:52 +0xbf
github.com/spacemeshos/go-spacemesh/activation.(*NIPostBuilder).persist(0xc0003def00)
	/go/src/github.com/spacemeshos/go-spacemesh/activation/nipost.go:66 +0x4b
github.com/spacemeshos/go-spacemesh/activation.(*NIPostBuilder).BuildNIPost(0xc0003def00, 0x12679e0, 0xc000226e80, 0xc0092b61e0, 0xc00680d500, 0x0, 0x0, 0x0)
	/go/src/github.com/spacemeshos/go-spacemesh/activation/nipost.go:205 +0x716
github.com/spacemeshos/go-spacemesh/activation.(*Builder).createAtx(0xc000240480, 0x12679e0, 0xc000226e80, 0x11087cf, 0x1a, 0xc0051c3b78)
	/go/src/github.com/spacemeshos/go-spacemesh/activation/activation.go:534 +0x283
github.com/spacemeshos/go-spacemesh/activation.(*Builder).PublishActivationTx(0xc000240480, 0x12679e0, 0xc000226e80, 0x0, 0x0)
	/go/src/github.com/spacemeshos/go-spacemesh/activation/activation.go:478 +0x10f9
github.com/spacemeshos/go-spacemesh/activation.(*Builder).run(0xc000240480, 0x12679e0, 0xc000226e80)
	/go/src/github.com/spacemeshos/go-spacemesh/activation/activation.go:331 +0x145
github.com/spacemeshos/go-spacemesh/activation.(*Builder).loop(0xc000240480, 0x12679e0, 0xc000226e80)
	/go/src/github.com/spacemeshos/go-spacemesh/activation/activation.go:312 +0x233
created by github.com/spacemeshos/go-spacemesh/activation.(*Builder).StartSmeshing.func1
	/go/src/github.com/spacemeshos/go-spacemesh/activation/activation.go:246 +0x15f
```

It is built using this branch https://github.com/dshulyak/go-spacemesh/tree/devnet-dbg-memory, but there are no changes related to smeshing.

## Expected Behavior
Don't crash.

## Environment
devnet on gce

**Comment by nkryuchkov** [comment]
I tried to figure out why the panic happened, but I'm still not sure. I'm postponing this until I have more ideas. Here are my thoughts for now:

The topmost entry in the stacktrace refers to https://github.com/nullstyle/go-xdr/blob/master/xdr3/encode.go#L75-78:
```go
func Marshal(w io.Writer, v interface{}) (int, error) {
	enc := Encoder{w: w}
	return enc.Encode(v)
}
```

It looks like something inside the `return enc.Encode(v)` panicked. I wrote a few tests for `nil` arguments passed to `xdr3.Marshal`, it panicked only when `w` was `nil`. The only type that may be passed to `codec.EncodeTo` is `*bytes.Buffer` (https://github.com/dshulyak/go-spacemesh/blob/devnet-dbg-memory/codec/codec.go#L52). 

Here's the dump of arguments passed to `codec.EncodeTo` (and `xdr3.Encode` as well):
`github.com/spacemeshos/go-spacemesh/codec.EncodeTo(0x124bb20, 0xc0060222a0, 0xef7600, 0xc0003def48, 0xc004fd51c0, 0x10efc3d, 0x4)`

The first argument is `io.Writer` interface. The interface in Go is a `struct` with two pointers: the first one points to the interface type table entry, the second one points to the data (https://github.com/golang/go/blob/master/src/runtime/runtime2.go#L202-205):

```go
type iface struct {
	tab  *itab
	data unsafe.Pointer
}
```

So, the pointer to the type table entry was `0x124bb20` and the data pointer was `0xc0060222a0`. So both `w` and the underlying `*bytes.Buffer` were not `nil`.

Regarding `v`, table entry and data pointers were `0xef7600`/`0xc0003def48`, but this argument should not be the reason for panic.

For the remaining numbers, `0xc004fd51c0` is returned `int`, `0x10efc3d`/`0x4` are a returned `error`. Both look like uninitialized stack data.
