### ISSUE TITLE
devnet: improve debugging by fetching layer by layer ID (instead of hash) 

### ISSUE THREAD

**Issue by countvonzero** [spacemeshos/go-spacemesh#2704]
## Description
while debugging devnet failure, it gets pretty gnarly when using layer hash (of block IDs) to look up layer data.

using layer hash to look up layer contents serves 2 purposes:
- the layer id -> layer hash mapping allows verification of the blocks received for this layer
- the layer hash (combined with aggregated layer hash) itself allows efficient syncing between two layers with different mesh hash

currently when syncer queries about a layer content, it 
A. queries a peer about the layer hash (1 RTT)
B. queries the same peer about the contents corresponding to the hash (1RTT)

and when the peer received the request B, it does the following:
1. receive req msg as layer hash
2. look up layer hash -> layer ID
3. look up layer ID -> block IDs
4. return to peer block IDs

the proposal is to remove request A and step 1 and 2 from the responding peer. i.e. use layer ID to query a layer content directly. the pros:
- save 1 RTT
- remove leveldb entries for layerHash->layerID mapping
- ease of debugging

## Expected Behavior
the node fetches layer content correctly and still am able to verify peer's integrity w.r.t layer hash -> layer contents

**Comment by dshulyak** [comment]
This is great! I wasn't able to figure why we need to hash integer for this purpose. @countvonzero  Do you think that we can use id for GetLayerInputVector as well?

**Comment by countvonzero** [comment]
> This is great! I wasn't able to figure why we need to hash integer for this purpose. @countvonzero Do you think that we can use id for GetLayerInputVector as well?

@dshulyak yes. i am doing exactly that. 

btw, the hash is hash of ordered block IDs in the layer, not just an integer hash.

**Comment by dshulyak** [comment]
@countvonzero something is off then. i was recently refactoring that part and noticed that just id is hashed https://github.com/spacemeshos/go-spacemesh/commit/f04945575912465c073b88e20f15cb387d465e71#diff-4631ba6bc4f174ec995a1aa9299207e42c8f1db16abbea65bdd84777b2024414L352

**Comment by countvonzero** [comment]
@dshulyak you are correct. there are both. layerID.byte() is hashed for input vector, layer.BlockIDs() is hashed for layer content
