### ISSUE TITLE
Implement database tooling for introspection

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#2710]
While debugging issues in the network i found myself downloading db state and inspecting it a lot. It will be helpful if we had a reusable tool that can print details and summary in human readable form.

Some examples:

- mesh state (blocks, input vectors, contextual validity, rewards state)
- tortoise beacon
- tortoise opinions (layers, size of opinions list, good blocks)
- activation (atxs, timestamp)

To take it even further we can use db storage with efficient snapshots (such as badger or rocksdb) and save db state in tests for later introspection, or even automatic comparison.

**Comment by sudachen** [comment]
The big problem of most existing key-value databases (leveldb we use for example) they does not support full multiple process access. rocksdb supports limited readonly access, but not sure it will be enough. 

So it's possible we need implement introspection as an REST service into client with CLI tool to make that queries in scripts and console. This CLI tool ca be used also for database analyzes for dead client.

Regarding retrospection functionality, there are no serious problems as I see, we just need to implement it.
