### ISSUE TITLE
Smesher rewards address not getting updated

### ISSUE THREAD

**Issue by avive** [spacemeshos/go-spacemesh#2711]
## Repro
1. Set a rewards address 1 via the smesher api.
2. Setup post via the api and provide rewards address 2.
3. Query the node for its current reward address.

Result: address 1 is returned.
Expected: address 2 to be set as smesher rewards address (coinbase) and to be returned by the smesher api.

Reproduced on branch [healing-state-refactor](https://github.com/spacemeshos/go-spacemesh/tree/healing-state-refactor)

**Comment by dshulyak** [comment]
@avive can you clarify which API methods are used to update and query node for rewards address?

nvm: i will use smrepl

**Comment by dshulyak** [comment]
@avive just to clarify in

> Setup post via the api and provide rewards address 2.

are you talking about this request https://github.com/spacemeshos/smrepl/blob/master/repl/smesher_commands.go#L219?

**Comment by avive** [comment]
You highlight the command that sets the rewards as part of the post setup process. The command which is used to read it just uses the SmesherService api to get the current node's rewards address. I also tried getting rewards for the rewards address via the api but it returns 0 rewards.
