### ISSUE TITLE
No smeshing rewards

### ISSUE THREAD

**Issue by avive** [spacemeshos/go-spacemesh#2712]
## Steps To Reproduce
1. Sync a full node
2. Setup post via api
3. Wait ~5 epochs 
4. Check rewards via api - using smesher id or via the rewards address

## Behavior
Post status and smesher status are as expected but no rewards returned by the api 

```
$ post status
👍  Proof of spacetime data was created and is used for smeshing.
Proof of spacetime configuration:
  Data dir (relative to node or absolute): .
  Date files: 1
  Compute provider id: 1
  Throttle when computer is busy: false
  Bits per label: 8
  Units: 2
  Labels: 2048
  Size (GiB): 1.9073486e-06
  Size (Bytes): 2048
$ smesher status
Node is currently smeshing
$ smesher rewards
Smesher id: 0x02b34140cd1d6822afc4015deb69818365590b9815a68528889e8c0229ee319a
Total rewards: 0
$ smesher status
Node is currently smeshing
```

## Expected Behavior
Get smeshing rewards for smesher

## Environment
- macOS/amd64
- node branch healing-state-refactor

**Comment by dshulyak** [comment]
I investigated this today. Created a new miner, synced, started smeshing. And I was able to get rewards. Let me share some timings:
1.  First published ATX has a target 1272 
2.  First layer where i was eligible to produce block was at 1279.
At the moment i produced 3 blocks (1279, 1280, 1283) and received rewards for all of them.

```
$ status node
Node info:
Version: v0.0.0-unreleased
Build: d4df7947c6d6f982ce6ef9689c1659f0febf12a2
API server: localhost:9092 (GRPC API 1.1). >> Insecure Connection. Use only with a local trusted server <<
Synced: true
Synced layer: 1286
Current layer: 1286
Verified layer: 1283
Peers: 8
$ smesher rewards
Smesher id: 0xb587e9e03ab614a9fa839f51b92b1eb962d08675b030fe7745ebee416956c6a4
Total rewards: 3
Rewarded on layer: 1279
Layer reward 1666666666666 Smidge
Transaction fees 0 Smidge
Total reward 1666666666666 Smidge
Rewards account: 0xb5c655160054285D6fb6bd4eaB00bBb48383c19B
-----
Rewarded on layer: 1280
Layer reward 1724137931034 Smidge
Transaction fees 0 Smidge
Total reward 1724137931034 Smidge
Rewards account: 0xb5c655160054285D6fb6bd4eaB00bBb48383c19B
-----
Rewarded on layer: 1283
Layer reward 2000000000000 Smidge
Transaction fees 0 Smidge
Total reward 2000000000000 Smidge
Rewards account: 0xb5c655160054285D6fb6bd4eaB00bBb48383c19B
```

@avive i will explore later why it took 7 layers to become eligible to mine a block, do you know if eligibility is probabilistic? can you check if you was able to get rewards later?

Also there is a potential issue that tortoise didn't mark block as contextually valid, will need to explore it as well.

**Comment by avive** [comment]
It is my understanding that is should take up to 2 epochs to start smeshing from post init setup time, and that each smesher should get at least 1 reward in each epoch. Perhaps this is a bit different with the current devnet params. @noamnelke - can you please verify? I will try again today to sync and smesh on the devnet.

**Comment by avive** [comment]
From @dshulyak investigations it looks like this is a grpc api related issue because smeshing works as expected for joining nodes when smeshing is set-up via the node's config file on node startup.
