### ISSUE TITLE
Tortoise vote encoding data structure

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2719]
Right now tortoise stores/encodes votes in a matrix of size `windowSize**2 * blocksPerLayer**2`: each block includes votes from blocks going back `windowSize` layers, each of which includes votes going back `windowSize` layers.

It seems that this data structure is too big. See @dshulyak comment here: https://github.com/spacemeshos/go-spacemesh/pull/2683#issuecomment-904322215.

Per @tal-m,

> The data structure I had in mind is a 2D matrix, where each row represents a voting block and each column a content block. Each element of the matrix is the opinion of a voting block about the corresponding content block. The window size comes into play because we don't need to store the detailed opinions about content blocks that are more than `windowSize` layers in the past (for those, we only store our own opinion, which should be identical to the opinion of all the voting blocks we see)

> Regarding optimizations:
> I think the unified content block will be a huge improvement to complexity --- since there is almost always 1 block per layer, the matrix needs to be windowSize*votesPerLayer (votesPerLayer=blocksPerLayer in the previous scheme). So that's a blocksPerLayer factor improvement; if we're currently using 50 blocks per layer, it means that even without any additional optimization, the vote storage should be less than 140MB
> I'm sure there's a lot of optimization we can do in the data structure itself. Are we storing it in bit-packed fields? Are we making use of the fact that most honest votes actually have the same opinion? Etc.

See [this slack thread](https://spacemesh.slack.com/archives/CG91F13C7/p1629850014078200)

**Comment by lrettig** [comment]
Right now, block opinions (`BlockOpinionsByLayer`) are stored as a map of maps of maps: the outermost map key is layerID (of voting block), the second map key is blockID (of voting block), and the innermost map key is blockID (of being being voted upon). This is a very inefficient data structure for pruning by layerID of the inner blocks. #2424 is currently not possible for the same reason.

Let's find a better data structure in #2679 as a next step towards addressing this, and the other related issues.

**Comment by lrettig** [comment]
Tal is right that, once we move to a single, unified content block per layer and a division between content and voting blocks, the opinions data structure can become a 2d matrix where rows represent voting blocks and columns represent content blocks. However, until then, the data structure is in fact more complex because we also need multiple indices by layer: a. we need to know a "voting" block's opinions on all of the blocks in a given layer, b. we need to know all of the opinions of all of the blocks in a given layer about a given block, and c. we need to be able to evict not only all of the opinions of all of the blocks in a given layer, but also all of the opinions about all of the blocks in a given layer.

I suggest we go with the quick fix in #2734 for now, and revisit this later when we have a finalized design for content/voting blocks.

**Comment by dshulyak** [comment]
I think at this point we can wait for UBC to get fully implemented, and then decide what we want to do with that data structure. I expect that UBC will allow us to simplify it while keeping reasonable performance for required operations.

**Comment by dshulyak** [comment]
Tortoise is completely rewritten, the discussion here is not relevant anymore.
