### ISSUE TITLE
Zero cost debug logs

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2732]
@lrettig i removed some debug logs from a loop https://github.com/spacemeshos/go-spacemesh/pull/2683/commits/4a63c34b9d0b917f3b35384b053d499585eda3a0 . even on my machine it takes nearly 100s to print those logs in some tests. if they are needed we must find a more efficient way to log this information

_Originally posted by @dshulyak in https://github.com/spacemeshos/go-spacemesh/issues/2683#issuecomment-907584399_

**Comment by lrettig** [comment]
We've seen on several occasions that printing tons of debug lines can slow things down, impact performance, and even cause system tests to fail. This is a problem and we should explore ways to improve the situation. Simply adding debug statements, which are not triggered in production code or during ordinary testing, should not slow things down.

**Comment by moshababo** [comment]
@lrettig @dshulyak still relevant?

**Comment by lrettig** [comment]
I think so. Gave it a more accurate title. This is a nice to have, low priority. Would require some low level digging into our logging infrastructure.
