### ISSUE TITLE
Add nodes system test failure - too many blocks created

### ISSUE THREAD

**Issue by antonlerner** [spacemeshos/go-spacemesh#2735]
## Description
When running add nodes test, sometimes it fails with following error message: 
 `blocks created per layer 1.0, wanted average block per node 0.6666666666666666, layer_avg_size 50, layers_per_epoch 3, num_miners 51, blocks_sum 3, to_layer 18, from_layer 15`

deployment example `acu99` 

## Steps to reproduce
run add_nodes system test

## Environment
Please complete the following information:
 - OS: 
 
 - Node Version: 
 
 - Smapp version (if applicable):

**Comment by dshulyak** [comment]
In my case, the error is the opposite. One node consistently fails to publish atx. And doesn't produce blocks in the target epoch.
The funny fact is that nobody receives the atx from this node, including the node itself.

The mining test fails exactly the same way.

**Comment by dshulyak** [comment]
It looks like the very common root cause of this problem is:
```
received syntactically invalid atx 660b6ce0a7: invalid nipost: invalid Post: fast oracle output is above the threshold; index: 33, label: 0a, hash: 76eeb6deb148fffba99e5eaff3019dc5dc3b4446eca5811bd4cc1296d3602866, hashNum: 18158312151364071030, difficulty: 18014398509481983999
```

I recently updated post library, but i don't see how my change could lead to this issue. Still researching.

**Comment by dshulyak** [comment]
There are actually two root causes as far as i can tell:
- bug in proving that became more frequent because of my recent post update
- node doesn't publish atx in time because it is blocked on synced in atx builder, and sync is blocked because discovery haven't found enough peers

The first one already closed, still need to do something about the last one

**Comment by dshulyak** [comment]
example of the second failure: https://github.com/spacemeshos/go-spacemesh/runs/3470646436
