### ISSUE TITLE
p2p system test failure in `test_many_gossip_sim`

### ISSUE THREAD

**Issue by antonlerner** [spacemeshos/go-spacemesh#2736]
## Description
when running p2p system tests, this error occasionally fails `test_many_gossip_sim`
```
>       assert total_expected_gossip == len(results), err_msg
E       AssertionError: msg_testing: Total gossip messages in ES is not as expected
E         expected 2580, got 2548
E       assert 2580 == 2548
E         -2580
E         +2548
```

## Steps to reproduce
run p2p system tests

## Environment
Please complete the following information:
 - OS: 
 
 - Node Version: 
 
 - Smapp version (if applicable):

**Comment by dshulyak** [comment]
This is clearly some sort of a bug. Messages are definitely not received by one peer consistently. See for example logs from:
- good peer with 96 messages https://kibana-tests.spacemesh.io/goto/8a4f428dea3f69119288b4eb3bb4c8a1
- and then bad peer with 81 message https://kibana-tests.spacemesh.io/goto/8a5f2ad7cc9a2222c9eb66830f01d49c
