### ISSUE TITLE
Failing tests on tortoise beacon sync branch

### ISSUE THREAD

**Issue by nkryuchkov** [spacemeshos/go-spacemesh#2741]
## Description

Currently, some tests fail on the `feature/tortoise-beacon-sync` branch. Unit tests and app tests time out. The late nodes system test fails (namespace for debugging: `17v68`). Maybe other system tests fail as well, I haven't checked them. If they do, it's likely due to the same issue.

Tests were passing on commit `71a66c7`. The issue(s) is likely in the recent commits that implemented storing tortoise beacon only in the first block per epoch and miner.

**Comment by countvonzero** [comment]
obsolete by https://github.com/spacemeshos/go-spacemesh/pull/2850
