### ISSUE TITLE
flaky test: app test TestShutdown unexpected number of goroutines

### ISSUE THREAD

**Issue by countvonzero** [spacemeshos/go-spacemesh#2743]
## Description

https://github.com/spacemeshos/go-spacemesh/runs/3443623393
```
app_test.go:775: 
        	Error Trace:	app_test.go:775
        	Error:      	Not equal: 
        	            	expected: 4
        	            	actual  : 5
        	Test:       	TestShutdown
```

**Comment by countvonzero** [comment]
this turned out to be quite difficult to reproduce

$ go test -timeout 0 -v ./cmd/node -run TestShutdown -count 100

3 times now and still could not reproduce it

**Comment by nkryuchkov** [comment]
https://github.com/spacemeshos/go-spacemesh/runs/3815964636

**Comment by nkryuchkov** [comment]
https://github.com/spacemeshos/go-spacemesh/runs/4275261405

**Comment by moshababo** [comment]
Obsolete.
