### ISSUE TITLE
Node has not created expected number of blocks

### ISSUE THREAD

**Issue by antonlerner** [spacemeshos/go-spacemesh#2745]
## Description
mining test fails with following error:
```
E               AssertionError: summary.node_num_blocks[d531e3f13f4d1c160fd840507ddc99bb9c2e21ab9cf39102b93d077d2f442994]: 0
E               expected_blocks: 3
E               epoch_id: 2
```
https://github.com/spacemeshos/go-spacemesh/runs/3457606848
## Steps to reproduce
run mining test

## Environment
Please complete the following information:
 - OS: 
 
 - Node Version: 
 
 - Smapp version (if applicable):

**Comment by dshulyak** [comment]
Related https://github.com/spacemeshos/go-spacemesh/issues/2735#issuecomment-908985411

**Comment by dshulyak** [comment]
> received syntactically invalid atx e1fbed7b25: invalid initial Post: fast oracle output is above the threshold; index: 167, label: 3a, hash: 7d9c704d48a97cfacee02b6f17f8e76fdf4ea2285863c5eb03b389fa859993e8, hashNum: 18049487534596070525, difficulty: 18014398509481983999

this was resolved yesterday. closing
