### ISSUE TITLE
CI Release GPU-POST Bins

### ISSUE THREAD

**Issue by web3rover** [spacemeshos/go-spacemesh#2752]

**Comment by dshulyak** [comment]
@narayanprusty is it going to be a part of this repository? if not can we create such issues in https://github.com/spacemeshos/gpu-post/ or https://github.com/spacemeshos/pm/

**Comment by web3rover** [comment]
It's going to part of this repository. We will create GHA pipeline for this.

**Comment by avive** [comment]
As a future reference, we need to look into signing of distributed zip files for all platforms. We have an EV signing cert from SSL.com and a code signing cert for notarizing apps from Apple. I'm not 100% sure if windows and linux treat signed downloaded zip files differently but in terms of security but if they do then we should add this to the CI pipeline. Similar to how we sign Smapp installers already.
