### ISSUE TITLE
Mock NTP on testground 

### ISSUE THREAD

**Issue by y0sher** [spacemeshos/go-spacemesh#2777]
## Description
Currently tests are failing because the node is trying to reach NTP on the external internet. testground is a closed network within a docker/k8s cluster.

we need to be able to mock them to control the time the node knows. but most importantly right now testground doesn't allow external communication and it blocks us from running.

**Comment by dshulyak** [comment]
Maybe we can just disable ntp check on testground for now? I think the plan was to eventually turn it off anyway. We already have a process that will report if time is not in sync with peers.

**Comment by y0sher** [comment]
Well, I opened the test to outgoing networking now so it'll just work with NTP. we could probably reverse this when we drop the NTP dependency. easiest solution for now..
