### ISSUE TITLE
tortoise: good block candidate contains exception for block older than its base block

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#2782]
## Description

Periodically invalid blocks will be created and reported later by tortoise:

```
{"L":"ERROR","T":"2021-09-14T07:06:24.537+0300","N":"d402d.trtl         .turtle","M":"good block candidate contains exception for block older than its base block","node_id":"d402d6a59d870552a7d9c7ca6af2d1fada8e189fea82a712aa5495b6019388c0","module":"trtl","tortoise_rerun":"false","sessionId":"cfda9be0-8afa-4c17-86c4-ba2e333f8c0b","older_block":"02e6cb34f9","older_layer":201,"base_block_layer":202,"name":""}
``` 

@lrettig explained previously that this is implemented according to the specification, but it still seems off to me.

1. why would an honest node create a block if it knows that it will be reported as invalid by tortoise?
2. this definitely should not be happening in the network that has very little asynchrony and runs in cloud environment

**Comment by lrettig** [comment]
Re 1: this does not mean that a block is invalid or that its vote isn't
counted, just that tortoise isn't marking it "good." Not being good means
it won't be used as a base block in future.

**Comment by dshulyak** [comment]
should we lower the log level in this case then? 
it is still confusing why another honest node would create such block

**Comment by lrettig** [comment]
In and of itself, in a production network, this is expected and not an
error, but the log level is set to error because in the testing we're doing
right now it probably does indicate a real error. I agree with you, we
don't expect nodes to create blocks that aren't marked good if the network
is healthy. I'd rather find and address the cause of that rather than
change the log level for now.

**Comment by dshulyak** [comment]
Failure in the mining test https://kibana-tests.spacemesh.io/goto/834a8a45f46214e1994363a0ecd7479e

**Comment by dshulyak** [comment]
I have one idea about this issue, noting here to double check next time when this bug appears.
node is marked synced as soon as we download blocks, but not validate them by the tortoise. 
- we add a layer from hare, for example, 110
- we add a layer from sync, 109
- then we choose a base block from 110, but since blocks for 109 were missing when block for 110 was processed they won't be in votes and we will add them as exceptions.
- every other node marks this blog as not good due to such exceptions
