### ISSUE TITLE
hare: does not tag layer as empty when it outputs an empty set

### ISSUE THREAD

**Issue by countvonzero** [spacemeshos/go-spacemesh#2795]
## Description
hare declared output for a given layer, send it over for verifying tortoise to validate, and verifying tortoise failed to look up layer blocks.

this is because hare output an empty set for that layer but didn't tag it as zero-block layer.

![Screenshot from 2021-09-16 16-25-19](https://user-images.githubusercontent.com/30611210/133681046-0dacede8-1979-40d9-989c-163c9205cb7d.png)

## Actual Behavior
verifying tortoise failed to look up content of the given layer when hare output an empty set for that layer

## Expected Behavior
verifying tortoise should know this is a zero-block layer and behave accordingly instead of errorring out.

**Comment by dshulyak** [comment]
This will have a side effect that syncer will not even try to sync the missed layer because processed was advanced by hare, even when node is completely isolated.

**Comment by countvonzero** [comment]
> This will have a side effect that syncer will not even try to sync the missed layer because processed was advanced by hare, even when node is completely isolated.

i think this issue is orthogonal to hare not tagging empty layer.

even when a node is NOT isolated, it can still miss blocks for a given layer due to gossip not propagating to all nodes.
the root of the issue for the problem you pointed out is, like you also stated in the slack channel, that syncer should not sync data based on processed layer but on aggregated layer hash.

this bug may have been caused by https://github.com/spacemeshos/go-spacemesh/issues/2876 tho.
when hare truly terminates with empty set, it invalidates the layer, and that's it. no one will be notifying the mesh that we can try to process the layer. https://github.com/spacemeshos/go-spacemesh/issues/2875

**Comment by dshulyak** [comment]
do we still need this distinction between empty and zero layer in tortoise?

**Comment by countvonzero** [comment]
the original wording was not quite correct.
it really isn't hare's job to tag this layer as an empty layer. (a layer without any blocks).

either one of the conditions below can cause hare output empty set
- there are blocks in the layer, but somehow the hare committee voted down all of them
- hare terminated with failure
- there are no blocks in a layer

so i think this is still an issue that tortoise failed to look up content of the layer when asked to validate a layer
this means either 
- A. tortoise ignore ErrNotFound from mesh when there is empty input vector
- B. some component tag the layer as empty layer in the mesh when there really is no blocks in this layer
i think B is more correct, so that tortoise doesn't have to care about empty layer.

**Comment by countvonzero** [comment]
this is not relevant anymore after unified content block is implemented. closing. @jonZlotnik
