### ISSUE TITLE
Use go:embed to load version.txt

### ISSUE THREAD

**Issue by daonb** [spacemeshos/go-spacemesh#2816]
## Description

Today, a piece of makefile code reads version.txt and uses LDFLAGS to pass it
to the go compiler. In version 1.16 a new go syntax `//go:embed`  let's us load
the file using a single comment.

## Affected code

Just the Makefile, making it simpler.

**Comment by noamnelke** [comment]
Just pointing out that not "just the Makefile" is affected... `//go:embed version.txt` will have to be added to `main.go`, above `version string`.

It's also worth mentioning that, while this is a positive change, it won't help us entirely get rid of the clunky mechanics of using `LDFLAGS` to pass arguments into `main.go` - we'll still need it for the commit hash and branch.

**Comment by daonb** [comment]
Probably be a good time to add a comment above `commit` and `branch` saying it's the Makefile that fills their value.
