### ISSUE TITLE
CI flakes due to the NTP failures

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#2820]
we have some flakes on ci related to ntp unavailability. tests that are expected to publish atxs and produce blocks on time can't do so because ntp responds only after multiple retries or fails to do so completely (in a latter case there will be a crash reported by the harness). 

failures: 
- https://github.com/spacemeshos/go-spacemesh/runs/3683807350
- https://github.com/spacemeshos/go-spacemesh/runs/3683324532
- https://github.com/spacemeshos/go-spacemesh/runs/3682415112

PRs: https://github.com/spacemeshos/go-spacemesh/pull/2815 https://github.com/spacemeshos/go-spacemesh/pull/2807

I suggest to move ntp checks to the background for now and keep error log, but don't exit the node in case of failure.

**Comment by countvonzero** [comment]
thanks for the investigation @dshulyak

**Comment by moshababo** [comment]
@dshulyak still relevant?
