### ISSUE TITLE
Add config.json to the release ZIP file

### ISSUE THREAD

**Issue by daonb** [spacemeshos/go-spacemesh#2821]
## Description

Tooday the user needs to download the zipped binaries from one URL and the `config.json` from another URL. This can be confusing as it's expected to have all the files in one tar ball (or zip file).

## Affected code

depends on how we do it

**Comment by daonb** [comment]
I found two ways to do this and I'm not sure which is best:

1. automate spacecraft and run it before building the binary and creating the zip. spacecraft uses the docker images so we can run it just after the "push to dockerhub" workflow runs.
2. move the read-only network variables from config.json to a new `net.json` and host it in a URL based on the version name. For example, for "v0.2.2-beta.1" we can have something like https://storage.googleapis.com/spacecraft-data/v0.2.2-beta.1/net.json that include all the required network data.

**Comment by noamnelke** [comment]
IMO, there's no room for config files mentioning specific resources (a specific testnet with bootnodes and poet IPs) in the `go-spacemesh` repository.

A `go-spacemesh` release should be a pristine pure software release. We can then repackage the release somewhere else, so e.g. we could have a testnet page where we host a repackaged zip that includes a compatible `go-spacemesh` release as well as a config file. We can host a similar SMApp release on the same page.

To reduce confusion, we should explain this on the Github `go-spacemesh` release page and possibly link to the testnet page and direct users to download the release from there if they want to join the testnet.

**Comment by moshababo** [comment]
We ended up using https://github.com/spacemeshos/sm-net as the release platform for network-specific packaging of `go-spacemesh` build + `config.json`, along with some other relevant tooling.
