### ISSUE TITLE
Implement SVM API methods

### ISSUE THREAD

**Issue by noamnelke** [spacemeshos/go-spacemesh#2828]
- [x] Create `api.go` in root of `svm`
- [x] Implement SVM package methods (listed below)
- [x] Replace existing calls into `state` package with the new methods
- [x] Ensure `state` package is not imported anywhere outside the `svm` package
- [x] https://github.com/spacemeshos/go-spacemesh/issues/2888
- [x] System tests must pass (to ensure the change didn't break any functionality), but any unit test that needs to temporarily import `state` or be skipped should be fixed in a separate PR

<table><td>ℹ️ <b>Keep PRs small (~1 day of work)!</b> Each method can have it's own PR, if needed.</td></table>

## Methods
- [x] Constructor (`func New(...) *SVM`) should be implemented incrementally as other methods are implemented.
- [x] https://github.com/spacemeshos/go-spacemesh/issues/2830
- [x] https://github.com/spacemeshos/go-spacemesh/issues/2831
- [x] https://github.com/spacemeshos/go-spacemesh/issues/2832
- [x] https://github.com/spacemeshos/go-spacemesh/issues/2833
- [x] https://github.com/spacemeshos/go-spacemesh/issues/2834

**Comment by neysofu** [comment]
Completed.
