### ISSUE TITLE
Implement `ApplyLayer` in SVM package

### ISSUE THREAD

**Issue by noamnelke** [spacemeshos/go-spacemesh#2831]
```go
func (s *SVM) ApplyLayer(layerID types.LayerID, transactions []types.Transaction, rewards []types.Reward)
```
Method called when a layer is applied, after Hare/Tortoise validation. This functionality is currently spread across different places and I'm not sure it's atomic (it should be).

#### Note Regarding `types.Reward`
This may not be a suitable type for this method's parameter, as it holds much more information than is needed (likely only an address and amount are required). I've used it because it was there, but we should definitely consider creating a special type for this.

### Called From
- `mesh/mesh.go` -> `Mesh.applyState`

### Existing Functions
- `TransactionProcessor.ApplyRewards`
- `TransactionProcessor.ApplyTransactions`
- `TransactionProcessor.DB.Commit`
- `TransactionProcessor.GetStateRoot`

### SVM Functions
- `IncreaseBalance`
- `Deploy`
- `Spawn`
- `Call`
- `Commit`

**Comment by neysofu** [comment]
Circular dependencies between `go-spacemesh/svm` and `go-spacemesh/mesh` (indirectly through `go-spacemesh/svm/state`) are throwing me off. Any tips?
