### ISSUE TITLE
Improve memory consumption of `tortoise.(*turtle).processBlock`

### ISSUE THREAD

**Issue by nkryuchkov** [spacemeshos/go-spacemesh#2838]
## Description

In devnets 204 and 205 `tortoise.(*turtle).processBlock` consumes a lot of memory (`inuse_space`). Nodes don't crash though. 

Flamegraph:
![flamegraph_visual_29_08_2021](https://user-images.githubusercontent.com/24493220/135167492-2cbda2af-a59f-431b-ae90-b77e226fb109.png)

## Affected code
`tortoise.(*turtle).processBlock`

This issue appears in commit hash: 
`6181576`

Related files (optionally with line numbers): 
https://github.com/spacemeshos/go-spacemesh/blob/develop/tortoise/verifying_tortoise.go#L554

**Comment by dshulyak** [comment]
It is not easy to improve though, this is an issue with core data structure being bloated. It will be addressed as a part of UCB. And partially in this PR https://github.com/spacemeshos/go-spacemesh/pull/2734
