### ISSUE TITLE
timesync: `/peersync/1.0/` handler is missing for request

### ISSUE THREAD

**Issue by nkryuchkov** [spacemeshos/go-spacemesh#2841]
## Description

Sometimes these errors happen on devnet 205 (it happened on previous devnets as well):
`can't find handler`
`handler missing for request`

Handlers are:
- `/peersync/1.0/`
- `/sync/2.0/`

![image](https://user-images.githubusercontent.com/24493220/135174536-abc147b8-a91d-46bc-b9c1-a35fd6b3493f.png)

**Comment by dshulyak** [comment]
By the way the log is somewhat confusing, but it means that the handler was evicted by timeout in the server before actual response was received. Definitely a bug somewhere.

**Comment by dshulyak** [comment]
This seems to be a serious issue. Requests should not timeout on a new devnet that much. This will get replaced with libp2p soon, so no need to investigate for now.

**Comment by nkryuchkov** [comment]
Depends on https://github.com/spacemeshos/go-spacemesh/pull/2801 according to https://github.com/spacemeshos/go-spacemesh/issues/2841#issuecomment-935416814

**Comment by nkryuchkov** [comment]
#2801 was merged, closing
