### ISSUE TITLE
sync: blocks are not synced when tortoise verifies the layer

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#2847]
## Description

When layer is verfied after the sync tortoise doesn't always receive all blocks that were produced in that layer. For example compare the amount of blocks that were received by the miner-5 that was participating from the genesis and miner-90 that was started after a day - http://34.70.9.43:5601/goto/b9d7302d425f9924600f861996433b4c. The miner got stuck at layer 322, because received 324 and 325 didn't have enough weight for 323 to pass the threshold.

Somehow we managed to sync those blocks later, i downloaded state from miner-90 and all necessary blocks exist in the database. So if i manually trigger re-run starting from 324 layer it works as expected. Note that by manually i mean downloading state and executing HandleIncomingLayer for each new layer.

This problem can't be fixed by self-healing since we do not re-index the internal tortoise data structure. This issue would be fixed by re-run https://github.com/spacemeshos/go-spacemesh/issues/2846 but i don't know if it works as expected.

**Comment by dshulyak** [comment]
According to the timing and logs this error occurred exactly when connections were flaky. Based on the error handling in layers poller we need at least one successful response, probably we got a response from some not-fully synced peer and synced only known blocks.

We shouldn't ask for the layer if that layer is not yet finalized by the peer (does it always means processed, or in some cases it is safe to use layer before that?), see https://github.com/spacemeshos/go-spacemesh/issues/2805 for options.

Also, we can error if the processed layer is lower than the requested layer.

**Comment by lrettig** [comment]
> This problem can't be fixed by self-healing since we do not re-index the internal tortoise data structure. This issue would be fixed by re-run #2846 but i don't know if it works as expected.

Right. To be clear, self-healing cannot fix a situation where block data is missing entirely. If the data arrive late, however, then healing should work.
