### ISSUE TITLE
blocks: block is missing in the database after it was received

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#2857]
## Description

In devnet206 miner-6 received block 141cf4361b at Oct 4, 2021 @ 17:09:02.081.
Three blocks used this block as a base block, but miner-6 can't process them a couple of minutes later.

**Comment by dshulyak** [comment]
For the record, i downloaded db and this block is stored in it.

**Comment by dshulyak** [comment]
This seems to reproduce quite often.

**Comment by moshababo** [comment]
@dshulyak outdated?
