### ISSUE TITLE
Swarm.SendMessage should accept PublicKey instead of a string as the node id

### ISSUE THREAD

**Issue by zalmen** [spacemeshos/go-spacemesh#287]
Accepting strings is error prone

**Comment by Bluetegu** [comment]
I'd like to try and address this.

**Comment by almogdepaz** [comment]
@Bluetegu go for it
i moved the issue to "in progress" 
also  you can assign yourself so everybody can see you are handling this

**Comment by Bluetegu** [comment]
I guess changing peerPubKey from string to a pubKey only in SendMessage doesn't make much sense. That is, the same change should be applied all across (e.g. also in gossip.Peer(), in dht.Lookup() etc.), right?

Do you mean replacing string with *btcec.PublicKey, or with *crypto.PublicKey? 

Why did you choose to wrap btcec.PublicKey with crypto.PublicKey? Why not use  btcec.PublicKey directly?

Thanks!

**Comment by almogdepaz** [comment]
we want to change the string in SendMessage to crypto.PublicKey.
notice that crypto.PublicKey is an interface so you shouldn't use a pointer there.

cheers!
