### ISSUE TITLE
activation: failed contextual validation due to inconsistent state between atx receiver and atx producer

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#2871]
## Description

Multiple smeshers are producing atx's that are discarded with the next error on receiver side: `last atx is not the one referenced`.
ATX's are indexed using last epoch id, last atx is the one with largest epoch id. It must mean that the receiver has a newer atx than the producer.

## Steps to reproduce
Reproduced on devnet207.
Look for error with M: `atx failed contextual validation` or errmsg: `last atx is not the one referenced`

**Comment by dshulyak** [comment]
It is possible if we sent an ATX, but terminated the node before ATX was stored in the database locally. After restart smesher might be never able to produce ATX that will be accepted by the network again. This is exactly what i am seeing with `39f5d5fd0b32f9f67a727e68d07cad0bdb29d583534e03acd133313fd2da34d1` and `5c83fcbd0878435eb698c451d05e18e9de7973ba4c9cd4ff41752290718bad80` on devnet207. As a solution we should always persist ATX before sending it.

**Comment by nkryuchkov** [comment]
https://github.com/spacemeshos/go-spacemesh/pull/2982 changes the `atx failed contextual validation` log level to WARN, so it won't be found by ERROR level anymore

**Comment by moshababo** [comment]
@dshulyak outdated?
