### ISSUE TITLE
tortoise: layers invalidated by hare are ignored

### ISSUE THREAD

**Issue by countvonzero** [spacemeshos/go-spacemesh#2875]
## Description

`GetLayerInputVectorByID` should check it and return `mesh.ErrInvalidLayer` if the layer is invalid. it is then checked in verifying_tortoise.go https://github.com/spacemeshos/go-spacemesh/blob/4f6a8b2ca56dcaba0d947e2bcec43899299c455b/tortoise/verifying_tortoise.go#L1099

## Actual Behavior
invalidated layer output by hare is ignored.

## Expected Behavior
invalided layer should be processed and voted against

**Comment by lrettig** [comment]
The change was made here in #2709:

https://github.com/spacemeshos/go-spacemesh/pull/2709/files#diff-4631ba6bc4f174ec995a1aa9299207e42c8f1db16abbea65bdd84777b2024414L400

**Comment by countvonzero** [comment]
> The change was made here in #2709:
> 
> https://github.com/spacemeshos/go-spacemesh/pull/2709/files#diff-4631ba6bc4f174ec995a1aa9299207e42c8f1db16abbea65bdd84777b2024414L400

thats me! i won! yayyyy

**Comment by countvonzero** [comment]
@lrettig question.

what was the consideration for not persisting `invalidatedLayers`?
how does the network remember that the hare terminated with empty set for a given layer?

**Comment by lrettig** [comment]
> what was the consideration for not persisting `invalidatedLayers`?
> how does the network remember that the hare terminated with empty set for a given layer?

Sorry for the slow reply. I think we didn't persist it because we don't persist any hare output. It's only relevant for a brief period after hare terminates for a given layer. I can take a closer look if necessary.
