### ISSUE TITLE
blocks: verified layer will get stuck if hare terminates with a block that was failed by blockHandler

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#2909]
## Description

This was reproduced several times in recent devnets. In recent devnet the sequence of events is the next one:

- 12:20:40.230 failed to validate block blockid=2f60a4a9e7 err=failed to fetch ref block e97126425a e: protocol not supported
it failed to download one of the exceptions from peers and therefore failed current block
- 12:23:10.067 hare terminated with block that is not present in mesh blockid=2f60a4a9e7 layer=2028
hare terminates with a missing block. which can be expected in theory, but should not be possible in the network that runs in the cloud. as the result we don't push the whole layer to the tortoise. and it will miss the votes from this layer.
- 12:24:00.049 got new block and added block to database blockid=2f60a4a9e7
we get missing block from the network either through the sync or gossip, at this point we can validate 2028 properly.
but the only time we do this is by rerun.
- 12:26:30.062 handling incoming layer layer=2029
we can't count any votes from layer 2029 because we don't have blocks from layer 2028. 

There are several problems:
- fetcher for some reasons fails to download dependency, even though this dependency was added to the database at 12:20:40.081 .
- why sync didn't trigger verify layer for 2028?

## Actual Behavior

The verified layer is stuck and the only way to recover is by self-healing rerun.
Which is even when will be enabled will take time to recover the layer.

## Expected Behavior

In we failed to verify layer using hare - sync will trigger verify layer when all blocks are recovered. 

## Environment

miner-4 from latest unnamed devnet.

**Comment by countvonzero** [comment]
syncer did indeed trigger layer verification for 2028. but tortoise get stuck

```
global opinion on block differs from our vote, cannot verify layer 
global opinion on block is abstain, cannot verify layer

candidate_layer: 2027
global_opinion: (+0, -0)
local_opinion: (+1, -0))
```

i don't understand how this is possible. at that time the network is moving forward happily. miner-4 couldn't fetch a block in layer 2028 so its call to HandleIncomingLayer was delayed by ~10 layers. but this should NOT affect votes on 2027 from the blocks. at the time this happened, good blocks were marked up to layer 2037. so how can the global opinion abstain on 2027 when there is only miner-4 in trouble?

**Comment by countvonzero** [comment]
@dshulyak @lrettig

**Comment by dshulyak** [comment]
This problem appears because we check in processBlock if baseBlock is in the opinions map, we need that to "inherit" opinions from baseBlock. So in this case when 2029 was handled it failed to process blocks because none of the base blocks were in tortoise state (all base blocks were from 2028). 2030 failed because of the 2029 failed and so on.

This can be reliably reproduced with a test https://github.com/spacemeshos/go-spacemesh/pull/2914

**Comment by dshulyak** [comment]
Let's make this issue about the out-of-order layer in tortoise. We need to handle them somehow (either by buffering before they got to tortoise or by simply reprocessing blocks) and not wait for a rerun to fix things.
