### ISSUE TITLE
Feedback from self-healing code walkthrough

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2924]
There are a few points of feedback from @tal-m here that we may want to follow up on, from this call on Sept. 22:

 - it might be good if everyone stores the same base block for a given layer.
   this would be much easier later than if the base block is always chosen
   randomly. security analysis probably does not require randomization, check
   w Iddo.
 - tortoise window: should be more like 2000 than 100
 - we can have eviction based on Last not LastVerified; with a long enough window
   getting stuck (for e.g. 2000 layers) would indicate a serious problem
 - the output of self healing is the input vector for verifying tortoise
 - during rerun, if local opinion differs from global opinion, which would cause verified
   layer to get stuck (e.g., after deep reorg), could we ask a peer for their input vector
   rather than triggering self-healing? Kimmy: we could maybe do this as part of hash
   resolution algorithm. if all peers agree, we don't need to ask anyone else. if they
   don't agree...?
 - optimization: re: trying to self heal historical layers during sync of historical data: don't run the
   regular self-healing algorithm. there's an algorithm that makes it much more efficient
   that requires your peers to give you some hints, e.g., where healing ended. (there's an
   old forum thread about this.)

[Link to call recording (internal)](https://spacemesh.slack.com/archives/C89QJJY3G/p1632343863328700)

**Comment by moshababo** [comment]
@dshulyak still relevant?

**Comment by dshulyak** [comment]
Most of the items were implemented, and some are outdated
