### ISSUE TITLE
Create an API client for testground

### ISSUE THREAD

**Issue by y0sher** [spacemeshos/go-spacemesh#2929]
## Description

We decided to not test only using white-box memory access in testground but also test using the API. 
this issue consists :
- [x] - Creating the API client code
- [x] - Testing the client against the miners in testground
- [ ] - Decide on relationship between client and miner (same process? same docker? different instance?)
- [ ] - Provide the api client as lib for writing tests.
- [ ] - Test against simple api call for the first test.

**Comment by countvonzero** [comment]
testground is shelved for now
