### ISSUE TITLE
Confirmation speeds?

### ISSUE THREAD

**Issue by lonnietc** [spacemeshos/go-spacemesh#2931]
Hello,

I have just come across SpaceMesh and it looks like a great project.

Can you please tell me more about its TPS confirmation speeds?

I know that blockchains like Nano (aka. Raiblocks) and FuturePia are 3rd generation blockchains boast high TPS confirmations (although may not be realized yet) and I was wondering about SpaceMesh TPS in comparrison:

Bitcoin, 4–10 TPS
Gulden, 16–40TPS
Dash, 30–56 TPS
Digibyte, 300–560TPS
Neo, 1000 TPS
Eos, 5000 TPS
Nano, 7000 TPS
Komodo, 20.000 TPS
Ternio, 1.000.000 TPS
Futurepia, 300.000 TPS

Any information that you could provide would be greatly appreciated.
Thanks in advance

**Comment by dshulyak** [comment]
Thank you for your interest, we will publish TPS closer to the release date.
