### ISSUE TITLE
blocks, sync: do not publish blocks until the the most recent layer is verified

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#2934]
## Description

After sync fetches layers from peers it submits them for verification to a separate goroutine. Verification always lags behind sync, especially on slow machines. So at the time when we set synced state, we still might be lagging behind arbitrarily. 

The synced state enables blocks builder to publish blocks. So if our current verified layer is behind cluster verified layers by more than sliding window difference - all blocks that will be produced by use base block that is not valid from the rest of the network point of view.

It doesn't mean that we shouldn't handle such blocks gracefully, but we definitely shouldn't increase the likelihood of creating such blocks. 

## Steps to reproduce
1. Have a network with at least 2000-3000 layers
2. Launch sync
3. Compare by how many layers verified is lagging behind synced

## Actual Behavior
Block from new joiner is very likely to use base block from evicted layer.

## Expected Behavior
Block from new joiner is not likely to use base block from evicted layer.

**Comment by countvonzero** [comment]
this is not my understanding of the code.

syncer always wait for the verification thread to complete before changing sync state. 

say node restarted. and syncer is catching up from layer 1990, and the current layer is 2000, that sync run will
- set new state if necessary
- start a verification thread that call `mesh.ValidateLayer()`
- for each layer bwtnlayer 1991-1999
  - fetch the layer data
  - (at this point block data should be fetched and syntactically validated)
  - submit the layer to verification thread
- wait for verification thread to exist
- set new state if necessary

do you think what you are describing is an effect of this PR https://github.com/spacemeshos/go-spacemesh/pull/2873

**Comment by dshulyak** [comment]
So let's say we started sync when current was 2000 and fetched everything up to it into the buffer. Then we wait for verification up to 2000 to complete, and if it is slow then current can move up to 2100, for example. Are we in synced state anyway after that, or not?

In the cloud verification after sync was very slow for some reason, it could take 9h or so, but i don't remember if this is before or after some optimization that i did. 

> do you think what you are describing is an effect of this PR #2873

no idea about that

**Comment by dshulyak** [comment]
Most likely the base block was selected from the last known layer, layer 2326 has 26 blocks and new block that uses base block from 2326 declares support for exactly 26 blocks. If a new block knew about other layers it would add exceptions for layers inbeetween.

**Comment by countvonzero** [comment]
> So let's say we started sync when current was 2000 and fetched everything up to it into the buffer. Then we wait for verification up to 2000 to complete, and if it is slow then current can move up to 2100, for example. Are we in synced state anyway after that, or not?

no. if the current layer changes, the loop will not end until it's `currentLayer-1`.
and it won't set the sync state to `synced`. it will set it to `gossipSynced`, which allows the node to receive gossip messages but not participate in the hare or beacon protocol.
a node will stay in `gossipSynced` for 2 layers before entering to `synced` state

**Comment by dshulyak** [comment]
> no. if the current layer changes, the loop will not end until it's currentLayer-1.

but the buffer will be 2000, so the actual current will move forward after the last layer in the loop is sent to the buffer. for example if fetching takes 3h, and validation 6h then the current will be advanced by 2-3h while we wait for validation.

but due to another sync step this looks unlikely to be caused by sync. i will set up a joiner in the cloud when we will have network with 2-3k of layers. if it is related in any way should be easy to reproduce.

**Comment by countvonzero** [comment]
> > no. if the current layer changes, the loop will not end until it's currentLayer-1.
> 
> but the buffer will be 2000, so the actual current will move forward after the last layer in the loop is sent to the buffer. for example if fetching takes 3h, and validation 6h then the current will be advanced by 2-3h while we wait for validation.
> 
> but due to another sync step this looks unlikely to be caused by sync. i will set up a joiner in the cloud when we will have network with 2-3k of layers. if it is related in any way should be easy to reproduce.

you are right tho. it is still possible that syncer caused this problem. if the node is already in `gossipSync`, and the validation delay (after the loop exited) caused it to lag current, then the code will still set it to `synced`.
