### ISSUE TITLE
AccountDataStream skips sending some rewards

### ISSUE THREAD

**Issue by brusherru** [spacemeshos/go-spacemesh#2977]
## Description
`GlobalStateService.AccountDataStream` with the `AccountDataFlag.ACCOUNT_DATA_FLAG_REWARD` (`2`) skips sending some rewards, however, the same stream with the flag that watches for account balance (`4`) seems working fine. At least it sends updates even more often than rewards.

What is a bit more strange, that when I run Smapp and also listen for this stream using `grpcurl` both connected to the local node I got different responses. However, I also run the same `grpcurl` command against the remote GRPC API and it receives more messages, but not all.

For the last session I've got:
- couple of messages in Smapp, for layers `327` and `334`
- grpcurl against local node: `307`, `308`, `316`, `324`, `329`, `331`, `332`, `336`
- grpcurl against remote grpc API: `296`, `299`, `303`, `304`, `307`, `308`, `311`, `312`, `313`, `314`, `316`, `318`, `319`, `321`, then it got `Message: stream terminated by RST_STREAM with error code: INTERNAL_ERROR` and I can't provide a log for the further period of time 😬  Anyway it seems that remote API works much better than local node. 🤔 
- at the moment latest layer is 339

Here is the log file for the last session: [spacemesh-log.txt.zip](https://github.com/spacemeshos/go-spacemesh/files/7635772/spacemesh-log.txt.zip)

## Environment
OS: macOS 11.6 (M1)
Node: [v0.2.7-beta.0](https://github.com/spacemeshos/go-spacemesh/releases/tag/untagged-08e5832bcf08d3c031d8)
Smapp: [PR#825 build](https://github.com/spacemeshos/smapp/pull/825#issuecomment-982890960)
Devnet: `devnet-kirill-2` (it uses the Node build mentioned above)

## Steps to reproduce
You can try to reproduce it using Smapp, however much easier to just run the Node.
1. Run the Node and start smeshing
2. Encode your account address to base64
3. Replace mine address with yours in the command and run: `grpcurl -d '{ "filter": { "accountId": { "address": "7mwZv3PQrg0H5uDbfYI0lSPdyao=" }, "accountDataFlags": 2 } }' api-devnet-kirill-2.spacemesh.io:443 spacemesh.v1.GlobalStateService.AccountDataStream`
4. Also you can run the same against your local node: `grpcurl -d '{ "filter": { "accountId": { "address": "7mwZv3PQrg0H5uDbfYI0lSPdyao=" }, "accountDataFlags": 2 } }' -plaintext localhost:9092 spacemesh.v1.GlobalStateService.AccountDataStream`

## Actual Behavior
Only a few rewards messages were received.

## Expected Behavior
Stream sends all reward messages without skipping anything. Even on

**Comment by nkryuchkov** [comment]
Waiting for confirmation from @brusherru whether it can be reproduced on the latest network

**Comment by brusherru** [comment]
Seems like this issue is not actual anymore.
I can't reproduce skipping rewards anymore.
🙌
