### ISSUE TITLE
verifying tortoise implementation

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#2979]
## Overview

In this table we store marging differences for all blocks and validity. For layers within hdist this is based on input vector, outside of hdist it is based on contextual validity.

Start with two arbitrary blocks Q, W. Q is valid, W is invalid. Q and W are both in layer 1. Threshold is 60%.

| blocks             | Q   | W   |     |     |     |
| ------------------ | --- | --- | --- | --- | --- |
| validity           | 1   | -1  |     |     |     |
| margin differences | 0   | 0   |     |     |     |

At next layer we receive ballots A, S, D that vote for Q and against W. Total expected vote weight is 30, each ballot weight is 10. And one new block E, which is also confirmed by input vector. Q and W are now confirmed and the layer 1 is verified.

| blocks             | Q     | W     | E   |     |     |
| ------------------ | ----- | ----- | --- | --- | --- |
| validity           | 1     | -1    | 1   |     |     |
| margin differences | 30/30 | 30/30 | 0   |     |     |

Next layer we receive ballots F and G. Both are voting for E. Only F is good, it provides 10 weight, it is not enough to verify layer since threshold is 18 (30 * 0.6). We also receive block R, confirmed by the input vector.

| blocks             | E     | R   |     |
| ------------------ | ----- | --- | --- |
| validity           | 1     | 1   |     |
| margin differences | 10/30 | 0   |     |

Receive ballots H, J, K. All are good. Add 30 weight in votes.

| blocks             | E     | R     |     |
| ------------------ | ----- | ----- | --- |
| validity           | 1     | 1     |     |
| margin differences | 40/60 | 30/30 |     |

Once E is verified, we decrease total expected weight by weight of layer 2, and then verify R.

## Implementation

Code is simplified and provided for clarity, actual implementation may differ.

```go
type VerifyingTortoiseState struct {
    // optimized margin differences stores total expected weight - voting weight
    MarginDifferences map[BlockID]*big.Float
    // Validity stores opinion according to input vector within hdist
    // before verified layer it stores contextual validity.
    // if outside hdist opinion is abstain - verifying tortoise can't make progress
    Validity          map[BlockID]int8
    LayerBlocks       map[LayerID][]BlockID
    GoodBallots       map[BallotID]bool
}

func addBlocks(s VerifyingTortoiseState, lid LayerID, bids []BlockID) {
    s.LayerBlocks[lid] = bids
    for _, bid := range bids {
        s.Validity[bid] = -1
    }
}

func addInputVector(s VerifyTortoiseState, vector []BlockID) {
    for _, bid := range vector {
        s.Validity[bid] = 1
    }
}

// Ballot simplified.
type Ballot struct {
    ID, Base   BallotID
    // Votes store both explicit and implicit votes.
    Votes  map[BlockID]int8
    // ATX weight / number of ballots
    Weight *big.Float
}

// get expected weight based on activations
func getExpectedWeight(LayerID) *big.Float

func isGood(s VerifyingTortoise, ballot Ballot) bool {
    if _, exist := s.GoodBallots[ballot.Base]; !exist {
        return false
    }
    for vote, sign := range ballot.Votes {
        if s.Validity[vote] != sign {
            return false
        } 
    }
    return true
}

func addBallots(s VerifyingTortoise, ballots []Ballot) (*big.Float) {
    sum := 0
    for _, ballot := range ballots {
        if !isGood(s, ballot) {
            continue
        }
        s.GoodBallots[ballot.ID] = true
        sum += ballot.Weight
    } 
    return sum
}

func verifyLayers(s VerifyingTortoiseState, verified, last LayerID, sum *big.Float) LayerID {
    for lid := verified + 1; lid < last; lid++ {
        for _, bid := range s.LayerBlocks[lid] {
            s.MarginDifferences[bid] += sum
            if s.MarginDifferences[bid] <= getExpectedWeight(lid) * GLOBAL_TRESHOLD {
                return lid - 1
            }
        }
    }
    return last - 1
}

func processLayer(s VerifyingTortoiseState, lid, verified LayerID, blocks, vector []BlockID, ballots []Ballot) LayerID {
    sum := addBallots(s, ballots)
    verified := verifyLayers(s, verified, lid, sum)

    addBlocks(s, lid, blocks)
    addVector(s, vector)
    return verified
}
```

## Questions

- if block is neutral outside of hdist, does it mean that verifying tortoise failed and we suppose to enter healing?

**Comment by dshulyak** [comment]
@countvonzero @lrettig please take a look if the proposed implementation is consistent with the way you understood the protocol.

**Comment by dshulyak** [comment]
I removed the optimized variant. Code is much simpler without it, and it doesn't seem to be much more efficient. I guess it should be considered after implementing this variant.

**Comment by countvonzero** [comment]
overall LGTM

>  Once E is verified, we decrease total expected weight by weight of layer 2, and then verify R.

we don't need to do anything specific right? `getExpectedWeight(E.LayerIndex)` will always have 30 more weight than `getExpectedWeight(R.LayerIndex)`

> if block is neutral outside of hdist, does it mean that verifying tortoise failed and we suppose to enter healing?

by neutral do you mean specifically voted neutral? or haven't crossed the global threshold?
if it's outside hdist, and it hasn't crossed global threshold for long enough, i think self-healing is called for.

questions:
- how does the window factor in? in the call, Tal said that we need a window for a couple thousand layers, and for verifying tortoise less (don't remember how much less).
you only update `MarginDifferences` btwn verified and last layers. i think it should be updated as long as it is in the window for correctness.

- curious how is the optimized variant not seem more efficient?

**Comment by dshulyak** [comment]
> we don't need to do anything specific right? getExpectedWeight(E.LayerIndex) will always have 30 more weight than getExpectedWeight(R.LayerIndex)

yes, i just added a note for clarity

> by neutral do you mean specifically voted neutral? or haven't crossed the global threshold?
if it's outside hdist, and it hasn't crossed global threshold for long enough, i think self-healing is called for.

i meant didn't cross the global threshold. 

> how does the window factor in? in the call, Tal said that we need a window for a couple thousand layers, and for verifying tortoise less (don't remember how much less).
   
so in my understanding this window comes up during rerun because `getExpectedWeight(E.LayerIndex)` will return expected weight based on a diff `current - e.layer_index`, so naturally verified layer will be stuck until we count votes from later layers and window will grow.

> curious how is the optimized variant not seem more efficient?

as you noted i am only updating margins after verified layer, and in this case i will always have to loop through them to check if they are ready to verify. Tal basically designed a solution that doesn't need to update the margins for every layer, but i am looping through them anyway.

but maybe i missed some edge case where we need to update margins past verified layer, so i intend to think more about it once the simplified version is implemented

**Comment by dshulyak** [comment]
> but maybe i missed some edge case where we need to update margins past verified layer, so i intend to think more about it once the simplified version is implemented

i think it is important if we do reruns using sliding window. which we currently don't, as they are fast enough without sliding window. and probably remain fast for at least a year after genesis.

**Comment by countvonzero** [comment]
> so in my understanding this window comes up during rerun because getExpectedWeight(E.LayerIndex) will return expected weight based on a diff current - e.layer_index, so naturally verified layer will be stuck until we count votes from later layers and window will grow.

my memory is that Tal also want a window for verifying tortoise. but i cannot remember why it needs to be past verified layers in the normal case. for reruns the windows will naturally be bigger for the reason you stated. maybe clarify with Tal again.


>> curious how is the optimized variant not seem more efficient?
>>
> as you noted i am only updating margins after verified layer, and in this case i will always have to loop through them to check if they are ready to verify. Tal basically designed a solution that doesn't need to update the margins for every layer, but i am looping through them anyway.

i think the optimization make sense if we keeps a sliding window beyond the verified layer.
then the uncounted-weight algo optimizes for layers btwn (window_start, verified) where you don't need to loop over.

**Comment by countvonzero** [comment]
> i think it is important if we do reruns using sliding window. which we currently don't, as they are fast enough without sliding window. and probably remain fast for at least a year after genesis.

i am confused. the code currently still supports sliding window with default size 100.
and the point of having sliding window is not for speed but for possible change of history?

**Comment by dshulyak** [comment]
> i think the optimization make sense if we keeps a sliding window beyond the verified layer.
then the uncounted-weight algo optimizes for layers btwn (window_start, verified) where you don't need to loop over.

this is what i meant in the comment regarding rerun based on sliding window. if we want to rerun from window_start instead of genesis then we need to keep everything from window_start in memory, because block goodness is recursive. in that case it will be definitely inefficient to update everything. i don't recall other reasons to have a window in the past, but i will clarify.

**Comment by dshulyak** [comment]
> i am confused. the code currently still supports sliding window with default size 100.
and the point of having sliding window is not for speed but for possible change of history?

it is not removed completely because we are using those votes to encode exceptions when base ballot is chosen. i think it can be revisited once verifying tortoise is implemented, as exceptions selection is very simple in verifying mode. and we need full votes only when tortoise is in healing mode.

**Comment by dshulyak** [comment]
There is a flaw in the implementation above. If length of the unverified layer is large the protocol still needs to update weight for each of them, so exiting when first layer cannot be verified is not allowed. This will be definitely a performance issue in case of rerun where this length can be a million layers. So this is why an optimized variant is required.

I also had in mind an alternative optimized implementation that is a bit simpler. Instead of margin differences we will need to store weight per layer and total weight. 

For example we got this weight during rerun for 5 layers:

| layers | 1   | 2   | 3   | 4   | 5   |
| ------ | --- | --- | --- | --- | --- |
| weight | 30  | 10  | 30  | 20  | 20  |
| total  | 110 |     |     |     |     |

To verify blocks from layer 1 we need to count weight from Layer_2 - Layer_5, which is also TOTAL - Layer_1. And after layer is verified total is updated.

So this is how the total will change during verification:

| layers | 1   | 2   | 3   | 4   | 5   |
| ------ | --- | --- | --- | --- | --- |
| weight | 30  | 10  | 30  | 20  | 20  |
| total  | 110 | 80  | 70  | 40  | 20  |
