### ISSUE TITLE
Consolidate ballots and proposals with same smesher and layer to one

### ISSUE THREAD

**Issue by noamnelke** [spacemeshos/go-spacemesh#2998]
1. Update the `EligibilityProof` in `InnerBallot` to `EligibilityProofs`—a slice of `VotingEligibilityProof`s. https://github.com/spacemeshos/go-spacemesh/blob/a22d1eeee6f593b54fbb5f89fb32573f965a6528/common/types/ballot.go#L38-L44
2. Update `proposal_builder.go`→`createProposal()` https://github.com/spacemeshos/go-spacemesh/blob/a22d1eeee6f593b54fbb5f89fb32573f965a6528/miner/proposal_builder.go#L245-L253 to accept a slice of eligibility proofs.
3. Unwrap the code in this loop: https://github.com/spacemeshos/go-spacemesh/blob/8951b6fa049c8f91e774e69f751973eebc34d690/miner/proposal_builder.go#L362-L412 in `proposal_builder.go`→`handleLayer()` - instead of looping, pass `proofs` into `createProposal` directly.
4. In `handler.go`→`checkBallotDataIntegrity()` https://github.com/spacemeshos/go-spacemesh/blob/a22d1eeee6f593b54fbb5f89fb32573f965a6528/proposals/handler.go#L242-L280 add a check that counter values (`J`) of all eligibility proofs are distinct.
5. In `handler.go`→`processBallot()` https://github.com/spacemeshos/go-spacemesh/blob/a22d1eeee6f593b54fbb5f89fb32573f965a6528/proposals/handler.go#L204-L218 add a check for an existing ballot by the same smesher in the same layer. If such a different ballot already exists in our database the expected behaviour is to blacklist the smesher and publish a fraud-proof consisting of the two ballots. Since we don't have this mechanism implemented (and it's non-trivial to implement) we should create a stub method as follows and call it:

```golang
func Blacklist(types.SmesherID) {
    // TODO: Implement me!
}
```

6. Change the following method to account for multiple eligibility proofs in a ballot. This will probably require changing the `weights` data structure or augmenting it with another one for the weight of a single ballot of a smesher in an epoch. https://github.com/spacemeshos/go-spacemesh/blob/a22d1eeee6f593b54fbb5f89fb32573f965a6528/tortoise/threshold.go#L10-L59

We currently don't limit the number of transactions in a proposal. Sizing proposals based on ballot weight will be part of the task of limiting the size (part of the transaction selection epic that's being written these days).

**Comment by dshulyak** [comment]
> Change the following method to account for multiple eligibility proofs in a ballot. This will probably require changing the weights data structure or augmenting it with another one for the weight of a single ballot of a smesher in an epoch. 

it won't require changing weights or any other data structure. what is needed is to track which ballots are malicious and either completely skip them when they are loaded into the tortoise, or explicitly register them with 0 weight. Probably registering with 0 is the most convenient, as it will handle cases when ref ballot was malicious so a new ballot based on ref ballot automatically won't be counted.

**Comment by noamnelke** [comment]
@dshulyak 
> it won't require changing weights or any other data structure. what is needed is to track which ballots are malicious and either completely skip them when they are loaded into the tortoise, or explicitly register them with 0 weight. Probably registering with 0 is the most convenient, as it will handle cases when ref ballot was malicious so a new ballot based on ref ballot automatically won't be counted.

The problem is not malicious ballots, it's valid ballots with more than one eligibility. So if the ref ballot has 2 eligibilities its weight will be double. When we then calculate the weight of the current ballot, if it only has a single eligibility then we can't use the weight of the ref ballot (we need half).

Two possible solutions I can think of - both seem too complex - we can probably find something simpler/more efficient:
1. `weight` is currently a wrapper around a `*big.Float`[^1] - we can have two numbers in there `weight` and `eligibilityCount` with an additional method that returns the weight of a single eligibility (before multiplying by the eligibility count).
2. We can create an additional `map[layerID][smesherID]weight` (weight here will be the weight of a single eligibility).

[^1]: The TODO there says it should be replaced with a fixed float, but I think it should be replaced with an integer - we should discuss this some other time.

**Comment by dshulyak** [comment]
Thanks, i misunderstood the intent. I think we should index by atxid then. Map with atxid will store just atx_weight / eligibility_count, and weight of the ballot will be computed as that weight multiplied by eligibilities included into the ballot. And then for efficient eviction it probably needs to be indexed by epoch as well.

So full structure will `map[EpochID][AtxID]weight`
