### ISSUE TITLE
tortoise: tortoise state loading will be growing in time 

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#3006]
After persistent state was removed tortoise loads state from meshdb and atxdb when the node is started. In the initial implementation i am also re-verifying everything, as it allowed to reuse code for rerun almost as is.

However after https://github.com/spacemeshos/go-spacemesh/pull/3000 is merged rerun in full mode will be rather slow. So instead of verifying when node is booted we can just load state.

the end goal is to make restart fast, we can achieve that:
- by eliminating bottlenecks in tortoise
- by snapshotting tortoise when node is stopped gracefully
- by loading state without verifications
- by offloading state loading into background, and blocking components that rely on tortoise

**Comment by dshulyak** [comment]
Note: we don't need state in full.weight for verified layers, but we need to know which ballots are good, because the definition is recursive.

**Comment by dshulyak** [comment]
Also need to compute real margins for layers between verified and processed, as we will use them for voting. So it is not completely possible to avoid vote counting. Will postpone this change.

**Comment by dshulyak** [comment]
We can do this after mutable ballots will be implemented. They allow us to verify goodness of the ballot without recursively decoding all previous votes, instead we can just compare if ballot encoded opinion is identical to local opinion.

**Comment by countvonzero** [comment]
minor issue i encountered is that the loading is not interrupt-able with sigterm as it doesn't check context cancel.
