### ISSUE TITLE
xdr library consumes excessive amount of memory on decoding some malformed data

### ISSUE THREAD

**Issue by nkryuchkov** [spacemeshos/go-spacemesh#3014]
## Description

When I try to sync from scratch with `testnet-02` on develop (`8e9bc4093f7a2838a3c6668960f29b69c658b879`), the node consumes 53 GB RAM a couple of minutes after the start and then gets killed by OOM.

![image (1)](https://user-images.githubusercontent.com/24493220/146765780-ae349a37-d28b-4cea-a2b8-4aa4fb30e38d.png)

I tried to run `v0.2.7-beta.0`, it doesn't have such an issue.

The logs of `pprof` on start:
```
(pprof) top
Showing nodes accounting for 23.76GB, 99.71% of 23.83GB total
Dropped 42 nodes (cum <= 0.12GB)
Showing top 10 nodes out of 17
      flat  flat%   sum%        cum   cum%
   23.76GB 99.71% 99.71%    23.76GB 99.71%  reflect.unsafe_NewArray
         0     0% 99.71%    23.76GB 99.71%  github.com/nullstyle/go-xdr/xdr3.(*Decoder).Decode
         0     0% 99.71%    23.76GB 99.71%  github.com/nullstyle/go-xdr/xdr3.(*Decoder).decode
         0     0% 99.71%    23.76GB 99.71%  github.com/nullstyle/go-xdr/xdr3.(*Decoder).decodeArray
         0     0% 99.71%    23.76GB 99.71%  github.com/nullstyle/go-xdr/xdr3.(*Decoder).decodeStruct
         0     0% 99.71%    23.76GB 99.71%  github.com/nullstyle/go-xdr/xdr3.Unmarshal (inline)
         0     0% 99.71%    23.76GB 99.71%  github.com/spacemeshos/go-spacemesh/codec.Decode
         0     0% 99.71%    23.76GB 99.71%  github.com/spacemeshos/go-spacemesh/codec.DecodeFrom
         0     0% 99.71%    23.76GB 99.71%  github.com/spacemeshos/go-spacemesh/layerfetcher.(*Logic).GetBlocks
         0     0% 99.71%    23.76GB 99.71%  github.com/spacemeshos/go-spacemesh/layerfetcher.(*Logic).PollLayerContent.func1
(pprof) 
```

UPD: `devnet-kirill-6` is down, `testnet-02` is run instead of it. The issue is also reproducible on `testnet-02`, so I changed the description

## Steps to reproduce
1. Run sync from scratch with `testnet-02` on `8e9bc4093f7a2838a3c6668960f29b69c658b879`
2. Wait a couple of minutes until you see

## Actual Behavior

Node uses too much memory and gets OOM-killed

## Expected Behavior

Node uses an acceptable amount of memory and continues working

## Environment
Please complete the following information:
 - OS: 
 
 MacOS
 - Node Version: 
 
 `8e9bc4093f7a2838a3c6668960f29b69c658b879`
 - Smapp version (if applicable): 
 
 N/A

**Comment by nkryuchkov** [comment]
I wasn't able to reproduce this on commit before merging #2997 but was able to do it after merging #2997, so it may cause the issue.

cc @countvonzero

**Comment by dshulyak** [comment]
Just adding a note that `devnet-kirill-6` network is not compatible with develop. So it is not expected to work. But overall it is weird that node crashed with OOM, so maybe it exposed some bug.

**Comment by nkryuchkov** [comment]
The reason for the crash is indeed the incompatibility between `devnet-kirill-6` and `develop`. However, https://github.com/spacemeshos/go-spacemesh/pull/3018 shows that decoding of one malformed proposal with 3 KB length with the https://github.com/nullstyle/go-xdr/xdr3 library takes 3 GB of memory
