### ISSUE TITLE
log: change the destination of all logs from `stdout` to `stderr`

### ISSUE THREAD

**Issue by nkryuchkov** [spacemeshos/go-spacemesh#3025]
## Description

As @dshulyak said, it's a common practice to use `stderr` instead of `stdout` for logs. Not urgent. When implemented, we need to ensure that this action doesn't break anything in the infrastructure.

https://github.com/spacemeshos/go-spacemesh/issues/3024#issuecomment-1001620954

## Affected code

Logging

This issue appears in commit hash: 
`9972b2c9c7ee79a2ef913eeb0d8ead05ee74769c`

**Comment by moshababo** [comment]
All logs, or all error-or-higher logs?

**Comment by nkryuchkov** [comment]
@moshababo All logs
