### ISSUE TITLE
log: add a field with error text code

### ISSUE THREAD

**Issue by nkryuchkov** [spacemeshos/go-spacemesh#3027]
## Description

Introduce a new field in `FATAL` logs, the field has a common name and contains an error text code like `ERR_CLOCK_AWAY`. With it, the app knows what error occurred and, for example, shows a possible solution. The error text code can also be used for localization (e.g. in the future we can have a web service that accepts a text code (e.g. `ERR_CLOCK_AWAY`) and a language code (e.g. `en-us`) and returns a text in that language (e.g. `Clock is away from NTP servers`). The field is urgent.

https://github.com/spacemeshos/go-spacemesh/issues/3024#issuecomment-1001620954

## Affected code

Logging

This issue appears in commit hash: 
`9972b2c9c7ee79a2ef913eeb0d8ead05ee74769c`

**Comment by brusherru** [comment]
> 3. Introduce a new field in FATAL logs, the field has a common name and contains an error text code like ERR_CLOCK_AWAY. With it, the app knows what error occurred and, for example, shows a possible solution.

aka `{  ..., "errorCode": "ERR_CLOCK_AWAY" }`
Right?

**Comment by nkryuchkov** [comment]
@brusherru yes, we can choose any field name

**Comment by dshulyak** [comment]
Consider making use of errors.As and log.ObjectMarshaller interface. So when log.Err is called and error implements ObjectMarshaller it will encode error code and details how it is defined in MarshalLogObject method.

**Comment by nkryuchkov** [comment]
@dshulyak yes, that's what I'm doing, thanks
