### ISSUE TITLE
Proposal Construction

### ISSUE THREAD

**Issue by noamnelke** [spacemeshos/go-spacemesh#3035]
A proposal is a set of transactions randomly selected from the predicted block. The block is predicted by assuming all smeshers see the same mempool and selecting the highest gas-price transactions that fit into a block out of the mempool.

Given pre-configured values for `block_gas_limit` and `proposal_num_transactions` perform the following:
1. Predict the contents of the next block by doing the following:
    ```python
    def predict_block():
        remaining_gas = block_gas_limit
        txs = []
        for tx in mempool.txs_by_gas_price_and_seniority():
            if tx.max_gas > remaining_gas:
                continue
            remaining_gas -= tx.max_gas
            txs.append(tx)
            if remaining_gas < MIN_TX_GAS:  # gas required for the most basic transaction
                break
        return txs
    ```
    _Note: Because transactions currently don't have a `max_gas` property (more precisely, it's not used) we should add a getter to transactions that currently returns a fixed value of 1. This should work until we finish SVM integration, when the getter will return the correct value._

2. Randomly select `proposal_num_transactions` from the predicted block (using local randomness).
_Note: The randomness of a proposal's transactions cannot be verified and doesn't need to be. Since layer committee members share rewards, they are naturally incentivized to collaboratively produce a block with all highest `gas_price` transactions. Since there will be some redundancy in proposed transaction, a small number of deviating participants won't significantly change the outcome._
3. Check if all layers prior to the proposal layer are verified. If they are, include the `state_root` in the proposal, otherwise use a sentinel value (e.g. all-zeros).
4. Sign the proposal and publish it (along with the ballot, which includes the layer committee eligibility proof).

**Comment by countvonzero** [comment]
@noamnelke 

> 3. Check if all layers prior to the proposal layer are verified. If they are, include the state_root in the proposal, otherwise use a sentinel value (e.g. all-zeros).

if by "verified" you mean by tortoise, this is NEVER the case.
in the most optimistic case, the latest hare committee is running on layer N, the node only has ballots up to layer N-1, this means the highest layer tortoise can verify is layer N-2. 

cc @dshulyak

**Comment by dshulyak** [comment]
I realized some time ago that this a shortcoming of the current implementation (https://github.com/spacemeshos/go-spacemesh/issues/3054). 

We don't need to wait for a hare from layer N to complete in order to verify layer N - 1. we just need to wait for ballots from layer N and they are expected to be received much sooner, like 5-10s after layer N has started. It does require some additional work.

**Comment by noamnelke** [comment]
Actually, verified by Hare is enough. The test here is whether all previous layers have been applied to global state. If they have - it should be in consensus. No need to wait for Tortoise.

**Comment by dshulyak** [comment]
> The test here is whether all previous layers have been applied to global state

We don't apply layers to global state before tortoise verifies them. Hare only determines how tortoise votes.

**Comment by countvonzero** [comment]
the best we can do, after hare terminate, is the accumulated layer hash in the mesh.

**Comment by countvonzero** [comment]
> Actually, verified by Hare is enough. The test here is whether all previous layers have been applied to global state. If they have - it should be in consensus. No need to wait for Tortoise.

https://github.com/spacemeshos/go-spacemesh/pull/3131 implemented this

**Comment by countvonzero** [comment]
@noamnelke 

> 2. Randomly select proposal_num_transactions from the predicted block (using local randomness).

FYI. this step is tricky. the mempool is sorted by gas price and may contain multiple TXs for the same account. in that case, we need to ensure the nonce ordering in this "locally random selection" process

**Comment by countvonzero** [comment]
> 3. Check if all layers prior to the proposal layer are verified. If they are, include the state_root in the proposal, otherwise use a sentinel value (e.g. all-zeros).

i'm going to include 2 things in the proposal when hare terminated successfully for previous layer:
- mesh_hash
- state_root (placeholder for either temporary solution if any, or future state_root when state trie is implemented)

@noamnelke @dshulyak
