### ISSUE TITLE
Block Construction (Unification of Proposals)

### ISSUE THREAD

**Issue by noamnelke** [spacemeshos/go-spacemesh#3036]
This issue covers how to construct a block after the Hare converged on a set of proposals. This is done as part of the Hare certification phase and the Hare certifies the resulting `block_id`.

1. Calculate the **block seed**:
	1. Sort proposal IDs lexicographically.
	2. Initialize a Sha256 hash and write the sorted proposal IDs into it.
	3. Calculate the Sha256 sum and use it as the block seed.
2. **Combine** transactions from entire set of proposals into a single set.
3. **Fetch** available transactions from mempool and missing transactions from peers.
4. If more than one transaction competes for the same principal and nonce:
	1. Pick the one that pays the highest gas (`max_gas * gas_price`).
	2. If multiple transactions pay the same highest gas - use a tie breaker: Calculate the Sha256 sum of the concatenation of the block seed and the transaction ID and pick the one that's lowest, lexicographically. Hashing the transaction ID with the block seed makes the selection unpredictable, preventing users from being able to replace transactions without bumping the fee.
	3. **Remove all remaining transactions** from the set.
5. Perform **initial shuffling** of transactions:
	1. Sort transaction IDs lexicographically.
	2. Initialize a Mersenne Twister with the block seed.
	3. Use the MT as a source of randomness for a Fisher-Yates shuffle of the previously-sorted transaction IDs.

    Something similar, but for blocks, is implemented today [here](https://github.com/spacemeshos/go-spacemesh/blob/9972b2c9c7ee79a2ef913eeb0d8ead05ee74769c/mesh/mesh.go#L603-L627) and can be used as a reference.

6. Perform **intra-principal sorting by nonce**. We want transactions associated with a principal account which have a lower nonce value to appear before transactions associated with the same principal account that have a higher nonce value. We want to do this without affecting the order of other transactions.
E.g. if `a3` is a transaction with principal `a` and nonce `3`, then the shuffled list of transactions:
`[ a3 c1 a0 b0 a2 c0 b1 ]`
will become, after intra-principal sorting:
`[ a0 c0 a2 b0 a3 c1 b1 ]` 
Note that the principal in each slot in the list never changes. One way to implement this (but feel free to come up with a more efficient method) is:
    ```python
    txs_by_principal = defaultdict(list)
    for tx in shuffled_list:
        txs_by_principal[tx.principal].append(tx)
    for txs in txs_by_principal.values():
	    # sort in decsending order, because pop() pops from the end.
	    txs.sort(key=lambda tx: tx.nonce, reverse=True)
	final_list = [txs_by_principal[tx.principal].pop() for tx in shuffled_list]
    ```
7. **Prune the list:**
	1. **Initialize** `remaining_gas` to `block_gas_limit`.
	2. **Check if the conditions for optimistic transaction filtering are met:** at least `optimistic_transaction_filtering_threshold` (an absolute number set in the config - default can be 90% of `layer_committee_size` - 45) of the valid proposals are signaling the same `state_root`. If this is the case, validate that we have the same state root. If we don't, block construction fails and our only recourse is to try to sync this block from neighbors. If it fails and we're supposed to certify this block in Hare, we abstain (by not participating).
	3. **If conditions are met,** we can perform optimistic transaction filtering. Iterate over each transaction in the list, in order and check if it can cover it's maximal gas cost based on conservative balance. If it can't - prune it from the list. Otherwise, if `tx.max_gas > remaining_gas` also prune it from the list and skip to the next transaction. Finally, reduce `remaining_gas` by `max_gas`. Continue this until `remaining_gas < MIN_TX_GAS` - then remove all remaining transactions.
	4. **Otherwise (no optimistic transaction filtering),** iterate over the list of transactions as in the previous case, but skip the balance check.
8. **Create set of rewards** (based on proposals): For each proposal, find the coinbase address referenced in the associated ATX and its weight. Create a list of tuples `(coinbase_address, proposal_weight)`, sorted and aggregated by `coinbase_address` (if an address appears twice, sum its weight). Include this list in the block.

**Comment by countvonzero** [comment]
adding a discussion in slack https://spacemesh.slack.com/archives/CG91F13C7/p1646814768216309 on March 9 2022 in the research channel.
the conclusion is in the non-optimistic scenario (no filtering), we will not drop any transactions, even if the transaction has been previously applied.
