### ISSUE TITLE
Block Execution

### ISSUE THREAD

**Issue by noamnelke** [spacemeshos/go-spacemesh#3037]
When a block is applied we must perform something similar to what happens during optimistic transaction filtering. We execute each transaction, in the order they appear in the block, first checking that it can cover gas (skipping if it can't).

While executing transactions, all paid fees should be accumulated. Then the total fee is added to the newly minted coins and distributed to the coinbase accounts in the reward set in the block, based on their weights.

**Comment by dshulyak** [comment]
> When a block is applied we must perform something similar to what happens during optimistic transaction filtering. We execute each transaction, in the order they appear in the block, first checking that it can cover gas (skipping if it can't).

can you explain the rationale behind this please?

**Comment by noamnelke** [comment]
Sure.

Firstly, there's no indication in the block if optimistic transaction filtering occurred or not. It only happens if there's broad consensus on the state right before the proposals were made, which won't happen if Hare doesn't converge on the first attempt. If optimistic filtering doesn't happen there's no way to filter transactions even if their principle never existed, since there's no known consensus about that.

Even if we were to add a flag that indicates if optimistic filtering happened, it would not be guaranteed in all cases, since a reorg could mean that while there was consensus about the state prior to the proposals, the actual state when executing the block is different.

Let's look at it from another angle: there are exactly 4 scenarios in which we execute a block.
1. **As part of optimistic filtering** - in that case the balance check happens before executing the transactions and a transaction that fails the balance check gets filtered out - I assume it's obvious that the check is needed in this scenario.
2. **If the conditions for optimistic filtering didn't occur** -  this means there was no consensus on state at proposal time (e.g. due to a bug or because one of the previous layers weren't verified yet). In that case we need to check each transaction's ability to pay gas because this was never done (theoretically transactions that can't pay gas shouldn't make it into proposals, but there's nothing to guarantee that).
3. **If optimistic filtering was done, but then there was a reorg and we have to re-apply this block** - after the reorg state may have changed and transactions that had gas coverage may no longer have it, so we have to perform this check again.
4. **If we're applying the block during sync** - we may not know which of the scenarios above it was.

Even if we could prevent the need to check in some cases by including a flag or something, it's probably not worth it since this is a very cheap and easy check. If we're gonna execute a transaction we have to load its principle state from disk anyway, so performing one integer comparison is practically free.

**Comment by dshulyak** [comment]
Do we need to check that transaction covers fees for validation (including payload parsing) or fees for execution as well (literally MaxGas value?)?

**Comment by dshulyak** [comment]
forgot to link a commit that implemented it, but current vm behavior matches this description
