### ISSUE TITLE
flake in systemtet-blocks-add-node

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#3096]
- assertion fails with missing proposal in the first layer of the epoch (layer 15)
- in logs proposal builder fails with missing beacon (layer 15)
- node doesn't participate in the tortoise beacon in epoch 4 as the atx that targets this epoch is not available, and learns the beacon only after other nodes from layer 15 created ballots
- atx in epoch 3 is not published as the node is not in the synced state
- layer 6 took ~3 minutes to download http://34.105.32.157:5601/goto/804aeca259705e5c919423077ae75fa0

**Comment by countvonzero** [comment]
from this kibana http://34.105.32.157:5601

> in logs proposal builder fails with missing beacon (layer 15)

i only saw proposal builder logging about not able to find own ATX from previous epoch. all by the same node (sm-client-dmitry-test-5wtx4-5c7bf58c7d-7qdtg). this is expected since this is the last node added to the network.
```
failed to get valid atx for node for target epoch 4: get ATX ID: atx for node 94769 with publication epoch 3: get value: leveldb: not found
```

the only missing beacon related log is from trtl `failed to get beacon for epoch` from the same node sm-client-dmitry-test-5wtx4-5c7bf58c7d-7qdtg. this makes sense because this node is doing beacon sync. tortoise probably want to check to have beacon value for the epoch before start processing ballots for that epoch.

**Comment by dshulyak** [comment]
here is a link http://34.105.32.157:5601/goto/6f9daa3e1268dfdb6a3e55e28105bffc

**Comment by dshulyak** [comment]
> i only saw proposal builder logging about not able to find own ATX from previous epoch. all by the same node (sm-client-dmitry-test-5wtx4-5c7bf58c7d-7qdtg). this is expected since this is the last node added to the network.

the test is written in a way to give enough time for a node to produce an atx and participate in tortoise beacon. it fails when node for some reason can't sync in time, e.g. it is getting delayed for 3m

**Comment by countvonzero** [comment]
> here is a link http://34.105.32.157:5601/goto/6f9daa3e1268dfdb6a3e55e28105bffc

this is also expected. this node (podname sm-client-dmitry-test-5wtx4-5c7bf58c7d-7qdtg) is doing beacon sync, 

you can check the log [here](http://34.105.32.157:5601/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-28T08:37:25.313Z',to:'2022-01-28T09:22:32.985Z'))&_a=(columns:!(M,layer_id,kubernetes.pod_name,module,epoch_id),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!t,index:sm,key:node_id,negate:!f,params:(query:'9476917f5fd5acaf6816cd75cfeae4d7472afafdd84fc0b1cba6823230b411d4'),type:phrase),query:(match_phrase:(node_id:'9476917f5fd5acaf6816cd75cfeae4d7472afafdd84fc0b1cba6823230b411d4'))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:sm,key:sessionId,negate:!f,params:(query:d5021fe7-ed3f-4123-9d6f-d3f1172d5730),type:phrase),query:(match_phrase:(sessionId:d5021fe7-ed3f-4123-9d6f-d3f1172d5730))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:sm,key:L,negate:!f,params:!(ERROR),type:phrases,value:ERROR),query:(bool:(minimum_should_match:1,should:!((match_phrase:(L:ERROR)))))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:sm,key:module,negate:!t,params:(query:hare),type:phrase),query:(match_phrase:(module:hare))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:sm,key:M,negate:!f,params:!('beacon%20determined'),type:phrases,value:'beacon%20determined'),query:(bool:(minimum_should_match:1,should:!((match_phrase:(M:'beacon%20determined'))))))),index:sm,interval:auto,query:(language:kuery,query:''),sort:!())) for the timing.

**Comment by dshulyak** [comment]
no, this is not correct. i checked that, and tortoise beacon is learned from ballots. it must be learned from tortoise beacon protocol. and in order for a node to participate in tortoise beacon protocol it needs to be synced earlier

> node doesn't participate in the tortoise beacon in epoch 4 as the atx that targets this epoch is not available, and learns the beacon only after other nodes from layer 15 created ballots

because of

> atx in epoch 3 is not published as the node is not in the synced state

and it would be published if atx fetching would complete faster than 3m

**Comment by countvonzero** [comment]
> > i only saw proposal builder logging about not able to find own ATX from previous epoch. all by the same node (sm-client-dmitry-test-5wtx4-5c7bf58c7d-7qdtg). this is expected since this is the last node added to the network.
> 
> the test is written in a way to give enough time for a node to produce an atx and participate in tortoise beacon. it fails when node for some reason can't sync in time, e.g. it is getting delayed for 3m

right. this is definitely an issue.

**Comment by countvonzero** [comment]
tho i think all these issues you raised are not new, and is not the reason that caused the flake.
i actually don't think this test is flaky.

**Comment by dshulyak** [comment]
> tho i think all these issues you raised are not new, and is not the reason that caused the flake.
i actually don't think this test is flaky.

it passed 3/4 times when i was executing it locally. why you don't think that this test is flaky?

**Comment by countvonzero** [comment]
> > tho i think all these issues you raised are not new, and is not the reason that caused the flake.
> > i actually don't think this test is flaky.
> 
> it passed 3/4 times when i was executing it locally. why you don't think that this test is flaky?

to me that sounds like 3/4 times a node is expected to produce 2 proposals a layer, but only produced 1.

**Comment by countvonzero** [comment]
> > > tho i think all these issues you raised are not new, and is not the reason that caused the flake.
> > > i actually don't think this test is flaky.
> > 
> > 
> > it passed 3/4 times when i was executing it locally. why you don't think that this test is flaky?
> 
> to me that sounds like 3/4 times a node is expected to produce 2 proposals a layer, but only produced 1.

i mean 1/4 time

**Comment by dshulyak** [comment]
> i mean 1/4 time

in all failures that I've seen proposal is not published at layer 15. there are also checks at earlier layers, from 6 to 9, from 9 to 12.. so i would expect it to fail at least once that way in all attempts.

**Comment by countvonzero** [comment]
let me run this test locally from develop a few times.
