### ISSUE TITLE
crypto unit tests

### ISSUE THREAD

**Issue by avive** [spacemeshos/go-spacemesh#31]
Feature request template

#### Feature description
All functions in https://github.com/spacemeshos/go-spacemesh/tree/master/crypto should have unit tests.

#### Reasons for adding this feature
You can never have enough tests.

**Comment by vorsprung** [comment]
scrypto done, see https://github.com/spacemeshos/go-spacemesh/pull/61

**Comment by avive** [comment]
@vorsprung - keep these good tests coming! I think we are getting decent coverage for this package now thanks to your work.

**Comment by jamesandrews-iopp** [comment]
Glad to be of service!  Gonna drop off for a few days though, I have a meetup tonight (Bristol Devops) and job interviews to prep for

**Comment by avive** [comment]
Good luck!

**Comment by vorsprung** [comment]
Back again.  Added randg_test.go ( PR #92 ), Travis didn't like the overall effect.  Won't fix stuff outside of crypto tests ( which seemed to work in Travis).  API and p2p are blowing up

Notice that "findnode.go:131:15: undefined: "github.com/spacemeshos/go-spacemesh/crypto".MinInt32" so probably something will be changing in crypto soon anyway.

Will check in some time this week and take another look.  Next target probably getting keys_test.go nearer 100%

**Comment by avive** [comment]
Looking at the develop branch - we have pretty good coverage - we should add a bit more tests to keys.go

**Comment by avive** [comment]
I'm closing this as I think we are at a good place regarding coverage. Please reopen if you feel like adding additional tests.
