### ISSUE TITLE
atomic.panicUnaligned() when compiled for raspberry pi

### ISSUE THREAD

**Issue by willemsFEB** [spacemeshos/go-spacemesh#3107]
## Description
Hi, even though raspberry pi is currently not 100% supported, I tried to run it anyway by manually compiling gpu-post for raspberry pi and using that one instead of the precompiled one.

All works fine, however when trying to smesh, go-spacemesh crashes with the following error:

```
goroutine 432 [running]:
runtime/internal/atomic.panicUnaligned()
	/usr/local/go/src/runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Load64(0x3c20adc)
	/usr/local/go/src/runtime/internal/atomic/atomic_arm.s:286 +0x14
github.com/spacemeshos/post/initialization.(*Initializer).SessionNumLabelsWritten(...)
	/home/pi/go/pkg/mod/github.com/spacemeshos/post@v0.0.0-20211014030409-e1a8091bb648/initialization/initialization.go:181
github.com/spacemeshos/go-spacemesh/activation.(*PostSetupManager).Status(0x3b40060)
	/home/pi/Programs/spacemesh/go-spacemesh/activation/post.go:142 +0x78
github.com/spacemeshos/go-spacemesh/activation.(*Builder).StartSmeshing.func1(0x39344b0, 0x383e140, {0xff0f90, 0x3991020}, 0x383e180)
	/home/pi/Programs/spacemesh/go-spacemesh/activation/activation.go:244 +0x130
created by github.com/spacemeshos/go-spacemesh/activation.(*Builder).StartSmeshing
	/home/pi/Programs/spacemesh/go-spacemesh/activation/activation.go:234 +0x244
```

As raspberry pi is currently not supported, I dont expect this bug to get resolved soon, but I just wanted to already make you aware of it.

## Steps to reproduce
1. start go-spacemesh
2. start smrepl
3. inside smrepl: execute `post setup`
4. after setting up post, go-spacemesh crashes

## Actual Behavior
go-spacemesh crashes when starting to smesh

## Expected Behavior
go-spacemesh smeshes

## Environment
Please complete the following information:
 - OS: Raspbian 32bit
 - Node Version:  v0.0.0-unreleased+e311ff3fb2295bbd4d92923c7c73fe0841595bf6
 - Smapp version (if applicable): not applicable

**Comment by nkryuchkov** [comment]
@willemsFEB Hi, thank you for reporting!
