### ISSUE TITLE
beacon, sync: ReportBeaconFromBallot should account for a number of eligibilities in the ballot

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#3118]
this got missed when eligibilities were merged.
weight and number of ballots for all purposes of the beacon sync should be multiplied by the number of eligibilities.

**Comment by countvonzero** [comment]
specifically beacon should be reported with weight multiplied by the number of eligibilities here 
https://github.com/spacemeshos/go-spacemesh/blob/5e3afd74acc428a76d8bf23128d9248c7c756c75/proposals/eligibility_validator.go#L140

**Comment by kanghua309** [comment]
please explain why “beacon should be reported with weight multiplied by the number of eligibilities here” ？

**Comment by kanghua309** [comment]
**fix like below is allright？**

layerWeight := weight * uint64(len(ballot.EligibilityProofs)) / uint64(numEligibleSlots)
v.beacons.ReportBeaconFromBallot(epoch, ballot.ID(), beacon, layerWeight)

**Comment by countvonzero** [comment]
the change should have been part of https://github.com/spacemeshos/go-spacemesh/pull/3085
it basically merge multiple proposals in the same layer into one proposal. so i literally mean

:s/weight/weight * len(ballot.EligibilityProofs)/

**Comment by kanghua309** [comment]
I wonder --  weight is atx weight during a epoch , and miner can take proposals cross multi layer( same layer only one proposal) , ReportBeaconFromBallot need record ballot weigh in the layer(ballot belong to), so need to use layerWeight instead of atx weight !    ——  What do I understand wrong ? please tell me .

**Comment by countvonzero** [comment]
you are right that we need to record ballot weight. ballot weight is miner's `ATX weight / number of eligibility in epoch`.
your question prompts me to think deeper and realize current implementation is not right to begin with. thanks.
i am closing this bug in favor of https://github.com/spacemeshos/go-spacemesh/issues/3174
