### ISSUE TITLE
hare, proposals: don't vote for proposals with missing transactions

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#3139]
if a proposal with the transaction that is not available to any node gets into hare output it will halt the network. since we don't plan to prune transactions the simplest solution is to change this https://github.com/spacemeshos/go-spacemesh/blob/develop/layerfetcher/layers.go#L674-L688 method so that it will fail even if single transaction is not found.

**Comment by kanghua309** [comment]
if only need return “err” instead of “continue” in method GetTxs in file layers？
