### ISSUE TITLE
sync: data sync keeps going while validation stuck

### ISSUE THREAD

**Issue by countvonzero** [spacemeshos/go-spacemesh#3164]
## Description

at the beginning of every epoch, there is a period of time when beacon is unavailable (until enough ballots are seen by the node and beacon value determined)
during this time, syncer will see that beacon is not available and will not request tortoise to verify a layer.

but the problem is: syncer uses two goroutines
goroutine 0: sync data from processedLayer (say 100) -> currentLayer-1 (say 10_000)
goroutine 1: request tortoise to verify layer

say at the beginning of epoch 3 (layer 120) the above beacon check stops goroutine1 but not goroutine0. so syncer will end up syncing data all the way from 120 -> 10_000 (while verified layer get stuck at 119) for goroutine0 to exit, and allow the next syncer run to proceed.

this is wildly inefficient.

## Steps to reproduce
1. starts a new node and one can see log message from syncer `skip validating layer: beacon not available`

## Actual Behavior

see above

## Expected Behavior

verifying a layer should be able to progress after the beacon value is available for that epoch.

**Comment by kanghua309** [comment]
"wildly inefficient"  refer to sync duplicated layer content ？

********** below logic ？****** 
for layerID := s.mesh.ProcessedLayer().Add(1); layerID.Before(s.ticker.GetCurrentLayer()); layerID = layerID.Add(1) { 	
     if layerID.After(lastSynced) { 		
          lastSynced = layerID 		
          if err := s.syncLayer(ctx, layerID); err != nil { 	
		return false 		} 	
    } 	
    vQueue <- layerID 	logger.With().Debug("finished data sync", layerID) 
}

**Comment by countvonzero** [comment]
> "wildly inefficient" refer to sync duplicated layer content?

it means we need to wait for all layer data to be synced (120 -> 10_000) before we have a chance to retry verifying a layer that gets stuck earlier (120) due to lack of beacon, since beacon should be available after a few more layers are synced for each epoch.
