### ISSUE TITLE
beacon sync: threshold for accepting beacon for epoch is incorrect

### ISSUE THREAD

**Issue by countvonzero** [spacemeshos/go-spacemesh#3174]
## Description

from Tal
I think the abstract protocol should be:
- Look at the last cluster of layers (a cluster is the smallest number of consecutive layers for which the expected number of weight units (in ballots) is at least 800; if we have expected 50 weight units per layer, then a cluster is 16 layers).
- For each ballot in the cluster, determine which beacon it supports, and add its weight to that beacon value
- Take the majority value (if there's no majority, use the plurality value, but in this case there should be a strong warning to the user)

The ballot weight is the associated ATX weight divided by the number of ballot slots this ATX committed to (there's a lower bound on the number of slots --- which depends on how much weight is 'visible' to the ATX ---  but not an upper bound).
Because we're sampling, we can't just take the entire ATX weight (otherwise, a "whale" ATX would dominate the voting).
Unless we support miners changing beacons mid-epoch (we talked about doing this to allow faster network rejoins), the way to decide which beacon a ballot supports is to take it from the first ballot from the same id in that epoch.

for more detailed discussion see
https://spacemesh.slack.com/archives/CG91F13C7/p1649770485044299

## Actual Behavior

- absolute number of ballot is used for the threshold, instead of weight unit.
- ballot's number of eligibility is not counted correctly
- ATX weight is used instead of ballot weight

## Expected Behavior

see above

**Comment by kanghua309** [comment]
https://spacemesh.slack.com/archives/CG91F13C7/p1649770485044299 not allow to access！

**Comment by countvonzero** [comment]
the slack link is internal. sorry. but the issue description captures everything needed to fix this bug. thanks
