### ISSUE TITLE
hare: save certificate on completion

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#3199]
- [x] 1. fix https://github.com/spacemeshos/go-spacemesh/issues/2942
completed in #3449 
- [x] 2. persist certificate
completed in #3449 

below moved to https://github.com/spacemeshos/go-spacemesh/issues/3588 for separate tracking
- [ ] 3. evict it after hdist layers
https://github.com/spacemeshos/go-spacemesh/issues/3199#issuecomment-1221321627

it will be used by peers that want to download recent hare output

**Comment by jonZlotnik** [comment]
completed in https://github.com/spacemeshos/go-spacemesh/pull/3449

**Comment by jonZlotnik** [comment]
#3449

**Comment by jonZlotnik** [comment]
completed in #3449

**Comment by countvonzero** [comment]
@jonZlotnik 
i dont understand why you keep closing this issue when its not closed. the PR explicitly said it is partly done. the eviction is not done yet, and its pending verifying/changing the tortoise code.

**Comment by jonZlotnik** [comment]
got too excited when #3449  merged 🤦
I thought this issue just failed to close automatically.

**Comment by countvonzero** [comment]
moved the 3rd item to https://github.com/spacemeshos/go-spacemesh/issues/3588
and closing this one.
