### ISSUE TITLE
sync: hare output should be saved only if peer can provide a certificate for it

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#3200]
after: https://github.com/spacemeshos/go-spacemesh/issues/2942, https://github.com/spacemeshos/go-spacemesh/issues/3199

1. download certificate for the layer within hdist
2. validate it using eligibility oracle from hare module
3. save hare output and certificate only if validation passes

this is important for safety, otherwise it will be trivial to force a new node to vote in the specific way.

**Comment by jonZlotnik** [comment]
@countvonzero , we still `SetHareOutput` (without cert) in `ProcessLayerPerHareOutput` whether or not a cert is available. https://github.com/spacemeshos/go-spacemesh/blob/a5269257c54ee59fc082f37b9b2ee2f6431d1a33/mesh/mesh.go#L607

Will this change when you update the tortoise behaviour?

**Comment by countvonzero** [comment]
> @countvonzero , we still `SetHareOutput` (without cert) in `ProcessLayerPerHareOutput` whether or not a cert is available.
> 
> https://github.com/spacemeshos/go-spacemesh/blob/a5269257c54ee59fc082f37b9b2ee2f6431d1a33/mesh/mesh.go#L607
> 
> Will this change when you update the tortoise behaviour?

no. this part of the behavior won't change. 

for tortoise, i need to make sure tortoise uses the cert between [current-hdist, current). 
if my memory serve, currently tortoise is using [latest-hdist, latest) and when syncing, latest != current. before then, i cannot safely prune certificates.
