### ISSUE TITLE
Spacemesh API

### ISSUE THREAD

**Issue by zalmen** [spacemeshos/go-spacemesh#321]
The purpose of the Spacemesh API is to allow external parties to query the state of the blockmesh in general and the state of each account in specific. This API should be unified and be supported by both local nodes and remote (web) nodes.

Few examples of such parties are - 
1. Wallet app - can query account's states and publish signed transactions.
2. Block explorer - can query mesh state (e.g. last irreversible layer)
3. Smart contract - query both mesh state and account states based on the contract's logic

Current APIs that we have in mind (WIP - full detailed list will eventually be specified in SM's wiki) - 
// Returns the API version
Version() string

// Returns false if mesh is not yet ready for queries e.g it is still syncing
IsReady() boolean

// Returns the current mesh layer info
GetLatestLayerNumber() number

// Returns the latest irreversible mesh layer number
GetLatestIrreversibleLayerNumber() number

// Gets an account balance
GetBalance(account: string, layer: ILayer) BigNumber

// Get the transactions count for this account. e.g. account nonce
GetTransactionsCount(account: string, layer: ILayer) number

// send a signed transaction, returns tx hash
SendSignedTransaction(tx:ITransaction) TransactionResult

// Gets a transaction from the blockmesh (Tx will include layer number and whether it is reversible or not)
GetTransaction(txHash: string) TransactionResult

// Subscribe a callback to recieve tx status changes
SubscribeToTxStatus(txHash: string, callback: (TransactionStatus) => void ) boolean
UnsubscribeFromTxStatus(txHash: string) boolean

// Subsribe to get called back when a transaction for the user is on the mesh
SubscribeToIncomingTxs(account: string, callback: (TransactionStatus) => void ) boolean

// Unbsuscribe from incoming transactions for the user
UnsubscribeFromIncomingTxs(account: string) boolean

**Comment by avive** [comment]
no longer relevant as of 0.2
