### ISSUE TITLE
`TestPostSetupManager` is flaky

### ISSUE THREAD

**Issue by noamnelke** [spacemeshos/go-spacemesh#3217]
## Description
`TestPostSetupManager` is flaky.

## Steps to reproduce
Run `make test` on a fresh clone of the repo.

## Actual Behavior
@jonZlotnik reported getting the following failure:
```
--- FAIL: TestPostSetupManager (0.58s)
    post_test.go:56: 
                Error Trace:    post_test.go:56
                                                        asm_amd64.s:1581
                Error:          Not equal: 
                                expected: &activation.PostSetupStatus{State:2, NumLabelsWritten:0x800, LastOpts:(*activation.PostSetupOpts)(0xc00047bc50), LastError:error(nil)}
                                actual  : &activation.PostSetupStatus{State:3, NumLabelsWritten:0x800, LastOpts:(*activation.PostSetupOpts)(0xc00047bc50), LastError:error(nil)}
                            
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1,3 +1,3 @@
                                 (*activation.PostSetupStatus)({
                                - State: (activation.postSetupState) 2,
                                + State: (activation.postSetupState) 3,
                                  NumLabelsWritten: (uint64) 2048,
                Test:           TestPostSetupManager
FAIL
FAIL    github.com/spacemeshos/go-spacemesh/activation  24.039s
```

## Expected Behavior
Tests on `develop` should always pass.

## Environment
N/A

## Additional Resources 
From a quick glance at the test, this can possibly be explained by a timing issue (where a second event gets placed in the status channel before the first one is handled). I believe this can be fixed by only performing this check on line 56 if `len(mgr.StatusChan())==0`. Before doing that we should try to consistently reproduce and then ensure that this fixes it. There’s also a potential race here - if we check this, nothing guarantees that it doesn’t change between the check and the following assertion. This can be fixed by first querying the value and then performing the length check (so in the worst case we skip a validation we could perform).

**Comment by poszu** [comment]
This should be fixed now. Please reopen if it fails again.
