### ISSUE TITLE
Tweak SmesherService API

### ISSUE THREAD

**Issue by brusherru** [spacemeshos/go-spacemesh#3222]
## Rationale
We need to implement some APIs to make it possible to show all interesting information to our smeshers.
Check out the issue: https://github.com/spacemeshos/smapp/issues/912

## Required API endpoints

**SmesherService.EstimatedRewards**
- Exists in API: https://github.com/spacemeshos/api/blob/master/proto/spacemesh/v1/smesher.proto#L39
- But not implemented in go-spacemesh: https://github.com/spacemeshos/go-spacemesh/blob/ffc0c927d0d3e96dce55597cba2da8a54bcfc4e6/api/grpcserver/smesher_service.go#L154
- In addition to it, probably we'd like to have time estimation (layer number), and also query estimation of rewards for the ongoing epoch. Or probably this endpoint should accept a layer/epoch number as an argument and return the estimation. We need to discuss it.

**SmesherService.SmeshingStatus**
I think we also need a stream or only stream that sends the latest state to new subscribers before sending the next updates.

- It does not exist. Most likely we need to have a discussion about it.

- This is some kind of extended version of `IsSmeshing`, it tells API consumers what really happens under the hood:
   - Not smeshing
   - Creating PoS data
   - Waiting for PoET
   - GeneratingPoST
   - Eligible for rewards
   - Publishing ballot
   - doing something else
   - Not eligible: error

- We should pay attention, that some of these statuses make sense for the upcoming epoch.
   E.G. we're waiting for PoET for the next layer, but we're already eligible in this epoch and even publishing ballots from time to time.
   So probably it should return statuses for current and next epochs separately.

---

Please, share your ideas and thoughts, maybe you know how to solve the problem better and simpler.
cc: @noam, @moshababo, @countvonzero, @dshulyak, @oriya, @avive

**Comment by oriya** [comment]
🙏🏻

**Comment by abergasov** [comment]
SmesherService.SmeshingStatus endpoint will be done in separate issue 
https://github.com/spacemeshos/go-spacemesh/issues/3281
