### ISSUE TITLE
vm, mempool: nonces implementation

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#3273]

**Comment by dshulyak** [comment]
@countvonzero @pigmej up to you if to use this task or close it completely, there should be a task from @lrettig somewhere

**Comment by pigmej** [comment]
@dshulyak there is https://github.com/spacemeshos/pm/issues/150 from Research. I think we should close this one and create one(s) based on that https://github.com/spacemeshos/pm/issues/150.
