### ISSUE TITLE
node restart fails on committing genesis state

### ISSUE THREAD

**Issue by countvonzero** [spacemeshos/go-spacemesh#3303]
## Description

when the node aborted before it records the latest layer (but already generated the genesis accounts), upon restarts it will try to create genesis account again and fail as below. we need to find a better signal for whether to regenerate the genesis account.

```
{"L":"FATAL","T":"2022-06-28T19:13:00.129+0300","N":"00000.defaultLogger","M":"Failed to run the node. See logs for details.","errmsg":"start node: cannot start services: setup genesis: cannot commit genesis state: failed to insert account [255 8 60 154 34 224 93 52 89 176 63 61 190 214 28 122 214 224 162 9] for layer 119: database: object exists","name":""}
```

**Comment by brusherru** [comment]
Am I understood right that every Node that made a pause in syncing process will get such error (fatal and user have to delete db and resync from scratch)? 🤔
Sounds like a super critical bug

**Comment by countvonzero** [comment]
> Am I understood right that every Node that made a pause in syncing process will get such error (fatal and user have to delete db and resync from scratch)? thinking Sounds like a super critical bug

you don't get this error every time the node restarts. tho there may be other errors and we need better testing there.

specifically to this error, the first abort has to happen in a specific window. e.g. when node fails the initialization or is aborted manually during this window. and when this happens, the database does not have any data other than those genesis accounts. that's why i determine this to be not too critical.

**Comment by lrettig** [comment]
In general it shouldn't be possible for the node to get into a state with a corrupted DB (such that, e.g., the user has to delete the DB entirely) unless something really crazy happens like the power goes out when it's trying to write the file. We need to wrap operations like this into some sort of transaction that can be rolled back. @countvonzero does this make sense?

**Comment by countvonzero** [comment]
> In general it shouldn't be possible for the node to get into a state with a corrupted DB (such that, e.g., the user has to delete the DB entirely) unless something really crazy happens like the power goes out when it's trying to write the file. We need to wrap operations like this into some sort of transaction that can be rolled back. @countvonzero does this make sense?

it make sense in general, and we already do this with sqlite db transaction whenever we can. 

in this particular case, the db write was NOT interrupted. it was successful and went on to do other initialization stuff and failed there. at the time of failure, all db has is the set of genesis account.

when the node restarts, it sees that there is no mesh data, so it thought it should save those genesis account again, and then crashed again. 

what needs to be fixed is a better signal to determine whether the node is starting from scratch or restoring from db.
current logic is to use whether the mesh's latest layer is set.

one potential approach is to write a status file to datadir to indicate whether we've initialize the genesis accounts. but that's a micro-view on this issue. i think this should be considered as part of the graceful shutdown issue.
