### ISSUE TITLE
mesh: inconsistent data in db

### ISSUE THREAD

**Issue by countvonzero** [spacemeshos/go-spacemesh#3311]
reported by @brusherru 

node is stuck with the following log.
```
{"L":"INFO","T":"2022-06-30T17:50:00.413+0300","N":"eb074.sync         ","M":"processing synced layers","node_id":"eb074e3c8588fd378111ef54332be8a3d0fa76c073aab0eff5f426f9e73d2804","module":"sync","in_state":"10745","last_synced":"10839","name":"sync"}
{"L":"INFO","T":"2022-06-30T17:50:00.413+0300","N":"eb074.mesh         ","M":"processing layer","node_id":"eb074e3c8588fd378111ef54332be8a3d0fa76c073aab0eff5f426f9e73d2804","module":"mesh","layer_id":10746}
{"L":"INFO","T":"2022-06-30T17:50:00.413+0300","N":"eb074.trtl         ","M":"on layer terminated","node_id":"eb074e3c8588fd378111ef54332be8a3d0fa76c073aab0eff5f426f9e73d2804","module":"trtl","layer_id":10746,"name":"trtl"}
{"L":"INFO","T":"2022-06-30T17:50:00.415+0300","N":"eb074.mesh         ","M":"tortoise results","node_id":"eb074e3c8588fd378111ef54332be8a3d0fa76c073aab0eff5f426f9e73d2804","module":"mesh","layer_id":10746,"verified":10783,"name":"mesh"}
{"L":"INFO","T":"2022-06-30T17:50:00.415+0300","N":"eb074.mesh         ","M":"trying to set processed layer to an older layer","node_id":"eb074e3c8588fd378111ef54332be8a3d0fa76c073aab0eff5f426f9e73d2804","module":"mesh","processed":10784,"layer_id":10746,"name":"mesh"}
{"L":"INFO","T":"2022-06-30T17:50:00.415+0300","N":"eb074.mesh         ","M":"pushing layers to state","node_id":"eb074e3c8588fd378111ef54332be8a3d0fa76c073aab0eff5f426f9e73d2804","module":"mesh","from_layer":"10746","to_layer":"10784"}
{"L":"INFO","T":"2022-06-30T17:50:00.415+0300","N":"eb074.conState     ","M":"applying layer to conservative state","node_id":"eb074e3c8588fd378111ef54332be8a3d0fa76c073aab0eff5f426f9e73d2804","module":"conState","layer_id":10746,"block_id":"091c0b752c"}
{"L":"ERROR","T":"2022-06-30T17:50:00.416+0300","N":"eb074.conState     ","M":"layer not applied in order","node_id":"eb074e3c8588fd378111ef54332be8a3d0fa76c073aab0eff5f426f9e73d2804","module":"conState","expected":"10745","to_apply":"10746","name":"conState"}
{"L":"ERROR","T":"2022-06-30T17:50:00.416+0300","N":"eb074.mesh         ","M":"failed to apply transactions","node_id":"eb074e3c8588fd378111ef54332be8a3d0fa76c073aab0eff5f426f9e73d2804","module":"mesh","layer_id":10746,"num_failed_txs":0,"errmsg":"layers not applied in order","name":"mesh"}
{"L":"ERROR","T":"2022-06-30T17:50:00.417+0300","N":"eb074.mesh         ","M":"failed to push layers to state","node_id":"eb074e3c8588fd378111ef54332be8a3d0fa76c073aab0eff5f426f9e73d2804","module":"mesh","layer_id":10746,"errmsg":"failed to update state 10746: apply layer: layers not applied in order","name":"mesh"}
{"L":"WARN","T":"2022-06-30T17:50:00.417+0300","N":"eb074.sync         ","M":"mesh failed to process layer from sync","node_id":"eb074e3c8588fd378111ef54332be8a3d0fa76c073aab0eff5f426f9e73d2804","module":"sync","errmsg":"failed to update state 10746: apply layer: layers not applied in order","name":"sync"}
```

there are two components at play here:
- syncer: thinks the latest layer applied in state is `10745` (from table `mesh_status`). so it trigger `mesh.ProcessLayer(10746)`
- conservative cache: thinks the latest applied in state is `10744` (from table `layers`), so it rejects to apply layer for `10746`.

the code in mesh.go was not written in such a way that guarantees database integrity. specifically here
https://github.com/spacemeshos/go-spacemesh/blob/ff1a96c97412c0fdcf2bf1954dca6346019ae0d6/mesh/mesh.go#L629
```
if err := layers.SetApplied(msh.cdb, layerID, applied); err != nil {
		return fmt.Errorf("set applied for %v/%v: %w", layerID, applied, err)
}

if err := msh.setLatestLayerInState(layerID); err != nil {
		return err
}
```
it first updates the `layers` table, then updates the `mesh_status` table without using a db transaction to guarantee atomicity.

the situation is similar with the revert flow.
https://github.com/spacemeshos/go-spacemesh/blob/ff1a96c97412c0fdcf2bf1954dca6346019ae0d6/mesh/mesh.go#L320

my guess is that the code is interrupted when a revert took place. as `mesh_status` table had the higher layer as applied than the `layers` table. unfortunately, my theory cannot be confirmed as the earlier log isn't available.

in any case, mesh.go needs to be reworked such that db updates are atomic.

**Comment by dshulyak** [comment]
don't you think that it would be more robust if latest applied layer was queried from layers where applied block is not null? 
the same logic can be applied to processed and latest

i really don't see any good argument to have mesh_status table

**Comment by countvonzero** [comment]
> don't you think that it would be more robust if latest applied layer was queried from layers where applied block is not null? the same logic can be applied to processed and latest
> 
> i really don't see any good argument to have mesh_status table

field applied_block is added later and that does take away argument from mesh_status.
one can derive latest (max layer)/applied (applied_block not null) from table `layers`, 
but how do you derive processed layer? adding another processed bool into table `layers`. @dshulyak 

however, there are some other stuff in mesh.go that need to be atomic. for example, processed layer/hash/aggregated hash.

**Comment by countvonzero** [comment]
here is what i am planning to do: @dshulyak 
- remove mesh_status table
- get last layer from max(ballots.layer, blocks.layer) or maybe just max(ballots.layer)
- get applied layer from max(layers.id) where applied_block not null
- save hash/aggregated hash in the same sql stmt and get processed layer from max(layers.id) where hash not null.
