### ISSUE TITLE
Genesis address format

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#3315]
See https://github.com/spacemeshos/pm/issues/140

- [x] choose and import a bech32 implementation (see [this list](https://github.com/spacemeshos/pm/issues/106#issuecomment-1171613630)) (chosen github.com/cosmos/btcutil)
- [x] use this to write a simple address parser (string -> `Address`) with error-handling code for wrong format, too long, bad HRP, etc. (this should probably be published as a separate library so it can be used elsewhere)
- [x] change `Address` type to `[24]byte` (i.e., change `AddressLength`)
- [x] update API code to receive address as string and parse it
  - [x] go-spacemesh (https://github.com/spacemeshos/go-spacemesh/pull/3336)
  - [x] API (https://github.com/spacemeshos/api/pull/173)
- [x] update addresses in genesis account config and tests
- [x] register HRPs (mainnet, testnet) in [SLIP-0713](https://github.com/satoshilabs/slips/blob/master/slip-0173.md)
  - [x] wait pr to be merged https://github.com/satoshilabs/slips/pull/1386

**Comment by abergasov** [comment]
check, does checksum of address inside bech32
if not - good idea to add it

**Comment by lrettig** [comment]
@abergasov not sure what you mean - bech32 does include a checksum

**Comment by lrettig** [comment]
added a task to register our HRPs in the global SLIP list: `sm` and `stest`

**Comment by lrettig** [comment]
@abergasov this task appears not to be done:
register HRPs (mainnet, testnet) in [SLIP-0713](https://github.com/satoshilabs/slips/blob/master/slip-0173.md)
