### ISSUE TITLE
tortoise: may have an incorrect verified layer at startup

### ISSUE THREAD

**Issue by countvonzero** [spacemeshos/go-spacemesh#3318]
## Description
https://github.com/spacemeshos/go-spacemesh/blob/036035099f8a4aa8801096587b3f8864f4c4b6f3/cmd/node/node.go#L498

this is the last layer with an applied block, and may not have been the last verified layer from tortoise.

**Comment by dshulyak** [comment]
That code is going to be removed in the changes for https://github.com/spacemeshos/go-spacemesh/issues/3573. Closing this
