### ISSUE TITLE
Hare: oracle explicitly depends on hare round number

### ISSUE THREAD

**Issue by jonZlotnik** [spacemeshos/go-spacemesh#3335]
## Description

The Oracle explicitly depends on "k". In the code, this is the total number of rounds since the pre-round.
We should rename this parameter to be some other kind of identifier such that the oracle can be used to prove eligibility for things other than hare rounds. Termination certification, for example, requires oracle-chosen committee members.

Relates to: https://github.com/spacemeshos/go-spacemesh/issues/3283

## Affected code

This issue appears in commit hash: 

Related files (optionally with line numbers): 

dependency call stack:

https://github.com/spacemeshos/go-spacemesh/blob/aa7ac8467c7e86164b1fad2c3facaeac33385f6a/hare/interfaces.go#L17-L22

Note, there aren't actually any named parameters in the interface above. Very difficult to understand what all the params are for.
Implementations of the interface above depend on:

https://github.com/spacemeshos/go-spacemesh/blob/aa7ac8467c7e86164b1fad2c3facaeac33385f6a/hare/eligibility/oracle.go#L159

https://github.com/spacemeshos/go-spacemesh/blob/cd169eaaa8935094e11aa79884a38900951294b9/hare/eligibility/oracle.go#L136

**Comment by countvonzero** [comment]
termination certification, aka block certificate, also uses round number (CertifyRound)
