### ISSUE TITLE
database: SQLITE_BUSY

### ISSUE THREAD

**Issue by countvonzero** [spacemeshos/go-spacemesh#3364]
running longevity test `make run test_name=TestScheduleBasic size=10 bootstrap=1m keep=true namespace=long` on my local machine with 512GB SSD. it failed after 70mins with the following error

```
2022-07-15 12:26:01	
{"L":"WARN","T":"2022-07-15T15:26:01.695-0400","N":"b4fbe.txHandler    ","M":"failed to handle tx","node_id":"b4fbe634f6177343d23c7c6d3b1b56b4ef14f2862e16c309960c0aa58828ce30","module":"txHandler","requestId":"5350a686-7414-4136-a77e-81e802969739","errmsg":"insert 0x699a2762edcab73902874e4570cd6e0f87bc0794e97185ac79fd0edf5a969251: step 0: sqlite.Stmt.Step: SQLITE_BUSY: database is locked (\n\t\tinsert into transactions (id, tx, header, layer, block, principal, nonce, timestamp, applied)\n\t\tvalues (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)\n\t\ton conflict(id) do update set \n\t\theader=?3, principal=?6, nonce=?7 \n\t\twhere header is null;)","name":"txHandler"}
```

**Comment by dshulyak** [comment]
i looked into similar issue some time ago https://github.com/spacemeshos/go-spacemesh/issues/3330

it was definitely due to slow disk on gke. all smeshers were failing at the same time when they reached certain iops. maybe it is not as severe as on gke, but still not fast enough in your case

**Comment by dshulyak** [comment]
please reopen if you think that we need it to be opened. i don't know what we should do with it in such state
