### ISSUE TITLE
Update node config to turn off optimistic filtering on currently working network

### ISSUE THREAD

**Issue by brusherru** [spacemeshos/go-spacemesh#3385]
## Description
We have an already filed issue in the go-spacemesh #3384
Meanwhile, @countvonzero said that it is possible to update the node config in the way to turn off this buggy new feature, and then the current network should continue working well.

## Acceptance criteria
- [ ] New node config fixes the problem, node syncing well
- [ ] New node config uploaded to the cloud (GCS)
- [ ] [Discovery service](https://discover.spacemesh.io/networks.json) points out on the new node config

**Comment by countvonzero** [comment]
this issue should be closed. turned out the config update is straightforward than i reported.
