### ISSUE TITLE
systest: allow multiple poet servers

### ISSUE THREAD

**Issue by countvonzero** [spacemeshos/go-spacemesh#3387]
## Description

longevity tests only has 1 poet server. with 50 nodes, TestScheduleBasic will inevitably fail within 5-6 hrs of running. 
this makes reproducing bugs time-consuming.

having multiple poet servers should allow longevity test to run longer

**Comment by dshulyak** [comment]
> with 50 nodes, TestScheduleBasic will inevitably fail within 5-6 hrs of running.
this makes reproducing bugs time-consuming.

why does it fail? thats a critical bug in the poet if it can run only for 5-6 hrs

**Comment by countvonzero** [comment]
> > with 50 nodes, TestScheduleBasic will inevitably fail within 5-6 hrs of running.
> > this makes reproducing bugs time-consuming.
> 
> why does it fail? thats a critical bug in the poet if it can run only for 5-6 hrs

it fails with the following log. tho i never checked poet log itself. will file another issue to track this.
```
L | "ERROR"
M | "failed to build NIPost: builder: poet service is unstable: failed to submit challenge to poet service: perform request: Post \"http://poet:80/v1/submit\": context deadline exceeded"
N | "fe6cb.atxBuilder   "
T | "2022-07-27T19:58:17.199-0400"
module | "atxBuilder"
node_id | "fe6cb573fa586a6535ed26a77dad1ac684549abe78df6dda0ffe240cf9e66a4a"
ts | 2022-07-27T23:58:17.199Z
tsNs | 1658966297199926835
```
