### ISSUE TITLE
Document use of different weight types

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#3393]
We have two distinct, competing types for weight.

RatNum, used to store rewards in blocks:

https://github.com/spacemeshos/go-spacemesh/blob/0a6e5094a765b3361dc8c51ca1d56061d74b40e0/common/types/block.go#L57-L66

and `big.Rat`:

https://github.com/spacemeshos/go-spacemesh/blob/0a6e5094a765b3361dc8c51ca1d56061d74b40e0/common/util/weight.go#L27-L30

Is there a reason we need to maintain this distinction? Can we harmonize around one of these types?

**Comment by countvonzero** [comment]
`big.Rat` is for internal calculation and is golang specific. it's used to do math.

`RatNum` is the representation of a rational number, and is language independent. 
another client implementation can translate RatNum to its own type for rational number to do the math on weight.

we had discussed this in one of the dev calls a couple months back. this was the conclusion.

**Comment by lrettig** [comment]
Thanks for clarifying. At the very least, this should be explained in
comments in the code to prevent further confusion :)

**Comment by lrettig** [comment]
Relabeling with documentation tag to make sure this gets documented :)
