### ISSUE TITLE
Replace float64 with fixed point arithmetic

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#3408]
We're already using fixed-point arithmetic in hare, see hare/eligibility/oracle.go.

The only place I'm aware of this being an issue today is rewards:

https://github.com/spacemeshos/go-spacemesh/blob/5234b07a2bff387ee83d3f5d7ef4ec66713333d3/genvm/rewards.go#L67-L75

But this code will be replaced anyway as part of https://github.com/spacemeshos/pm/issues/151.

There's nothing wrong with rounding down to the nearest smidge, but without fixed-point arithmetic we cannot be sure that precisely the same operation will happen regardless of platform, architecture, etc.

Double-check that we're not doing this anywhere else.

**Comment by dshulyak** [comment]
The concern here is what happens inside Float64 conversion. Not because of the casting to uint64.
But right this is probably an issue because of `f = math.Ldexp(float64(mantissa), exp-Msize1)`.

Before swapping libraries consider using Num/Denom from Rat number and simply round down the integer division.

**Comment by lrettig** [comment]
> consider using Num/Denom from Rat number and simply round down the integer division

Don't understand, could you elaborate?

**Comment by dshulyak** [comment]
rational number (big.Rat) internal state is two integers (numerator/denominator). when Float64 is called they are divided and floating part is kept. instead we can divide them ourselfs and round down.

**Comment by lrettig** [comment]
One option here is to switch to the library I'm using in github.com/spacemesh/economics: https://github.com/ericlagergren/decimal. It allows you to [convert directly to uint64](https://pkg.go.dev/github.com/ericlagergren/decimal#Big.Uint64), bypassing float entirely. And since it's used in the economics library, it's already in our "trusted codebase."
