### ISSUE TITLE
activation: resumes building atxs after poet servers recover 

### ISSUE THREAD

**Issue by countvonzero** [spacemeshos/go-spacemesh#3441]
## Description

part of https://github.com/spacemeshos/go-spacemesh/issues/3381

the network needs to resume building ATXs after network recover from poet server failures.

**Comment by countvonzero** [comment]
after further testing, when the network was able to move forward by this PR https://github.com/spacemeshos/go-spacemesh/pull/3439, it turned out that the node cannot resume building ATX.

### problem with positioning ATX
say we failed to build ATXs from epoch 5 -7, and resume building again, we will fetch the positioning ATX from epoch 4, which set the challenge's PubLayerId to somewhere in epoch 5. but epoch 5 had already expired so atx builder gets into an infinite loop. what should we do in this case?

slack convo. https://spacemesh.slack.com/archives/C89QJJY3G/p1660361378432829
still under discussion. will update GH when a solution emerges.

**Comment by dshulyak** [comment]
i believe it works as expected now
