### ISSUE TITLE
atx: register with multiple poet servers

### ISSUE THREAD

**Issue by countvonzero** [spacemeshos/go-spacemesh#3460]
### Motivation
PoET servers are a potential single-point-of-failure. There are many scenarios where PoETs can be attacked and possibly fail. In addition, a single widely used PoET service provides its operators centralized control of the network. If a widely used PoET service is malicious or attacked it can have detrimental effects on the network.

### Mitigation
Allow smeshers to register for multiple PoET services and pick one proof to use in their ATX.

### Design
https://community.spacemesh.io/t/redundant-poet-registration/310/1

**Comment by moshababo** [comment]
Pending design proposal by @noamnelke.

**Comment by poszu** [comment]
> Pending design proposal by @noamnelke.

The design was proposed in https://community.spacemesh.io/t/redundant-poet-registration/310/1

**Comment by selfdual-brain** [comment]
Design effort is tracked in https://github.com/spacemeshos/pm/issues/181

**Comment by countvonzero** [comment]
> Design effort is tracked in [spacemeshos/pm#181](https://github.com/spacemeshos/pm/issues/181)

this seems circular. this issue->research forum->pm issue->research forum. 
why do we need the pm issue here?

**Comment by pigmej** [comment]
@countvonzero, the current idea was to use PM as a placeholder for research work. So PM would have both "epics" and meta containers for Research work.

**Comment by countvonzero** [comment]
> @countvonzero, the current idea was to use PM as a placeholder for research work. So PM would have both "epics" and meta containers for Research work.

so the expected workflow for a given topic T is
A. create research meta on T in PM repo  
B. create research forum thread on T for discussion
C. once B conclude, create epic on T in PM repo
D. create go-spacemesh issues based on epic T 

do i understand correctly?
