### ISSUE TITLE
hashes: SHA256 is old and insecure and our hash abstraction is becoming messy

### ISSUE THREAD

**Issue by jonZlotnik** [spacemeshos/go-spacemesh#3474]
Currently go-spacemesh uses [SHA256](https://github.com/minio/sha256-simd) for every hashing operation. Besides left-over [FNV](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjfxsvUndv5AhVdkYkEHbZ-CW4QFnoECAgQAQ&url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FFowler%25E2%2580%2593Noll%25E2%2580%2593Vo_hash_function&usg=AOvVaw1qx1RKmB00PRmO4bawpA3u) in hare package

There are a few things that need to be considered:

1. SHA256 digests are being reduced to 20bytes (160bit preimage, 80bit collision resistance) and then padded with zeros in order to maintain compatibility with other code. The problem originates here: https://github.com/spacemeshos/go-spacemesh/pull/1635
The following are examples where the 20byte padding is being used.

https://github.com/spacemeshos/go-spacemesh/blob/a58e39b6f6276d5211c6502f29767cf08305e64b/common/types/ballot.go#L266-L269
https://github.com/spacemeshos/go-spacemesh/blob/a58e39b6f6276d5211c6502f29767cf08305e64b/common/types/block.go#L106-L109
https://github.com/spacemeshos/go-spacemesh/blob/a58e39b6f6276d5211c6502f29767cf08305e64b/common/types/proposal.go#L137-L140

A new type `Hash20P32`, (P for padded) or something similar should be created to highlight this extra compatibility logic so as not to confuse those looking to write new code depending on types/hashes.go

2. Less important, but the digest "types" are defined by their byte length instead of bit length. I don't know if that was intentional, but it is confusing. Hash12 -> 96bit, Hash20 -> 160bit, Hash32 -> 256bit

3. SHA256 is old and is susceptible to length extension attack. Bitcoin actually uses double-sha256 because sha3 and blake2 weren't available at the time.

**Comment by lrettig** [comment]
Related: https://github.com/spacemeshos/pm/issues/148

**Comment by dshulyak** [comment]
switched to blake3
