### ISSUE TITLE
systests: TestAddNodes occasionally flaky

### ISSUE THREAD

**Issue by countvonzero** [spacemeshos/go-spacemesh#3479]
## Description

TestAddNodes expected once every nodes participated in making proposals in epoch N, then all nodes should participate in every epoch after N. however, sometimes a node skips producing ATX in an epoch and cannot produce proposals in the following epoch. 

```
    nodes_test.go:105: 
        	Error Trace:	/nodes_test.go:105
        	Error:      	"map[0x10a75b212022136d325bda97157fe3028ec15db90cfc6ad3a8dd9350f5cf4bdb:{} 0x14afb03cf1c7e8e331b042fb6e67fd688c33341223ff2cf964f486ca86b860ec:{} 0x1a673bd54f3f09a3a65e2cc948022125e545dd222f3bd1c242f8da0bad18b980:{} 0x22e0ab5f3eb398b0cc3df0d68c0b3bedfb18acf786d94978c71f0c62fe9806e6:{} 0x2a212dc585a7dff9f69c139dd2706ff19ea1acf61a5a9ab2f14cb63999ec219d:{} 0x346a09a530772c2042f07d20ad2a4fc6e67c74281ab510882c1ae764782cc781:{} 0x3b969e79efa0d874683ea6babf813e5cb44fc1a1c02c978aa0f8a9592003a2eb:{} 0x3ccc7442b028ed63318481a41bf3fe2c181df3d39548c786cd6e580cbdc76acb:{} 0x430659ccf91023c6e3087d9b63064bc2cfb15631f24ede6855baf276b9901060:{} 0x430cb08429249a10e118c3a48acf25f9abfb736ed011c8569dfbfc2c62d594cd:{} 0x47b69f8586fefcb16eafd45dbbfad477c8b0a19bdcda0dd9d7274b0f277e6063:{} 0x51516a97111fd275a47066e879aaafddcf2c6d1ee8074a9ef2ba22e6e874f6fb:{} 0x6b329fdaecdea8c6c80f1ad0e5c8cbad07d0a4a5befd948f37935efd20492bb8:{} 0x6e1b8fc1a315f8a6c0f577cabf80a90bb1cf6e537f9b87c8fc2ff16269143a1a:{} 0x721ac67c3c620dafd17a6e9ef3d5fc8fe1c40711348a4baf856c97e384c323f6:{} 0x7251b852d68a381000efd3593bced3908c544d76b77b1d1f83f73d6a19ac2ea3:{} 0x898c73649a62313686c2bd0decdccae57939861ed16f6956c29483dd6917572d:{} 0x8994adac27ff5b94221d56db215c159b065dd41f4b1aa6ace13875cabf9a4cc2:{} 0x8e174315408b1265b318590de0d44095748fa249af7b781800cc7adf9dcf2ef4:{} 0x96d1ce81406e92082ca9ef9818dcec997e5b1f2e2c39f07b0e6198cb4a82a838:{} 0xaaeddbbb1737a11f0107f3e5dcf3e62abb3cc897d624c02ef9bd781c728557ca:{} 0xb207e21cb7ccb5240ed6836450178e1cfe9353dad30b99a2ab156cbb6dafc1c0:{} 0xb6860bfa1c67704eb71cc309b329588978042a0e1420d35b1a9e18be90460245:{} 0xb98a7110a6e9b81c06276a5c00032e6bfb4d0378b37c3a81e290d3a6236fe7b1:{} 0xbb01641aa199e8f06e5ac3c73e38b5a9538518d0f83d78ecb73fb6cd0b949a8c:{} 0xbef568226a09ba0aa05106f079856e2afae09625d6c3b422ca50f4cc80530803:{} 0xccfe7c73565771563b89bf9328cf112dc8f78cad2549bcc8eff4a810a2364610:{} 0xdfab87ebbdbe92ffc2018ab839cdd762abbeca5cf083e4b519aa0afecdae3703:{} 0xfbb2d9a5561f5b64f8f45e817f38670f78d8de79e7c65d082268deaeaca5a900:{}]" should have 30 item(s), but has 29
        	Test:       	TestAddNodes
        	Messages:   	epoch=7
--- FAIL: TestAddNodes (1214.76s)
FAIL
```

in this particular failure, the smesher node is building ATX in epoch 6. but it got an position ATX in epoch 6 (some other smesher publish early), which push back its publish_epoch to epoch 7. this smesher then skips publishing ATX for epoch 6, and cannot build any proposals in epoch 7.

```
{"L":"INFO","T":"2022-08-24T05:45:46.065-0400","N":"6367a.atxBuilder   ","M":"new atx challenge is ready","node_id":"6367a248803280fa1a85d3cb055c3b85dcad9ca26ed5ef9c7c967e11adea3e9b","module":"atxBuilder","target_epoch":"7","current_epoch":"6","name":"atxBuilder"}
```

**Comment by dshulyak** [comment]
it is already too late for a node to build an atx if another node got a proof from the poet. since poet round for that epoch has finished. maybe what you described could happen with multiple poets that run different configuration, but i can't imagine it working like that in system tests with one poet. are logs still kept somewhere?

**Comment by dshulyak** [comment]
there were no early publishers in epoch 6. the problem is that smesher-26 published two first atxs way too late.
normally (because of current config) atx that targets epoch N, will be published 10 seconds into epoch N - 1 (first layer of epoch N - 1). smesher-26 was publishing two first atxs that targeted epoch N in the epoch N (not N - 1). `{namespace="test-rcws", pod="smesher-26-0"} |= "atxBuilder" |= "awaiting atx pub"`


i think that it worked out this way because it had no better atxs when atx builder started to work. specifically it picked positioning atx for its own first atx between 05:42:42 and 05:43:23 

```
{"L":"INFO","T":"2022-08-24T05:42:42.999-0400","N":"6367a.atxBuilder   ","M":"building new atx challenge","node_id":"6367a248803280fa1a85d3cb055c3b85dcad9ca26ed5ef9c7c967e11adea3e9b","module":"atxBuilder","epoch_id":3,"name":"atxBuilder"}

{"L":"INFO","T":"2022-08-24T05:43:23.001-0400","N":"6367a.atxBuilder   ","M":"new atx challenge is ready","node_id":"6367a248803280fa1a85d3cb055c3b85dcad9ca26ed5ef9c7c967e11adea3e9b","module":"atxBuilder","target_epoch":"4","current_epoch":"4","name":"atxBuilder"}
```

but got better atxs 20 seconds later, as expected

```
{"L":"INFO","T":"2022-08-24T05:43:46.067-0400","N":"6367a.atxHandler   ","M":"got new atx","node_id":"6367a248803280fa1a85d3cb055c3b85dcad9ca26ed5ef9c7c967e11adea3e9b","module":"atxHandler","requestId":"7727ee59-82be-43a9-b599-15d1aa0b8ae2","atx_id":"c75daf2c73b9f3fde5af14b1a96db7f96c789d9f3aa1517988b72637c0b18653","challenge":"0xe296aca4580ef7ff97f1a28b50b91994e782e53ed1434679080bae0af5246368","id":"c75daf2c73","sender_id":"721ac67c3c620dafd17a6e9ef3d5fc8fe1c40711348a4baf856c97e384c323f6","prev_atx_id":"ffd19d8d30","pos_atx_id":"40f12f8f11","coinbase":"stest1qqqqqqp3qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqql50dsa","pub_layer_id":16,"epoch":4,"num_units":2,"sequence_number":3,"base_tick_height":53657,"tick_count":17664,"weight":35328,"size":271,"name":"atxHandler"}
```

we need to wait for time when poet stops execution of the previous round (epoch_time + phase_shift - cycle_gap) plus some time for those atxs to propagate, but no more than cycle_gap.

**Comment by countvonzero** [comment]
> we need to wait for time when poet stops execution of the previous round (epoch_time + phase_shift - cycle_gap) plus some time for those atxs to propagate, but no more than cycle_gap.

@dshulyak 
do you mean a new node needs to wait this amount of time to pass in the current epoch N to build an ATX that targets epoch N+1, instead of hurrying into building for epoch N?

**Comment by countvonzero** [comment]
@dshulyak can you confirm as i may have to fix this as part of https://github.com/spacemeshos/go-spacemesh/pull/3497. it is failing like every 3 times during my testing.

**Comment by dshulyak** [comment]
> do you mean a new node needs to wait this amount of time to pass in the current epoch N to build an ATX that targets epoch N+1, instead of hurrying into building for epoch N?

yes, it doesn't make sense for new node to publish atx that target epoch N in the middle of epoch N. so it definitely should target epoch N+1. what i provided above will work if majority will use poet that is configured the same way, but it won't be future proof if everyone will use its own poet instance.
