### ISSUE TITLE
cmd/node: configuration changes for genesis id

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#3505]
part of: https://github.com/spacemeshos/pm/issues/135
depends on: https://github.com/spacemeshos/go-spacemesh/issues/3505

- add a genesis section into config
- for this issue genesis section needs to include: genesis time and genesis extra data (other fields can be moved into this config later)
   - genesis time is a string with time encoded according to RFC3339
   - genesis extra data is a string with a max size of 255 chars. defaults to `mainnet`
- when node is started check if genesis section is already stored in the data directory (example: /data/genesis.conf)
   - if it is not stored, encode genesis section with json and persist it on disk
   - if stored - decode object with json into another instance of genesis config, compute diff using https://github.com/google/go-cmp/ and print fatal error to the operator with a diff and a path to persisted genesis conf
- compute genesis id as a hash from genesis time and genesis extra data
- golden atx should be set to genesis id

**Comment by WilfredTA** [comment]
Why the extra issue here? This is all described in the Epic already, isn't it?
