### ISSUE TITLE
layer fetcher erroneously sets hare_output to zero value

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#3522]
this is what is causing TestShortTimeskew to fail after i fixed issue with abstain votes in https://github.com/spacemeshos/go-spacemesh/pull/3513

at layer 11 `{namespace="test-koki"} |= "choose base ballot" | json | voting_layer="11"` , there will be a split in votes. half of the nodes will be voting for layer 9 as empty, and other will vote to support block. this split will remain for hdist since we are voting according to hare output within it.

both smesher-21 and smesher-1 correctly generated a block. however smesher-1 loaded hare_output into tortoise `{namespace="test-koki", pod="smesher-1-0"} |= "on hare output" | json | layer_id=9` and smesher-21 loaded empty layer `{namespace="test-koki", pod="smesher-21-0"} |= "on hare output" | json | layer_id=9`.

looking further smesher-21 actually tried to save hare output right before calling tortoise `{namespace="test-koki", pod="smesher-21-0"} |= "saving hare output for layer" | json | layer_id=9`. see a timing, it is right before a call to the tortoise. but it failed to update hare_output since syncer already updated layer as a zero `{namespace="test-koki", pod="smesher-21-0"} |= "tagging zero block layer" | json | layer_id=9`.

@countvonzero i don't recall what is the purpose of this code https://github.com/spacemeshos/go-spacemesh/blob/develop/fetch/layers.go#L434-L438  . it looks like that it needs to be removed

**Comment by countvonzero** [comment]
the only purpose calling SetZeroBlockLayer() from syncer is to set the latest layer in mesh so we know that the node is data synced. 
normally the latest layer is pushed forward by blocks/proposals arriving via gossip/sync. but when a layer truly has no data, it won't advance.

but setting hare output there is a mistake and should be updated along with the certificate generation PR.
