### ISSUE TITLE
determine malicious behavior and course of actions

### ISSUE THREAD

**Issue by countvonzero** [spacemeshos/go-spacemesh#3553]
## Description

the node currently does not act on malicious miners. the only action taken right now are
- when receiving a ballot, if the smesher has already published a ballot in the same layer
- when receiving a ballot that has inconsistent votes
  - vote for multiple blocks within hdst
  - vote support/against for the same block
  - vote abstain on a layer but voted support/against for blocks in that layer

tortoise will consider such ballot has weight/height 0. are these action sufficient for mainnet launch?

also, there are other behaviors that should also be considered malicious. for example, a smesher that
- publishes syntactically invalid atx/proposal/ballot
- publishes multiple ATXs in the same epoch
- publishes two ATXs of the same sequence number
...

we should create a list of behaviors that we consider malicious and decide the course of actions for them.

**Comment by dshulyak** [comment]
In particular there is a gap that needs to be closed before genesis in atxs https://github.com/spacemeshos/go-spacemesh/blob/develop/activation/handler.go#L126-L129 . Otherwise same post can be reused for any number of atxs.

There is a solution that was used for ballots we can reuse the same for atxs, but as noted above it needs to be a part of some larger work so that we don't miss other holes like this.

**Comment by fasmat** [comment]
@countvonzero @dshulyak what's the state on this? I think at some malicious behavior checks have already been implemented.

Is there still something that needs to be done and I can help with?

**Comment by countvonzero** [comment]
it would be great to generate a more comprehensive list of malfeasance behaviors (i think @noamnelke may have a doc for that) first, and go through that list to determine 
- what are we supposed to do in each scenario
- what we are, if any, doing in each scenario
- come up with a cohesive way to manage these if possible.

**Comment by dshulyak** [comment]
there are several issues and all of them are placeholders, i will close atleast some of them
