### ISSUE TITLE
Multiple data races reported by `go test -race`

### ISSUE THREAD

**Issue by poszu** [spacemeshos/go-spacemesh#3583]
## Description
I ran unit tests with Go's [race detector](https://go.dev/doc/articles/race_detector). Please find the results [here](https://github.com/spacemeshos/go-spacemesh/actions/runs/3104409998/jobs/5028857780).

It reported data races in code around the following structures:
- [`AddrBook`](https://github.com/spacemeshos/go-spacemesh/blob/500e0a3d4ebcbe53179d051da3beabc98974f632/p2p/addressbook/addrbook.go#L42)
- [`Set`](https://github.com/spacemeshos/go-spacemesh/blob/b37af29e79c9d81c534a22785a16a938ad6f59e2/hare/haretypes.go#L54)
- [`Hare`](https://github.com/spacemeshos/go-spacemesh/blob/b5bb06945d4d15100178ca1a355f72d99a8cb652/hare/hare.go#L68)

## Actual Behavior
`go test -race` reports multiple data races

## Expected Behavior
No data races detected

**Comment by fasmat** [comment]
@poszu would you mind if I take over this issue?

**Comment by poszu** [comment]
> @poszu would you mind if I take over this issue?

Go ahead, thanks! :)

**Comment by poszu** [comment]
The tests are already executed with `-race` and pass. Closing.
