### ISSUE TITLE
Test `TestNIPostBuilderWithClients` from `activation` pkg times out on Windows

### ISSUE THREAD

**Issue by poszu** [spacemeshos/go-spacemesh#3625]
## Description
Test `TestNIPostBuilderWithClients` from `activation` pkg times out on Windows

## Steps to reproduce
go test --timeout=30s -run "^TestNIPostBuilderWithClients$" github.com/spacemeshos/go-spacemesh/activation

## Actual Behavior
The test hangs in clean up awaiting for the PoET harness to be shut down.

## Expected Behavior
Test passes

## Environment
 - OS:  Windows

**Comment by fasmat** [comment]
Fixed with https://github.com/spacemeshos/go-spacemesh/pull/3679
