### ISSUE TITLE
vm: use 16 for spend methods on all templates

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#3676]
this has to be set https://github.com/spacemeshos/go-spacemesh/blob/develop/genvm/core/types.go#L13 to 16, and smapp needs to be updated

**Comment by countvonzero** [comment]
this is cryptic. what's the difference btwn 1 and 16 for smapp? is it a restriction on data type?

**Comment by dshulyak** [comment]
0-15 was supposed to be reserved for "system" methods that have to be supported by every template (such as spawn, deploy, relay, ?)
16 -  are template methods
