### ISSUE TITLE
beacon: protocol broken

### ISSUE THREAD

**Issue by countvonzero** [spacemeshos/go-spacemesh#3685]
## Description

beacon protocol is broken. all epochs now have the same beacon value. the number of input hashes is always 0

```
{"L":"INFO","T":"2022-10-23T23:24:35.027-0400","N":"d45ca.beacon       ","M":"calculated beacon","node_id":"d45ca688f971a824666feebdab9a55b1c51dd51464e594e6cbda8402a3c6d45b","module":"beacon","sessionId":"64757c96-6c76-4153-85cf-f14693555d7e","epoch_id":3,"target_epoch":4,"beacon":"e3b0c442","num_hashes":0,"name":"beacon"}
```

metrics from devnet-998

![Screenshot from 2022-10-24 13-24-45](https://user-images.githubusercontent.com/30611210/197454372-a845bd3a-2a38-4b07-9a56-0c0b3bb2e5b8.png)

**Comment by countvonzero** [comment]
### investigations
- beacon protocol in systests is broken since https://github.com/spacemeshos/go-spacemesh/pull/3399 
- before PR
```
{
"M":"created proposal checker with ATX threshold",
"node_id":"7aedbff0f5a60edb04c1b126c491f95b11d697f6e1e497037158e31367c74c10",
"module":"beacon",
"epoch_id":2,
"epoch_weight":56,
"threshold":"2391414306777284761556671594222121413041639121586695349078842922314196084025615080694642252368961122474945952096883273646102105562811559805668339793800378245615411382623445462677059727651766272",
"name":"beacon"
}
```
- after PR
```
{
"M":"created proposal checker with ATX threshold",
"node_id":"492ee189ff8711270157d4f3dac5e06e5c2bedfd46aac638fbddc2688ee1c4c6",
"module":"beacon",
"epoch_id":2,
"epoch_weight":1138088,
"threshold":"166720942623914584035474423063283466672422374759330514545082536434996614502628245311917131046854497654232394421238823920543738157756631366746886085914294147094135636354431318283668946944000",
"name":"beacon"
}
```
- the threshold is significantly lower (10^-4) and in the new code no miner can make beacon proposals.
```
2391414306777284761556671594222121413041639121586695349078842922314196084025615080694642252368961122474945952096883273646102105562811559805668339793800378245615411382623445462677059727651766272
vs
166720942623914584035474423063283466672422374759330514545082536434996614502628245311917131046854497654232394421238823920543738157756631366746886085914294147094135636354431318283668946944000
```

### possible fixes

1. adjust `kappa` in the beacon config. current systests uses the following

```
"config":"{Kappa:40 Q:1/3 RoundsNumber:4 GracePeriodDuration:2s ProposalDuration:2s FirstVotingRoundDuration:10s VotingRoundDuration:2s WeakCoinRoundDuration:2s Theta:1/4 VotesLimit:100 BeaconSyncNumBallots:30}"
```

2. fix https://github.com/spacemeshos/go-spacemesh/issues/2785

3. check beacon value in systests (maybe TestSmeshing) 

3 is a must. 2 is the long term solution.

**Comment by dshulyak** [comment]
what is kappa? 
i find it really unexpected and fragile that protocol can become broken due to the change in absolute value of the weight. do we have a formula to keep kappa in sync with the expected weight in the network (because it will be different on ci, devnets and mainnet)?

**Comment by countvonzero** [comment]
> what is kappa? 

https://community.spacemesh.io/t/tortoise-beacon-based-on-bad-vrf/100/54

> i find it really unexpected and fragile that protocol can become broken due to the change in absolute value of the weight. do we have a formula to keep kappa in sync with the expected weight in the network (because it will be different on ci, devnets and mainnet)?

i am equally surprised. this predates me. what's strange to me was that the miner's own weight didn't factor into the eligibility check at all. i am not sure how this jive with option 2. i think we will need Tal's help here.

**Comment by dshulyak** [comment]
~i think in that response atx weight is meant to be relative to the total atx weight, e.g atx weight / total atx weight > atx threshold. otherwise it doesn't make sense, result of that computation is always less than 1.~ actually i don't understand what how that works

wrt reusing code, it doesn't look possible, maybe it would be possible with some heavy refactoring. i think what is meant is to use the same math. anyway needs to be specified how that suppose to work exactly

**Comment by countvonzero** [comment]
> wrt reusing code, it doesn't look possible, maybe it would be possible with some heavy refactoring. i think what is meant is to use the same math. anyway needs to be specified how that suppose to work exactly

@noamnelke, Nikita and i had a meeting about this. we concluded that to reuse code, the code in hare needs changing too. tho i don't exactly remember what/how :P

**Comment by countvonzero** [comment]
clarification from Tal:

```
The W  is weight units (where unit here means minimal weight for an honest user). 
If you have 30 miners, and each has minimal weight, then W=30 in this case.

The  calculation gives the threshold that ensures at least one honest miner's proposal will pass, 
except with 1/2^K probability. This is actually a pretty easy to show. We want to compute the threshold p, 
which is the probability that a single weight unit will be eligible to send a proposal:

- Each weight unit has probability p to succeed, and all units are independent
- There are at least (1-q)W honest units
- The probability that  no honest unit succeeds is (1-p)^{(1-q)W}. 
  We want this probability to be less than 2^{-K}, so we get the inequality (1-p)^{(1-q)W} < 2^{-K}
- Raise to the power of "(1-q)W" root from both sides: 1-p < 2^{-K/((1-q)W)}

Note that W changes from epoch to epoch --- it depends on the number of valid ATXs received...
```

currently the code use epoch total weight for `W`. but it needs to be the number of ATXs in that epoch instead.

**Comment by countvonzero** [comment]
fixed by https://github.com/spacemeshos/go-spacemesh/pull/3845
