### ISSUE TITLE
GRPC GlobalStateService.AccountDataStream skips some updates

### ISSUE THREAD

**Issue by brusherru** [spacemeshos/go-spacemesh#3687]
## Description
Smapp requests the current balance via `GlobalStateService.AccountDataQuery` and subscribes to account balance updates via GRPC Endpoint `GlobalStateService.AccountDataStream` (flag 4).
Meanwhile, this stream does not send any updates when some funds are received there and updates it only after the second transaction. But the message contains the previous state.

## Steps to reproduce
1. Create an account and subscribe to this endpoint
2. Send 100 smidges to the account
3. Wait until the transaction will be processed. You'll find out that there are no updates on the stream.
4. Send 200 more smidges to the account
5. Wait. And you'll find out that Stream shows up 100 smidges in current & projected balances
6. If you send a request to `GlobalStateService.AccountDataQuery` you'll see that the account has 300 smidges on the balance.

Waiting for some more layers applied after the transaction does not work.

## Actual Behavior
The endpoint sends the previous state all the time.

## Expected Behavior
It should send all the latest changes as soon as possible.

## Environment
 - Node Version: [5279493](https://github.com/spacemeshos/go-spacemesh/tree/5279493f46a831e26293719013ad86a079387732)
 - Smapp version: [from PR](https://github.com/spacemeshos/smapp/pull/975)

## Additional Resources 
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/1897530/197592726-a3ef2bf0-ddcb-4844-9511-1a29a2a31066.png">
If I restart Smapp, then it will request the `AccountDataQuery` endpoint and balance will be fine.
Tested it on devnet-300.

**Comment by dshulyak** [comment]
event is emitted before transaction that persists account changes is committed. i guess the simple fix would be to iterate over changed accounts after tx is committed and only then emit events.
