### ISSUE TITLE
dependencies should be fully processed before processing dependant object

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#3729]
protocol objects have many dependencies, that must be stored in db and related memory structures (such as tortoise state), examples:
- refballot -> ballot dependency for reading active set and beacon
- base ballot -> ballot dependency for decoding votes

it looks like that there is a code path that allows concurrent execution, yet it is unclear in what cases. in the example below ballot was passed to the tortoise, before base ballot and failed to decode as expected:
 
![Screenshot from 2022-11-08 09-22-52](https://user-images.githubusercontent.com/1964576/200742737-aa3cf287-4ba3-4df2-80ad-c557833f46ab.png)

**Comment by dshulyak** [comment]
i think to fix this problem all dependencies have to be saved into database after they are loaded into tortoise.

**Comment by dshulyak** [comment]
there are two more possible problems in this area:
- [x] persisting atxs before adding them to tortoise may result in undefined behavior https://github.com/spacemeshos/go-spacemesh/pull/3904
- [ ] persisting ballots before storing decoded ballot may result in undefined behavior

**Comment by countvonzero** [comment]
> it looks like that there is a code path that allows concurrent execution, yet it is unclear in what cases.

i think this is fixed by https://github.com/spacemeshos/go-spacemesh/pull/3778

> i think to fix this problem all dependencies have to be saved into database after they are loaded into tortoise.

can you elaborate more on the reasoning behind this conclusion? it is not obvious to me.

**Comment by dshulyak** [comment]
every handler checks if dependency exists locally before fetching it. for example base ballot -> ballot dependency.
if it is stored in the database before loading in the tortoise then another thread may process ballot before first one loaded base ballot into tortoise and decoding will fail.

example with two threads t1 and t2 and ballots b1 -> b2 

1. t1 receives b1
2. t2 receives b2
3. t1 adds b1 to the database
4. t2 checks that b1 in the database, adds b2 to the database, runs tortoise decoding step and it fails
5. t1 adds b1 to the tortoise 

i realized that fetcher pr slightly improves this. but it only affects objects that are requested by a node. any two objects can be processed concurrently from broadcast. leaving it like this is just not robust

**Comment by countvonzero** [comment]
thank you for the explanation. that makes sense. this behavior remains because
- concurrent gossip processing
- recursive data availability check

@dshulyak do you think we could add a callback for database save? most of the time it's a noop. but for atx/ballot/block we add the data to tortoise after they are saved in db.

my concern is updating state *before* persisting the data can be problematic too. maybe less unlikely but difficult to debug should it happens.

**Comment by dshulyak** [comment]
> do you think we could add a callback for database save?

i don't understand what callback and where. 
if this is about adding it to tortoise, then it is definitely not the right place. tortoise will be completely data-driven and it won't save data

> my concern is updating state before persisting the data can be problematic too. maybe less unlikely but difficult to debug should it happens.

if save fails due to the disk issue it is a good idea to terminate application, as it is critical. other failures (such as SQLITE_BUSY) are temporary and can be retried till success, so i am not what to debug there

**Comment by countvonzero** [comment]
i am talking about making dbSave() and updateTortoiseCallback() atomically executed. 
so essentially your example (two threads t1 and t2 and ballots b1 -> b2) will become
- t1 receives b1
- t2 receives b2
- t1 adds b1 to the database and update tortoise with b1
- t2 checks that b1 in the database, adds b2 to the database, runs tortoise decoding step and succeed, update tortoise with b2

**Comment by countvonzero** [comment]
> if save fails due to the disk issue it is a good idea to terminate application, as it is critical. other failures (such as SQLITE_BUSY) are temporary and can be retried till success, so i am not what to debug there

this may work for sqlite now, but it's still possible we will change storage solution in the future with different ways of failure.
to me, updating state without first persisting data usually leads to hidden problem.

**Comment by dshulyak** [comment]
database failures are not random, failure is either retriable or not. with kv store it is even simpler 
in general there are other options that registers every received object somewhere and fetcher can check if it is being processed. i can leave it open
