### ISSUE TITLE
mesh: block validity updater is not robust

### ISSUE THREAD

**Issue by countvonzero** [spacemeshos/go-spacemesh#3744]
### current approach:
- mesh will apply the hare output `A` for layer `N` to the mesh optimistically when hare terminates
- tortoise verifies layer `N` (earliest at layer `N+1`) and voted against A, supported B, it triggers mesh to set `minUpdatedLayer` to `N`
- when mesh is processing layer `N+2`, it sees the `minUpdatedLayer` is `N`, it discovers that it applied the wrong block, reverts the state to layer `N-1`, and applies `B` for layer `N`.

### problem

1.  updating `minUpdatedLayer` and saving validity to db aren't atomic. if the node is checking for revert between this window, it'll be incorrect. (`UpdateBlockValidity` doesn't hold a lock)
2. if the node exits right after the block validity updated in db, upon restart, mesh will not re-examined if the applied block is correct
3. if tortoise changed its opinion about the same layer within a narrow window of resetting `minUpdatedLayer`, then that 2nd opinion will be ignored

a memory-only solution will not work for 2.

### proposed fix
- add a boolean field `dirty` to blocks table.
- when tortoise verifies layer `N`, it immediately saves block validity for `A` and `B` into database and mark their `dirty` field to true
- when mesh process layer `N+2`
  1. query all the dirty blocks from db and found `A` is invalid and `B` is valid
  2. re-examines the applied block in `N`, reverts to layer `N-1`, and applies `B`
  3. sets `A`'s `dirty` to false iff `A`'s `valid` is still false, and sets `B`'s `dirty` to false iff `B`'s `valid` is still true

**Comment by dshulyak** [comment]
i wanted to use interface for the tortoise that returns updated validities, such as

```go
type Tortoise interface {
     Updates() []Event
}

type Event struct {
    Layer uint32
    []BlockHeader
}

type BlockHeader struct {
    Height uint64
    Layer uint32
}
```

there should be atmost on thread that updates to vm therefore no concurrency issues.
tortoise always have to load 2 windows (e.g. if window is 10 000 we will have to load 20 000 layers), so on startup it will re-verify things that weren't persisted

**Comment by countvonzero** [comment]
@dshulyak 
so i guess you are suggesting to
- still use memory-only model to facilitate communication btwn mesh and tortoise
- mesh needs to bridge the gap btwn the time checking needs for revert (t1), checking for which block to apply (t2), and the actual validity update to db (t3)

what is the downside you see from the db solution with dirty flag? 
in my prototype it work and simplifies the logic in mesh/tortoise, does make the db code slightly more complicated.

**Comment by countvonzero** [comment]
how about this implementation?

in `turtle` struct:
- maintain a list `updated` which contain the list of updated `*blockInfo`
- when `Updates()` is called, compose a list of events from `updated` and clear `updated`

in `mesh.ProcessLayerPerHareOutput(N)`
- save hare output N
- call `tortoise.Updates()` to get those events
- from those events determine the `minLayerUpdated`
- starting from `minLayerUpdated`, determine whether there is need to revert. revert if necessary
- persist those updated validities into DB 
- process layer N

**Comment by dshulyak** [comment]
> what is the downside you see from the db solution with dirty flag?

in general the downside is that we should not misuse database. this solution won't be even considered if we wouldn't use sqlite. for example, would you wnat to add an index for dirty field? this is unnaceptable in my opinion. but if no index, how do you query that table efficiently then?

moreover it is simply unnecessary 

> how about this implementation?

this is similar to what i meant. however i don't understand what is the point of maintaining minLayerUpdated.
tortoise returns list of updated validities, mesh checks if it applied correct block, if not it will revert after processing validities and apply everything according to new validities

**Comment by countvonzero** [comment]
thanks.

> however i don't understand what is the point of maintaining minLayerUpdated.

i don't mean it as a member of mesh struct. just a local variable in the function to decide which layer to revert to.

**Comment by countvonzero** [comment]
there is still a remaining issue that latest verified layer and validity update are not in sync.
should change to suggestion here https://github.com/spacemeshos/go-spacemesh/pull/3791#discussion_r1041872562

**Comment by countvonzero** [comment]
another issue is that accumulated layer hashes are not updated properly after validity updates if applied block is unchanged

UPDATE: i meant layer hash, which is currently unused and can be deleted.
