### ISSUE TITLE
Can not psubmit spend transaction with amount >=0.01 SMH

### ISSUE THREAD

**Issue by brusherru** [spacemeshos/go-spacemesh#3745]
## Description
When I'm sending a spend transaction with `0.01 SMH` or more the transaction fails with a validation error.
Meanwhile, if I send a less amount of `5000 Smidges` or even `0.0001 SMH` it works well.

Another strange behavior that I've found, is that in case if I retry sending the same transaction it passes through and GRPC Endpoint returns the tx id and state === 4 (mempool). Meanwhile, if I request the `TransactionStateQuery` endpoint with this id I'll get nulls/zeroes in transaction data and state "UNSPECIFIED".

## Environment
Please complete the following information:
 - OS: macOS 11.6 Big Sur
 - Node Version: 0.2.18-beta.0 (tested on devnet-300)
 - Smapp version (if applicable): develop (da779b79af3fb908c0e4115c6f4d5337372c0c9a)

## Steps to reproduce
I've used Smapp and tx composer from the same repo to encode and sign transaction and send it to GRPC Endpoint.
1. Get enough money (more than 0.01 SMH) on the account
2. Spawn account
3. Try to send spend tx with amount >= 0.01 SMH
4. You'll get a verification error here
5. Try to send it again
6. You'll get a response with txId & state === 4

## Actual Behavior
- Transaction does not sent
- Node returns a verification error the first time, and falsy response on the second try

## Expected Behavior
Transaction should be sent

## Additional Resources 
Log:
```
2022-11-12T03:03:59.502+0300	WARN	6a1f7.txHandler    	failed to handle tx	{"node_id": "6a1f7a84dfa6d53428aa48a0a2a3ae62574743911b15fa479f285afd8e5cdd85", "module": "txHandler", "requestId": "1d6fa7eb-5bb5-4c27-a77c-5d4f1c997b1c", "errmsg": "failed to verify tx: 0x678f36edb3a40fa163f15fb8b9fee0fcebbbcfd6c261dc834423883a487c3cb2", "name": "txHandler"}
2022-11-12T03:03:59.503+0300	ERROR	00000.defaultLogger	error broadcasting incoming tx: failed to publish to topic tx1: validation ignored
```

Encoded transactions & signatures:
```
0.01 SMH (not working)
tx:  0, 0, 0, 0, 0, 136, 115, 101, 220, 126, 211, 50, 161, 69, 251, 61, 50, 57, 9, 205, 103, 53, 34, 165, 70, 4, 48, 0, 4, 0, 0, 0, 0, 154, 103, 118, 245, 131, 241, 187, 149, 189, 14, 154, 148, 51, 9, 243, 222, 157, 98, 37, 203, 7, 0, 228, 11, 84, 2
sig: 26, 101, 215, 58, 2, 97, 25, 112, 178, 159, 209, 157, 85, 27, 251, 167, 77, 130, 24, 176, 238, 194, 196, 152, 252, 186, 56, 134, 225, 21, 67, 130, 78, 6, 178, 250, 113, 65, 9, 44, 7, 254, 156, 196, 93, 251, 104, 219, 12, 168, 2, 4, 67, 236, 184, 46, 176, 143, 78, 65, 243, 86, 203, 0

1 Smidge (working)
tx:  0, 0, 0, 0, 0, 136, 115, 101, 220, 126, 211, 50, 161, 69, 251, 61, 50, 57, 9, 205, 103, 53, 34, 165, 70, 4, 40, 0, 12, 0, 0, 0, 0, 154, 103, 118, 245, 131, 241, 187, 149, 189, 14, 154, 148, 51, 9, 243, 222, 157, 98, 37, 203, 4
sig: 189, 170, 215, 127, 252, 135, 110, 6, 152, 240, 57, 54, 171, 188, 66, 102, 95, 196, 201, 50, 116, 199, 160, 193, 238, 248, 138, 242, 81, 5, 100, 195, 222, 63, 208, 247, 179, 126, 92, 149, 200, 245, 211, 16, 248, 144, 220, 245, 95, 153, 238, 204, 139, 201, 220, 233, 250, 1, 94, 222, 165, 52, 218, 15
```

`SubmitTransaction` response on the second try:
```
{"status":{},"txstate":{"id":{"id":{"type":"Buffer","data":[12,57,144,232,41,10,151,35,90,122,252,10,117,0,20,217,71,118,186,210,184,184,118,163,210,31,197,34,19,44,209,25]}},"state":4}}
```

**Comment by dshulyak** [comment]
sorry it was a known bug and fixed long time ago, but lib wasn't updated (https://github.com/spacemeshos/go-scale/issues/3)
let's try to confirm on latest version, but i expect it to get closed then

**Comment by Stizerg** [comment]
I'm very sorry, but this bug wasn't fixed.
I'm using v0.2.8-pr.1011
OS: Win10Pro

P.S. I can see it was merged, but it didn't fix the issue.

**Comment by brusherru** [comment]
@Stizerg thanks for participating. But you have tested a PR with some hotfixes, which is still using older version of go-spacemesh under the hood.
To have the fix of this issue we need to integrate genesis-id into Smapp first and then we can deploy a new network and make a new release of Smapp that are using newer version of go-spacemesh.
Then we're expecting that the problem will disappear.

**Comment by brusherru** [comment]
I can't reproduce this bug anymore (on 0.2.19-beta.0). So I'm closing the issue.
