### ISSUE TITLE
applied empty layer despite succesfully generating a block 

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#3755]
{namespace="dmitry-chaos", pod="smesher-39-0" } | json |~ "hare terminated|layer hashes|block generated" | layer_id=249

![image](https://user-images.githubusercontent.com/1964576/201875835-1047b89e-d40a-415b-8e65-77a48b2a0227.png)

**Comment by countvonzero** [comment]
there was a log from mesh.go that saved block validity for the hare output to be false. if verified layer is after 249, block validity will be used over hare output.

![Screenshot from 2022-11-15 10-43-05](https://user-images.githubusercontent.com/30611210/202000364-bac116cd-b1d7-4e90-9425-2b5d5b7e8ad5.png)

**Comment by dshulyak** [comment]
i think it was fixed with https://github.com/spacemeshos/go-spacemesh/pull/3758
will reopen if i see it again
