### ISSUE TITLE
ATX: remove restrictions on positioning ATX 

### ISSUE THREAD

**Issue by countvonzero** [spacemeshos/go-spacemesh#3774]
## Description

currently positioning ATX must be from the previous epoch. this will prevent network from healing on its own when there are 1+ epochs without ATXs.

- positioning ATX can be a previous ATX of any smeshers from any previous epochs
- ATX need to declare explicitly its publish epoch (instead of inferring from its positioning ATX)

**Comment by fasmat** [comment]
What was the inital reason for introducing the positioning ATX? If we allow any ATX to be chosen and explicitly set a publish epoch what prevents a smesher from always chosing the same ATX? At that point why have it at all?

cc @noamnelke @selfdual-brain
