### ISSUE TITLE
Hare: bug in termination condition

### ISSUE THREAD

**Issue by selfdual-brain** [spacemeshos/go-spacemesh#3783]
https://github.com/spacemeshos/go-spacemesh/blob/b2da54055571b1d8e6724dc96e75aac17befc92f/hare/notifytracker.go#L42

On page 64 of the latest Hare specification, the termination condition for Hare is described as:

```
If at any point in the protocol, Pi party gathers f+1 notication headers (S; notify; k) from distinct parties on a set S, it terminates.
```

In this context `k` is a bound variable referencing the current iteration of the protocol. Therefore, the termination condition requires achieving at least f+1 notification messages in the CURRENT ITERATION. In other words, the counter of notifications should be restarted at the beginning of every iteration.

In the current implementation this is not the case. The counter is initialized once and the accumulation of notifications runs for the whole Hare run. This is a bug.

Caution:  This bug was not discovered before because it would only manifest during an equivocation-based attack. Using this hole, a colluding minority of malicious nodes could trick the protocol into accepting "wrong" consensus result..

**Comment by dshulyak** [comment]
For completeness: we should also allow every participant to create more than one notification message, current implementation tracks if notification was sent before and won't send it again.
