### ISSUE TITLE
Extend node api with rewards eligibility 

### ISSUE THREAD

**Issue by pigmej** [spacemeshos/go-spacemesh#3794]
For better UX, it would make sense if node API could return node rewards eligibility. 

Details are to be defined. 

In an ideal situation, I'd love to see the following:
* when I'm expecting to get rewards (which epoch)
* how much time is left to get the rewards
* is everything ok with my node to get the rewards

**Comment by pigmej** [comment]
@brusherru that was slightly improved and is now kinda displayed in Smapp, isn't it?

**Comment by dshulyak** [comment]
we have that in events. will assume that it is sufficient
