### ISSUE TITLE
PostSetupStatusStream and PostSetupStatus working slowly, without status 2. 

### ISSUE THREAD

**Issue by maparr** [spacemeshos/go-spacemesh#3795]
## Description
After connection to PostSetupStatusStream and set up proof of space folder, stream is sending status 1 at least 1 minute till status 3 , without status 2

## Steps to reproduce

1. Create an account in smapp with node + wallet mode
2. Start syncing node
3. Add POS directory , check logs

https://user-images.githubusercontent.com/54288612/203874028-5d84d33a-90e7-4513-8771-5a5404c92234.mp4

## Actual Behavior
Getting sync state after 1-3 minutes
App loading if POS directory mounted 1-3 minutes , waiting state 3 

## Expected Behavior
Get state 3 directly after sing in
Speed up app start

## Environment
Please complete the following information:
 - OS: MacOS
 - Node Version: latest develop
 - Smapp version 0.2.8 with GenesisID funcionality
 
## Additional Resources 

[2022-11-23T22:09:37.378Z INFO f2e7b.trtl.txt](https://github.com/spacemeshos/go-spacemesh/files/10087098/2022-11-23T22.09.37.378Z.INFO.f2e7b.trtl.txt)

**Comment by fasmat** [comment]
Status 2 is reported between status 1 and status 3.

The reason you don't see it is because it only lasts for a few milliseconds when initializing 4KB of post data.
