### ISSUE TITLE
flaky test: Test_ValidateVRFNonce

### ISSUE THREAD

**Issue by countvonzero** [spacemeshos/go-spacemesh#3884]
## Description

https://github.com/spacemeshos/go-spacemesh/actions/runs/3744669735/jobs/6358299384
```
=== FAIL: activation Test_ValidateVRFNonce/invalid_vrf_nonce (0.00s)
    validation_test.go:59: 
        	Error Trace:	/home/runner/work/go-spacemesh/go-spacemesh/activation/validation_test.go:59
        	Error:      	An error is expected but got nil.
        	Test:       	Test_ValidateVRFNonce/invalid_vrf_nonce
    --- FAIL: Test_ValidateVRFNonce/invalid_vrf_nonce (0.00s)

=== FAIL: activation Test_ValidateVRFNonce (0.76s)
```

**Comment by fasmat** [comment]
I've not yet encountered this yet, but yes this test has a 1 in 256 chance of randomly failing. This is when the very first label of an initialized PoST happens to successfully validate as a nonce for POPS-VRF.

I can make it less likely, but this will increase the time this test takes to execute. I can make it a 1 in 1000 chance and then the test would take ~ 8 seconds to execute and still fail (very) occasionally.
