### ISSUE TITLE
Messages arriving early (in previous round) due to time drifts

### ISSUE THREAD

**Issue by zalmen** [spacemeshos/go-spacemesh#390]
Since we assume that honest peers might not agree on the current time, it is possible (need to be verified) that an honest peer will receive a round2 message at the end of round1 and therefore ignore it. We first need to verify that this scenario is possible and then think of whether or not it is a problem and fix it.

**Comment by antonlerner** [comment]
Shouldn't we have a network delay parameter that also allows minor time drifts between clocks? As I see it, any drift of more than a couple of seconds should be considered malicious anyways
