### ISSUE TITLE
Re-assess nonce encoding in VRF signatures

### ISSUE THREAD

**Issue by fasmat** [spacemeshos/go-spacemesh#3902]
## Description
With https://github.com/spacemeshos/go-spacemesh/pull/3877 nonces were added to VRF signatures. These are currently just added as an 8 byte little endian prefix to the message that is signed before signing (and validation).

We should re-assess how we want to encode this nonce (see also https://github.com/spacemeshos/go-spacemesh/pull/3877#discussion_r1056026113) :
- Add it to the message as a field before serializing it with go-scale
- using a separate `VRFMessage` type that has 2 fields: the message to be signed and the nonce before encoding that with go-scale
- possibly a different encoding

Both have advantages and disadvantages; using it as a field in the actual message means we can have messages with and without the nonce, and the messages can be validated without first needing to fetch and validate the initial ATX of a node. The second requires less code change and keeps the message objects themselves clean to contain only the data that is relevant for the message itself.

## Affected code
`signing` package and possibly `common/types` for the objects that are signed with the VRFSigner

**Comment by fasmat** [comment]
cc @countvonzero

**Comment by countvonzero** [comment]
> Add it to the message as a field before serializing it with go-scale

yes. my preference would be to add nonce to all the VRF messages the node would sign/prove with the vrf signer.
rationale:

- having customized encoding for the nonce is not porting friendly when the node is implemented in a different language
- it's declarative, so the logic of nonce is not hidden in the signing package.
- only one vrf verifier instance is needed per node, not per vrf msg

note that msg size is not an argument for the current impl.

the sender construct a vrf msg, sign with vrf signer (as some eligibility proof of some protocol), and send it as part of a separate message (hare round msg, block proposal, beacon proposal...)

the receiver, when verifying eligibility, reconstructs the expected vrf msg, and verify it with the sender's vrf signature/output and public key. 

as such, vrf msg are never sent over the wire. so the size of the vrf msg struct is not a concern. all output of vrf signing has fixed size.

**Comment by countvonzero** [comment]
> using a separate VRFMessage type that has 2 fields: the message to be signed and the nonce before encoding that with go-scale

note that there was a misunderstanding here. i didn't mean to have the nonce separate from the vrf message, but embedded in.
for example
```
type beaconVRF struct {
  beacon_eligibility
  nonce
  epoch  
}
```

**Comment by fasmat** [comment]
> only one vrf verifier instance is needed per node, not per vrf msg

This is already the case, there is only one instance of the VRF Verifier that is used to verify all signatures against their messages independent of who signed the message.
