### ISSUE TITLE
clock is skipping ticks

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#3909]
![image](https://user-images.githubusercontent.com/1964576/209544874-cfa6f15e-0806-42d6-8ee7-c76d89c630b0.png)

**Comment by dshulyak** [comment]
i wasn't actually aware that we can skip layers, this is super fragile..
there surely should be a warning, but never skip even if layer is late. it will just mess up protocols that are waiting for epoch start for example

**Comment by countvonzero** [comment]
i recall asking @noamnelke the same question. unfortunately i had forget the rationale.

**Comment by noamnelke** [comment]
Last time I was coding things related to the clock, I was in the process of eliminating ticks all together. When a protocol needs to do something at a certain layer, it should subscribe to be notified when that layer passes. It's then the specific protocol's responsibility to decide what to do if it gets notified too late (e.g. if computer was sleeping) and then subscribe to the next relevant layer (probably the next one that's in the wall-clock future).

If we send out a "tick" for every layer, then how do we handle a computer resuming from sleep in a way that makes sense? E.g. the computer has slept for 50 minutes - do we send 10 ticks in close succession or do we just send a single one the next time we cross a layer boundary? I can imagine things breaking regardless of what we choose here...

When waiting for the next epoch, you should subscribe to be notified upon its first layer. You'll get a channel in return and that channel will be closed when the layer passes (even if it's 45 minutes later).

**Comment by poszu** [comment]
@dshulyak, make sure you didn't hit a remanifestation of #3617.

**Comment by fasmat** [comment]
With the implementation of #4010 this log message has been removed. It is still possible to skip layers, due to any reasons that cause the node clock not to tick when it should, e.g. high CPU load as we see in #4020 or the node just hibernating.

This shouldn't happen in system tests, but a real node imo should be able to deal with skipped layers in the same way as if it was offline or not running for the time it skipped.

**Comment by dshulyak** [comment]
looks like it either got fixed, or we had problems with logging. i didn't observe it anymore. closing for now
