### ISSUE TITLE
Avoid storing the list of members of a Poet round in the proof

### ISSUE THREAD

**Issue by poszu** [spacemeshos/go-spacemesh#3929]
### Motivation
Currently, the Poet proof is stored in the following structure, along with a potentially huge list of all members of the respective poet round: https://github.com/spacemeshos/go-spacemesh/blob/5c7f4867ccbe1750b31862e9a4d5576621ebb3d3/common/types/activation.go#L343-L349

It is excessive (the proof is big). It should be enough to only store the merkle proof proving the sequential work. It should be the responsibility of the NiPoST to prove the NiPostChallenge it references is actually a member of the PoET.

### Proposal
The proposed changes are to:
- avoid storing a list of members in a poet proof,
- store a merkle proof proving membership in NiPoST,
- modify NiPoST validation as follows.

#### Updated structures:
```go
type NIPost struct {
	// A proof that the challenge for the PoET, which is
	// constructed from fields in the activation transaction,
	// is a member of the Poet's proof.
	// Proof.ProvenLeaves contains the challenge.
	// Proof.Root must match the Poet's POSW statement.
	Proof poetShared.MerkleProof

	// Post is the proof that the prover data is still stored (or was recomputed) at
	// the time he learned the challenge constructed from the PoET.
	Post *Post

	// PostMetadata is the Post metadata, associated with the proof.
	// The proof should be verified upon the metadata during the syntactic validation,
	// while the metadata should be verified during the contextual validation.
	PostMetadata *PostMetadata
}
```
```go
// PoetProof is the full PoET service proof of elapsed time. It includes the leaf count and the actual PoSW.
type PoetProof struct {
	poetShared.MerkleProof
	LeafCount      uint64
}
```

A node should store `PoetProof` along with the `statement` in a key-value store. The `Statement` will be later used to verify if the nipost challenge of an ATX is actually a member of a PoSW it references. For example:
```go
type PoetProofWithStatement {
	PoetProof
	// The input to Poet's POSW.
	// It's the root of a merkle tree built from all of the members
	// that are included in the proof.
	Statement []byte
}
```

#### Validation of a PoET in nipost builder
1. Construct a merkle tree from the list of poet round's members.
2. The root of the merkle tree is the PoET proof's `statement`.
3. Validate the PoET's merkle proof (POSW) with the `statement`
4. Save `PoetProof` in DB.

When a `PoetProof` is already saved in DB we consider it validated.

#### Validation of NiPoST in ATX handler
1. verify `NIPost.Proof`
2. obtain (from DB/fetch) `PoetProof` by its ref (`NIPost.PostMetadata.Challenge`)
  a. if poet proof needs to be fetched, validate it against `NIPost.Proof.Root`, which is (should be) the POSW `statement`
  b. otherwise verify if `NIPost.Proof.Root` == `proof.Statement` - this check proves the "elapsed time" part
3. verify NIPost.Post the same way as it is done now - this check proves that the smesher still held data after "elapsed time"

**Comment by dshulyak** [comment]
just two important limits from yesterday call:
- merkle path should be limited to some small'ish number based on the total number of members that poet can accept
- poet should limit total number of members, to ~100000, so then path should be max 17 i think
