### ISSUE TITLE
Consider replacing our DHT

### ISSUE THREAD

**Issue by noamnelke** [spacemeshos/go-spacemesh#393]
Our current implementation has a Distributed Hash Table (DHT) for peer discovery. This is not the simplest solution we could use and was originally selected because the previous Hare protocol depended on it. The current Hare protocol doesn't depend on it, so it may be worth considering to replace it with a simpler solution before releasing mainnet.

**Comment by y0sher** [comment]
We might use the DHT for service discovery (e.g `POET` servers or archival nodes) in the future.

for any protocol that will require "Probing" (resolving pubkey to ip) of other nodes for sending direct messages, `DHT` is well suitable. 
`Dolev Strong` used to require such capability but we our latest `Hare` protocol relays on `gossip` so it's not required.

**Comment by noamnelke** [comment]
If the only anticipated use-case for the `DHT` is `PoET` server discovery - I think it's worth considering a simpler solution.

E.g. each node can hold a list of references to `PoET` servers. When a node bootstraps it can query for `PoET` servers, in addition to neighbors, build its list and then select one to use, randomly.

Even if we keep the `DHT` we need some list of `PoET` servers (otherwise, how would we query for them?), so the only difference is that we'll now keep their IP and port in addition to an ID/pubkey.
