### ISSUE TITLE
Flaky Test_ValidateVRFNonce/wrong_commitmentAtxId

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#3944]
![image](https://user-images.githubusercontent.com/1964576/211560006-95b0e2d0-c9dc-4c68-8667-6e8626a82cf1.png)

https://github.com/spacemeshos/go-spacemesh/actions/runs/3883510948/jobs/6624908612

**Comment by fasmat** [comment]
duplicate of https://github.com/spacemeshos/go-spacemesh/issues/3884
