### ISSUE TITLE
malfeasance proof: prevent cross-data types misuse of eligibility

### ISSUE THREAD

**Issue by countvonzero** [spacemeshos/go-spacemesh#3967]
## Description
currently ATX, ballot and hare message uses different metadata for signing. and the code only validates that the same identity signed two different message hash.

since ATX and ballot metadata are structurally equivalent, a malicious actor can stitch up one metadata from ballot and one from atx for an honest identity H and convince the network that H is malicious.

the research team concluded that there should be shared metadata across all roles (beacon, ATX, ballots, hare for now, possibly validator... for future). such metadata has the structure below and is fixed-sized.

```
Metadata {
  Role: 1 byte
  Layer/Epoch: 4 bytes (Layer for ballots/hare roles, Epoch for beacon and ATX roles)
  Round: 2 bytes (for hare only, ignored for others. for hare it also infers)
  MessageHash: 32 bytes (the hash of the beacon/ATX/ballot/hare message body)
}
```

there were discussion on whether to include protocol versions into the metadata as well. the decision is nay.

the main idea here is not allowing for protocol versions enforce the rule:
one eligibility can be used for one role at most once, even across protocol versions.

for example, if spacemesh were to upgrade ATX protocol version from A->B. if a miner generates one ATX for version A and one ATX for version B in the same epoch, it is considered to be malicious.

**Comment by countvonzero** [comment]
@dshulyak @selfdual-brain

**Comment by selfdual-brain** [comment]
In the above, for the Hare case, I assume we use the "integrated" round number (i.e. where round and iteration is combined into a single number) ?

Looks OK to me, if not counting the fact that I would generally prefer the other design - with more flexibility, i.e. where the exact structure Metadata is specific per protocol. In the design proposed above the metadata is uniform across protocols, which is not buying us much advantage in terms of implementation cost or performance, but limits our flexibility regarding conflict-free evolution of the Spacemesh architecture.

**Comment by dshulyak** [comment]
This combined metadata looks super ugly, what was the argument not to prefix every message with one uint8 (domain separator)? i would personally use it for versioning as well, it is better than a layer id. Btw moving layer id from the first position will create a bit of a mess during upgrades

cleaner code would be:

```go
type Metadata struct {
      Domain uint8
      Enum Enum
      MsgHash32 [32]byte
}
```

> for example, if spacemesh were to upgrade ATX protocol version from A->B. if a miner generates one ATX for version A and one ATX for version B in the same epoch, it is considered to be malicious.

this is also seems off. i would personally update domain and leave it for the validation, so if atx proof validator can check domain is in any of activation domains. other validators may not need it.

**Comment by dshulyak** [comment]
also what about other signatures? is there a *some* confidence that one of the beacon message's can't be decoded into a valid hare message? i am pretty sure that every security report will mark this as a highest vulnerability.

i would use `Domain uint8` in every message (or atleast protocol) and make sure that it is unique. this is also a better versioning approach.

**Comment by countvonzero** [comment]
> In the above, for the Hare case, I assume we use the "integrated" round number (i.e. where round and iteration is combined into a single number) ?

iteration is inferred by round number. iteration = round % 4

**Comment by countvonzero** [comment]
@noamnelke can you help resolve this please?
i personally also prefer the prefix approach as well, as it's also simpler to implement. i am not sure why Tal and Iddo preferred this unified header/metadata.

**Comment by noamnelke** [comment]
I might have not paid attention when this was discussed in the meeting, or I would have objected in real-time. It's obviously counterproductive to shoehorn slightly different data structures into one, so we shouldn't. Regardless, for safety reasons I strongly agree with @dshulyak that every signature in the system should be prefixed with an identifier of the message type being signed. This identifier should not be included in the actual message on the wire or in the DB, but should be prepended to the pre-image before signing and validation, based on context that the node should have.

I also wholeheartedly agree with @dshulyak's point about keeping the layer/epoch ID as the first member of any data structure (with the semi-exception of the message type identifier that will be prepended).

So, to conclude, a malfeasance proof should have the following structure:
```golang
struct MalfeasanceProof {
	// used to deserialize the messages, and also needed since it's not explicit in the message
	Domain         uint8
	MessageHeader1 []byte
	MessageHeader2 []byte
}
```

The node can then deserialize the actual messages using the `Domain` hint. This will also be used to validate the signature.

This alleviates the need to have a common structure for all headers (a term I prefer over `Metadata`).

Does this answer all questions or did I miss something?

**Comment by countvonzero** [comment]
we already have the domain you described in malfeasance proof. the problem is that atx header and ballot header can serialize to the same byte data. so the discussion was about further adding domain into the header msg.

**Comment by noamnelke** [comment]
I think I addressed this when I said:
> [...] every signature in the system should be prefixed with an identifier of the message type being signed. This identifier should not be included in the actual message on the wire or in the DB, but should be prepended to the pre-image before signing and validation, based on context that the node should have.

To clarify: I think that the domain identifier should be prepended to every message being signed, but it's just not needed in the header. If the ballot and ATX headers have the same serialization, signature validation will fail if we prepend the domain identifier. This is exactly like adding it to the header, except you don't need to transmit or store it.

Still unclear?

**Comment by countvonzero** [comment]
> Still unclear?

understood now. thank you for highlighting for my benefit. 

> i would use Domain uint8 in every message (or atleast protocol) and make sure that it is unique. this is also a better versioning approach.

@dshulyak i think the research team agreed with you here. they just want to call it `role` using 1 byte.
i like @noamnelke 's proposal here. since we already have MalfeasanceType defined, the exact message type/domain can be inferred. do you agree?

**Comment by dshulyak** [comment]
i would also prefer to use domain as an explicit version, instead of layer/epoch as a first field, but i don't mind if described apparoach will be used instead
