### ISSUE TITLE
Hash immutable state into spawned template address

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#3977]
Rationale explained [here](https://spacemesh.slack.com/archives/CG91F13C7/p1674164777434639) in internal slack thread. It was discussed on today's research call. Basically, without this, it's trivially easy for someone to "clone" or "squat" the address of an existing, deployed contract (i.e., spawned template) (say, Uniswap) from chain X on chain Y. We shouldn't allow this.

We should emulate the behavior of Ethereum's [create2](https://eips.ethereum.org/EIPS/eip-1014).

CC @noamnelke, @selfdual-brain, @countvonzero, @dshulyak

**Comment by dshulyak** [comment]
and what can be achieved by such squating? contract ownership must be validated using immutable state, so this is basically a standard spawn use case. and the "squte" is just a "spawn".

i don't mind doing this ofcourse, i just think that this doesn't do anything

**Comment by dshulyak** [comment]
i realized that it doesn't quite work, or otherwise i misunderstood the idea

to generate address we have this function:
`principal = compute_principal(template, spawn_args)`
the suggestion is to change it to
`principal = compute_principal(principal, template, spawn_args)`
this has an obvious cycle in it

**Comment by lrettig** [comment]
We discussed this on yesterday's research call and decided to go with @selfdual-brain's "compromise" proposal: in future, we'll encourage template authors to include deployer address in immutable state, which would cause the deployer address to be hashed into the spawned template address (by, e.g., making this part of our default template code, automating this at the compiler level, etc.). This could be accomplished with a "spawn" method like the following:

```
fn spawn(pubkey, deployer_address, env) returns Address {
  assert env.sender == deployer_address;
  return new Address(hash(pubkey + deployer_address));
}
```

(Not including deployer address in immutable state should, in general, be considered an unsafe pattern and discouraged.)

However, this is not an issue for our genesis templates, as they all follow the "single tenant" use case and are intended to emulate Ethereum EOAs (which are already uniquely identified by one or more pubkeys).

I'll update this issue subject accordingly. Feel free to close this and link elsewhere if this is being tracked elsewhere.

**Comment by dshulyak** [comment]
@selfdual-brain clarified that it is not supposed to be used for self-spawn and will be used only by regular spawn
