### ISSUE TITLE
Use `spacemeshos/address` dependency

### ISSUE THREAD

**Issue by brusherru** [spacemeshos/go-spacemesh#3984]
## Description
Some time ago we made https://github.com/spacemeshos/address-wasm repo for Smapp purposes, which wraps the go library https://github.com/spacemeshos/address into wasm and provides JS-interface for it.

Meanwhile, `go-spacemesh` does not depend on `address` lib and still has a local copy.

Obviously it may cause some problems in the future like having two incompatible versions. To get rid of such risks let's reuse `address` lib as a dependency in go-spacemesh.

**Comment by lrettig** [comment]
Another option is to move this logic into the SDK (https://github.com/spacemeshos/spacemesh-sdk/), where there could be a single master version. Obvious downside is that's Rust and would have to come in as a dylib.
