### ISSUE TITLE
Flaky Test_multipleCPsAndIterations UT

### ISSUE THREAD

**Issue by poszu** [spacemeshos/go-spacemesh#4001]
## Description
Unit test `Test_multipleCPsAndIterations` is flaky

Example CI run: https://github.com/spacemeshos/go-spacemesh/actions/runs/3997966599/jobs/6859990376

**Comment by fasmat** [comment]
Test_multipleCPs is also flaky, probably for the same reasons.

**Comment by piersy** [comment]
AFAICS these haven't been particularly flaky on CI for a while now, but they become very flaky if trying to run tests without
the `-p 1` flag
