### ISSUE TITLE
Verify if a mutex is required in hare preround tracker

### ISSUE THREAD

**Issue by poszu** [spacemeshos/go-spacemesh#4007]
## Description
There is TODO to verify if a mutex is required.

## Affected code

This issue appears in commit hash: d9c39b6f925c97171a2ca1a5eafff7c3e8018d9e

Related files (optionally with line numbers): 
https://github.com/spacemeshos/go-spacemesh/blob/b08bdd7271416f5fc74cf3c1cd2e6bec48e979ba/hare/preroundtracker.go#L59

**Comment by countvonzero** [comment]
i am not sure why this is related to the commit as stated https://github.com/spacemeshos/go-spacemesh/commit/d9c39b6f925c97171a2ca1a5eafff7c3e8018d9e

messages in hare are first received by the gossip handler in broker.go, and dispatched to a channel for the intended consensus process. 
once dispatched, it's processed one by one by the consensus process. there is no need for mutex.

**Comment by poszu** [comment]
Then the comment can be removed and this issue can be closed.
