### ISSUE TITLE
investigate malfeasance proofs in devnet-323-short

### ISSUE THREAD

**Issue by countvonzero** [spacemeshos/go-spacemesh#4067]
## Description

metrics for malfeasance proofs in devnet-323-short running binary [v0.2.21-beta.0](https://github.com/spacemeshos/go-spacemesh/releases/tag/v0.2.21-beta.0)

![Screenshot from 2023-02-17 12-53-18](https://user-images.githubusercontent.com/30611210/219552596-03244978-98c4-4165-aee3-7d7b4d8f8483.png)

things that are wrong:
- metrics over-reported the proofs: in DB there are [atxs:1 ballots:72 hare:3] malfeasance proofs (total 76). metrics reported 121 total.
- ballots
  - a bug was discovered and fixed in https://github.com/spacemeshos/go-spacemesh/pull/4026/files#diff-352cd57ffb5b4a49d2aa14b595f10c044d2f89abfd5dbfb92362ff4e67d6c61dR696 but didn't make it into the binary
- there are not enough information to verify whether the malfeasance proofs are legit. for example, objects used for proofs were not recorded.
- no metrics to indicate the number of malicious identity, which should match the total of malfeasance proof metrics.

the network also reported 3 instances of hare equivocation. but it's not clear yet whether it's legitimate malfeasance or a software bug.

![Screenshot from 2023-02-17 13-07-48](https://user-images.githubusercontent.com/30611210/219554464-8ab72734-017e-41ff-955a-1f3b3655b2f3.png)

![Screenshot from 2023-02-17 13-08-12](https://user-images.githubusercontent.com/30611210/219554506-3935c713-337c-46c9-a86f-75788845b9bb.png)

![Screenshot from 2023-02-17 13-08-29](https://user-images.githubusercontent.com/30611210/219554522-9c47ce37-85b2-4b39-80a9-9def13f87b02.png)

**Comment by countvonzero** [comment]
to summarize the state of this issue.
- ballots equivocations was most likely a bug that was fixed in https://github.com/spacemeshos/go-spacemesh/pull/4026/files#diff-352cd57ffb5b4a49d2aa14b595f10c044d2f89abfd5dbfb92362ff4e67d6c61dR696
- atx and hare equivocations are still unclear. loggings were added to improve understanding in #4068

see #4085 for proposals

**Comment by lrettig** [comment]
anything pending here? Can this be closed?

**Comment by countvonzero** [comment]
mystery still unsolved. no code change is made.

**Comment by countvonzero** [comment]
many bugs have since been fixed regarding malfeasance proofs. closing this and will open new one for new networks.
