### ISSUE TITLE
mitigate slightly faster poet servers

### ISSUE THREAD

**Issue by countvonzero** [spacemeshos/go-spacemesh#4084]
## description

research discussion https://community.spacemesh.io/t/fast-poet-could-prevent-voting-by-honest-smeshers/339

specifically [Preventing Voting for Future Proposals in Hare](https://community.spacemesh.io/t/fast-poet-could-prevent-voting-by-honest-smeshers/339#preventing-voting-for-future-proposals-in-hare-3) will be implemented.

## implementation plan
- before:
hare preround participants voted for proposals that have the same beacon value as the participant
- after:
hare preround participants voted for proposals that
  - carry the same beacon value as the participant
  - reference ATXs that have lower tick height than the participant's own ATX

@noamnelke @pigmej

**Comment by fasmat** [comment]
as far as I understand the issue LGTM

**Comment by pigmej** [comment]
There was crucial update on the research forum about that topic: https://community.spacemesh.io/t/fast-poet-could-prevent-voting-by-honest-smeshers/339/5

**Comment by countvonzero** [comment]
> There was crucial update on the research forum about that topic: https://community.spacemesh.io/t/fast-poet-could-prevent-voting-by-honest-smeshers/339/5

thanks. the current implementation is consistent with the update.
