### ISSUE TITLE
temporarily disable identity cancellation for ballot and hare equivocation

### ISSUE THREAD

**Issue by countvonzero** [spacemeshos/go-spacemesh#4086]
## Description

https://github.com/spacemeshos/go-spacemesh/issues/4067 most likely caused devnet-323-short grind to a halt because too many identities are canceled.

before we understand whether this is a software bug or actual malicious behavior, during Gdansk research meeting, @tal-m agreed that it's ok to not cancel identity for ballot and hare equivocation while the dev clarify the cause of equivocations.

**Comment by dshulyak** [comment]
i am not sure if we are doing it, but it is clearly not ok to count ballots with the same eligibility in the tortoise. as it breaks the tortoise

**Comment by countvonzero** [comment]
this is an idea from Gdansk where Tal feels ok to do so. not fully fleshed out. we should discuss with Tal again.

**Comment by dshulyak** [comment]
i think there is no plan to do it. please reopen if i am wrong
