### ISSUE TITLE
recover from a checkpoint state

### ISSUE THREAD

**Issue by countvonzero** [spacemeshos/go-spacemesh#4090]
## description

when multiple errors cascade in the network, it's very likely that network stalls to a grind. in situations where mesh data is in a bad state such that tortoise cannot make progress, we want to revert to a genesis-like state and restart tortoise.

## considerations:
- preserve global state (accounts/stubs balances)
- accounts do not need to be re-spawned (via preserving account state)
- prevent replay attack on transactions (via reserving account nonce)
- preserve ATXs so that smeshers do not have to re-initialize the storage (keep the same genesis ID)
- it's ok to reset vesting schedule (the only vesting account is for investors/devs)
- rewards for staying in the network (?)

## proposal
the spacemesh administrator will provide a json file that contains necessary data for the network to recover.
the revived network will use the same genesis ID so that miners can use existing identities and PoST data.

### recovery data
- reboot layer: the first layer the revived network will start running hare protocol
  - tortoise will tally votes starting from this layer
  - syncer and mesh will manage mesh and states from this layer

- active set: the bootsrapping active set at reboot layer

- beacon: the bootstrapping beacon at reboot epoch

- snapshot of all ATXs: this is the most recent ATX of each miner. it serves two main purposes:
  - miners do not need to re-initialize their PoST data
  - used as previous/positioning ATX for building next ATXs in the revived network

  each ATX should contain
    - coinbase (for the first epoch rewards after recovery)
    - space unit (numUnit) (?) 
    - tick height (base tick height + tick count), for new ATX's base tick height
    - vrf nonce (for building new ATX)
    - commitment atx (for building new ATX)
    - publish layer (?)
    - sequence
    - initial post indices (?)

- snapshot of accounts at a known good layer

### a known good layer to recover state from
the spacemesh administrator manually determine a known good layer. (manner TBD)

### dump recovery data
given a known good layer, issue an RPC to a node that does the following
- start a sql transaction, do
- query latest accounts data before reboot layer 
- query latest atxs data before reboot layer
- dump result into json file

the spacemesh administrator should dump recovery data from multiple nodes to verify that
the dumped data are identical.

### load recovery data
node operator download the recovery data from spacemesh website and restart go-spacemesh 
binary with --recovery_data pointing to this file. the node will do the following on startup
- backup the old database
- create new database
- fill the account table with the account snapshot
- fill the atxs table with most recent ATXs from miners
- set effective genesis layer to reboot layer - 1

### implementation
- [x] https://github.com/spacemeshos/go-spacemesh/issues/3774
- [x] https://github.com/spacemeshos/go-spacemesh/issues/4284
- [x] #4345
- [x] #4368
- [x] #4404 
- [x] #4405  
- [x] #4406  
- [x] #4485

**Comment by dshulyak** [comment]
i realized that we technically don't need any revert on vm if the block that we want to target was already applied. vm stores accounts with a version (version is layer number), so to get the state at layer 10 - we need to load account state at layer 10 or below. it is better because you can do snapshot without stopping node, so testing is simpler, and you can do that just periodically.

why do you need to pause syncer/hare ? i think you can just open sql transaction, select atx data, select account data (as described above), close tx, dump data. read sql transaction can be open for as long as you need it, it won't affect anything else, but you will have same concurrency guarantees

**Comment by countvonzero** [comment]
> why do you need to pause syncer/hare ? 

i missed the fact that accounts table is versioned by layer! that's why i want to freeze the mesh after revert. syncer and hare are the only two components that can advance the mesh state. now it's not necessary.

> read sql transaction can be open for as long as you need it, it won't affect anything else, but you will have same concurrency guarantees

yes. will update the description.

**Comment by countvonzero** [comment]
adding discussion from slack:

from kimmy
```
questions about checkpoint recovery 

say we checkpoint at layer 200. recover at 205.
but only part of the network recovered from this checkpoint file, say partition A, partition B 
continues on with the old mesh.
how should we handle gossip from partition B->A? say a layer 210 ballot from miners in B
and direct peer fetch requests from A->B? say syncing a block certificate for layer 210
currently the only way i can think of is to add some protocol id in gossip/sync requests... any ideas?
```
from Iddo
```
When we establish secure channel (sodium secretbox) with peer we should check that the peer's
protocol_id us high enough, and drop the peer if he later sends signed messages (such as ballots) 
with lower protocol_id ? Even for the discovery protocol it's better to store in the address book tuples 
(pubkey, ip_address, protocol_id) rather than just (pubkey, ip_address) so that we wouldn't try to 
select a random peer (for establishing a new secure channel) whose protocol_id is too low.
```
from Dmitry
```
Yes a bump in the protocol will do. Technically it is a bump in what we pass to libp2p
```
from kimmy
```
thanks both. let me double-check on what i understood.
afaik we have the following 3 kinds of protocol versioning
1. peers connection: handshake protocol version
this prevents establishing peer connection btwn partition A and B
2. gossip: gossip topic version per data type
this prevents gossip msgs mixing btwn partition A and B
3. direct peer requests: protocol version per data type
this prevents fetching data btwn partition A and B
i think updating 1 is sufficient?
```
from Iddo
```
kimmy, If I understand correctly then the way that any communication is done is by discovery 
(to maintain address book of potential peers) and then (1) establishing secure channel with 
several peers and doing all the gossip and direct peer requests with them.
So we just check the protocol_id during (1) and refuse to talk with a peer that has a low 
protocol_id, but if the peer is malicious then he might later send gossip data (2) with wrong 
protocol_id so if we does it for the kind of data that the protocol_id is important (such as ballots 
after the layer in which the upgrade happened because we don't want to count the ballots of 
the old version after that layer) then we should drop/blacklist this peer.

I also mentioned that for the discovery it would be nice to have the protocol_id of each potential 
peer, so if we can do that then that's better.
```
from Dmitry
```
> i think updating 1 is sufficient?
i would rather update all relevant protocols. handshake doesn't block negotiation of the protocol, 
so if we also do what Iddo said (as we should), then we may erroneously blacklist node that was 
slow with update
```

a followup conversation with Dmitry regarding 
> handshake doesn't block negotiation of the protocol

the order of peer handshake and gossip messages are not guaranteed. there was concurrency 
issues observed. there maybe a setting to guarantee but it's safer all around to update all protocols.
