### ISSUE TITLE
revisit collections limits and apply sane max values

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#4095]
some time ago we added feature to go-scale that allows to limit memory allocation size for collections. the default is set to 1 << 20, so that scale can be used for any types in go-spacemesh. this is arguable a security hole and needs to be addressed.

https://github.com/spacemeshos/go-scale/blob/master/examples/bytes.go#L21-L23

**Comment by fasmat** [comment]
should we move this to the `go-scale` repository?

**Comment by dshulyak** [comment]
we will have to add `scale:"max=XX"` annotations in this repository
