### ISSUE TITLE
hare data volume improvement ideas

### ISSUE THREAD

**Issue by countvonzero** [spacemeshos/go-spacemesh#4099]
## Description
following are current non-exhaustive ideas to reduce hare live traffic volume:

### 32 byte MsgHash in every hare message
```go
type HareMetadata struct {
	Layer LayerID
	// the round counter (K)
	Round uint32
	// hash of hare.Message.InnerMessage
	MsgHash Hash32
}
```
the `MsgHash` field is used to decide whether the same identity signed two different messages (hashes). `HareMetadata`+signature is then kept in malfeasance proof for perpetuity. however, in real-time we can calculate that from the message body and can be removed from live traffic.

### repetitive layer ID, round and committed round
in notify round, we gossip the hare certificate that contains a list of commit messages from the commit round. each of the message has the same value for layer ID and round. committed round is irrelevant after proposal round (based on current impl), but it is part of the signed pre-image. note that integers are encoded to variable-length ints in scale

### use fixed size types
byte slice is encoded with length prefix in scale. for example, signature can be a [64]byte instead of []byte.

**Comment by dshulyak** [comment]
i think what is written here is already covered in https://github.com/spacemeshos/go-spacemesh/issues/4099 . lets keep one bug, as this stuff is pretty much about the same thing
