### ISSUE TITLE
investigate partition test failure 

### ISSUE THREAD

**Issue by countvonzero** [spacemeshos/go-spacemesh#4112]
## Description

this failure https://github.com/spacemeshos/go-spacemesh/actions/runs/4300663720/jobs/7497080392 
is from this PR https://github.com/spacemeshos/go-spacemesh/pull/4105
namespace `test-havd`

the PR should not impact tortoise. same partition-50-50 test was run in systemtest nodepool 5 times in a row and passed.
tortoise from two sides disagreed on layer 16. i checked boot-0-0 and boot-1-0, they received the same amount of ballots (869 of them)

**Comment by dshulyak** [comment]
so far i don't see any bug in the tortoise. maybe it will be worth talking about beacon<>self-healing interaction, it doesn't seem to be nice.

block was generated at layer 16 on one side of the partition (boot-1-0 side):
![image](https://user-images.githubusercontent.com/1964576/222693349-3babd9b7-95df-4253-b05a-2cf242a6f05d.png)

that side voted for it and confirmed it early
![image](https://user-images.githubusercontent.com/1964576/222693468-409836da-5ec4-483c-8c3d-983ab21c1a59.png)

based on the beacon value partition lasted starting at from layer 20 till layer 30. logs are a bit verbose, but here they are [ballot has different beacon logs](https://grafana.spacemesh.dev/explore?orgId=1&left=%7B%22datasource%22:%22loki-gke-dev%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki-gke-dev%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22%7Bnamespace%3D%5C%22test-havd%5C%22,%20pod%3D%5C%22boot-1-0%5C%22%7D%20%7C%3D%20%5C%22trtl%5C%22%20%7C%3D%20%5C%22ballot%20has%20different%5C%22%22,%22queryType%22:%22range%22%7D%5D,%22range%22:%7B%22from%22:%221677631495491%22,%22to%22:%221677677594254%22%7D%7D)

we delay counting ballots with different beacons to prevent concentration of the weight, therefore nodes on the side of the boot-0-0 are voting against the block, during the time while partition lasts.

later when there is no difference in beacon partition on the side of boot-0-0 seems to terminate the same way as boot-1-0 side.

![image](https://user-images.githubusercontent.com/1964576/222694683-d9be1503-eebc-45af-bf18-fe08ff0c509f.png)

so i don't see anything bug-like, but the protocol behavior doesn't seem to be good in this case. will have to ask Tal probably

**Comment by dshulyak** [comment]
beacons 

![image](https://user-images.githubusercontent.com/1964576/222695971-bf8fbd8a-00c1-472c-ad47-03003dc71f4b.png)

**Comment by dshulyak** [comment]
@countvonzero would it make sense to tune the duration of the partition? based on the logs it lasted for 3 epochs, maybe with 1-2 recovery will be faster

**Comment by dshulyak** [comment]
this kind of failures are close to undebugable for me. it is possible to make some guesses but they still don't make complete sense. i think i will need some tracing capabilities to replay events as they are received

**Comment by dshulyak** [comment]
it seems stable after reducing ballot delay value? i will close the issue for now
