### ISSUE TITLE
Review closing code to prevent goroutines from leaking

### ISSUE THREAD

**Issue by piersy** [spacemeshos/go-spacemesh#4128]
## Description
There seem to be lots of places in the code that are leaking goroutines, we should start using goleak in all our tests to make ourselves aware of leaked goroutines. Leaked goroutines can lead to flaky tests, memory leaks and persistent data corruption, so its important that we ensure that we are gracefully closing goroutines that we have started.

**Comment by dshulyak** [comment]
just to track where are the offenders

![image](https://user-images.githubusercontent.com/1964576/223488346-9857c050-9b6f-4700-90dd-624e2a032891.png)
