### ISSUE TITLE
Settle on block, layer (,etc...) type and size

### ISSUE THREAD

**Issue by y0sher** [spacemeshos/go-spacemesh#413]
# Overview / Motivation

As pieces start to connect within the node towards MS-1.0, we want different modules to speak (almost) the same language when referring to protocol primitives, as `BlockID`, `LayerID` and more.

# The Task

Decide on a system-wide type and size that would be used for `BlockID` , `LayerID` and possibly other primitives. and change all modules to use same implementation or implement the same types. 

# Implementation Notes

Currently different modules consider different types. `hare` treats blocks ids (or values in his terms) as 32 byte arrays. `sync` and `mesh` use a uint32.

*NOTE*: This issue doesn't mean that blockid and layerid should use the same type or underlying type.

# Contribution Guidelines
Important: Issue assignment to developers will be by the order of their application and proficiency level according to the tasks complexity. We will not assign tasks to developers who have'nt introduced themselves on our Gitter [dev channel](https://gitter.im/spacemesh-os/Lobby)

1. Introduce yourself on go-spacemesh [dev chat channel](https://gitter.im/spacemesh-os/Lobby) - ask our team any question you may have about this task
2. Fork branch `develop` to your own repo and work in your repo
3. You must document all methods, enums and types with [godoc comments](https://blog.golang.org/godoc-documenting-go-code)
4. You must write go unit tests for all types and methods when submitting a component, and integration tests if you submit a feature
5. When ready for code review, submit a PR from your repo back to branch `develop`
6. Attach relevant issue to PR

**Comment by almogdepaz** [comment]
@y0sher there is a pkg called types where all this is decided 
all pkg's should use the shared types then we can avoid discrepancies
