### ISSUE TITLE
crypto: use canonical ed25519 signature in all domains except HARE

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#4139]
domains were recently added and specified here https://github.com/spacemeshos/go-spacemesh/blob/develop/signing/signer.go#L19-L23

all domains except hare will avoid public key extraction and can use canonical ed25519 (both curve-voi and stdlib are good). my preference is towards curve-voi for performance, and stricter verification. additionally we may use batch verification in the future during sync.

#### BEACON

ProposalMessage includes NodeID. FirstVotingMessage and FollowingVotingMessage have to be extended with PublicKey.

#### ATX

Initial ATX will have to include public key in the body of atx, to guarantee that initial atx is unique (not sure if this is necessary, if we are using strict signature). Public key can be always found by following the chain of references.

But in order to enable validation without downloading full chain of atxs, public key can be also attached to every message.

#### BALLOT    
 
Similarly to ATXs, ballot can recover public key by following chain of references. However we would like to enable more efficient validation as well, so that signature can be validated before doing any disk reads or requests from peers. 

#### POET

Public key needs to be sent as a part of the message.

#### Malfeasance proofs

It is not a separate domain, but the proofs will have to be extended with public key as well.

#### Summary & Changes

With several exceptions (hare, and messages that include only output from vrf) we can encode messages that are sent over the wire using next pattern:

message + signature + public key

it is equivalent to the next golang type

```go
type SignedMessage[T scale.Type] struct {
     Message  T
     Signature [64]byte
     PublicKey [32]byte
}
```

**Comment by countvonzero** [comment]
regarding ATX

> But in order to enable validation without downloading full chain of atxs, public key can be also attached to every message.

with the prev_atx field, the public key can be looked up in database.

**Comment by dshulyak** [comment]
> with the prev_atx field, the public key can be looked up in database.

it can be done both with atxs and ballots (if we preserve reference to atx id at least for reference ballot). but i think that it will be better to gossip public key together with the message. in order to validate signature as a first step in the validation pipeline
