### ISSUE TITLE
Logging configuration

### ISSUE THREAD

**Issue by piersy** [spacemeshos/go-spacemesh#4174]
## Description
Currently there is no way to configure a global log level, logging must be configured on a per module basis. Also the AppLogger acts as a sort of gate to the log levels set for each module. If a modules log is set to a more detailed level than that of the AppLogger then it will have its level set to the default of info. Thus it's impossible to set the log level of any module to a certain detail level unless the AppLogger is at least that level.

It should be possible to set a global default log level and it should also be possible to configure the level of each module independently.

We will likely want to use `zap.AtomicLevel` to achieve this.

## Affected code
Log config code

This issue appears in commit hash: a57b3305070b11c9f9fb4e427308224791302172

**Comment by dshulyak** [comment]
@piersy do you want to submit fix for original problem? i can do that if you plan to work on bigger refactoring longer, but i think we need fix asap

**Comment by countvonzero** [comment]
> This issue appears in commit hash: https://github.com/spacemeshos/go-spacemesh/commit/a57b3305070b11c9f9fb4e427308224791302172

i cannot put two and two together. what is wrong with this commit logging wise? @piersy
