### ISSUE TITLE
ballot: include active set hash in signature instead of the set itself

### ISSUE THREAD

**Issue by countvonzero** [spacemeshos/go-spacemesh#4237]
## Description
as active set data size is large, the node should de-duplicate active set from peers and and transmit/store just one copy of it for all honest ATXs of the epoch.

- when generating the first ballot, we get all the atxs in the previous epoch
  - sort the active set (AS) and generate hash(AS)
  - sign the ballot that includes hash(AS)
  - gossip ballot, and attach AS to the gossip message
  - locally save hash(AS)->AS mapping
- when receiving a ballot via gossip:
  - if the gossip msg doesn't have AS attached, this ballot is invalid
  - validate the ballot as usual
  - locally save hash(AS)->AS mapping
- when a node requesting a ballot during sync, the peer send the ballot, also attaching the corresponding AS

for genesis, we can delay implementing the mapping. simply define the first ballot to always be serialized/deserialized as (x=ballot_containing_hash(AS), AS, signature_of_x). in other words, always send/receive the full data and assume that any other format of transmitting this data is malicious

after genesis, optimization can be done by not transmitting the actual active set and only fetch from peers by its hash.

**Comment by dshulyak** [comment]
i think this was implemented
