### ISSUE TITLE
flaky Test_CalcEligibility_MainnetParams

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#4273]
![image](https://user-images.githubusercontent.com/1964576/231075899-e776cb7a-3e29-42bb-9ca7-0b53fd85f2ae.png)

https://github.com/spacemeshos/go-spacemesh/actions/runs/4664438812/jobs/8256690009

**Comment by fasmat** [comment]
Test has been removed as part of https://github.com/spacemeshos/go-spacemesh/issues/4241
