### ISSUE TITLE
Node crashes on start smeshing

### ISSUE THREAD

**Issue by brusherru** [spacemeshos/go-spacemesh#4287]
## Description
The node crashes on start smeshing (called via GRPC API the first time, having only `key.bin` in the directory).

## Steps to reproduce
1. Clean up `~/post`
1. Run go-spacemesh with turned off smeshing (`"smeshing": {}` in node-config.json)
2. Call GRPC API `SmesherService.StartSmeshing` with valid opts, like this:
    ```
      {
        "coinbase": {
            "address": "stest1qqqqqqp8r9d6yzz8kqc3e9t0rgtlu8jwhlhyc4gm2xaut"
        },
        "opts": {
            "data_dir": "/Users/username/post/data",
            "num_units": 4,
            "max_file_size": 2147483648,
            "compute_provider_id": 1,
            "throttle": false
        }
    }
    ```
    In this example, I used the same default directory `~/post/data`.

## Actual Behavior
It crashes with a long stack trace.
Check out logs and generated files in the archive: [node-crash.zip](https://github.com/spacemeshos/go-spacemesh/files/11216426/node-crash.zip)

## Expected Behavior
It should start smeshing without any errors.

## Environment
 - Node Version: 0.3.0-beta.0
 - Faced on Testnet-03 within genesis phase

**Comment by piersy** [comment]
I think this was caused by spacemeshos/post#120 which added an option `config.InitOpts.ComputeBatchSize` which was used in place of the default value, but no corresponding change was made in this repo to set that option.
