### ISSUE TITLE
invalid initial Post: verify PoST: invalid proof

### ISSUE THREAD

**Issue by pigmej** [spacemeshos/go-spacemesh#4328]
Observed on testnet-03 cloud miners

```
2023-04-16T09:02:08.510+0300    WARN    12140.atxHandler        failed to process atx gossip   ..."12D3KooWHtpowTvREKRESWK87Qsyb6JZoiANnQB6VE4jozA4qtTU", "errmsg": "received syntactically invalid atx 3fe004fe43: invalid initial Post: verify PoST: invalid proof", "name": "atxHandler"
```

Our two miner nodes running in different phase decided ` verify PoST: invalid proof` the keys, and everything is valid.

**Comment by dshulyak** [comment]
This is easy to reproduce locally, if you have post data and metadata. code to reproduce https://github.com/dshulyak/go-spacemesh/blob/prepare-post-debug/activation/post_test.go#L326-L365

Similar error was also reported by testnet users, this is one that was shared with me:
> 57368:Proof is invalid: value for index: 693849119 doesn't satisfy difficulty: 1556101589490121197 > 2396591751167 (label: [233, 21, 98, 231, 206, 207, 47, 163, 125, 146, 146, 22, 57, 23, 36, 236])

in general i think that overwhelming majority of testnet users simply crashed with this error

**Comment by pigmej** [comment]
It's very likely caused by https://github.com/spacemeshos/gpu-post/issues/100
