### ISSUE TITLE
fallback: detect new fallback content

### ISSUE THREAD

**Issue by countvonzero** [spacemeshos/go-spacemesh#4342]
## description
once the spacemesh admin provides the network fallback data, each node will continue to query the url and realize the content is unchanged, until the admin delete the file from the gs bucket.

## mitigations
- short-term:
  - for beacon in epoch N: delete it ~5 layers after epoch N starts (this file is tiny. just a 4 byte beacon value + json text)
  - for activeset fallback, prolly best to keep it for the whole epoch. 10K *32byte atx ID + json text

- medium-term:
consider use etag to detect new content

- long-term:
remove the needs to have network fallback

**Comment by dshulyak** [comment]
i think we estimated overhead wrongly, it is not 100-200MB, it is 1-2GB of additional data per day.
given 10000 atxs in json file, 64 bytes per atx (hexary encoding). every 30s the data is downloaded, around 1.8GB per day.
so seems very important to fix this

**Comment by countvonzero** [comment]
@dshulyak 
first we can easily make it every 2 min. so that's 4X less.

would like to understand the severity.
putting cost aside, do you think 64KB-70KB every 2 min interrupt the node somehow (other than being wasteful)?

**Comment by pigmej** [comment]
@countvonzero if I'm not mistaken 64 * 10000 is 640kB not 64.

Therefore it's a lot of traffic. Given that it's http(s) I'm pretty sure that there are existing cache mixins available in go that we could just use.


Partial content from GPT :)


```
package main

import (
	"bytes"
	"crypto/md5"
	"encoding/hex"
	"fmt"
	"io/ioutil"
	"net/http"
	"net/http/httptest"
	"sync"
	"time"
)

type cacheEntry struct {
	etag   string
	expiry time.Time
	body   []byte
}

type cachingTransport struct {
	http.RoundTripper
	cache sync.Map
}

func (t *cachingTransport) RoundTrip(req *http.Request) (*http.Response, error) {
	if req.Method != http.MethodGet {
		return t.RoundTripper.RoundTrip(req)
	}

	key := req.URL.String()
	entry, found := t.cache.Load(key)

	// If cache entry found and not expired, return it
	if found {
		cached := entry.(*cacheEntry)
		if time.Now().Before(cached.expiry) {
			req.Header.Set("If-None-Match", cached.etag)
		}
	}

	// Perform the actual request
	resp, err := t.RoundTripper.RoundTrip(req)
	if err != nil {
		return nil, err
	}

	// If status is 304 Not Modified, return the cached response
	if found && resp.StatusCode == http.StatusNotModified {
		cachedResp := &http.Response{
			Status:           resp.Status,
			StatusCode:       resp.StatusCode,
			Proto:            resp.Proto,
			ProtoMajor:       resp.ProtoMajor,
			ProtoMinor:       resp.ProtoMinor,
			Request:          req,
			Header:           resp.Header,
			Body:             ioutil.NopCloser(bytes.NewReader(entry.(*cacheEntry).body)),
			ContentLength:    int64(len(entry.(*cacheEntry).body)),
			TransferEncoding: resp.TransferEncoding,
			Close:            resp.Close,
			Uncompressed:     resp.Uncompressed,
			Trailer:          resp.Trailer,
		}
		resp.Body.Close()
		return cachedResp, nil
	}

	// Cache the response
	etag := resp.Header.Get("ETag")
	cc := resp.Header.Get("Cache-Control")
	expiry := parseCacheControl(cc)

	if etag != "" && !expiry.IsZero() {
		body, err := ioutil.ReadAll(resp.Body)
		if err != nil {
			return nil, err
		}
		resp.Body.Close()
		resp.Body = ioutil.NopCloser(bytes.NewReader(body))

		entry := &cacheEntry{
			etag:   etag,
			expiry: expiry,
			body:   body,
		}
		t.cache.Store(key, entry)
	}

	return resp, nil
}

func parseCacheControl(cc string) time.Time {
	var maxAge time.Duration

	_, err := fmt.Sscanf(cc, "max-age=%d", &maxAge)
	if err != nil {
		return time.Time{}
	}

	return time.Now().Add(maxAge * time.Second)
}

func main() {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("ETag", "12345")
		w.Header().Set("Cache-Control", "max-age=10")
		w.Write([]byte("Hello, world!"))
	}))
	defer server.Close()

	client := &http.Client{
		Transport: &cachingTransport{
			RoundTripper: http.DefaultTransport,
		},
	}

	for i := 0; i < 3; i++ {
		resp, err := client

```

**Comment by countvonzero** [comment]
@pigmej 
sorry about the wrong math. i am not arguing it's a difficult change. i just want to understand the concerns. 

there is a disconnection on my part.
why do i think it's small amount of traffic for a node (640KB every 2 min), whereas you and @dshulyak think it's a lot. 
i want to understand what i am missing.

i already understand the cost issue. i want to understand the scale of impact in terms of a node's overall traffic.

**Comment by pigmej** [comment]
I think it's a lot too :)

**Comment by pigmej** [comment]
~500MB daily of "extra" traffic for not a big reason (that's already with your x4 opt). It's a lot. That would be 15TB monthly traffic per node.

Out of many reasons why it's a lot, for example:
* 500MB is 1hour one-to-one video on zoom call,
* 640kB of data being downloaded at 10Mbps will take 0.5seconds. That's 0.5 seconds every 120 seconds which makes it close to 0.5% of time downloading the file (not to mention a CPU & ram needed to process JSON)
* That's per *every* node. So if one wants to run some small node on some VPS for API experimenting, then he'd need to have 15TB traffic included per node, etc.

I think if we can fix it "for cheap" using `etag` and normal HTTP protocol cache rules then I think it's really "cheap" and hopefully fast fix with huge bandwidth savings.

And since we control the other end, we can pretty much make the e-tag cache to be valid ~forever.

**Comment by countvonzero** [comment]
let me try it this way.

in our latest 2K nodes tests. with hare committee set to 200. the average traffic is 500KB/s.

if there is another task to reduce hare traffic, which happens every at least once every 5 min with 500KB/s.
compared to this file 
- generated only when hare fails continuously for N layer
- kept for max time 2 weeks

which one would like to fix first? this is the kind of comparison i am asking for prioritizing purposes.
