### ISSUE TITLE
Add basic auth to metrics-push

### ISSUE THREAD

**Issue by pigmej** [spacemeshos/go-spacemesh#4421]
https://github.com/prometheus/client_golang/blob/v1.15.1/prometheus/push/push.go#L70 the lib supports it, we should expose that as a config.

**Comment by poszu** [comment]
Perhaps we should turn it around and expose a `/metrics` endpoint in a node and fetch metrics from there instead of pushing metrics?

**Comment by pigmej** [comment]
@poszu some of these nodes will be behind NAT, some on constrained env, some will die some be created again etc.
