### ISSUE TITLE
actvation: handler doesn't handle duplicates well

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#4426]
![image](https://github.com/spacemeshos/go-spacemesh/assets/1964576/afc84838-c253-48a4-9860-a58a5bf36b26)

green is fully processed, yellow - ignored, e.g. were processed previously.

as you can see on the screen handler on some nodes process as much as 1.5x of unique activations. in this case number of unique activations is ~1000.  it doesn't affect state, as they have unique ids and will be indexed by them, but will increase resource usage for no good reason.

**Comment by fasmat** [comment]
fixed in #5379
