### ISSUE TITLE
fetch: FuzzMeshHashRequest crashes with out of memory error.

### ISSUE THREAD

**Issue by fasmat** [spacemeshos/go-spacemesh#4427]
## Description
As part of the work on https://github.com/spacemeshos/go-spacemesh/issues/4439 the following issue was identified:

When fuzzing `FuzzMeshHashRequest` eventually the test will crash with a generic error message:

```shell
--- FAIL: FuzzMeshHashRequest (24.30s)
    fuzzing process terminated by unexpected signal; no crash will be recorded: signal: killed
```

## Steps to reproduce
1. Run `go test ./fetch -v -run=FuzzMeshHashRequest -fuzz=^FuzzMeshHashRequest$` for at least 30 seconds
2. Observe memory consumption of the process (keeps increasing)
3. Eventually `go test` will be terminated by the OS because it consumes more memory than available.

## Actual Behavior
Process termination due to high memory consumption

## Expected Behavior
Fuzzing should continue without a crash

## Environment
Please complete the following information:
 - OS: Linux
 - Node Version: develop `2a36d0455f024bb7fcb2d126bc096526211ee292`

## Additional Info 

The culprit is seems to be `layers.GetAggHashes`. It will cause a crash by building a very large SQL query:

```golang
func TestGetAggHashesOom(t *testing.T) {
	db := sql.InMemory()

	lids := make([]types.LayerID, 0, math.MaxUint32)
	for i := 0; i < math.MaxUint32; i++ {
		lids = append(lids, types.LayerID(i))
	}

	GetAggHashes(db, lids)
}
```

**Comment by fasmat** [comment]
cc @dshulyak

A quick fix would be to limit the number of layers that can be queried in one request (maybe to 1000?) or alternatively rewrite the sql from

```sql
select aggregated_hash from layers where id in (...) order by id asc;
```

to 

```sql
select aggregated_hash from layers where id >= (start) and id <= (to) and (id-(start))%(stepsize) = 0 order by id asc;
```

to not require building a large query in the first place.

EDIT: the request already contains a `from`, `to` and `steps` that can be used in the query (after sanity checking of course)

**Comment by dshulyak** [comment]
btw there exists https://github.com/spacemeshos/go-spacemesh/issues/4389

we need to rework mesh hash request api completely. it also has out of bounds vulnerability in there

**Comment by fasmat** [comment]
I would still make a small PR limiting the number of layers that can be queried at once to avoid memory issues, since it is a relatively small change and shouldn't break anything.
