### ISSUE TITLE
Implement hare 3.0

### ISSUE THREAD

**Issue by piersy** [spacemeshos/go-spacemesh#4456]
- [x] https://github.com/spacemeshos/go-spacemesh/issues/4494
- [x] https://github.com/spacemeshos/go-spacemesh/issues/4563
- [x] https://github.com/spacemeshos/go-spacemesh/issues/4648
- [x] https://github.com/spacemeshos/go-spacemesh/issues/4649
- [x] https://github.com/spacemeshos/go-spacemesh/issues/4650

**Comment by dshulyak** [comment]
i think we should use hare 2 instead of hare 3 for the sake of the implementation versioning. hare 2 didn't really came out of the private research discussions

**Comment by piersy** [comment]
Ok, so we'll call it hare 2.0 in the code, but we'll use what we are currently referring to as the hare 3.0 spec.

**Comment by piersy** [comment]
So it was decided that it would be easier if we just refer to this as hare 3.0 and have a gap in the versioning, so from now on both the conceptual design and the implementation will be referred to as hare3 or hare 3.0
