### ISSUE TITLE
syncer: fetch activations during genesis

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#4469]
if node is started in epoch 1 it will not ask peers for activations that target epoch 2.
as a consequence it will have low base ballot weight, if it publishes atx that targets epoch 3

**Comment by dshulyak** [comment]
@countvonzero clarified that it will ask atxs at the end of epoch 1, but this is already too late too to use them as a positioning

**Comment by countvonzero** [comment]
thanks @dshulyak 
the problem is that node will consider itself `atxSynced` if it joins during genesis and will not sync atx until the end of epoch.
will improve. thanks
