### ISSUE TITLE
Modify ForkFinder such that the responder determines the limit for requested hashes

### ISSUE THREAD

**Issue by piersy** [spacemeshos/go-spacemesh#4486]
## Description

The way that the fork finder works is that the requester requests a range of hashes and they will ensure that their request does not exceed MaxHashesInReq. But if the responder has a lower MaxHashesInReq configured then the request will fail. In a network where the the values for MaxHashesInReq are distributed across some range, the nodes with the highest MaxHashesInReq values can be locked out of the network, since their requests will always be rejected.

Instead the requester should define a range and if it exceeds the responder's MaxHashesInReq then the responder should sub-sample that range so that they return MaxHashesInReq and an indication of how the sub-sampling was performed so that the requester can understand what hashes they have received.

## Affected code
Code in the fetch package.

This issue appears in commit hash: ea496f4708f9475a7b85a53c22ec88d5c29669cd

**Comment by countvonzero** [comment]
the solution sound more complicated than it need.
it suffice to define a constant in fetcher for max hashes in request. 
there is no good reason for nodes to want a different value.

**Comment by piersy** [comment]
@countvonzero agreed!
