### ISSUE TITLE
TestCheckpoint flake

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#4488]
> === CONT  TestCheckpoint
    checkpoint_test.go:198: 
        	Error Trace:	/build/systest/tests/checkpoint_test.go:198
        	            				/build/systest/tests/checkpoint_test.go:160
        	Error:      	"map[0ad658b95dd0240b529eef1e6bf504af5f4325ea7f01b8958ab5ab6ee48ca60b:*** 15822ccd7c39787ee77fb6a9fc4509add2f151cb141bd12e7dc201a9fb43bcfd:*** 166622d2f35bf46e37917910b1c2ac8819a9513c3493fcc759264cac2f73a711:*** 1bc9fa7395c05ef4a362c225ea2349fae11f944416d5875e60317671fc0481a4:*** 1f19e7d021ac625f9c6ec2ff1b045df2bacf48c91e31e361003e5e6166d89e3e:*** 2072ea8c45bd7798b9ebf5db0abf7086e928fe178a44230269cb67d40e764232:*** 2e8392fbe6c41d64e309b2beba07f61dcfde643fd587885e858d1361d0a220c7:*** 3205686b321cd252e6b57551768b7c6fe36511756a27d8f926f948936900de82:*** 3f6a1f101899ddfcbde8acdf6c133893b664635b2127144a019567f8942333ac:*** 4bed6b838259d23ae79cb55629ccfba87912a202269ceaf87e02ec1a3f330b8b:*** 59200a9c2f55252367009868520161ceddebd142d3808450bea0feb5eca2c28e:*** 83be9aef729f38ab394eaa535f04b722dc72fe759eba2c3656d53678c057afd5:*** 8d3ced3120b8ba87cee12b56a81e9910f2f7672484545f3f5fa61cfe60a0d571:*** 90b3da13a9003bb0e2c7cf7b451d64d3fdc806cf461e3d1acdf1c51bfc9f7b41:*** adac54635d8b25ae60cc74b2464d010e4a434241a05ca30fd13607aa8187e37f:*** bdafee8dcd339b27e74cbd9c289f72d14bc11f19f102324f9201acfe27053d39:*** c2a893614e4729d06d3b1fe5e5875cc665a569a5b28abcf028c1e1ffc1ef4c08:*** c84bde9ed28344fbdce0c2e96f5186deac131dbab9a0d1922713ddfe7b914cee:*** d282eca86ce4663af796505d5c214e1d2f80cc4f2f0f8f4bef9f3b480f649dd0:*** d83b2e75571b8bc2f5e91f64318b6923029c9481cf60b8f04ab513cc22fd095b:*** d8624a47b7ada34787139f0ddc956b42138056ed868afc6c5853311c621d04f0:*** d86f2b9c094c4ce6fe2446a16e345090bd9e972cf35c1275a79968909eaab28b:*** db28318d0cf64370243e5576245bb7574524e4cac6f26cc740c64e00034e5cfe:*** e5b9f87762f0b9cd97f0651381257960a42577158b0a997a3c53a30ff3bae42a:*** ec6ac81b5277e1825af1f5d729503edbe901d5d1257cc5785840dfa8db2f1fe2:*** f1573cb750f2d98b42e040ca5f6098629d57a2793c028a31bdfaaf615999ecc3:***]" should have 28 item(s), but has 26
        	Test:       	TestCheckpoint
        	Messages:   	not all miners are smeshing, expected 28, got 26

https://github.com/spacemeshos/go-spacemesh/actions/runs/5190489166/jobs/9357967404

**Comment by poszu** [comment]
The test is still flaky, for example: https://github.com/spacemeshos/go-spacemesh/actions/runs/9841780386/job/27169199799

**Comment by acud** [comment]
With #6193 this should be improved. If it degrades again we could open a new issue
