### ISSUE TITLE
Persist the last POST 

### ISSUE THREAD

**Issue by poszu** [spacemeshos/go-spacemesh#4491]
## Description
Currently neither the initial nor the subsequent proofs are persisted. Thus it might happen that the node is shut down between the proof is created and it is used. That proof would be lost and would have to be recreated, which is hard.

## Affected code
- especially the initial POST,
- every post built by `nipostBuilder`,

## Proposed solution
The last proof should be persisted (in a DB or in a file, like the nipost builder state).

**Comment by dshulyak** [comment]
i think for ephemeral data it is better to stick with files
