### ISSUE TITLE
Persisting nipost state is done inefficiently

### ISSUE THREAD

**Issue by fasmat** [spacemeshos/go-spacemesh#4506]
## Description
NiPoST state persistence can be optimised to avoid coping data when writing or reading state from disk. The general process should be:

writing:
- create a new temporary file
- write CRC (as zeroes) to file
- use a `io.MultiWriter` to write to the file and calculate `CRC` simultaneously
- seek back to the beginning of the file and update CRC
- use [atomic.ReplaceFile](https://github.com/natefinch/atomic/blob/v1.0.1/file_unix.go#L12) to replace existing file with new file

reading:
- read CRC
- use a `io.TeeReader` to calculate CRC while reading the file
- decode data by reading from `io.TeeReader`
- compare calculated CRC with CRC read from file
- check if all data has been read from file while decoding (i.e. did read end in `io.EOF`?)

## Affected code
- Functions in `activation/nipost_state.go`
- Possibly other places where data is persisted to disk
- Discussion can be found here: https://github.com/spacemeshos/go-spacemesh/pull/4493/files#r1226351812

**Comment by poszu** [comment]
@fasmat , IMO, it's not required for genesis.

**Comment by fasmat** [comment]
@poszu  Changing the file layout will make it more difficult to change it later
