### ISSUE TITLE
sync: downloading malfeasence proofs fails with malformed data

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#4513]
> 230:2023-06-13T19:52:30.996+0200	WARN	9eba1.sync	failed fetching malfeasance proofs	{"node_id": "9eba1a2b30d76d51f0ca71fbc2dece8352aa62ed7e97a3f0a13c66bf588aa757", "module": "sync", "sessionId": "a51bc4be-3357-4074-b5e1-6eb459072fdb", "malicious_ids": ["06b58855e73ba4373924704b0f0573a63ef9c602731834c35f655662594f7124", "7a37e956289a6b452c0e88c6ea9e79be1b904d254e8a8f2a99faaa5139d6897f", "a5f1c1d9bb69aa36c330aea8187a1a517e4c29a093db5919e4073a5dfee5291c", "df5d211df3c73ebf3704115d3076df4dfb0ff2e0ce92f855c57b7b83a4e1f1b4"], "errmsg": "2 errors occurred:\n\t* hint: malfeasance, hash: 0x7a37e956289a6b452c0e88c6ea9e79be1b904d254e8a8f2a99faaa5139d6897f, err: validation reject: malformed data\n\t* hint: malfeasance, hash: 0xa5f1c1d9bb69aa36c330aea8187a1a517e4c29a093db5919e4073a5dfee5291c, err: validation reject: malformed data\n\n", "name": "sync"}
235:2023-06-13T19:52:31.374+0200	WARN	9eba1.sync	failed fetching malfeasance proofs	{"node_id": "9eba1a2b30d76d51f0ca71fbc2dece8352aa62ed7e97a3f0a13c66bf588aa757", "module": "sync", "sessionId": "a51bc4be-3357-4074-b5e1-6eb459072fdb", "malicious_ids": ["955b0a2ac8681a8dee6453c081fe19fe635be1cbe4755ab31ea8b06532d2fc61"], "errmsg": "1 error occurred:\n\t* hint: malfeasance, hash: 0x955b0a2ac8681a8dee6453c081fe19fe635be1cbe4755ab31ea8b06532d2fc61, err: validation reject: malformed data\n\n", "name": "sync"}

not clear what may cause this, but it is reproducible all the time in recent testnet

**Comment by dshulyak** [comment]
this wasn't fixed

**Comment by countvonzero** [comment]
do you mean the failure to publish malfeasance proof in the atx verification codepath?

**Comment by dshulyak** [comment]
yes. i thought that this is the same problem. only later realized that this is simply due to sync state
