### ISSUE TITLE
Send SmesherId in grpc reward object.

### ISSUE THREAD

**Issue by kacpersaw** [spacemeshos/go-spacemesh#4529]
Currently, go-spacemesh sends only coinbase with the reward, which is not enough to identify which smesher got their reward. 
The ask is to send smesher id along with the coinbase, so we will be able to identify multiple smeshers which are working on one coinbase.

GlobalStateStream reward: https://github.com/spacemeshos/go-spacemesh/blob/develop/api/grpcserver/globalstate_service.go#L409

This is important to fix problem in explorer, because currently we cannot map coinbase with smesher id which is confusing for end users.
Explorer is using GlobalStateStream to get the rewards.

https://github.com/spacemeshos/explorer-frontend/issues/189

**Comment by piersy** [comment]
From slack @kacpersaw would like the smesherID encoded as a string and currently is only using the GlobalStateStream endpoint to retrieve this information, which means that we can fix this problem without having to modify the DB structure, which would probably require nodes to perform a re-sync.

**Comment by countvonzero** [comment]
@piersy how does explorer recover these events? does it have to persist locally? 
requiring explorer node to resync doesn't sound feasible to me.

**Comment by piersy** [comment]
@countvonzero I imagine that resync is the only option for the explorer since @kacpersaw informed me that the explorer is only using the GlobalStateStream endpoint.

**Comment by lrettig** [comment]
[layer, smesherID] should be usable as a unique index/key for a reward.
