### ISSUE TITLE
TestBuilder_StartSmeshingAvoidsPanickingIfPrepareInitializerReturnsError

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#4544]
> panic: Fail in goroutine after TestBuilder_StartSmeshingAvoidsPanickingIfPrepareInitializerReturnsError has completed

goroutine 2163 [running]:
testing.(*common).Fail(0xc0000d6b60)
	/opt/hostedtoolcache/go/1.19.10/x64/src/testing/testing.go:824 +0x1a8
testing.(*common).FailNow(0xc0000d6b60)
	/opt/hostedtoolcache/go/1.19.10/x64/src/testing/testing.go:847 +0x51
testing.(*common).Fatalf(0xc0000d6b60, {0x1c3c0b3, 0x2e}, {0xc00011fbd0, 0x5, 0x5})
	/opt/hostedtoolcache/go/1.19.10/x64/src/testing/testing.go:955 +0xaf
github.com/golang/mock/gomock.(*Controller).Call.func1(0xc000185e60, {0x1b48860?, 0xc0002862a0}, {0x1c0064a, 0x4}, {0x0, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/golang/mock@v1.6.0/gomock/controller.go:231 +0x46d
github.com/golang/mock/gomock.(*Controller).Call(0xc000185e60, {0x1b48860, 0xc0002862a0}, {0x1c0064a, 0x4}, {0x0, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/golang/mock@v1.6.0/gomock/controller.go:247 +0xce
github.com/spacemeshos/go-spacemesh/log.(*MockLogger).With(0xc0002862a0)
	/home/runner/work/go-spacemesh/go-spacemesh/log/log_mock.go:125 +0x9b
github.com/spacemeshos/go-spacemesh/activation.(*Builder).generateInitialPost(0xc000317880, {0x1f1e578, 0xc00032a000})
	/home/runner/work/go-spacemesh/go-spacemesh/activation/activation.go:284 +0x3fb
github.com/spacemeshos/go-spacemesh/activation.(*Builder).run(0xc000317880, {0x1f1e578, 0xc00032a000})
	/home/runner/work/go-spacemesh/go-spacemesh/activation/activation.go:250 +0x68
github.com/spacemeshos/go-spacemesh/activation.(*Builder).StartSmeshing.func1()
	/home/runner/work/go-spacemesh/go-spacemesh/activation/activation.go:209 +0x31f
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 +0x87
created by golang.org/x/sync/errgroup.(*Group).Go
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:72 +0x12f
FAIL	github.com/spacemeshos/go-spacemesh/activation	0.483s

**Comment by dshulyak** [comment]
@piersy @pigmej it fails very often on ci, needs to be fixed asap

**Comment by poszu** [comment]
I think it fails sporadically because it mocks logger and _sometimes_ logs are emitted. For some reason, `atomic.WriteFile` misbehaves in unittests:

>failed to save initial post: saving post: writing file: save file /tmp/TestBuilder_StartSmeshingAvoidsPanickingIfPrepareInitializerReturnsError1089292189/001/post.bin: cannot replace "/tmp/TestBuilder_StartSmeshingAvoidsPanickingIfPrepareInitializerReturnsError1089292189/001/post.bin" with tempfile "/tmp/TestBuilder_StartSmeshingAvoidsPanickingIfPrepareInitializerReturnsError1089292189/001/post.bin1876321059": rename /tmp/TestBuilder_StartSmeshingAvoidsPanickingIfPrepareInitializerReturnsError1089292189/001/post.bin1876321059 /tmp/TestBuilder_StartSmeshingAvoidsPanickingIfPrepareInitializerReturnsError1089292189/001/post.bin: no such file or directory

**Comment by piersy** [comment]
@dshulyak I'm looking into it.

@poszu thanks!
