### ISSUE TITLE
Create document outlining the high level design of the hare3 protocol

### ISSUE THREAD

**Issue by piersy** [spacemeshos/go-spacemesh#4563]

**Comment by dshulyak** [comment]
lets keep personal todo lists outside the repository. i understand that this is for tracking progress, but this is just a mess

**Comment by piersy** [comment]
Hi @dshulyak, I'm confused as to what exactly is a mess, and also how does an issue get classified as a personal todo list rather than a regular issue?

**Comment by dshulyak** [comment]
my impression is that all https://github.com/spacemeshos/go-spacemesh/issues/4456 are used to track personal progress, they contain zero information. i don't see what is the advantage of having this in repository, this is what i meant by a mess. if such things are necessary it is better to move them to pm repo

**Comment by piersy** [comment]
Hi @dshulyak the intention of these issues was to break down the work on hare 3 and provide clarity to everyone (rather than being used to track only personal progress) on the progress of the implementation.

Would you be able to clarify what are the criteria you use to determine if a ticket should live in this repo or the pm repo, or do we have something written down describing our approach?
