### ISSUE TITLE
hare: Certificate should include known equivocator's malfeasance proof and eligibility

### ISSUE THREAD

**Issue by countvonzero** [spacemeshos/go-spacemesh#4585]
## Description

at notify round, a miner would construct a Certificate from the commit messages that it received.
since the threshold is f+1-k where KE (known equivocators) may not have an actual commit message, just an eligibility proof.
say f=100, the miner collected 100 commit messages and 1 KE.
so the commit round passes threshold. but the miner can only include 100 commit messages in the Certificate.
so in notify rounds, this particular Certificate was consider invalid by other miners because it doesn't pass the threshold,
and the Certificate doesn't record info about KE.

Tal's response
```
other miners should also have have the malfeasance proof and eligibility from gossip. 
But to solve the timing problem that can cause some miners to receive the certificate 
before the malfeasance/eligibility, you should include both the malfeasance proof and 
eligibility proof in the certificate.
```

should assess priorities based on the implementation of hare 3

**Comment by countvonzero** [comment]
this is also observed in testnet-05

```
2023-06-24 11:47:06.254 | {"L":"WARN","T":"2023-06-24T14:47:06.254-0400","N":"718f8.hare","M":"invalid certificate","node_id":"718f8e6723d19b084760eb3a2ebd0c73351691017e6f6b59a28fc1aadafbd96c","module":"hare","protocol":"hr1_tickloop","sessionId":"c79d438f-ee41-4d76-ab31-ed56c0941cb2","errmsg":"number of messages does not match the threshold: expected 101, actual dishonest 0 honest 95","name":"hare"}
```

**Comment by dshulyak** [comment]
i think we should instead include signatures from whole committee. and not include malfeasance proofs

we also should drop this separate eligibility proof and gossip original message. it was something extremely unrobust and clearly misguided decision to use it

**Comment by countvonzero** [comment]
i am inclined to wait for hare3...
