### ISSUE TITLE
Node should *not* delete POST files when there is more on a disk than configured

### ISSUE THREAD

**Issue by pigmej** [spacemeshos/go-spacemesh#4594]
In the situation when there are more post files than node expects node should error and give up, and not delete the files. 

That should help not surprise users with "your data is gone because config was wrong".

In the situation when there are too less files, then node should clearly indicate that it will generate more. 

There probably should be a flag that would change node behavior:
* `--do-not-touch-pos` and then it should fail regardless of the found situation on the disk (smaller, bigger etc).
* we could have a flag that would keep current behaviour too.

**Comment by schinzelh** [comment]
I just lost 1 TiB post data due to this "feature" - please fix this ASAP!

**Comment by lrettig** [comment]
See also https://github.com/spacemeshos/post/issues/236

**Comment by pigmej** [comment]
It will be addressed with https://github.com/spacemeshos/pm/issues/259

**Comment by lrettig** [comment]
This is [still happening](https://discord.com/channels/623195163510046732/691262492390719498/1156883602752143371)

**Comment by Stizerg** [comment]
I lost 4TiB today, when will you fix it? 
--do-not-touch-pos should be default behavior.
there's so many complains since testnet, more than 6 month later the issue haven't been fixed

**Comment by pigmej** [comment]
Post-service implementation will have that fixed, as mentioned https://github.com/spacemeshos/go-spacemesh/issues/4594#issuecomment-1733625198

**Comment by ytx1991** [comment]
I believe the issue could be resolved in less than 10 minutes; however, it seems there is a lack of willingness to address user concerns promptly.

**Comment by lrettig** [comment]
> I believe the issue could be resolved in less than 10 minutes; however, it seems there is a lack of willingness to address user concerns promptly.

Our small development team is very busy focusing on network stability. This is an open source project. Feel free to make the desired change and submit it as a PR here! We're more than happy to review.

For the record, if it were a "ten minute change" we would've made it a long time ago. The change is more complex as it ties into the post service work that @pigmej mentioned above.

**Comment by pigmej** [comment]
This is fully solved with post-service.
