### ISSUE TITLE
Flaky tests on windows 

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#4599]
=== Failed
=== FAIL: activation TestBuilder_RetryPublishActivationTx (10.02s)
    activation_test.go:1068: 
        	Error Trace:	D:/a/go-spacemesh/go-spacemesh/activation/activation_test.go:1068
        	Error:      	failed waiting for required number of tries to occur
        	Test:       	TestBuilder_RetryPublishActivationTx
    controller.go:137: missing call(s) to *activation.MocknipostBuilder.BuildNIPost(is anything, is anything) D:/a/go-spacemesh/go-spacemesh/activation/activation_test.go:1043
    controller.go:137: aborting test due to missing call(s)

=== FAIL: hare TestRecvDelayedDishonest (8.80s)
    consensus_test.go:111: Validity 1 failed: output does not contain the intersection of honest parties

=== FAIL: hare TestEquivocation (10.02s)
    consensus_test.go:111: Validity 1 failed: output does not contain the intersection of honest parties

https://github.com/spacemeshos/go-spacemesh/actions/runs/5387202693

**Comment by dshulyak** [comment]
they are probably generally flaky. just failed for me on winddows

**Comment by fasmat** [comment]
So far I have only seen `TestRecvDelayedDishonest` fail on windows:

https://github.com/spacemeshos/go-spacemesh/actions/runs/5424306542/jobs/9863491112

after this test is fixed we can probably add Windows to the `unittest` job and have it failing block merges.

**Comment by countvonzero** [comment]
i found this one as well :(

=== Failed
=== FAIL: hare TestHare_onTick (10.03s)
    hare.go:337: Unexpected call to *mocks.MockRolacle.IsIdentityActiveOnConsensusView([context.Background.WithCancel.WithValue(type log.correlationIDType, val af86acdf-1a48-4386-a54e-0caec80fe276).WithValue(type log.correlationIDType, val <not Stringer>).WithValue(type log.correlationIDType, val 456e7430-ef47-44a4-8bb6-29e26384a443) 71a7692c195432e63fa4504fcc5c8c8b2a4d83936b42f84aa703d534fc17be05 9]) at D:/a/go-spacemesh/go-spacemesh/hare/hare.go:337 because: 
        expected call at D:/a/go-spacemesh/go-spacemesh/hare/hare_test.go:335 doesn't match the argument at index 2.
        Got: 9 (types.LayerID)
        Want: is equal to 7 (types.LayerID)
        expected call at D:/a/go-spacemesh/go-spacemesh/hare/hare_test.go:336 doesn't match the argument at index 2.
        Got: 9 (types.LayerID)
        Want: is equal to 8 (types.LayerID)

**Comment by fasmat** [comment]
Two more tests failed in a recent build:

TestSndDelayedDishonest:
consensus_test.go:111: Validity 1 failed: output does not contain the intersection of honest parties

https://github.com/spacemeshos/go-spacemesh/actions/runs/5449769234/jobs/9914347141?pr=4630

**Comment by dshulyak** [comment]
i will skip hare tests, as they will be removed in upcoming weeks. there are some other flaky tests, but we can address separately
