### ISSUE TITLE
sync: limit resources spent on serving data to peers

### ISSUE THREAD

**Issue by countvonzero** [spacemeshos/go-spacemesh#4603]
## Description
currently it's trivial to dos an honest node by repeatedly asking the node to serve data via the sync protocol.

we need to 
- keep track of the resources spent on a peer
- rate-limit once a peer reached a configured max value

**Comment by dshulyak** [comment]
we should also limit number of concurrent requests to the half of available db connections (e.g if by default we have 16, not more than 8 should be used in sync).

**Comment by dshulyak** [comment]
actually rather simple solution is to throttle requests per peer, with token based rate limiter. should be simple to implement and will make it harder to do any meaningful abuse
