### ISSUE TITLE
Provide a way to get commitmentATX for post via api call / cmd

### ISSUE THREAD

**Issue by pigmej** [spacemeshos/go-spacemesh#4614]
For proper usage of `postcli` we would need to have a way to get commitmentATX that can be used for post, otherwise users of `postcli` are forced to start using smapp to get commitmentATX or use goldenATX always.

**Comment by dima-stefantsov** [comment]
According to https://discord.com/channels/623195163510046732/820605182970036245/1125251881615228990 it is already possible with `go-spacemesh with start smeshing arg`, which generates `postdata_metadata.json` which has nodeid and atxid needed, all from cli.

**Comment by dshulyak** [comment]
grpcurl -plaintext 127.0.0.1:9092 spacemesh.v1.ActivationService.Highest | jq -r '.atx.id.id' | base64 -d | xxd -p -c 64
