### ISSUE TITLE
GRPC endpoint PostSetupStatus returns incorrect value for provider_id

### ISSUE THREAD

**Issue by tjb-altf4** [spacemeshos/go-spacemesh#4622]
## Description
gRPC endpoint `spacemesh.v1.SmesherService.PostSetupStatus` returns incorrect value for `provider_id`, which seems is the value for `max_file_size` -1.
 `-1` is a common not-applicable value, which would be correct for this instance (no gpu) and may explain the origin of this bug.

## Steps to reproduce
Query go-spacemesh over gRPC with `grpcurl -plaintext localhost:9093 spacemesh.v1.SmesherService.PostSetupStatus`

## Actual Behavior
Returned value for `provider_id` is same (almost) as `max_file_size`:
```
{
    "status": {
        "state": "STATE_COMPLETE",
        "num_labels_written": "2147483648",
        "opts": {
            "data_dir": "/root/post",
            "num_units": 4,
            "max_file_size": "4294967296",
            "provider_id": 4294967295,
            "throttle": true
        }
    }
}
```

## Expected Behavior
Returned value for `provider_id` should be 1, or 2 etc in line with GPU/provider assignment, or a suitable flag value for not applicable, e.g. -1.

## Environment
Please complete the following information:
 - OS: 
Linux / Docker
spacemeshos/go-spacemesh-dev:727dc8b
 - Node Version: 
v0.3.10-beta.2+727dc8be09d6513e365538808609aeeaac6ab863

## Additional Resources 
![image](https://github.com/spacemeshos/go-spacemesh/assets/33798260/3b845ae7-69f8-4fb6-a0f9-6f9541652817)

**Comment by pigmej** [comment]
Hey,

We have made a conscious decision to make the CPU provider "very last" and by doing it very last it's basically that magic number.

Given that this seems to be your situation (docker with no GPU) I believe that's that.
