### ISSUE TITLE
implement poet k2pow

### ISSUE THREAD

**Issue by countvonzero** [spacemeshos/go-spacemesh#4634]
## Description
spec: https://community.spacemesh.io/t/proof-of-work-and-post-proof-generation/361

**Comment by countvonzero** [comment]
the spec as of now is not ready for implementation. the communication btwn poets and nodes need to be specified.

**Comment by pigmej** [comment]
@countvonzero I think it's far too unspecified to consider it for implementation. It could even end with NOT being poet side k2pow.

**Comment by countvonzero** [comment]
maybe lets close this for now? the research thread on the forum is still open. we can track it there.
