### ISSUE TITLE
activation: don't loop with retries when node needs to wait for next poet window

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#4643]
if node missed poet window in the current epoch it will loop with retries and fail the same way.
instead it should understand that it needs to wait for next epoch and extend wait period. 

relevant code https://github.com/spacemeshos/go-spacemesh/blob/develop/activation/activation.go#L365-L384

maybe it is enough to increment `current`, if `until` is negative

**Comment by fasmat** [comment]
This issue has been fixed as part of #5207

**Comment by fasmat** [comment]
The link in the issue shows the current `develop` state of the code. When this issue was created the link referred to this section of the code:

https://github.com/spacemeshos/go-spacemesh/blob/1e9d5ed0ec1de54b9290d0bd1fd53f1c5c1b7162/activation/activation.go#L365-L384
