### ISSUE TITLE
sync: layer opininons protocol uses too much traffic

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#4674]
if i read it correctly it receives certificate from every peer, which explains unreasonably high traffic, even worth that unlike gossip - it will increase linearly with number of peers. see cyan (?) and deep purple for incoming/outgoing traffic on the screenshot below.

one solution is to switch into two step protocol:

1. request opinion

```go
type LayerOpinion struct {
	PrevAggHash types.Hash32
	Certified          bool
}
```  
and then execute step 2 if Certified is true, and it doesn't match our opinionn

2. ask certificate for a specific layer

![image](https://github.com/spacemeshos/go-spacemesh/assets/1964576/67972fc1-8200-4dc4-adf4-47e125c0f181)

**Comment by dshulyak** [comment]
this eats quite a lot of traffic on mainnet

![image](https://github.com/spacemeshos/go-spacemesh/assets/1964576/52ad4e25-eebe-4aa1-8028-725156d855f8)

**Comment by dshulyak** [comment]
cc @countvonzero

**Comment by countvonzero** [comment]
@dshulyak i think it's more likely this bug 
https://github.com/spacemeshos/go-spacemesh/issues/4585 that cause the traffic.
we keep fetching certificates and discarding them. this will improve when hdist is reduced as well.

**Comment by dshulyak** [comment]
but do we request certificate from every peer  as a part of that layer opinion?

**Comment by countvonzero** [comment]
> but do we request certificate from every peer as a part of that layer opinion?

yes we do. but only in the range of `min(inState, processed)` to `current-1`, and the interval is 2*sync_interval (10s now)
this issue is still valid and need to be fixed. i was referring to that the constant traffic stream in mainnet may be caused by the other bug.

**Comment by countvonzero** [comment]
actually i am wrong. i was confusing hare certificate with block certificate. #4585 is irrelevant. sorry @dshulyak
