### ISSUE TITLE
Start net, cpool and addrbook

### ISSUE THREAD

**Issue by y0sher** [spacemeshos/go-spacemesh#470]
# Overview / Motivation

We should split creation of modules and starting them, it makes more sense to know whether this service is running or not. this will make it easier to expect routines to be running only after Start.  

# The Task

Find modules that start on their creation function (`discovery`, `net`, `cpool`) and break down the logic to creation and starting. 

If `discovery` is created within `swarm` it should be `Start`ed on `swarm`'s `Start` function.

# Implementation Notes

Will probably be better to create a unified way of implementing this that can be reused. @gavraz implemented `Closer` in hare, maybe we should implement a `Starter` and take those two structs to a different package.

# Contribution Guidelines
Important: Issue assignment to developers will be by the order of their application and proficiency level according to the tasks complexity. We will not assign tasks to developers who have'nt introduced themselves on our Gitter [dev channel](https://gitter.im/spacemesh-os/Lobby)

1. Introduce yourself on go-spacemesh [dev chat channel](https://gitter.im/spacemesh-os/Lobby) - ask our team any question you may have about this task
2. Fork branch `develop` to your own repo and work in your repo
3. You must document all methods, enums and types with [godoc comments](https://blog.golang.org/godoc-documenting-go-code)
4. You must write go unit tests for all types and methods when submitting a component, and integration tests if you submit a feature
5. When ready for code review, submit a PR from your repo back to branch `develop`
6. Attach relevant issue to PR

**Comment by zalmen** [comment]
@y0sher is it still relevant? (if not, plz close it)

**Comment by y0sher** [comment]
I know in fact that some of this is done but we have to revisit to know it everything is aligned (init then start) so we don't split functionality that we don't want before starting.
