### ISSUE TITLE
evaluate schema and data reverts with sqlite session extension

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#4711]
https://www.sqlite.org/sessionintro.html

future updates may change schema and data layout during upgrade. there is always a chance that upgrade will have regressions and in such case we want node to seamlessly use previous software version, which may not be possible due to the changes in database.

during upgrade some data may be modified, deleted, added and the same for schema. all of that can be recorded into changeset using sqlite session extension, and undone when, for example, previous version is loaded. i would try to use some reasonable heuristic, for example, add migration version to changeset name, and if current migration included in the binary is lower than that - undo changeset.  

the alternatives:
- backups, might be large, so not very nice to make them automatically. popular tool for live backup https://github.com/benbjohnson/litestream
- special revert migration, doesn't work if data was deleted (dropped column) or modified in non-revertable way during upgrade
. also requires automation code in node manager (smapp usually) or manual work

**Comment by dshulyak** [comment]
on the second thought if we noticed regression only after downloading new data (e.g after few hours or a day), then any revert is most likely won't work and we have to update software further or do a checkpoint recovery.

**Comment by countvonzero** [comment]
as a principal, i feel we should never do drop column/table in a regular update, until much later (so we can revert back to old code), or during a checkpoint.

in the case where we add new data (column/table) in a failed update A, and wanting to fix with update B, we may want to have a process that fixes db data before the B initializes the node.

i'd suggest we only do add going forward, and only take special occasions like checkpoint recovery to do major schema change.
and only very rarely, when there are no version of software needing such data, do we drop columns/table.

**Comment by dshulyak** [comment]
i think if go-ethereum at its scale can ask to resync the node then it certainly works for go-spacemesh as well. ofcourse there are cheaper sync methods available, but until it will become relevant we can use regular sync
