### ISSUE TITLE
Verify peer Network ID and Client Version when dialing

### ISSUE THREAD

**Issue by noamnelke** [spacemeshos/go-spacemesh#472]
# Motivation
Ensure Network ID and Client Version of remote peer are compatible. We're currently only validating incoming connections.

The problem is that we're currently not returning a handshake message when receiving an incoming connection.

**Comment by y0sher** [comment]
this requires adding a RTT to the handshake sequence, meaning we'll have to send an handshake message and wait for the response in order to make sure we're running on same client version and networkid.

**Comment by lrettig** [comment]
Related: #718 (we want to verify both the peer's advertised IP/port, and netid/version)

**Comment by dshulyak** [comment]
We have protocol for that. See handshake in p2p module
