### ISSUE TITLE
valid malicious proof should be accepted despite unknown identity

### ISSUE THREAD

**Issue by countvonzero** [spacemeshos/go-spacemesh#4731]
## Description
if a malfeasance proof for identity A is received via gossip before the first atx from A, such proof should be accepted if the proof is valid.

as a result, function `checkIdentityExists` should check table atxs and the existence of an identity.

## Actual Behavior
a valid malfeasance proof will be rejected if a node never receives an atx from the identity in the proof

## Expected Behavior
a valid malfeasance proof should be accepted regardless.

**Comment by dshulyak** [comment]
it definitely should not be acceptable. such objects can be generated for free, and it enables trivial dos.
it will fill the disk, but even worse it will allow to dos gossip network

**Comment by countvonzero** [comment]
true. a big oversight on my part.

in tgis case the node will consider A honest after receiving the atx. syncing of malicious identities need to be adjusted somehow. otherwise node would never learn that A is malicious.
