### ISSUE TITLE
Tracking progress of PoST proof generation

### ISSUE THREAD

**Issue by Amadis11** [spacemeshos/go-spacemesh#4742]
GRPC API should have more available information about Post Proof. One of API current or new could response with information about proof after initialization. Time of data reading and nonce of proof which gave nonce and number of prooving tries. There should be also an information about current situation. So when node was trying to make proof, same information, time, nonce, if it was successful and overall information at the end if node is currently taking participation in smeshing. 

Something like:
{"post_proof":
 {status: "ready"|"not_started"|"in_progress",
"calculating_time": "minutes_value",
"nonce_found": "nonce_value",
"next_poet_round": "unix_start_of_poet"}}

**Comment by reb0rn21** [comment]
I would love to see this option, many rin spacemesh go in screen without logs and a lot is unknown

**Comment by lrettig** [comment]
This is bothering me too. The node reports the status of the PoST _initialization_ process, but once this is complete there is no info whatsoever on proof _generation._ There's not even any log message, so you really have no idea what's going on or how much progress has been made.

**Comment by lrettig** [comment]
This should be tackled as part of https://github.com/spacemeshos/pm/issues/259

**Comment by pigmej** [comment]
I consider that this is solved for now.
