### ISSUE TITLE
Make possible to disable local network scanning in discovery in the config

### ISSUE THREAD

**Issue by pigmej** [spacemeshos/go-spacemesh#4788]
Currently, go-spacemesh will eagerly /scan/ local networks for peers. 

In some environments, that's not good and could be seen as suspicious network activity by cloud providers and some local network providers too.

Currently, the workaround is to block it via a firewall:
```
iptables -A OUTPUT -d 192.168.0.0/16 -j DROP
iptables -A OUTPUT -d 172.16.0.0/12 -j DROP
iptables -A OUTPUT -d 10.0.0.0/8 -j DROP
```

But there should be in code equivalent for more polite behavior of go-spacemesh.

**Comment by dshulyak** [comment]
actually i forgot to mention this, it can be implemented in p2p/gater.go. so to implement add config option DisableDialPrivate or something like that. and then check if dialed address is in one of he private ranges. there is a helper in libp2p libraries for checking private ip4/ip6 ranges `github.com/multiformats/go-multiaddr/net` `IsPrivateAddr`
