### ISSUE TITLE
sync: downloaded block without tx

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#4830]
> 2023-08-13T07:04:07.414+0200	WARN	fd68b.sync	mesh failed to process layer from sync	{"node_id": "fd68b9397572556c2f329f3e5af2faf23aef85dbbbb7e38447fae2f4ef38899f", "module": "sync", "sessionId": "efbf489e-17e5-4aad-a684-b82800582312", "layer_id": 8556, "errmsg": "execute block 8555/f2a52726b7: executor get tx: database: not found: tx 0x0b89aeb78430836f2eb55af819adb395bf9dc1ec2e6acae4c30616a20105c1f0", "name": "sync"}

expected behavior is that block downloading will fail if tx can't be fetched

**Comment by dshulyak** [comment]
@countvonzero

**Comment by dshulyak** [comment]
i think that we don't actually check if we got requested object. so if for some reason we got something else fetcher will be satisfied

**Comment by countvonzero** [comment]
> i think that we don't actually check if we got requested object. so if for some reason we got something else fetcher will be satisfied

fetcher only fetches hashes it was told to. it doesn't care about referenced objects. those logic are in the handlers. in this case `HandleSyncedBlock`. i don't understand how this block will pass `checkTransactions` there.
do you have full log?

**Comment by dshulyak** [comment]
[log7.tar.gz](https://github.com/spacemeshos/go-spacemesh/files/12329342/log7.tar.gz)

**Comment by dshulyak** [comment]
> fetcher only fetches hashes it was told to. it doesn't care about referenced objects

i meant that asks for a hash, but it doesn't check that it actually got anything, just that response succeeded. all handlers will be thinking that data is available, but in fact it may not

**Comment by countvonzero** [comment]
> [log7.tar.gz](https://github.com/spacemeshos/go-spacemesh/files/12329342/log7.tar.gz)

this log started with the block 8555/f2a52726b7 locally available already. so i cannot see how that block got saved

**Comment by dshulyak** [comment]
@countvonzero that can't be the case. this is my node. latest block that i had before today morning is in the log below. so i turned out the node on layer 8478. and then i turned it on 8604

> 2023-08-12T20:32:06.006+0200	INFO	fd68b.mesh	consensus results	{"node_id": "fd68b9397572556c2f329f3e5af2faf23aef85dbbbb7e38447fae2f4ef38899f", "module": "mesh", "sessionId": "59b39a68-2b95-4539-bf08-30cebce70441", "layer_id": 8478, "results": [{"layer": 8476, "opinion": "e764cf33a4", "verified": true, "blocks": [{"id": "68060637a1", "layer": 8476, "height": 0, "valid": true, "invalid": false, "hare": true, "data": true, "local": false}]}, {"layer": 8477, "opinion": "76bf417743", "verified": true, "blocks": [{"id": "06ecb4135a", "layer": 8477, "height": 0, "valid": true, "invalid": false, "hare": true, "data": true, "local": false}]}, {"layer": 8478, "opinion": "08c04bc332", "verified": false, "blocks": [{"id": "f3a5c77ba8", "layer": 8478, "height": 0, "valid": false, "invalid": false, "hare": true, "data": true, "local": false}]}], "name": "mesh"

**Comment by countvonzero** [comment]
maybe the wrong log file? this is at the beginning of the log you uploaded.

> 2023-08-13T07:02:41.704+0200	INFO	fd68b.sync	fetching malfeasance proofs	{"node_id": "fd68b9397572556c2f329f3e5af2faf23aef85dbbbb7e38447fae2f4ef38899f", "module": "sync", "sessionId": "b7ee3a76-f4ea-4c50-8975-8ff69b308c24", "to_fetch": 96, "name": "sync"}
2023-08-13T07:02:41.705+0200	INFO	fd68b.sync	malicious IDs synced	{"node_id": "fd68b9397572556c2f329f3e5af2faf23aef85dbbbb7e38447fae2f4ef38899f", "module": "sync", "sessionId": "b7ee3a76-f4ea-4c50-8975-8ff69b308c24", "name": "sync"}
2023-08-13T07:02:57.265+0200	INFO	fd68b.mesh	consensus results	{"node_id": "fd68b9397572556c2f329f3e5af2faf23aef85dbbbb7e38447fae2f4ef38899f", "module": "mesh", "sessionId": "da666e0e-8840-4e53-9000-c22d98b6668f", "layer_id": 8554, "results": [{"layer": 8548, "opinion": "e63180add6", "verified": true, "blocks": [{"id": "6d133a7128", "layer": 8548, "height": 0, "valid": true, "invalid": false, "hare": true, "data": true, "local": true}]}, {"layer": 8549, "opinion": "f98a9021f9", "verified": true, "blocks": [{"id": "5ab53f1045", "layer": 8549, "height": 0, "valid": true, "invalid": false, "hare": true, "data": true, "local": true}]}, {"layer": 8550, "opinion": "850ea77db1", "verified": true, "blocks": [{"id": "61f8a12eb9", "layer": 8550, "height": 0, "valid": true, "invalid": false, "hare": true, "data": true, "local": true}]}, {"layer": 8551, "opinion": "2a28494b67", "verified": true, "blocks": [{"id": "cb36685901", "layer": 8551, "height": 0, "valid": true, "invalid": false, "hare": true, "data": true, "local": true}]}, {"layer": 8552, "opinion": "d36c696563", "verified": true, "blocks": [{"id": "69bb7c1c87", "layer": 8552, "height": 0, "valid": true, "invalid": false, "hare": true, "data": true, "local": true}]}, {"layer": 8553, "opinion": "67d5975316", "verified": true, "blocks": [{"id": "965f215697", "layer": 8553, "height": 0, "valid": true, "invalid": false, "hare": true, "data": true, "local": true}]}, {"layer": 8554, "opinion": "783fab3b2f", "verified": true, "blocks": [{"id": "cc87757414", "layer": 8554, "height": 0, "valid": true, "invalid": false, "hare": true, "data": true, "local": true}]}, {"layer": 8555, "opinion": "6e9a2c6d52", "verified": true, "blocks": [{"id": "f2a52726b7", "layer": 8555, "height": 0, "valid": true, "invalid": false, "hare": false, "data": true, "local": true}]}, {"layer": 8556, "opinion": "27f962d528", "verified": true, "blocks": [{"id": "00971b4f95", "layer": 8556, "height": 0, "valid":

**Comment by dshulyak** [comment]
it could be that i restarted something and now can't recall, i don't have any other logs file from this morning

**Comment by countvonzero** [comment]
> i meant that asks for a hash, but it doesn't check that it actually got anything, just that response succeeded. all handlers will be thinking that data is available, but in fact it may not

can you point me to the codepath you are referring to?
syncer ignores error from GetBlocks() to avoid node being DoS'ed by bad data.
but on the fetch thread, error is not ignored. since data is saved on handlers' path, and other components check if block exists locally in db. maybe tortoise's OnBlock is called by mistake somehow?

**Comment by dshulyak** [comment]
> can you point me to the codepath you are referring to?

the code path is just regular fetching code path. after calling getHash(receiver), peer can give you any other object - as long as this objects passes `receiver` validation then all good

i made a note sometime ago https://github.com/spacemeshos/go-spacemesh/issues/3797

> but on the fetch thread, error is not ignored. since data is saved on handlers' path, and other components check if block exists locally in db. maybe tortoise's OnBlock is called by mistake somehow?

but what is has to do with block? transaction is missing. block id is correct and in consensus, after i resynced it got executed correctly

**Comment by countvonzero** [comment]
> the code path is just regular fetching code path. after calling getHash(receiver), peer can give you any other object - as long as this objects passes `receiver` validation then all good
> 
> i made a note sometime ago #3797

the old codepath that verifies hash correctness after receiving was never enabled. (not since i joined). so i deleted the code at some point. 

> but what is has to do with block? transaction is missing. block id is correct and in consensus, after i resynced it got executed correctly

the confusion here for me is that 
- a block exisits locally for layer 8555 with hash `f2a52726b7`. this is in consensus. 
- but somehow the block is missing txs locally. 
but if you look at `HandleSyncedBlock` code, the block id is calculated based on the blob it was given. so `f2a52726b7` was calculated correctly. how is that possible if the block doesn't contain txs when the block is downloaded?

**Comment by dshulyak** [comment]
> the old codepath that verifies hash correctness after receiving was never enabled. (not since i joined). so i deleted the code at some point.

it would be better to enable it, instead of removing. the code without checking is very broken. in fact it is so easy to abuse. i think this is one of the most important things to fix

> but if you look at HandleSyncedBlock code, the block id is calculated based on the blob it was given. so f2a52726b7 was calculated correctly. how is that possible if the block doesn't contain txs when the block is downloaded?

it computes id from included hashes, apparently getHash didn't return an error. i think we should just do a more robust api, that will include verification that we actually received what we asked for

**Comment by countvonzero** [comment]
> it would be better to enable it, instead of removing. the code without checking is very broken. in fact it is so easy to abuse. i think this is one of the most important things to fix

the code was not correct. the hash it checked was just hashing the blob. doesn't contain any app logic. it wasn't a simple flag flip to enable it. anyhow, sent https://github.com/spacemeshos/go-spacemesh/pull/4839 for this.

> apparently getHash didn't return an error

getHash is supposed to return error, so there is a bug.

> i think we should just do a more robust api, that will include verification that we actually received what we asked for

sure
