### ISSUE TITLE
No rewards.

### ISSUE THREAD

**Issue by scj85** [spacemeshos/go-spacemesh#4832]
## Description
I created my first 256GB post data and published it within 12h window before the 24th of July (using Smapp). I was keeping that node almost 100% online all the time.

My post data seems to be registered fine:
https://explorer.spacemesh.io/smeshers/0xe2d279e52ded8a8b4f8d229e04b3e64767f7895e64c866bdeb9fdfb1154645a6

Activation has been made:
https://explorer.spacemesh.io/atxs/0xeffc4139b67beb5d15460f4bfddaaa6eaf2c6ca7108a122a57e3aabf13e65bb6

But I still have no rewards for that node. Even though I am seeing that I am eligible for rewards in some layers
```
{
  "timestamp": "2023-08-12T08:05:03.103431900Z",
  "help": "Computed eligibilities for the epoch. Rewards will be received after publishing proposals at specified layers. Total amount of rewards in SMH will be based on other participants in the layer.",
  "eligibilities": {
    "epoch": 2,
    "beacon": "4+M4ng==",
    "atx": "7/xBObZ7610VRg9L/dqqbq8sbKcQihIqV+OqvxPmW7Y=",
    "activeSetSize": 2368,
    "eligibilities": [
      {"layer": 11211,"count": 1},
      {"layer": 11218,"count": 1},
      {"layer": 11133,"count": 1},
      {"layer": 11439,"count": 1},
      {"layer": 8373,"count": 1},
      {"layer": 11408,"count": 1},
      {"layer": 10598,"count": 1},
      {"layer": 11944,"count": 1},
      {"layer": 11591,"count": 1},
      {"layer": 9920,"count": 1},
      {"layer": 11209,"count": 1},
      {"layer": 11422,"count": 1},
      {"layer": 8629,"count": 1},
      {"layer": 11554,"count": 1},
      {"layer": 10381,"count": 1},
      {"layer": 9297,"count": 1},
      {"layer": 8529,"count": 1},
      {"layer": 9765,"count": 1},
      {"layer": 9168,"count": 1},
      {"layer": 11314,"count": 1},
      {"layer": 8300,"count": 1},
      {"layer": 8840,"count": 1},
      {"layer": 11891,"count": 1},
      {"layer": 9307,"count": 1
      }
    ]
  }
}
{
  "timestamp": "2023-08-12T09:45:00.969431800Z",
  "help": "Published proposal. Rewards will be received, once proposal is included into the block.",
  "proposal": {
    "layer": 8373,
    "proposal": "qknRjqTHC62ShTJ3EOuRgLSoWos="
  }
}
```

Worth to note. I have accidentally created another post data 1.75 TB with the same SmesherID, but seems to be they have not been published. My 256 GB node on the explorer seems to be looking correct.

## Steps to reproduce
N/A

## Actual Behavior
N/A

## Expected Behavior
N/A

## Environment
Please complete the following information:
 - OS: Windows
 - Node Version: 
 - Smapp version (if applicable): 1.0.14
 - 
## Additional Resources 
[spacemesh-log-7c8cef2b.zip](https://github.com/spacemeshos/go-spacemesh/files/12329817/spacemesh-log-7c8cef2b.zip)

**Comment by dshulyak** [comment]
> {"L":"INFO","T":"2023-08-11T13:02:03.452Z","N":"35162.malfeasance","M":"new malfeasance proof","node_id":"35162dcc8b32bb059844a8eb36a6edd65f55ec9e3e2aeb3698e4a437c7d5bda4","module":"malfeasance","requestId":"49f5a9e3-4c5b-471e-9e74-fbcaf13d6b7f","smesher":"e2d279e52ded8a8b4f8d229e04b3e64767f7895e64c866bdeb9fdfb1154645a6","proof":{"generated_layer":8124,"type":"hare equivocation","msgs":{"first":{"layer":8124,"round":3,"msgHash":"0x1b8d0dd0bd8d12dc853b2597d90e40c039a6336590e27e27ff3358d7ac1b5fce"},"second":{"layer":8124,"round":3,"msgHash":"0x6e89367da9fa58c0e7b1172532045a8b17ca95cf45011e94f5f73c9f4d6c334c"}},"received":"0001-01-01T00:00:00.000Z"},"hare eligibility":{"layer":8124,"round":3,"smesher":"e2d279e52ded8a8b4f8d229e04b3e64767f7895e64c866bdeb9fdfb1154645a6","count":1,"proof":"cbf1937f2cb9fb5e5f1030053e840218edfcebad7bd479f78d38e3665feed0915c6d4f8575a4c65b7757dc85835be066fc2be5f9aa1a737966a2dfe9f08cd71d761742e8c1c0d28f25697f115b7bf80c"},"name":"malfeasance"}

unfortunately this identity won't be able to receive rewards as it equivocated

**Comment by scj85** [comment]
Thank you @dshulyak. 
Won't be able to receive rewards permanently or just for the current epoch?

Can I continue creating another post data with new SmesherID, but using the same rewards address that has been used for the node above?

**Comment by dshulyak** [comment]
> Won't be able to receive rewards permanently or just for the current epoch?

yes unfortunately this is permanent

>  Can I continue creating another post data with new SmesherID, but using the same rewards address that has been used for the node above?

coinbase (rewards address) can be reused

**Comment by ndcc5** [comment]
> 
Due to the high resource consumption of version 1.014, I used Cli to run the updated data, and the original smapp was not closed for fear of missing the reward. This results in node addresses being permanently disallowed because of repeated runs. I don't think that's reasonable. Furthermore, you never announced that running the same node at the same time would permanently prohibit rewards, and if you did, we would certainly pay special attention.

**Comment by kawww** [comment]
1.0.14 cpu/mem too high and my vm nodes crashed many times, then I copy some nodes to other pc but vm nodes not closed..ok these nodes unfortunately "permanent" gone.

Another two nodes have same nodeid because forgot change disk. It was too late to know this when epoch2 begin,  20 ploting days wasted.

This is permanent rule should in faq or get started with red big bold** style or it must cause more and more people lost coins in the next epoch.

**Comment by ndcc5** [comment]
equivocated？

> > 
> 
> Due to the high resource consumption of version 1.014, I used Cli to run the updated data, and the original smapp was not closed for fear of missing the reward. This results in node addresses being permanently disallowed because of repeated runs. I don't think that's reasonable. Furthermore, you never announced that running the same node at the same time would permanently prohibit rewards, and if you did, we would certainly pay special attention.

I don't think it's equivocated on purpose
