### ISSUE TITLE
ballots, proposal: don't accept object from future

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#4834]
if someone's clock is off by more than a layer time, they may send objects for next layers.
this is useless from protocol perspective as users are submitting transactions with proposals.
tortoise is not supposed to count such ballots as well.

**Comment by countvonzero** [comment]
so if a miner see that it published a proposal in the log (even if it's far in the future), if the proposal is ignored as a result of this bug fix, the miner will lose reward for that proposal? 

should we try to re-publish own proposals somehow?

**Comment by dshulyak** [comment]
i think this fix should force them to fix the clock

**Comment by countvonzero** [comment]
even after they fix the clock, without republishing on startup, they will still miss the rewards.
in general republishing own data (future atx/proposals) should be a good thing to do.

**Comment by dshulyak** [comment]
from protocol perspective ballots/proposal that was created in advance is useless. it will have bad votes (it will vote on empty layers) and it will have no useful transactions. sure if someone will manually republish it will be accepted, as we don't have an in-protocol solution to prevent it. but otherwise i don't see what is good about it, and why we should care
