### ISSUE TITLE
My address is on the prohibited award list, what is the reason. How to solve it?

### ISSUE THREAD

**Issue by ndcc5** [spacemeshos/go-spacemesh#4843]
0x8d3da74d9bd398830389a30fd24bef5811d06fcbe9de5cf8408892f3b7ef8be0

What causes a node to be blacklisted? Please let me know that in the early stage, many things are not understood by everyone, and they are all exploring. Please do not prohibit node addresses so strictly.

**Comment by dshulyak** [comment]
lets keep this discussion in original thread https://github.com/spacemeshos/smapp/issues/1440 . we will clarify soon
