### ISSUE TITLE
Publish releases to docker-hub with corresponding tags

### ISSUE THREAD

**Issue by brusherru** [spacemeshos/go-spacemesh#4844]
## Description
Currently, we're uploading images to DockerHub using commit SHA.
It will be much more handy if we will also tag releases with the same version as we have in Github.

For example,
- release v1.0.17 [was pushed](https://github.com/spacemeshos/go-spacemesh/actions/runs/5848819088/job/15856490864#step:3:498) to `spacemeshos/go-spacemesh-dev:437777a`,
- but updates in [develop pushed](https://github.com/spacemeshos/go-spacemesh/actions/runs/5852385540/job/15864542755#step:3:504) to `spacemeshos/go-spacemesh:411d98c`.

I think it'd be better to have the release version available by `spacemeshos/go-spacemesh:v1.0.17`

## Affected code
GHA workflow.

**Comment by pigmej** [comment]
@brusherru https://github.com/spacemeshos/go-spacemesh/pull/4705 that's this one, isn't it?
