### ISSUE TITLE
can't run in docker

### ISSUE THREAD

**Issue by bugxzhu** [spacemeshos/go-spacemesh#4847]
## Description
 2023-08-15T03:16:48.564Z	ERROR	66cc9.post	post setup session failed	{"node_id": "66cc9a55b9dfe7a0f067d23e9581d1c4b74c9b2987a4051e4f9d60cbeb9f30b0", "module": "post", "errmsg": "failed to compute labels: initializing scrypter: no provider specified", "name": "post"}
spacemesh4    | 2023-08-15T03:16:48.565Z	ERROR	66cc9.atxBuilder	Fatal: goroutine panicked. Stacktrace: goroutine 4514 [running]:

the cli can't find GPUs!

**_this bug happed from go-spacemesh 1.0.15!_**

docker-compose.yaml

version: '3'
services:
   spacemesh:
     container_name: spacemesh
     image: spacemesh:1.0.17
     runtime: nvidia
     environment:
       NVIDIA_VISIBLE_DEVICES: 1             ### the second gpu
       NVIDIA_DRIVER_CAPABILITIES: compute,utility
     volumes:
       - ./entrypoint.sh:/root/entrypoint.sh
       - /pool/spacemesh/data:/data
       - /pool/spacemesh/data/spacemesh:/root/.spacemesh/
     entrypoint: ["/bin/bash","/root/entrypoint.sh"]
     logging:
       driver: "json-file"
       options:
         max-size: "5g"
     restart: always
     network_mode: "host"

**Comment by fasmat** [comment]
Hi @bugxzhu 

recently the auto-benchmarking of `post` has been removed. Instead nodes now need to explicitly specify which device they want to use as provider for initialisation.

You can temporarily re-enable the old behavior by adding the following to your node config:

```json
{
	"smeshing": {
		"smeshing-opts": {
			"smeshing-opts-provider": -1
		}
	}
}
```

This is deprecated functionality that will be discontinued in a future release. You should see in your logs warnings about the deprecation and which provider ID was selected. You can then replace the `-1` with that ID.
