### ISSUE TITLE
malfeasance: exit cleanly with clear error message when self malfeasance detected

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#4872]
Today, a node will continue smeshing even after it's equivocated and a malfeasance proof against it has been generated. But of course it won't earn any rewards in this situation. The right behavior here is, upon detection of a valid malfeasance proof against its own smesherID, to immediately shut down cleanly and display an error message to the user, something like, "This smesherID equivocated and is permanently ineligible to earn rewards or participate in consensus. For more information, see: <link>."

**Comment by dshulyak** [comment]
see last item in https://github.com/spacemeshos/go-spacemesh/issues/4857
