### ISSUE TITLE
Feature request: support connect to some whitelisted peers only

### ISSUE THREAD

**Issue by hairtail** [spacemeshos/go-spacemesh#4896]
## Environment
Please complete the following information:
 - OS: 
 
 - Node Version: 
 
 - Smapp version (if applicable):

**Comment by lrettig** [comment]
This is possible. The instructions are here: https://github.com/spacemeshos/go-spacemesh/blob/develop/p2p/README.md

Let us know if anything is unclear. Thanks!

**Comment by hairtail** [comment]
> This is possible. The instructions are here: https://github.com/spacemeshos/go-spacemesh/blob/develop/p2p/README.md
> 
> Let us know if anything is unclear. Thanks!

Thanks, it helps. I'm confused about the public node config part, do i have to add all private nodes in config `p2p. direct ` for public node?

**Comment by lrettig** [comment]
yes, exactly!
