### ISSUE TITLE
metrics-push Invalid argument

### ISSUE THREAD

**Issue by xiaoliuxiao6** [spacemeshos/go-spacemesh#4911]
type PublicMetrics struct {
	MetricsURL        string            `mapstructure:"metrics-url"`
	MetricsPushPeriod time.Duration     `mapstructure:"metrics-push-period"`
	MetricsPushUser   string            `mapstructure:"metrics-push-user"`
	MetricsPushPass   string            `mapstructure:"metrics-push-pass"`
	MetricsPushHeader map[string]string `mapstructure:"metrics-push-header"`
}

MetricsURL        string            `mapstructure:"metrics-url"`
should be:
MetricsURL        string            `mapstructure:"metrics-push"`

**Comment by dshulyak** [comment]
sorry, the config should match keys in this structure not in the opposite direction
