### ISSUE TITLE
miner.ActiveSetFromEpochFirstBlock will use different block depending on synced certificate

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#4912]
if node wasn't online and synced certificates only for several last layers it will use different block for active set compared with 
nodes that were online for all time and have the earliest certificates.

i think that function should ignore certificates and use any applied block regardless of the reason

**Comment by dshulyak** [comment]
this is mostly important for hare. will be obsolete with graded oracle

**Comment by countvonzero** [comment]
if code is changed to use applied block, and block downloading is delayed, it will fallback to tortoise active set. so the outcome is still not deterministic. maybe worth punting until graded oracle is deployed :D
