### ISSUE TITLE
Unable to run go-spacemesh program

### ISSUE THREAD

**Issue by ChanQ0en** [spacemeshos/go-spacemesh#4919]
I downloaded the source code through github, compiled the binary file directly on the running machine, and started running. At first, I thought it was my problem. Later, I found that I downloaded the official binary package and the same error was reported.

I downloaded the config file through https://configs.spacemesh.network/config.mainnet.json without modifying any parameters.

The binary command I run looks like this:
./go-spacemesh --listen /ip4/0.0.0.0/tcp/7513 --config ./tn1.json -d ./sm_data --smeshing-coinbase wallet-address --smeshing-start --smeshing-opts-datadir ./post_data

The error log is as follows:
panic: failed to start smeshing: failed to prepare post initializer: new initializer: invalid `opts.NumUnits`; expected: >= 4, given: 2

goroutine 1 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x0?, 0x0?, {0x0?, 0x1?, 0x0?})
	/root/go/pkg/mod/go.uber.org/zap@v1.25.0/zapcore/entry.go:196 +0x65
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000456ea0, {0x0, 0x0, 0x0})
	/root/go/pkg/mod/go.uber.org/zap@v1.25.0/zapcore/entry.go:262 +0x3ec
go.uber.org/zap.(*SugaredLogger).log(0xc00099ef88, 0x4, {0x1b8e1b1?, 0x0?}, {0xc00099f160?, 0x2?, 0x2?}, {0x0, 0x0, 0x0})
	/root/go/pkg/mod/go.uber.org/zap@v1.25.0/sugar.go:316 +0xee
go.uber.org/zap.(*SugaredLogger).Panicf(...)
	/root/go/pkg/mod/go.uber.org/zap@v1.25.0/sugar.go:202
github.com/spacemeshos/go-spacemesh/log.Log.Panic({0xc0008ec0e0?, {0x0?, 0x187e411214f76093?}}, {0x1b8e1b1, 0x1c}, {0xc00099f160, 0x1, 0x1})
	/opt/project/go-spacemesh/log/zap.go:47 +0x1bb
github.com/spacemeshos/go-spacemesh/node.(*App).startServices(0xc000372840, {0x1ed06a8?, 0xc000908f40})
	/opt/project/go-spacemesh/node/node.go:1026 +0x4a7
github.com/spacemeshos/go-spacemesh/node.(*App).Start(0xc000372840, {0x1ed06a8, 0xc000908f40})
	/opt/project/go-spacemesh/node/node.go:1403 +0x15f3
github.com/spacemeshos/go-spacemesh/node.GetCommand.func1.1({0x1ed06a8, 0xc000908f40})
	/opt/project/go-spacemesh/node/node.go:168 +0x377
github.com/spacemeshos/go-spacemesh/node.GetCommand.func1(0xc0002ec000?, {0x19fda3f?, 0xb?, 0xb?})
	/opt/project/go-spacemesh/node/node.go:189 +0x399
github.com/spf13/cobra.(*Command).execute(0xc0002ec000, {0xc00012c010, 0xb, 0xb})
	/root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002ec000)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd

I didn't find a corresponding solution from the documentation, and tried to find a solution from the code, but I couldn't find it. I couldn't find invalid `opts.NumUnits`; expected: >= 4, given: 2 from the code. Where is `opts.NumUnits` printed in the error message.

The hardware configuration of my machine:
cpu: Intel(R) Xeon(R) CPU E5-2678 v3 @ 2.50GHz * 2
memory: ddr4 32g * 8
disk: 480G SSD
graphics card: Nvidia RTX 3060

my binary version is v1.1.1+4441f5235007c944b369b12bd22c098106d1ad0a

my OS is 	Ubuntu 22.04 LTS 

my OS kernel is 5.15.0-79-generic

**Comment by countvonzero** [comment]
@ChanQ0en thanks for the reports.

please help with debugging by sharing 
- binary version you downloaded and compiled
- the error messages, both from compiled and downloaded binary if they are different.
- your OS

it's rather difficult to investigate further without more info.

**Comment by ChanQ0en** [comment]
The above is the problem I am currently encountering, and I have spent 2 to 3 days and can't solve it

**Comment by countvonzero** [comment]
@ChanQ0en sorry for the lack of documentation on this. we are working on improving that.

i assumed you followed this one https://github.com/spacemeshos/testnet-guide/blob/master/cli.md#go-spacemesh-node-1.
it was written for testnet participation and is a little outdated. it says --smeshing-opts-numunits defaults to 4 but that was incorrect. the code defaults to 2.

can you try setting --smeshing-opts-numunits=4 (or the actual unit you are initializing)?

**Comment by ChanQ0en** [comment]
I have added `--smeshing-opts-numunits=4` to the command line to execute, and the program is running, thank you very much
