### ISSUE TITLE
Data race in hare protocol

### ISSUE THREAD

**Issue by antonlerner** [spacemeshos/go-spacemesh#492]
# Overview / Motivation

# The Task
Fix data race 

# Implementation Notes
WARNING: DATA RACE
Read at 0x00c0001042c8 by goroutine 54:
  github.com/spacemeshos/go-spacemesh/hare.(*ConsensusProcess).eventLoop()
      /Users/anton/go/src/github.com/spacemeshos/go-spacemesh/hare/algorithm.go:138 +0x217

Previous write at 0x00c0001042c8 by goroutine 52:
  github.com/spacemeshos/go-spacemesh/hare.(*ConsensusProcess).createInbox()
      /Users/anton/go/src/github.com/spacemeshos/go-spacemesh/hare/algorithm.go:119 +0x6d
  github.com/spacemeshos/go-spacemesh/hare.(*Broker).Register()
      /Users/anton/go/src/github.com/spacemeshos/go-spacemesh/hare/broker.go:112 +0x7f
  github.com/spacemeshos/go-spacemesh/hare.(*Hare).onTick()
      /Users/anton/go/src/github.com/spacemeshos/go-spacemesh/hare/hare.go:179 +0x911

Goroutine 54 (running) created at:
  github.com/spacemeshos/go-spacemesh/hare.(*ConsensusProcess).Start()
      /Users/anton/go/src/github.com/spacemeshos/go-spacemesh/hare/algorithm.go:113 +0x157
  github.com/spacemeshos/go-spacemesh/hare.(*Hare).onTick()
      /Users/anton/go/src/github.com/spacemeshos/go-spacemesh/hare/hare.go:178 +0x899

Goroutine 52 (finished) created at:
  github.com/spacemeshos/go-spacemesh/hare.(*Hare).tickLoop()
      /Users/anton/go/src/github.com/spacemeshos/go-spacemesh/hare/hare.go:223 +0x6e
# Contribution Guidelines
Important: Issue assignment to developers will be by the order of their application and proficiency level according to the tasks complexity. We will not assign tasks to developers who have'nt introduced themselves on our Gitter [dev channel](https://gitter.im/spacemesh-os/Lobby)

1. Introduce yourself on go-spacemesh [dev chat channel](https://gitter.im/spacemesh-os/Lobby) - ask our team any question you may have about this task
2. Fork branch `develop` to your own repo and work in your repo
3. You must document all methods, enums and types with [godoc comments](https://blog.golang.org/godoc-documenting-go-code)
4. You must write go unit tests for all types and methods when submitting a component, and integration tests if you submit a feature
5. When ready for code review, submit a PR from your repo back to branch `develop`
6. Attach relevant issue to PR

**Comment by gavraz** [comment]
It is not a bug since createInbox and eventLoop should not be executed concurrently.
createInbox should be called before we run Start which executes eventLoop (and that's how we use it).
