### ISSUE TITLE
Don't silently delete post data

### ISSUE THREAD

**Issue by hieixu** [spacemeshos/go-spacemesh#4994]
Version:  go-spacemesh  v.1.1.4 Linux

After I create postdata in computer A (NumUnits19),   I transfer postdata to computer B. 
I make a mistake in B when start go-spacemesh,  I set  NumUnits to 9.
As a result, go-spacemesh delete 10 NumUnits files silently.

I hope go-spacemesh raise a error message to warn people, not delete files silently.

**Comment by schinzelh** [comment]
Duplicate https://github.com/spacemeshos/go-spacemesh/issues/4594

**Comment by lrettig** [comment]
Also https://github.com/spacemeshos/post/issues/236

**Comment by lrettig** [comment]
Closing as duplicate
