### ISSUE TITLE
Build tool install script

### ISSUE THREAD

**Issue by avive** [spacemeshos/go-spacemesh#5]
Write a Shell script to install all build tools.

**Comment by dgonzalez** [comment]
What about a Vagrant file? We can use Vagrant to manage all the required tools and it is a controlled environment.

**Comment by avive** [comment]
Good idea go for it!  btw - we already have a start of a docker file for containerized dev and also please check out `make devtools` but by all means go for it - I'm pretty sure there will be more devs on this project who would like to work in an isolated vagrant env and not a dockerized one...
