### ISSUE TITLE
AccountMeshDataQuery CPU and memory bomb

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#5006]
## Description

A simple API call will cause a running mainnet node to consume too many resources and eventually crash.

## Steps to reproduce

Call `MeshService.AccountMeshDataQuery` with `account_mesh_data_flags=2`, e.g.:

```
> grpcurl -plaintext -d "{ \"filter\": { \"account_id\": { \"address\": \"sm1qqqqqq9g4kj4za94p9kf8engzwe7kjkxh89u9tszxqr3y\" }, \"account_mesh_data_flags\": 2 } }" 127.0.0.1:9092 spacemesh.v1.MeshService.AccountMeshDataQuery
```

## Actual Behavior
CPU usage skyrockets, memory usage begins to explode. If you kill the API request, memory usage instantly explodes.

## Expected Behavior
The brute force code that performs the ATX search needs to be rewritten to use a proper index (see #2064)

## Environment
Please complete the following information:
 - OS: Linux
 - Node Version: 52949ec1a32b8698577578e67be4cdf0cc34056e

Related: https://github.com/spacemeshos/smapp/issues/1439

**Comment by countvonzero** [comment]
it would be helpful to provide an memory profile

**Comment by lrettig** [comment]
Here you go. 002 is after the API call is made and 003 is after it's cancelled.

[pprof.go-spacemesh.alloc_objects.alloc_space.inuse_objects.inuse_space.003.pb.gz](https://github.com/spacemeshos/go-spacemesh/files/12601255/pprof.go-spacemesh.alloc_objects.alloc_space.inuse_objects.inuse_space.003.pb.gz)
[pprof.go-spacemesh.samples.cpu.003.pb.gz](https://github.com/spacemeshos/go-spacemesh/files/12601256/pprof.go-spacemesh.samples.cpu.003.pb.gz)
[pprof.go-spacemesh.samples.cpu.002.pb.gz](https://github.com/spacemeshos/go-spacemesh/files/12601257/pprof.go-spacemesh.samples.cpu.002.pb.gz)
[pprof.go-spacemesh.alloc_objects.alloc_space.inuse_objects.inuse_space.002.pb.gz](https://github.com/spacemeshos/go-spacemesh/files/12601258/pprof.go-spacemesh.alloc_objects.alloc_space.inuse_objects.inuse_space.002.pb.gz)

**Comment by dshulyak** [comment]
I think this came up at the start, so we disabled it on smapp side. Maybe if someone wants to they can fix it, but otherwise this is to be deprecated and instead separate handler that streams activations should be added

**Comment by dshulyak** [comment]
another consideration is about adding indexes for everything. we don't see it now, but every index increases write latency and amount of storage required. so we shouldn't just add everything api may need. instead api should be efficient for reindexing by external users.
