### ISSUE TITLE
Node can destroy postdata_metadata.json contents

### ISSUE THREAD

**Issue by chrisxch** [spacemeshos/go-spacemesh#5025]
## Description
When go-spacemesh is unable to write to postdata_metadata.json - for example the disk is full - the file is overwritten with a blank. I guess the update method is write to temp and replace.

## Steps to reproduce
Full disk. Start node.

## Actual Behavior
Node fails to start because postdata_metadata.json is overwrriten with a blank file.

## Expected Behavior
1) Don't try and overwrite postdata_metadata.json when there are no changes!
2) Confirm the update is successful before replacing existing postdata_metadata.json
3) Log attempted edits of postdata_metadata.json

## Environment
Observed on linux

**Comment by fasmat** [comment]
Hi @reythia! Which version of `go-spacemesh` are you using?

EDIT: this bug has been fixed in `v0.9.4` of `spacemeshos/post`, by making updates to `postdata_metadata.json` atomic. The next version of `go-spacemesh` will include the fix.

**Comment by fasmat** [comment]
We just now released v1.1.6 which includes a fix for the problem. I will close this issue. Should you experience problems again feel free to reopen or create a new issue 🙂
