### ISSUE TITLE
sync should not turn off consensus

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#5036]
## Description
I'm running two nodes (both v1.1.6), both see exactly the same layer data, but one thinks it's synced and one doesn't:

```
> grpcurl -plaintext localhost:9092 spacemesh.v1.NodeService.Status
{
  "status": {
    "connectedPeers": "44",
    "syncedLayer": {
      "number": 19386
    },
    "topLayer": {
      "number": 19395
    },
    "verifiedLayer": {
      "number": 19385
    }
  }
}
> grpcurl -plaintext localhost:9192 spacemesh.v1.NodeService.Status
{
  "status": {
    "connectedPeers": "1",
    "isSynced": true,
    "syncedLayer": {
      "number": 19386
    },
    "topLayer": {
      "number": 19395
    },
    "verifiedLayer": {
      "number": 19385
    }
  }
}
```

The one that thinks it's out of sync keeps printing:

```2023-09-19T12:17:50.296-0400    INFO    abcde.sync      node is too far behind      {"node_id": "abcde", "module": "sync", "sessionId": "06dadc41-5e8b-4f6a-8e67-7baff90bb12c", "current": "19395", "last synced": "19389", "behind threshold": 3, "name": "sync"}```

The only difference between them is that the "in sync" node is a private, local peer connected only to the other node, and the "out of sync" node is a public node with 40-50 peers. Unclear if this is related.

**Comment by lrettig** [comment]
logfile for "out of sync" node:

[log.txt.gz](https://github.com/spacemeshos/go-spacemesh/files/12664552/log.txt.gz)

**Comment by dshulyak** [comment]
i think this is a big problem. sync should be very conservative when it can interrupt consensus. in fact it should almost never interrupt it. current heuristic of 3 layers is no good, or something else makes it so that it doesn't work.
in latest outage it makes some nodes change sync state consistently. 

![image](https://github.com/spacemeshos/go-spacemesh/assets/1964576/904e228d-4fe2-42f3-865a-558cfaca5395)

**Comment by dshulyak** [comment]
lets change to not synced only if node was offline (0 peers reported by libp2p) for 30 minutes. in all other cases sync should not interrupt consensus

**Comment by lrettig** [comment]
> looks like all private nodes are in sync while public ones aren't (https://discord.com/channels/623195163510046732/1141739980306272427/1153806007785496698, also: https://discord.com/channels/623195163510046732/1141739980306272427/1153911699691282482)

I noticed this behavior as well (before the patch, on v1.1.6). do we have any idea why this might've been the case?

**Comment by dshulyak** [comment]
i think thats because atx sync queries are slow, and it caused sync to be delayed and fall out of expected window. below you can see that problems stopped when epoch started, and atx sync stopped.

private query public and all queries are fast, but public queries random peers on the network and responses are unpredictable. i think this just highlighted that we should not have such risky heuristics. 

![image](https://github.com/spacemeshos/go-spacemesh/assets/1964576/23f77bce-e201-4ead-b07d-0417c3619e6b)

**Comment by lrettig** [comment]
For the record this is what @tal-m [said](https://spacemesh.slack.com/archives/CG91F13C7/p1695241875668139?thread_ts=1695219171.300019&cid=CG91F13C7) - in order for a node to participate in consensus:

> It definitely needs to have timing information for the Hare rounds in the current instance, and IIRC for voting on proposals it needs information about the current state and the recent transactions in the mempool (to compute "conservative balance").
> For generating ballots it needs information about the recent Hare instances, and if there are layers older than hdist that haven't passed the confidence threshold it also needs all the most recent ballots.
> Of course, for doing anything it needs to be able to evaluate eligibility, so it needs to know the active set and any malfeasance proofs.

**Comment by dshulyak** [comment]
i was advocating for something similar in this topic https://github.com/spacemeshos/go-spacemesh/issues/4504#issuecomment-1637409952

but i think think hare can have more relaxed conditions, unlike tortoise hare can't vote against, so it is the same as not voting at all. i think we will remove IsSynced condition all together, and rely on specific data being available.

but what is more important is that:
- sync can't stop consensus (maybe what i changed is enough, but i would remove this completely and turn off consensus only if i have 0 peers for longer than 20-30 minutes)
- additionally there is a persistent issue about selecting responsive peers, which is also quite important

**Comment by dshulyak** [comment]
likely same problem as https://github.com/spacemeshos/go-spacemesh/issues/4977
