### ISSUE TITLE
k2pow isn't cached

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#5044]
## Description

If I interrupt the PoST proof generation process, after k2pow has concluded but before the proof has been generated, by killing the node, then when I restart the node it runs k2pow all over again.

Is there any reason we can't cache/save k2pow once it's been found for a given proof/given set of nonces?

## Steps to reproduce

1. Allow node to start post proof generation
2. Allow k2pow to finish
3. Restart node

**Comment by poszu** [comment]
The functionality of stopping proof generation and continuing from the point it stopped (rather than starting from scratch) is not implemented yet. It's tracked in https://github.com/spacemeshos/post-rs/issues/81 thus I'm closing this issue as a duplicate.
