### ISSUE TITLE
configuration to load multiple smeshers from disk

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#5089]
please see https://github.com/spacemeshos/go-spacemesh/issues/5085 for interface that must be implemented by every protocol that requires access to signing key.

#### storing keys

store keys in separately configurable directory, defaults to {datadir}/keys/. each smesher is stored in a file with public key in hexary encoding. on startup we have to read all public keys and calll `Register` method on every protocol that supports it.

#### refactoring / migration from old

right now "node_id" is added to every log line, we want to drop that. instead print info log with public key that was loaded from disk.

- [ ] save way to migrate key.bin to keys directory

#### generating key

node itself can generate only one key when smeshing starts. other keys are either generated manually by user, or using dynamic configuration as will be discussed in a follow up.

**Comment by fasmat** [comment]
> right now "node_id" is added to every log line, we want to drop that. instead print info log with public key that was loaded from disk.

Aren't NodeID and public key the same? I still think we should add NodeID to logs where it makes sense; e.g. if a certain identity published an ATX or voted in a specific way. I agree for general logs that are not tied to an identity we can drop NodeID in the logs.

**Comment by poszu** [comment]
> > right now "node_id" is added to every log line, we want to drop that. instead print info log with public key that was loaded from disk.
> 
> Aren't NodeID and public key the same? I still think we should add NodeID to logs where it makes sense; e.g. if a certain identity published an ATX or voted in a specific way. I agree for general logs that are not tied to an identity we can drop NodeID in the logs.

NodeID is already present in each logger _name_, for example:
```
INFO    8cbde.sync      all syncer goroutines finished
```

We could keep it similar if each identity had its dedicated logger for a given protocol.

**Comment by fasmat** [comment]
I'm not a big fan of putting the node id into the logger name. It will get lost if one creates a sub-logger with `WithName` (`go-spacemesh/log`) or `Named` (`zap`). Instead I would pass e.g. a logger named `atxBuilder` with the `node_id` field of the node that uses that component to an instance of `atxBuilder`.

**Comment by poszu** [comment]
>  It will get lost if one creates a sub-logger with WithName (go-spacemesh/log) or Named (zap).

AFAIK, both append postfix to the existing name.

**Comment by fasmat** [comment]
This has been completed with https://github.com/spacemeshos/go-spacemesh/pull/5592
