### ISSUE TITLE
dynamic reconfiguration of smeshers used in the node

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#5090]
for static configuration see https://github.com/spacemeshos/go-spacemesh/issues/5089
for supported interface see https://github.com/spacemeshos/go-spacemesh/issues/5085

in addition to loading smeshers from disk we can implement trusted API to register smeshers. such API will have to:
- save a key to the same or different location
- register key to all protocols that support it (implement `Register` method)

to implement this we can add grpc API. note that this will be trusted API, if people will want to expose it and do pool-like software authentication is on them.

**Comment by pigmej** [comment]
Been looking to it, I Think with the addition of smashing service this is no longer valid.
