### ISSUE TITLE
regression in TestSmeshing 

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#5108]
it started to fail yesterday

one failure in grafana
> {namespace="default", pod="systest-c0b652a-1695846173-828xx"}

another from github
> https://github.com/spacemeshos/go-spacemesh/actions/runs/6330116856/job/17191799323

**Comment by fasmat** [comment]
Another systest run where `TestSmeshing` failed for a dependency update: https://github.com/spacemeshos/go-spacemesh/actions/runs/6429159197/job/17457698077
