### ISSUE TITLE
Spacemesh version 1.2.1 shows white screen after 5 seconds of starting on linux

### ISSUE THREAD

**Issue by travjzx** [spacemeshos/go-spacemesh#5133]
## Description
When I try to start small after updating to 1.2.1 on Linux x64 it works for 5 seconds then the app screen goes white and I can't see anything. 

## Steps to reproduce
1. Open small 1.2.1 and then it goes white after 5 seconds

## Actual Behavior
White screen after 5 seconds

## Expected Behavior
Rolling back to 1.1.11 it appears to function correctly

## Environment
Please complete the following information:
 - OS: 
 Linux x64
 - Node Version: 
 1.2.1

## Additional Resources 
I noticed it was a bug on a different OS in a closed ticket previously.

**Comment by dshulyak** [comment]
please reopen this issue in https://github.com/spacemeshos/smapp
