### ISSUE TITLE
Smesher with many small proposals/rewards

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#5137]
Right now we let smeshers choose their own active sets and correspondingly their eligibility slots for proposals each epoch, which can result in a smesher submitting many proposals that each receive only a tiny reward. This appears to be happening with one smesher: 0x318cceb3df7174d42b582ffb4ccfd6ef6fbce4def8aee342c33e264ff78909f8

Example reward: https://explorer.spacemesh.io/rewards/6524347792abdc943072d99c

Coinbase: sm1qqqqqq8q9hxmhdqnktagjx7r65cf3vjfk79knvqnzy7yg

CC @dshulyak

**Comment by dshulyak** [comment]
we have minimal active weight parameter in the config to prevent such issue, we should raise it to known weight in current epoch. additionally there is pending issue of not rewarding atxs in hare that were received too late https://github.com/spacemeshos/go-spacemesh/issues/4942 , it will disincentivize smesher from keeping his node offline before the start of the epoch
