### ISSUE TITLE
make build failed!

### ISSUE THREAD

**Issue by e665107** [spacemeshos/go-spacemesh#5140]
hi, 
   When i build this source code,   after i enter the make build cmd,   it tells me following error:
   undefined reference to `pthread_attr_getguardsize@GLIBC_2.34'

  And i have updated the glibc to 2.34,  it shows me the same error!
  Can you give me some suggestions?  
  And now i am trying to compile this app on the arm64 platform， what do i need care about？

**Comment by fasmat** [comment]
This usually happens if your linux distribution is older than we support. We currently target Ubuntu 22.04 for both amd64 and arm64.

**Comment by lrettig** [comment]
Regarding arm64, we support this platform (see https://github.com/spacemeshos/go-spacemesh/blob/develop/.github/workflows/release.yml) - I don't think any special steps are required to build for it.

**Comment by aerth** [comment]
its because it `curl`'s a pre-compiled binary .so file that is meant for a specific OS version

the makefile should build `post-rs` from source, specific git commit hash, and use that .so file for linking the program
