### ISSUE TITLE
make oracle committee size configureable 

### ISSUE THREAD

**Issue by y0sher** [spacemeshos/go-spacemesh#517]
# Overview / Motivation

We want to be able to test different committee sizes as we will not be able to test with large numbers at first. 
Currently we pass committee size as a function parameter. we'll probably have constant values for each role at each time. it will be better to clean the API and relay on configuration.

# The Task

Remove committeeSize from the function's signature and create configuration that will be used instead.

# Implementation Notes

package `oracle`

# Contribution Guidelines
Important: Issue assignment to developers will be by the order of their application and proficiency level according to the tasks complexity. We will not assign tasks to developers who have'nt introduced themselves on our Gitter [dev channel](https://gitter.im/spacemesh-os/Lobby)

1. Introduce yourself on go-spacemesh [dev chat channel](https://gitter.im/spacemesh-os/Lobby) - ask our team any question you may have about this task
2. Fork branch `develop` to your own repo and work in your repo
3. You must document all methods, enums and types with [godoc comments](https://blog.golang.org/godoc-documenting-go-code)
4. You must write go unit tests for all types and methods when submitting a component, and integration tests if you submit a feature
5. When ready for code review, submit a PR from your repo back to branch `develop`
6. Attach relevant issue to PR

**Comment by gavraz** [comment]
@y0sher what is this?
I don't think we need this
