### ISSUE TITLE
About “remote machine as provider for PoST proofs”

### ISSUE THREAD

**Issue by bugxzhu** [spacemeshos/go-spacemesh#5262]
Dear teamers
     I'm glad there is such a feature. https://github.com/spacemeshos/go-spacemesh/blob/develop/README.md#using-a-remote-machine-as-provider-for-post-proofs
     I have some problem about it.
     1) How to query the status of client connection to server？Such as a list of clients like Chia?
     2) Do the Post machines still need to sync nodes?This is related to network bandwidth.
     3）After verification, can the Post machine be shut down and only need the node service to be online?

about the config file, I try config the certs like VPN. but 
"post-opts-post-service": "/path/to/service-binary"
how to config the service-binary path? Is it means go-spacemesh path?

Looking forward to your reply。

**Comment by pigmej** [comment]
Hey, 

The base way to know more is to look through: https://github.com/spacemeshos/pm/issues/259

It contains the description and design of the post as a service.


But in short:
1) each of the post services will expose a small API
2) no, they're specialized micro services responsible only for post
3) yes, it will need to be online just for proving 


Please be aware that currently the setup allows only 1:1 mapping, 1:many is expected in the near future.

**Comment by bugxzhu** [comment]
> Hey,
> 
> The base way to know more is to look through: [spacemeshos/pm#259](https://github.com/spacemeshos/pm/issues/259)
> 
> It contains the description and design of the post as a service.
> 
> But in short:
> 
> 1. each of the post services will expose a small API
> 2. no, they're specialized micro services responsible only for post
> 3. yes, it will need to be online just for proving
> 
> Please be aware that currently the setup allows only 1:1 mapping, 1:many is expected in the near future.

thanks.
And how to know my config is right? What I mean is how do I know that it is normal to test the Post service and node?
