### ISSUE TITLE
Make Build command encounters gcc related bug

### ISSUE THREAD

**Issue by NoFeeding** [spacemeshos/go-spacemesh#5268]
## Description
After git clone and golang environment set up. Make install is done but when I cast make build it always stuck at running gcc failed: exit status 1. Wanna check here again after installed many packages but still in vain. Thanks in advance!

## Steps to reproduce
1. Git clone https://github.com/spacemeshos/go-spacemesh
2. Install Golang environment v1.21.4
3. make install in go-spacemesh directory (might require git-lfs installation here)
4. cast make build 

## Actual Behavior
stop during make build due to running gcc failed: exit status 1

## Expected Behavior
done make build step and get binary file in build directory

## Environment
Please complete the following information:
 - OS: 
Ubuntu 22.04
- Golang:
v1.21.4

## Additional Resources 
cd cmd/node ; go build -o /home/ubuntu/go-spacemesh/build/go-spacemesh -ldflags "-X main.version=v1.2.4 -X main.commit=c43676f39bce977cd550ddea9f09ba6045b77ecf -X main.branch=c43676f3" .
# github.com/spacemeshos/go-spacemesh/cmd/node
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: warning: libOpenCL.so.1, needed by /home/ubuntu/go-spacemesh/build//libpost.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: /home/ubuntu/go-spacemesh/build//libpost.so: undefined reference to `clSetUserEventStatus@OPENCL_1.1'
/usr/bin/ld: /home/ubuntu/go-spacemesh/build//libpost.so: undefined reference to `clEnqueueReadBufferRect@OPENCL_1.1'
/usr/bin/ld: /home/ubuntu/go-spacemesh/build//libpost.so: undefined reference to `clRetainContext@OPENCL_1.0'
/usr/bin/ld: /home/ubuntu/go-spacemesh/build//libpost.so: undefined reference to `clEnqueueWriteBufferRect@OPENCL_1.1'
/usr/bin/ld: /home/ubuntu/go-spacemesh/build//libpost.so: undefined reference to `clGetDeviceIDs@OPENCL_1.0'
/usr/bin/ld: /home/ubuntu/go-spacemesh/build//libpost.so: undefined reference to `clGetKernelWorkGroupInfo@OPENCL_1.0'
/usr/bin/ld: /home/ubuntu/go-spacemesh/build//libpost.so: undefined reference to `clReleaseCommandQueue@OPENCL_1.0'
/usr/bin/ld: /home/ubuntu/go-spacemesh/build//libpost.so: undefined reference to `clBuildProgram@OPENCL_1.0'
/usr/bin/ld: /home/ubuntu/go-spacemesh/build//libpost.so: undefined reference to `clCreateKernel@OPENCL_1.0'
/usr/bin/ld: /home/ubuntu/go-spacemesh/build//libpost.so: undefined reference to `clGetPlatformIDs@OPENCL_1.0'
/usr/bin/ld: /home/ubuntu/go-spacemesh/build//libpost.so: undefined reference to `clSetKernelArg@OPENCL_1.0'
/usr/bin/ld: /home/ubuntu/go-spacemesh/build//libpost.so: undefined reference to `clGetCommandQueueInfo@OPENCL_1.0'
/usr/bin/ld: /home/ubuntu/go-spacemesh/build//libpost.so: undefined reference to `clRetainEvent@OPENCL_1.0'
/usr/bin/ld: /home/ubuntu/go-spacemesh/build//libpost.so: undefined reference to `clRetainProgram@OPENCL_1.0'
/usr/bin/ld: /home/ubuntu/go-spacemesh/build//libpost.so: undefined reference to `clGetPlatformInfo@OPENCL_1.0'
/usr/bin/ld: /home/ubuntu/go-spacemesh/build//libpost.so: undefined reference to `clGetProgramInfo@OPENCL_1.0'
/usr/bin/ld: /home/ubuntu/go-spacemesh/build//libpost.so: undefined reference to `clCreateBuffer@OPENCL_1.0'
/usr/bin/ld: /home/ubuntu/go-spacemesh/build//libpost.so: undefined reference to `clReleaseProgram@OPENCL_1.0'
/usr/bin/ld: /home/ubuntu/go-spacemesh/build//libpost.so: undefined reference to `clSetEventCallback@OPENCL_1.1'
/usr/bin/ld: /home/ubuntu/go-spacemesh/build//libpost.so: undefined reference to `clReleaseEvent@OPENCL_1.0'
/usr/bin/ld: /home/ubuntu/go-spacemesh/build//libpost.so: undefined reference to `clEnqueueFillBuffer@OPENCL_1.2'
/usr/bin/ld: /home/ubuntu/go-spacemesh/build//libpost.so: undefined reference to `clGetKernelArgInfo@OPENCL_1.2'
/usr/bin/ld: /home/ubuntu/go-spacemesh/build//libpost.so: undefined reference to `clEnqueueReadBuffer@OPENCL_1.0'
/usr/bin/ld: /home/ubuntu/go-spacemesh/build//libpost.so: undefined reference to `clCreateContext@OPENCL_1.0'
/usr/bin/ld: /home/ubuntu/go-spacemesh/build//libpost.so: undefined reference to `clWaitForEvents@OPENCL_1.0'
/usr/bin/ld: /home/ubuntu/go-spacemesh/build//libpost.so: undefined reference to `clGetContextInfo@OPENCL_1.0'
/usr/bin/ld: /home/ubuntu/go-spacemesh/build//libpost.so: undefined reference to `clRetainCommandQueue@OPENCL_1.0'
/usr/bin/ld: /home/ubuntu/go-spacemesh/build//libpost.so: undefined reference to `clEnqueueWriteBuffer@OPENCL_1.0'
/usr/bin/ld: /home/ubuntu/go-spacemesh/build//libpost.so: undefined reference to `clGetProgramBuildInfo@OPENCL_1.0'
/usr/bin/ld: /home/ubuntu/go-spacemesh/build//libpost.so: undefined reference to `clEnqueueReleaseGLObjects@OPENCL_1.0'
/usr/bin/ld: /home/ubuntu/go-spacemesh/build//libpost.so: undefined reference to `clRetainMemObject@OPENCL_1.0'
/usr/bin/ld: /home/ubuntu/go-spacemesh/build//libpost.so: undefined reference to `clEnqueueCopyBuffer@OPENCL_1.0'
/usr/bin/ld: /home/ubuntu/go-spacemesh/build//libpost.so: undefined reference to `clGetKernelInfo@OPENCL_1.0'
/usr/bin/ld: /home/ubuntu/go-spacemesh/build//libpost.so: undefined reference to `clGetEventInfo@OPENCL_1.0'
/usr/bin/ld: /home/ubuntu/go-spacemesh/build//libpost.so: undefined reference to `clReleaseContext@OPENCL_1.0'
/usr/bin/ld: /home/ubuntu/go-spacemesh/build//libpost.so: undefined reference to `clEnqueueCopyBufferRect@OPENCL_1.1'
/usr/bin/ld: /home/ubuntu/go-spacemesh/build//libpost.so: undefined reference to `clGetDeviceInfo@OPENCL_1.0'
/usr/bin/ld: /home/ubuntu/go-spacemesh/build//libpost.so: undefined reference to `clEnqueueNDRangeKernel@OPENCL_1.0'
/usr/bin/ld: /home/ubuntu/go-spacemesh/build//libpost.so: undefined reference to `clCreateProgramWithSource@OPENCL_1.0'
/usr/bin/ld: /home/ubuntu/go-spacemesh/build//libpost.so: undefined reference to `clReleaseKernel@OPENCL_1.0'
/usr/bin/ld: /home/ubuntu/go-spacemesh/build//libpost.so: undefined reference to `clReleaseMemObject@OPENCL_1.0'
/usr/bin/ld: /home/ubuntu/go-spacemesh/build//libpost.so: undefined reference to `clEnqueueAcquireGLObjects@OPENCL_1.0'
/usr/bin/ld: /home/ubuntu/go-spacemesh/build//libpost.so: undefined reference to `clCreateCommandQueue@OPENCL_1.0'
collect2: error: ld returned 1 exit status

make: *** [Makefile:69: go-spacemesh] Error 1

**Comment by pigmej** [comment]
You need opencl-dev or similar package as indicated by:
```
/usr/bin/ld: warning: libOpenCL.so.1, needed by
```

Please refer to your distro manual.

**Comment by NoFeeding** [comment]
Thanks @pigmej !! The opencl-dev package is actually the missing one.

For people who got same issue. I made it work with 

- sudo apt update
- sudo apt install ocl-icd-opencl-dev

Then make build just work smoothly.

**Comment by NoFeeding** [comment]
Thanks @pigmej  !! The opencl-dev package is actually the missing one.

For people who got same issue. I made it work with

sudo apt update
sudo apt install ocl-icd-opencl-dev
Then make build just work smoothly.
