### ISSUE TITLE
The json-rpc(--grpc-json-listener) port cannot be used

### ISSUE THREAD

**Issue by blocknodehub** [spacemeshos/go-spacemesh#5292]
Can you give me an example of how I use the json-rpc port to get data from the node

**Comment by yytany** [comment]
me too , i also want to get it .

**Comment by pigmej** [comment]
It's kinda old request but still:
```curl -X POST https://mainnet-api.spacemesh.network/spacemesh.v2alpha1.NodeService/Status```
