### ISSUE TITLE
Cannot set log level for `proposalBuilder` in config

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#5295]
## Description

Setting this in config seems to have no effect:

```
  "logging": {
      "proposalBuilder": "error"
  }
```

It seems to be because the proposalBuilder logger is not configured here:

https://github.com/spacemeshos/go-spacemesh/blob/51b425e629b53a1985fc720e7ab28424c7ac823c/config/logging.go#L17-L50

This issue appears in commit hash: 51b425e

Related: #5167, #5179

**Comment by dshulyak** [comment]
looks fixed here https://github.com/spacemeshos/go-spacemesh/pull/5420
