### ISSUE TITLE
core/sql: panic on db.Exec error

### ISSUE THREAD

**Issue by fasmat** [spacemeshos/go-spacemesh#5298]
## Description
From a discussion on this PR: https://github.com/spacemeshos/go-spacemesh/pull/5219#discussion_r1398668625 `db.Exec` can only return an error in 2 cases:

- the DB has already been closed
- the provided SQL is syntactically invalid

In both cases the error is severe enough that `db.Exec` should panic and cause the node to exit to avoid a node in a state it won't / cannot recover from to keep running and just log those errors.

## Affected code
- `db.Exec` and most functions calling it.

**Comment by dshulyak** [comment]
it is not the exhaustive list. it can also exit with interrupt if connection wasn't able to acquire lock. in that case you should retry, but node doesn't do that

**Comment by fasmat** [comment]
In that case should db.Exec retry (up to X times) before panicking? Otherwise every call to db.Exec would need to repeat that logic.

**Comment by dshulyak** [comment]
no please don't panic there, if you think that in some component you should exit do it there.

**Comment by fasmat** [comment]
Since panicing might be a overreaction in a lot of cases, I'll close the issue.
