### ISSUE TITLE
Can anyone provide sign transaction example?

### ISSUE THREAD

**Issue by realm520** [spacemeshos/go-spacemesh#5305]
## Description

I need a command line to for sending transactions automatically.
By refering https://github.com/spacemeshos/wiki/wiki/Integration-guide#example i found the code cannot work.

So anyone can provide a complete code sample?

**Comment by dshulyak** [comment]
https://github.com/spacemeshos/go-spacemesh/blob/develop/genvm/sdk/wallet/tx.go#L36-L84
