### ISSUE TITLE
`MeshService.LayersQuery` broken

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#5315]
## Description
It takes a very long time to run, close to a minute for a single layer, probably because it reads all ATX data (presumably the entire active set), probably without caching (no memory issue AFAICT). Then it produces this error:

```
> grpcurl -plaintext -d '{"start_layer":{"number": 30000}, "end_layer":{"number": 30000}}' localhost:9092 spacemesh.v1.MeshService.LayersQuery
ERROR:
  Code: ResourceExhausted
  Message: grpc: received message larger than max (8411536 vs. 4194304)
```

## Affected code

`api/grpcserver/mesh_service.go`

This issue appears in commit hash: 6499e01

Related: #5006

**Comment by bobbychen** [comment]
Halo ?how about this issue going on?

**Comment by lrettig** [comment]
> Halo ?how about this issue going on?

This has been fixed in #5334 and should be merged and released soon!

**Comment by poszu** [comment]
@lrettig This error:
>ERROR:
  Code: ResourceExhausted
  Message: grpc: received message larger than max (8411536 vs. 4194304)

is on the client (grpcurl) side, not go-spacemesh. The client limits the maximum size of response payload to 4MiB by default. There is a CLI argument to change this:
```
-max-msg-sz int
        The maximum encoded size of a response message, in bytes, that grpcurl
        will accept. If not specified, defaults to 4,194,304 (4 megabytes).
```

**Comment by lrettig** [comment]
Good catch, thanks for the clarification.
