### ISSUE TITLE
Inconsistent genesisid for Smapp

### ISSUE THREAD

**Issue by arc0035** [spacemeshos/go-spacemesh#5319]
I'm using Smapp 1.2.9 in MAC.

## Steps to reproduce 

Go to Settings->Wallets, See genesis network:

<img width="1027" alt="image" src="https://github.com/spacemeshos/go-spacemesh/assets/6778136/25136ac8-1b75-4939-be40-1b14012b0795">

It is a 7c8cef2bfd54447d60c3ffcc5daf974b24b74605

## Actual Behavior
If I  call GenesisID api, it yields another result:

<img width="997" alt="image" src="https://github.com/spacemeshos/go-spacemesh/assets/6778136/48673a52-4e95-4004-b56b-2b563c41fc52">

This is a base64 encoded genesis id, whose binary value covered is:

9eebff023abb17ccb775c602daade8ed708f0a50

The correct one is the latter, it can be used to sign transaction, but the former one "7c8cef2bfd54447d60c3ffcc5daf974b24b74605" is not correct.

## Expected Behavior
Smapp shows correct genesis id.

## Environment
Please complete the following information:
 - OS: MacOS 12+
 - Smapp version (if applicable): 1.2.9

**Comment by pigmej** [comment]
That's a known issue, unfixable currently because of how it's used later on in smapp, and we're working in the meantime to create smapp 2.0. The correct id is the one on go-spacemesh side.
