### ISSUE TITLE
How to get the from and to addresses of a transaction using GRPC?

### ISSUE THREAD

**Issue by LXHLeaner** [spacemeshos/go-spacemesh#5325]
## get the from and to addresses 

how to get the from and to addresses of a transaction using GRPC?
 now I using spacemesh.v1.TransactionService.TransactionsState only can get the principal and template address:
this "template" address is not I want,how to get , please help me!

**Comment by bobbychen** [comment]
you can try to decode the to address from raw .

**Comment by LXHLeaner** [comment]
> you can try to decode the to address from raw .

How to decode it?  I'm still getting incorrect decoding from raw.
the txid is 0x506a1d2c667808481e2846fd71cfc9ec0cfe0c88a1c888a2f3a81f56dc4ab330
the raw is 0000000000ed14e74eaded0587c40b03aecf07438c3a14e6ee40b80400000000243c18849937ba9d55725719270321d018c480fe0700d0ed902e0c6f2b577ddbcf8111cdd5042ae844f7e383ec00bc6ff1977c74db6bc4c4e06e118529abbaed5ec733d9db340b19e8e9c6c91b23ea037019271ea8b8fbb89703

I use the spacemesh.v1.TransactionService/ParseTransaction and get the to address is  sm1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqg56ypy7
but in fact the address is sm1qqqqqqpy8svgfxfhh2w42ujhrynsxgwsrrzgplss9t0lv

**Comment by bobbychen** [comment]
Example spend tx sign:

```
    ByteArrayOutputStream buff = new ByteArrayOutputStream(256);
    ScaleCodecWriter writer = new ScaleCodecWriter(buff);

    writer.writeByte(txVersion);
    writer.writeByteArray( principal.getData() );
    writer.writeCompact( method );
    writer.writeUint64( payload.getNonce() );
    writer.writeUint64( payload.getGasPrice() );
    writer.writeByteArray(arguments.getDestination().getData());
    writer.writeUint64( arguments.getAmount() );
    byte[] tx = buff.toByteArray();

    return tx;
```

you can decode it like below.

**Comment by lrettig** [comment]
See https://github.com/spacemeshos/wiki/wiki/Integration-guide#decoding

**Comment by lrettig** [comment]
Okay, I see that this info isn't clear in the integration guide right now. I'll add some info on this.

The recipient is SCALE-encoded inside the Spend method payload. The code that decodes this (for a simple wallet, simple send tx) is here: https://github.com/spacemeshos/go-spacemesh/blob/3d8eedfd44c6f9f8987e604b768596f6001fe703/genvm/templates/wallet/handler.go#L65

**Comment by lrettig** [comment]
Added a bit of info here: https://github.com/spacemeshos/wiki/wiki/Integration-guide#types

The short answer is, as I said above, this hasn't been added to the API yet. Opened https://github.com/spacemeshos/api/issues/288 to fix this.

Going to close this as there's no pending task here; feel free to subscribe to that issue instead for updates. Thanks for highlighting this.

**Comment by yaoyf888** [comment]
@LXHLeaner Are the from and to addresses resolved? I have questions about that, too
