### ISSUE TITLE
SpaceMesh full node use too much resource.

### ISSUE THREAD

**Issue by bobbychen** [spacemeshos/go-spacemesh#5326]
## Description
I'm running a full node . machine config is 16 cores and 128G RAM, disk is 1T. but after running a while. node stoped automatically, RAM is runing out.
and cannot see any errors in the log file.

## Environment
Please complete the following information:
 - OS: linux

**Comment by bobbychen** [comment]
I guess this issue root cause is the layersquery api. I found it hang on long time when query a layer

**Comment by lrettig** [comment]
@bobbychen I'll close this as a duplicate of https://github.com/spacemeshos/go-spacemesh/issues/5315, and we'll follow up there. If you have any reason to believe there's something else going on here feel free to reopen. Thanks!

**Comment by bobbychen** [comment]
This issue still existing in latest release. @lrettig

**Comment by bobbychen** [comment]
Reopening.
