### ISSUE TITLE
FAILED TO START SMESHING: FAILED TO PREPARE POST INITIALIZER: LOAD METADATA: ENCODING/HEX: INVALID BYTE: U+005A 'Z'

### ISSUE THREAD

**Issue by tauruszhao** [spacemeshos/go-spacemesh#5341]
## Steps to reproduce
1. smapp start...
2. network error

## Expected Behavior

   Main Network
FAILED TO START SMESHING: FAILED TO PREPARE POST INITIALIZER: LOAD METADATA: ENCODING/HEX: INVALID BYTE: U+005A 'Z'
## Environment
Please complete the following information:
 - OS: macos M2
 
 - Node Version: 
 
 - Smapp version (if applicable): 
 
v1.2.10

## Additional Resources 

2023-12-11T23:20:14.635+0800	PANIC	failed to start smeshing: failed to prepare post initializer: load metadata: encoding/hex: invalid byte: U+005A 'Z'
2023-12-11T23:20:14.635+0800	INFO	cb609.hare	weak coin reporter exited	{"node_id": "cb6091c45789181b8e98996d069304761d3f7ac3088dcc1ba248383d818f1e4c", "module": "hare"}
2023-12-11T23:20:14.635+0800	INFO	cb609.hare	hare3 results reporter exited	{"node_id": "cb6091c45789181b8e98996d069304761d3f7ac3088dcc1ba248383d818f1e4c", "module": "hare"}
panic: failed to start smeshing: failed to prepare post initializer: load metadata: encoding/hex: invalid byte: U+005A 'Z'panic: failed to start smeshing: failed to prepare post initializer: load metadata: encoding/hex: invalid byte: U+005A 'Z'

goroutine 1 [running]:

goroutine 1 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x0?, 0x0?, {0x0?, 0x1?, 0x0?})
	/Users/runner/go/pkg/mod/go.uber.org/zap@v1.26.0/zapcore/entry.go:196 +0x54
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc02f30c270, {0x0, 0x0, 0x0})
	/Users/runner/go/pkg/mod/go.uber.org/zap@v1.26.0/zapcore/entry.go:262 +0x3ec
go.uber.org/zap.(*SugaredLogger).log(0xc066ae0e98go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x0?, 0x0?, {0x0?, 0x1?, 0x0?})
	/Users/runner/go/pkg/mod/go.uber.org/zap@v1.26.0/zapcore/entry.go:196 +0x54
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc02f30c270, {0x0, 0x0, 0x0})
	/Users/runner/go/pkg/mod/go.uber.org/zap@v1.26.0/zapcore/entry.go:262 +0x3ec
go.uber.org/zap.(*SugaredLogger).log(0xc066ae0e98, 0x4, {0x101669bb2?, 0x0?}, {0xc066ae1078?, 0x2?, 0x2?}, {0x0, 0x0, 0x0})
	/Users/runner/go/pkg/mod/go.uber.org/zap@v1.26.0/sugar.go:316 +0xec
go.uber.org/zap.(*SugaredLogger).Panicf(...)
	/Users/runner/go/pkg/mod/go.uber.org/zap@v1.26.0/sugar.go:202
github.com/spacemeshos/go-spacemesh/log.Log.Panic({0xc0004f80e0?, {0x0?, 0x4bf8cc9df023f89e?}, 0x4, {0x101669bb2?, 0x0?}, {0xc066ae1078?, 0x2?, 0x2?}, {0x0, 0x0, 0x0})
	/Users/runner/go/pkg/mod/go.uber.org/zap@v1.26.0/sugar.go:316 +0xec
go.uber.org/zap.(*SugaredLogger).Panicf(...)
	/Users/runner/go/pkg/mod/go.uber.org/zap@v1.26.0/sugar.go:202
github.com/spacemeshos/go-spacemesh/log.Log.Panic({0xc0004f80e0?, {0x0?, 0x4bf8cc9df023f89e?}}, {0x101669bb2, 0x1c}, {0xc066ae1078, 0x1, 0x1})
	/Users/runner/work/go-spacemesh/go-spacemesh/log/zap.go:47 +0x1b8
github.com/spacemeshos/go-spacemesh/node.(*App).startServices(0xc00027c180, {0x1019a1bf0?, 0xc00036e2c0})
	/Users/runner/work/go-spacemesh/go-spacemesh/node/node.go:1138 +0x407
github.com/spacemeshos/go-spacemesh/node.(*App).startSynchronous(0xc00027c180, {}, {0x101669bb2, 0x1c}, {0xc066ae1078, 0x1, 0x1})
	/Users/runner/work/go-spacemesh/go-spacemesh/log/zap.go:47 +0x1b8
github.com/spacemeshos/go-spacemesh/node.(*App).startServices(0xc00027c180, {0x1019a1bf0?, 0xc00036e2c0})
	/Users/runner/work/go-spacemesh/go-spacemesh/node/node.go:1138 +0x407
github.com/spacemeshos/go-spacemesh/node.(*App).startSynchronous(0xc00027c180, {0x1019a1bf0, 0xc00036e2c0})
	/Users/runner/work/go-spacemesh/go-spacemesh/node/node.go:1613 +0x157a
github.com/spacemeshos/go-spacemesh/node.(*App).Start(0xc00027c180, {0x1019a1bf0, 0xc00036e2c0})
	/Users/runner/work/go-spacemesh/go-spacemesh/node/node.go:1479 +0x4f
github.com/spacemeshos/go-spacemesh/node.GetCommand.func1.1({0x1019a1bf0, 0xc00036e2c0})
	/Users/runner/work/go-spacemesh/go-spacemesh/node/node.go:171 +0x328
github.com/spacemeshos/go-spacemesh/node.GetCommand.func1(0xc000486700?, {0x1014da929?, 0x4?, 0x1014da405?0x1019a1bf0, 0xc00036e2c0})
	/Users/runner/work/go-spacemesh/go-spacemesh/node/node.go:1613 +0x157a
github.com/spacemeshos/go-spacemesh/node.(*App).Start(0xc00027c180, {0x1019a1bf0, 0xc00036e2c0})
	/Users/runner/work/go-spacemesh/go-spacemesh/node/node.go:1479 +0x4f
github.com/spacemeshos/go-spacemesh/node.GetCommand.func1.1({0x1019a1bf0, 0xc00036e2c0})
	/Users/runner/work/go-spacemesh/go-spacemesh/node/node.go:171 +0x328
github.com/spacemeshos/go-spacemesh/node.GetCommand.func1(0xc000486700?, {0x1014da929?, 0x4?, 0x1014da405?})
	/Users/runner/work/go-spacemesh/go-spacemesh/node/node.go:191 +0x34b
github.com/spf13/cobra.(*Command).execute(0xc0002ba000, {0xc000146010, 0x6, 0x6})
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x863
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002ba000)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
})
	/Users/runner/work/go-spacemesh/go-spacemesh/node/node.go:191 +0x34b
github.com/spf13/cobra.(*Command).execute(0xc0002ba000, {0xc000146010, 0x6, 0x6})
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x863
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002ba000)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
	/Users/runner/work/go-spacemesh/go-spacemesh/cmd/node/main.go:24 +0xca
main.main()
	/Users/runner/work/go-spacemesh/go-spacemesh/cmd/node/main.go:24 +0xca

**Comment by pigmej** [comment]
That seems to be a damaged metadata file. Please check if you have some extra characters there.
