### ISSUE TITLE
fetch: panic: close of closed channel

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#5436]
## Description
Occurred seemingly randomly on a node running v1.2.13. Unclear whether this issue has been fixed in 1.3.x.

## Steps to reproduce
Unknown

## Actual Behavior
Unexpected panic:

```
panic: close of closed channel

goroutine 168364038 [running]:
github.com/spacemeshos/go-spacemesh/fetch.(*Fetch).hashValidationDone(0xc0594787e0, {0x4b, 0x29, 0x19, 0x4f, 0x18, 0xc2, 0xf7, 0x5f, 0x50, ...}, ...)
        /home/runner/work/go-spacemesh/go-spacemesh/fetch/fetch.go:420 +0x285
github.com/spacemeshos/go-spacemesh/fetch.(*Fetch).receiveResponse.func1()
        /home/runner/work/go-spacemesh/go-spacemesh/fetch/fetch.go:387 +0x8d
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /home/runner/go/pkg/mod/golang.org/x/sync@v0.4.0/errgroup/errgroup.go:75 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 168358472
        /home/runner/go/pkg/mod/golang.org/x/sync@v0.4.0/errgroup/errgroup.go:72 +0x96
```

## Environment
Please complete the following information:
 - OS: Linux
 - Node Version: 1.2.13

## Additional Resources 
Log tail attached: [buffer.txt](https://github.com/spacemeshos/go-spacemesh/files/13923258/buffer.txt)

**Comment by acud** [comment]
should be fixed by https://github.com/spacemeshos/go-spacemesh/pull/6152
