### ISSUE TITLE
verify PoST: invalid argument

### ISSUE THREAD

**Issue by sokach-dev** [spacemeshos/go-spacemesh#5483]
I use postcli initializing data, so this is invalid data or network error?

![image](https://github.com/spacemeshos/go-spacemesh/assets/93634186/def4e82a-2e5a-4866-b293-0445d11a4d9b)

**Comment by poszu** [comment]
It's impossible to tell what happened based on the screenshot. Could you share a full log and describe the go-spacemesh version that you use and the steps that you followed?

**Comment by fasmat** [comment]
Closed because of no follow up
