### ISSUE TITLE
After the node is upgraded to the latest version, data cannot be synchronized

### ISSUE THREAD

**Issue by blocknodehub** [spacemeshos/go-spacemesh#5505]
v1.2.13 => v1.3.5-hotfix2

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1335195]

goroutine 2026591 [running]:
github.com/spacemeshos/go-spacemesh/blocks.(*Generator).Stop(0xc07daa4800)
	/opt/smhmain/core/go-spacemesh/blocks/generator.go:124 +0x35
github.com/spacemeshos/go-spacemesh/node.(*App).stopServices(0xc000408380, {0x1e29848?, 0xc000369810?})
	/opt/smhmain/core/go-spacemesh/node/node.go:1468 +0x385
github.com/spacemeshos/go-spacemesh/node.(*App).Cleanup(0xc000408380, {0x1e29848, 0xc000369810})
	/opt/smhmain/core/go-spacemesh/node/node.go:504 +0x6d
github.com/spacemeshos/go-spacemesh/node.GetCommand.func1.1.1()
	/opt/smhmain/core/go-spacemesh/node/node.go:191 +0x2d
created by github.com/spacemeshos/go-spacemesh/node.GetCommand.func1.1 in goroutine 1
	/opt/smhmain/core/go-spacemesh/node/node.go:190 +0x412

**Comment by poszu** [comment]
Thanks for your report @blocknodehub. This problem had already been fixed in #5441 but, unfortunately, it was not ported to v1.3

**Comment by pigmej** [comment]
It was included in 1.3.8 via https://github.com/spacemeshos/go-spacemesh/pull/5509
