### ISSUE TITLE
Urgent Concern: Addressing Centralization in the Spacemesh Project

### ISSUE THREAD

**Issue by bugxzhu** [spacemeshos/go-spacemesh#5544]
Dear Spacemesh Team,

I hope this message finds you well. I am writing to express my ongoing concern regarding the increasing centralization of the Spacemesh project. While I have raised this concern previously, the responses from the team instilled a sense of hope and optimism. However, I believe it is crucial for us to revisit this issue once again.

In my view, the Spacemesh project should not rely on the existence of mining pools. Instead, we should strive to lower the barrier to entry for setting up post servers to encourage broader participation from nodes. Currently, we are witnessing a ratio of approximately 1:9 between the number of nodes running Spacemesh software and those participating in mining pools. This trend is deeply concerning as it indicates a movement towards increased centralization, posing a significant challenge to the Spacemesh project.

One major contributing factor is the lack of new mining pools joining the network. Additionally, the disparity in rewards between post times of 12 hours and 24 hours is leading to an increasing concentration of miners within a single pool. Furthermore, we must consider the impact of price dynamics. Premature involvement of mining pools in a project aimed at decentralization is not ideal. When pools monopolize the project and levy substantial fees, they often resort to selling off assets to recoup costs, as witnessed in some early-stage failed projects. Continual high centralization of mining pools may eventually lead Spacemesh to serve the pools rather than vice versa. This poses a fatal risk as pools typically do not prioritize the project's long-term viability.

Therefore, I urge the team to carefully consider my concerns and take appropriate measures to address them. The success of Spacemesh as a decentralized project hinges on our ability to maintain its decentralized nature. I look forward to hearing your thoughts and proposed actions regarding this matter.

Thank you for your attention to this important issue.

Best regards

**Comment by dshulyak** [comment]
i will reference people that may want to reply @noamnelke @lrettig @pigmej  :upside_down_face: but otherwise please open this in discussions, i think github issues is better for technical issues

**Comment by lrettig** [comment]
Hi @bugxzhu , @dshulyak is correct, an issue is not the right place to discuss this topic. In fact we already have an open discussion item on the topic. Happy to follow up there! https://github.com/spacemeshos/go-spacemesh/discussions/5104
