### ISSUE TITLE
Improve visibility around poet registrations in events

### ISSUE THREAD

**Issue by poszu** [spacemeshos/go-spacemesh#5565]
## Description
Users need a better UX around poet registrations to help them understand the process of registration in poet services and querying proofs.

## Acceptance Criteria
Add new events saying:
- created poet client (URL)
- registered in poet (URL, challenge, round)
- got proof from poet (URL, round, ticks)
- selected best poet proof (URL, round, ticks)

**Comment by chrisxch** [comment]
Great to see this getting some love from core devs!

Based on feedback and questions users raise on T24, might I also suggest considering:

- Cycle gap open for n hrs
Reassures users that the node "knows" the CG is open and is operating correctly / on the same basis as user expects. Useful for people switching between shifts + gaps.

- Not generating proof because... 
Many users still don't understand the circumstances of registration only and assume something is wrong. The 'waiting for registration' event still has users asking why and is it broken.

- Node failed to register with poet in time
Just another one for managing user expectations - negative confirmation can be as useful as positive confirmation.

**Comment by fasmat** [comment]
For me events should be targeted primarily at users/operators and give information relevant to them. Because of this I believe that `created poet client` isn't needed and `registered in poet` is an event we already have in `Event_PoetWaitProof` or at least it communicates the same information.

**Comment by poszu** [comment]
@fasmat, the `Event_PoetWaitProof` is not enough as it only communicates "finished registering in poets in epoch X". It doesn't say in which poets the node registered.

**Comment by jellonek** [comment]
So... Can you provide your perspective which events should stay, which should be removed, which should be merged and maybe which would be also useful to add? With the implementation of this task in my PR we have right now:
```Event_PoetClientCreated
Event_Beacon
Event_InitStart
Event_InitComplete
Event_PostServiceStarted
Event_PostStart
Event_PostComplete
Event_PoetWaitRound
Event_RegisteredInPoet
Event_PoetWaitProof
Event_PoetProofReceived
Event_BestPoetProofSelected
Event_PostStart
Event_PostComplete
Event_AtxPublished
```
I thing that after spending some time around that in the code i can reasonably quickly adapt whatever we will decide, but still i'm too fresh to decide on my own the final shape.

My view on that would be:
```
Event_Beacon
Event_InitStart
Event_InitComplete
Event_PostServiceStarted
Event_PostStart
Event_PostComplete
Event_WaitCloserToPoetStart
Event_RegisteredInPoet
Event_AskPoetAboutProof
Event_ProofDownloadedFromPoet
Event_BestProofSelected
Event_PostStart
Event_PostComplete
Event_AtxPublished
```
WDYT?

**Comment by fasmat** [comment]
I think `Event_WaitCloserToPoetStart` should be called `Event_WaitingForPoETRegistrationWindow` and `Event_PoetWaitProof` is probably better named by `Event_WaitingForPoETRoundEnd`. Besides that your suggestion works for me @jellonek

**Comment by poszu** [comment]
I don't think `Event_AskPoetAboutProof` could be useful. Another thing is that I'd be careful removing existing events as users' tooling might depend on it. At least give a deprecation notice saying it will be removed in future version, wdyt?

**Comment by jellonek** [comment]
Ok. So i'll duplicate renamed events, keeping also old one, with note in changelog that these with old names will be removed in some future version. They will be still kept in API but after some time old ones will be removed on node part.

**Comment by fasmat** [comment]
cc @brusherru

In smapp we probably need to not show some events then to avoid displaying the same information multiple times I assume?

**Comment by jellonek** [comment]
My guess is that new events will not be shown until added to smapp code, so in this code old ones will need to be simply turned into new ones. Am I correct @brusherru ?
