### ISSUE TITLE
Parallel merkle verification

### ISSUE THREAD

**Issue by noamnelke** [spacemeshos/go-spacemesh#562]
Parallel computation of subtrees (starting at each proven leaf).
* Possible implementation:
  * Store map of `leaf -> channel` when initializing the verifier.
  * Split out the proof nodes each subtree requires and its height.
  * Start a go routine for each leaf that sends the root of the subtree on the relevant channel.
  * Read from the channel whenever that node is needed.

**Comment by moshababo** [comment]
Obsolete.
