### ISSUE TITLE
Hare broker buffer for pending messages is unlimited

### ISSUE THREAD

**Issue by gavraz** [spacemeshos/go-spacemesh#563]
The buffer size of pending messages for both the broker and the CP are unlimited
Should limit the buffers and think about the logic that should be added when receiving messages when the buffer is full.
Currently, messages are dropped.

**Comment by gavraz** [comment]
Possible solutions
1. For broker merge pre-round messages (or maybe re-broadcast)
2. For CP - can process the message even if early

**Comment by countvonzero** [comment]
fixed at develop now
