### ISSUE TITLE
tortoise rollback layers

### ISSUE THREAD

**Issue by almogdepaz** [spacemeshos/go-spacemesh#565]
# Overview / Motivation
we need a mechanism to rollback and replay transactions  
after an opinion on an already verified block changes state

# The Task
we need to identify the case and role back the verifiedLayer counter in mesh.go
this will cause sync to replay all transactions since that layer

**Comment by almogdepaz** [comment]
@barakshani do we still need this in the "new" spacemesh ?

**Comment by barakshani** [comment]
yes, that's part of self healing
