### ISSUE TITLE
flaky activation/e2e

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#5652]
![image](https://github.com/spacemeshos/go-spacemesh/assets/1964576/8039d2c8-30d7-4e97-bdea-c886c6cd2999)

https://github.com/spacemeshos/go-spacemesh/actions/runs/8192234972/job/22403301542

@fasmat @poszu

**Comment by fasmat** [comment]
Since this has been reported multiple PRs like #6108, #6126 and #6134 have increase the stability of e2e tests. Closing.
