### ISSUE TITLE
Flaky --- FAIL: TestRewardService_List/coinbase (0.00s)

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#5672]
![image](https://github.com/spacemeshos/go-spacemesh/assets/1964576/45f0fa18-7802-4e6e-b93b-5e13cf9c50fb)

@kacpersaw

_Originally posted by @dshulyak in https://github.com/spacemeshos/go-spacemesh/issues/5669#issuecomment-1987163977_

**Comment by fasmat** [comment]
Duplicate of https://github.com/spacemeshos/go-spacemesh/issues/5636
