### ISSUE TITLE
Don't let protocols register after p2p has started

### ISSUE THREAD

**Issue by y0sher** [spacemeshos/go-spacemesh#571]
# Overview / Motivation

Now we allow protocols to register whenever they want. but the assumption is that protocols must be registered before `p2p` has started.

# The Task

block protocols registrations after `p2p` has started. (panic/error)

# Implementation Notes
TODO: Add links to relevant resources, specs, related issues, etc...

# Contribution Guidelines
Important: Issue assignment to developers will be by the order of their application and proficiency level according to the tasks complexity. We will not assign tasks to developers who have'nt introduced themselves on our Gitter [dev channel](https://gitter.im/spacemesh-os/Lobby)

1. Introduce yourself on go-spacemesh [dev chat channel](https://gitter.im/spacemesh-os/Lobby) - ask our team any question you may have about this task
2. Fork branch `develop` to your own repo and work in your repo
3. You must document all methods, enums and types with [godoc comments](https://blog.golang.org/godoc-documenting-go-code)
4. You must write go unit tests for all types and methods when submitting a component, and integration tests if you submit a feature
5. When ready for code review, submit a PR from your repo back to branch `develop`
6. Attach relevant issue to PR

**Comment by zalmen** [comment]
Once we do that we can remove the mutex that protects the map of protocol handlers

**Comment by y0sher** [comment]
that's right. 
we'll only have to find a solution for testing, some tests register protocols after p2p is started but that probably means the test structure has to change.

**Comment by y0sher** [comment]
I've found a testing solution though this task still needs to be done.

**Comment by lrettig** [comment]
> I've found a testing solution though this task still needs to be done.

Could you outline the testing solution here? Thanks
