### ISSUE TITLE
get the from and to addresses

### ISSUE THREAD

**Issue by yaoyf888** [spacemeshos/go-spacemesh#5742]
how to get the from and to addresses of a transaction using GRPC?
now I using spacemesh.v1.TransactionService.TransactionsState only can get the principal and template address:
this "template" address is not I want,how to get , please help me!

**Comment by yaoyf888** [comment]
@lrettig Can you help me?

**Comment by lrettig** [comment]
Please see https://github.com/spacemeshos/wiki/wiki/Integration-guide#transactions. The relevant code is in https://github.com/spacemeshos/go-spacemesh/blob/develop/genvm/vm.go. We don't yet have a clean SDK for this but hopefully we will soon!
