### ISSUE TITLE
avoid calls to WeightForSet for the same activeset

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#5765]
![image](https://github.com/spacemeshos/go-spacemesh/assets/1964576/83b72fbe-b361-4a9e-bc3d-c786f1a25cb4)

we compute and cache weight for every unique activeset. but when we start a node, we ask peers for all missed ballots layer by layer.
if we receive them at the same time code will try to compute WeightForSet for each ballot individually. if the number of simulateneously processed ballots is large it may trigger huge memory allocation.

the solution should be to compute WeightForSet only for the first ballot, and the rest should subscribe and wait until that computation has finished.

**Comment by ivan4th** [comment]
Closing as it is fixed in #5923
