### ISSUE TITLE
Avoid redundant queries to Poet service /proofs

### ISSUE THREAD

**Issue by poszu** [spacemeshos/go-spacemesh#5786]
## Description
With the support for 1:N, a node builds NiPoST for many IDs. They all register in the same poet services and later query them multiple times for the same proof. It causes N times more network traffic than necessary. 

The poet client should avoid redundant queries. It could keep track of pending requests and wait for the result of the pending request (for the given proof).

:bulb: The operators of a node running a 1:N could also avoid redundant queries by placing a caching HTTP proxy (Nginx) between the node and poets.

## Affected code
The `NipostBuilder` and the HTTP poet client.

**Comment by pigmej** [comment]
Solved with: https://github.com/spacemeshos/go-spacemesh/pull/5911
