### ISSUE TITLE
Add sha3-256 tests with published test vectors

### ISSUE THREAD

**Issue by vorsprung** [spacemeshos/go-spacemesh#58]
Unless there is some subtly here that I am missing, the sha256 function is returning incorrect data

I haven't looked for known bugs in golang.org/x/crypto/sha3 yet

#### Expected behavior
sha256 value input ABCDEFGHIJKL
output expected (as hexdigest) 922429ccdb7045d11143e2e3982a11afc11b537bf259d88d2425fa8806e86e78

#### Actual behavior
digest is d99428764cc43a2ff5c1ac4db1e5da826a97dae5530e268650318adb2e2e246f

#### Steps to reproduce the actual behavior
I am using the following sha3_test.go running in the crypto directory

package crypto

import (
	"encoding/hex"
	"fmt"
	"github.com/spacemeshos/go-spacemesh/assert"
	"testing"
)

func TestSha256(t *testing.T) {
	// biggest vs smallest
	data := []byte("ABCDEFGHIJKL")
	sha256hex := "922429ccdb7045d11143e2e3982a11afc11b537bf259d88d2425fa8806e86e78"
	shaOfData, err := hex.DecodeString(sha256hex)
	assert.Nil(t, err, fmt.Sprintf("hex.DecodeString: this should not happen"))
	try := Sha256(data)
	t.Errorf("%v", try)
	t.Errorf("%v", shaOfData)
	assert.Equal(t, fmt.Sprintf("%v", try), fmt.Sprintf("%v", shaOfData), fmt.Sprintf("sha256 should be %s but is %s", sha256hex, hex.EncodeToString(try)))
}

**Comment by avive** [comment]
Interesting find. Q: how did you determine the valid expected output? Having more reference data for tests will be a good thing to have. Looking at crypto/sha3.go - it is hard to see where we go wrong in using `golang.org/x/crypto/sha3`.

**Comment by avive** [comment]
I just put together this quick test using the sha test vectors I shared with you and it looks like we are getting good results - this test passes:
```
func TestSha256(t *testing.T) {

	data, err := hex.DecodeString("616263")
	assert.NoErr(t,err,"invalid input data")
	result := Sha256(data)

	expected, err := hex.DecodeString("3a985da74fe225b2045c172d6bd390bd855f086e3e9d525b46bfe24511431532")
	assert.NoErr(t,err,"invalid hex string")

	assert.True(t, bytes.Equal(result, expected), "unexpected result")
}
```

**Comment by avive** [comment]
This looks promising:
```
func TestSha256(t *testing.T) {

	// test vectors source: https://www.di-mgt.com.au/sha_testvectors.html#testvectors

	// keys and values MUST be valid hex-encoded strings
	testVectors := map[string]string {
		"" : "a7ffc6f8bf1ed76651c14756a061d662f580ff4de43b49fa82d80a4b80f8434a",
		"616263" : "3a985da74fe225b2045c172d6bd390bd855f086e3e9d525b46bfe24511431532",
		"6162636462636465636465666465666765666768666768696768696A68696A6B696A6B6C6A6B6C6D6B6C6D6E6C6D6E6F6D6E6F706E6F7071" : 
			"41c0dba2a9d6240849100376a8235e2c82e1b9998a999e21db32dd97496d3376",
	}

	for k, v := range testVectors {
		data, err := hex.DecodeString(k)
		assert.NoErr(t, err, "invalid input data")
		result := Sha256(data)
		expected, err := hex.DecodeString(v)
		assert.NoErr(t, err, "invalid hex string %s", v)
		assert.True(t, bytes.Equal(result, expected), "unexpected result")
	}
}
```

**Comment by vorsprung** [comment]
Initially I did this

```
Python 3.6.1 (default, May  1 2017, 08:54:15) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import hashlib
>>> h=hashlib.sha256(b"ABCDEFGHIJKL")
>>> h.hexdigest()
'922429ccdb7045d11143e2e3982a11afc11b537bf259d88d2425fa8806e86e78'
```

Then I looked on the web and got the same result from the top hit
http://www.xorbin.com/tools/sha256-hash-calculator

Your test page shows me what I did wrong though.  I am using "SHA-256" which is different to "SHA-3-256".   

I've recalculated the hash with the correct algorithm and it's fine.  Sorry for the noise!

**Comment by avive** [comment]
yes, all these sha-x-y naming can be quite confusing! this is not noise - it actually led us to have more confidence and more tested code!

**Comment by avive** [comment]
I think you should still add this test
```
func TestSha256(t *testing.T) {

	// test vectors source: https://www.di-mgt.com.au/sha_testvectors.html#testvectors

	// keys and values MUST be valid hex-encoded strings
	testVectors := map[string]string{
		"":       "a7ffc6f8bf1ed76651c14756a061d662f580ff4de43b49fa82d80a4b80f8434a",
		"616263": "3a985da74fe225b2045c172d6bd390bd855f086e3e9d525b46bfe24511431532",
		"6162636462636465636465666465666765666768666768696768696A68696A6B696A6B6C6A6B6C6D6B6C6D6E6C6D6E6F6D6E6F706E6F7071":                                                                                                                 "41c0dba2a9d6240849100376a8235e2c82e1b9998a999e21db32dd97496d3376",
		"61626364656667686263646566676869636465666768696a6465666768696a6b65666768696a6b6c666768696a6b6c6d6768696a6b6c6d6e68696a6b6c6d6e6f696a6b6c6d6e6f706a6b6c6d6e6f70716b6c6d6e6f7071726c6d6e6f707172736d6e6f70717273746e6f707172737475": "916f6061fe879741ca6469b43971dfdb28b1a32dc36cb3254e812be27aad1d18",
	}

	for k, v := range testVectors {
		data, err := hex.DecodeString(k)
		assert.NoErr(t, err, "invalid input data")
		result := Sha256(data)
		expected, err := hex.DecodeString(v)
		assert.NoErr(t, err, "invalid hex string %s", v)
		assert.True(t, bytes.Equal(result, expected), "unexpected result")
	}
}
```

**Comment by vorsprung** [comment]
fixedd with https://github.com/spacemeshos/go-spacemesh/commit/f2fc57b1febacef9152ba70e93d2111d8eb497c7
