### ISSUE TITLE
invalid post index malfeasance proof - POST is valid

### ISSUE THREAD

**Issue by hieixu** [spacemeshos/go-spacemesh#5808]
## Description
I see crazy log flood in my node. 

## Environment
Please complete the following information:
 - OS:  Ubuntu 22.04
 
 - Node Version:  go-spacemesh v1.4.4
 
 - Smapp version (if applicable): 
 

9d92ff23", "smesher": "278a65d0ef56ac532c7fc3cdb1ab293c5bf52af51df8389385e4fad032ddc11a", "invalid index": 0, "received": "0001-01-01T00:00:00.000Z"}, "errmsg": "invalid post index malfeasance proof - POST is valid", "name": "malfeasance"}                                                                                                                                                                                   2024-04-06T16:32:26.610+0800    WARN    node.malfeasance        failed to validate malfeasance proof    {"sessionId": "df57c09b", "proof": {"generated_layer": 72576, "type": "invalid post index", "atx_id": "509d92ff23", "smesher": "278a65d0ef56ac532c7fc3cdb1ab293c5bf52af51df8389385e4fad032ddc11a", "invalid index": 0, "received": "0001-01-01T00:00:00.000Z"}, "errmsg": "invalid post index malfeasance proof - POST is valid", "name": "malfeasance"}                                                                                                                                                                                   2024-04-06T16:32:26.610+0800    WARN    node.malfeasance        failed to validate malfeasance proof    {"sessionId": "df57c09b", "proof": {"generated_layer": 72576, "type": "invalid post index", "atx_id": "331f244c2a", "smesher": "bfb5adf3c819eed8e7841630bd27cad9f1e9ec684a09b16be1d97088801f359f", "invalid index": 0, "received": "0001-01-01T00:00:00.000Z"}, "errmsg": "invalid post index malfeasance proof - POST is valid", "name": "malfeasance"}                                                                                                                                                                                   2024-04-06T16:32:26.663+0800    WARN    node.malfeasance        failed to validate malfeasance proof    {"sessionId": "df57c09b", "proof": {"generated_layer": 72576, "type": "invalid post index", "atx_id": "509d92ff23", "smesher": "278a65d0ef56ac532c7fc3cdb1ab293c5bf52af51df8389385e4fad032ddc11a", "invalid index": 0, "received": "0001-01-01T00:00:00.000Z"}, "errmsg": "invalid post index malfeasance proof - POST is valid", "name": "malfeasance"}                                                                                                                                                                                   2024-04-06T16:32:26.665+0800    WARN    node.malfeasance        failed to validate malfeasance proof    {"sessionId": "df57c09b", "proof": {"generated_layer": 72576, "type": "invalid post index", "atx_id": "331f244c2a", "smesher": "bfb5adf3c819eed8e7841630bd27cad9f1e9ec684a09b16be1d97088801f359f", "invalid index": 0, "received": "0001-01-01T00:00:00.000Z"}, "errmsg": "invalid post index malfeasance proof - POST is valid", "name": "malfeasance"}                                                                                                                                                                                   2024-04-06T16:32:26.709+0800    WARN    node.malfeasance        failed to validate malfeasance proof    {"sessionId": "df57c09b", "proof": {"generated_layer": 72576, "type": "invalid post index", "atx_id": "331f244c2a", "smesher": "bfb5adf3c819eed8e7841630bd27cad9f1e9ec684a09b16be1d97088801f359f", "invalid index": 0, "received": "0001-01-01T00:00:00.000Z"}, "errmsg": "invalid post index malfeasance proof - POST is valid", "name": "malfeasance"}                                                                                                                                                                                   2024-04-06T16:32:26.709+0800    WARN    node.malfeasance        failed to validate malfeasance proof    {"sessionId": "df57c09b", "proof": {"generated_layer": 72576, "type": "invalid post index", "atx_id": "509d92ff23", "smesher": "278a65d0ef56ac532c7fc3cdb1ab293c5bf52af51df8389385e4fad032ddc11a", "invalid index": 0, "received": "0001-01-01T00:00:00.000Z"}, "errmsg": "invalid post index malfeasance proof - POST is valid", "name": "malfeasance"}                                                                                                                                                                                   2024-04-06T16:32:26.758+0800    WARN    node.malfeasance        failed to validate malfeasance proof    {"sessionId": "df57c09b", "proof": {"generated_layer": 72576, "type": "invalid post index", "atx_id": "509d92ff23", "smesher": "278a65d0ef56ac532c7fc3cdb1ab293c5bf52af51df8389385e4fad032ddc11a", "invalid index": 0, "received": "0001-01-01T00:00:00.000Z"}, "errmsg": "invalid post index malfeasance proof - POST is valid", "name": "malfeasance"}                                                                                                                                                                                   2024-04-06T16:32:26.758+0800    WARN    node.malfeasance        failed to validate malfeasance proof    {"sessionId": "df57c09b", "proof": {"generated_layer": 72576, "type": "invalid post index", "atx_id": "331f244c2a", "smesher": "bfb5adf3c819eed8e7841630bd27cad9f1e9ec684a09b16be1d97088801f359f", "invalid index": 0, "received": "0001-01-01T00:00:00.000Z"}, "errmsg": "invalid post index malfeasance proof - POST is valid", "name": "malfeasance"}                                                                                                                                                                                   2024-04-06T16:32:26.811+0800    WARN    node.malfeasance        failed to validate malfeasance proof    {"sessionId": "df57c09b", "proof": {"generated_layer": 72576, "type": "invalid post index", "atx_id": "331f244c2a", "smesher": "bfb5adf3c819eed8e7841630bd27cad9f1e9ec684a09b16be1d97088801f359f", "invalid index": 0, "received": "0001-01-01T00:00:00.000Z"}, "errmsg": "invalid post index malfeasance proof - POST is valid", "name": "malfeasance"}                                                                                                                                                                                   2024-04-06T16:32:26.811+0800    WARN    node.malfeasance        failed to validate malfeasance proof    {"sessionId": "df57c09b", "proof": {"generated_layer": 72576, "type": "invalid post index", "atx_id": "509d92ff23", "smesher": "278a65d0ef56ac532c7fc3cdb1ab293c5bf52af51df8389385e4fad032ddc11a", "invalid index": 0, "received": "0001-01-01T00:00:00.000Z"}, "errmsg": "invalid post index malfeasance proof - POST is valid", "name": "malfeasance"}

**Comment by poszu** [comment]
This log means that a peer send an invalid proof. It is not a problem with the node that logs this warning. In fact, this should not be a warning but a debug lvl log. A peer sending invalid proofs should be dropped. All of this has already been addressed in #6232.
