### ISSUE TITLE
Node should re-use instances of `hash.Hash` by using a `sync.Pool`

### ISSUE THREAD

**Issue by fasmat** [spacemeshos/go-spacemesh#5850]
## Description
This issue came up in a discussion here: https://github.com/spacemeshos/go-spacemesh/pull/5784#discussion_r1553962346 

Every time the node hashes data it re-instantiates `hash.Hash` objects, which is slow and can be mitigated by using a `sync.Pool`.

## Affected code
An example would be here: https://github.com/spacemeshos/go-spacemesh/blob/28480f57981d97fcc5a31a200cddd7136be4de66/common/types/wire/activation_v1.go#L129
Other places where instances of hash are created should also be checked to be re-used.

**Comment by acud** [comment]
done in #6044
