### ISSUE TITLE
smapp crashing

### ISSUE THREAD

**Issue by Nightbeem** [spacemeshos/go-spacemesh#5885]
## Description
For the last week and a half, smapp has been crashing in my system.  The node starts synchronizing once it launches, but eventually it uses up all 16GB of RAM in the computer in the syncing activations phase.  I have been operating this node for several months now with no issues. 

I have tried deleting the configuration folder and doing a full sync to no avail.  The problems seem to have started with version 1.4.6.  I read that the memory leak from 1.4.5 was fixed in 1.4.6.  It seems to persist in my system.

I also installed version 1.5 and it did not address the problem.

## Environment
Ubuntu 22.04.4, Intel processor, 16GB of RAM.

## Additional Resources 
Screenshot attached.
![smapp](https://github.com/spacemeshos/go-spacemesh/assets/111644831/4b399ed1-6fb0-444b-bfd7-be4f240751e4)

**Comment by pigmej** [comment]
We would need to get node logs and app logs. If possible please also follow: https://github.com/spacemeshos/smapp/issues/1439#issuecomment-1887397768 

>  I read that the memory leak from 1.4.5 was fixed in 1.4.6.

I'm not aware of a memory leak there.

**Comment by Nightbeem** [comment]
Thanks for your prompt response.  Attached are the requested logs.
[sm-logs.zip](https://github.com/spacemeshos/go-spacemesh/files/15110838/sm-logs.zip)

Note that I have been monitoring the smapp channel in Discord and several other people have reported similar problems with the app crashing.

I appreciate your assistance.

**Comment by Nightbeem** [comment]
Hi.  I recently upgraded to version 1.51 and also tried running smapp on a different computer.  It also crashed after using up all the RAM on the system (16GB).  This seems to be a bug and not directly related to my system.

Is there anything I can try to fix the issue?

Thanks for your help.

**Comment by Nightbeem** [comment]
Hi.  I just configured a clean Ubuntu system with version 1.5.2 of Smapp.  Created a completely new configuration and wallet.  Successfully performed a Quicksync.  The system uses up all 16GB of RAM while synchronizing activations and then crashes.  Have not been able to participate in the network for over a month now.  Any suggestions on how to fix the issue will be appreciated.  Thank you.

**Comment by Nightbeem** [comment]
Issued resolved as per recommendation in Discord to increase swap space.  Problem will be permanently fixed in an upcoming Smapp update.
