### ISSUE TITLE
Cannot start node, INITIALIZING SCRYPTER: INVALID PROVIDER ID"

### ISSUE THREAD

**Issue by sharpclone** [spacemeshos/go-spacemesh#6002]
## Description
I just tried to start SMAPP for the first time on my system (2tb free space, intel i3-6100, no gpu, debian 12, using rdp with xfce, since there is no CLI only app). I did everything it asked, and then when i try to start smeshing, i get the erro : 
NODE INITIALIZATION FAILED {"ERROR": "FAILED TO COMPUTE LABELS: INITIALIZING SCRYPTER: INVALID PROVIDER ID"}

## Steps to reproduce
1. Go to SMAPP
2. Click on START SMESHING

## Actual Behavior
The app asks to restart the node

## Expected Behavior
The should start smeshing

## Environment
Please complete the following information:
 - OS: 
Debian 12
 - Node Version: 
Node not started
 - Smapp version (if applicable): 
1.5.6

## Additional Resources 
[spacemesh-log-7c8cef2b.txt](https://github.com/spacemeshos/go-spacemesh/files/15500633/spacemesh-log-7c8cef2b.txt)

![image](https://github.com/spacemeshos/go-spacemesh/assets/103455720/9ca01dae-e2ee-4f8f-86b1-8ca02cb0e179)

**Comment by pigmej** [comment]
Most likely the provider in the config is wrong could you share something part of your config?

**Comment by sharpclone** [comment]
[config.json](https://github.com/spacemeshos/go-spacemesh/files/15500873/config.json)
[node-config.json](https://github.com/spacemeshos/go-spacemesh/files/15500874/node-config.json)

**Comment by poszu** [comment]
@sharpclone Your node is configured to use provider `0` (GPU) but it cannot be found on your platform (as you said - no gpu).  A GPU is required to initialize POST data to start smeshing. It's possible to initialize on a different system with a GPU and move the data.
