### ISSUE TITLE
P2P Documentation

### ISSUE THREAD

**Issue by zalmen** [spacemeshos/go-spacemesh#605]
# The Motivation
Keep our documentation up to date and also continue building our protocol guide independently from the implementation docs
# The Requirement
Update current p2p's wiki page as it is probably outdated. Also, add a detailed flow chart in the protocol repo.

**Comment by lrettig** [comment]
This can probably be closed in favor of spacemeshos/protocol#7; this documentation work will happen in the protocol repo.

**Comment by y0sher** [comment]
thanks. nice work over there. hope to hop in soon.
