### ISSUE TITLE
Graceful shutdown of json-http api server

### ISSUE THREAD

**Issue by avive** [spacemeshos/go-spacemesh#62]
#### Expected behavior
Properly shut-down json-http api server

#### Actual behavior
Calling server.Shutdown() panics

#### Steps to reproduce the actual behavior
- Uncomment s.server.Shutdown(s.ctx) in JsonHttpServer.Stop()
- Run api_test.go

**Comment by y0sher** [comment]
https://github.com/spacemeshos/go-spacemesh/pull/68
