### ISSUE TITLE
Transaction pool (mempool)

### ISSUE THREAD

**Issue by zalmen** [spacemeshos/go-spacemesh#624]
# The Motivation
The tx pool is where the node stores all unhandled txs to be added to the block once the node is eligible to mine. 
# The Requirement
The mempool should provide the following -

1. Store all live txs (remove tx once appears on another block)
2. When generating a block, hand over txs based on the protocol
3. Persist the txs and recover in case of a crash
4. Support syncing of mempool from/with peers

**Comment by moshababo** [comment]
Obsolete.
