### ISSUE TITLE
Node packaging and installation

### ISSUE THREAD

**Issue by zalmen** [spacemeshos/go-spacemesh#629]
# The Motivation
This epic should address everything required to allow a user to fetch the node, install it and get it ready to start making $$$$

# The Requirement
TODO: What is the expected behaviour of this epic?

**Comment by zalmen** [comment]
@avive is there a product page describing the requirements for installing the node (where will the user fetch the binary from? What is the flow for a user that wishes to install the node from the code?) If there isn't such page, can please write it down and add a link to the description

**Comment by avive** [comment]
Yes, for users who can run electron apps using installers: https://testnet.spacemesh.io/#/guide/install is the main page and see linked pages from it. e.g. verifying checksums...
Building and running from source needs to be supported as well: https://testnet.spacemesh.io/#/build
Linux w/o support to electron apps: https://testnet.spacemesh.io/#/linux
@zalmen
