### ISSUE TITLE
Malfeasance V2: Invalid Post for V1 Initial ATXs

### ISSUE THREAD

**Issue by fasmat** [spacemeshos/go-spacemesh#6433]
## Description

With #6141 a malfeasance proof was implemented that proofs to the network that some labels of a PoST of an identity are invalid. To confirm the invalid PoST in the malfeasance proof a merkle-proof for the CommitmentATX in the initial ATX of the identity is provided.

If the initial ATX of the identity is not ATXv2 this merkle proof cannot be created and instead the whole initial ATXv1 has to be included in the malfeasance proof to be able for other nodes to confirm that the PoST is invalid.

## Implementation hints

A second invalid post malfeasance proof is needed that instead of a CommitmentATX merkle proof has the full initial ATX v1 of the identity included. Then verify the following:

1. The PoST is invalid given the commitment ATX from the initial ATX
2. The initial ATX was actually the initial ATX by the identity (does not contain previous ATX and has been signed)
3. Besides this the Malfeasance proof should be basically the same as the proof from https://github.com/spacemeshos/go-spacemesh/issues/6141

**Comment by poszu** [comment]
How about including one valid label to prove the commitment ATX is real? The proof would also need to include num units and the challenge. It's much less than a whole ATX.

**Comment by fasmat** [comment]
The current proof already includes all that information, via https://github.com/spacemeshos/go-spacemesh/blob/ed14f54590e67a7743e71f598aee45ee54bf526b/activation/wire/malfeasance_invalid_post.go#L38-L40

https://github.com/spacemeshos/go-spacemesh/blob/ed14f54590e67a7743e71f598aee45ee54bf526b/activation/wire/malfeasance_invalid_post.go#L193-L230

The problem is this section:

https://github.com/spacemeshos/go-spacemesh/blob/ed14f54590e67a7743e71f598aee45ee54bf526b/activation/wire/malfeasance_invalid_post.go#L36-L37

https://github.com/spacemeshos/go-spacemesh/blob/ed14f54590e67a7743e71f598aee45ee54bf526b/activation/wire/malfeasance_invalid_post.go#L135-L149

In the case where the initial ATX is not v2 but v1 we have to include the full ATX here.

**Comment by fasmat** [comment]
> How about including one valid label to prove the commitment ATX is real?

That wouldn't work for the case where all labels are invalid. Sure we could then consider the ATX as syntactically invalid but then running a node that doesn't verify PoSTs at all isn't supported any more...

**Comment by poszu** [comment]
As you said, an ATX with all invalid labels can be treated as syntactically invalid and rejected (no need for a malfeasance proof then). 

> running a node that doesn't verify PoSTs at all isn't supported any more

This mode is not something we should recommend so I'm not sure we need to explicitly support it in the malfeasance proofs (complicating them a lot in effect).

The approach I suggest would greatly simplify the proof - it would only require to prove that the invalid label was in the faulty ATX and that the commitment ATX is valid for this ID.
