### ISSUE TITLE
Public key extraction in ed25519

### ISSUE THREAD

**Issue by barakshani** [spacemeshos/go-spacemesh#669]
# The Motivation
We enable public key extraction from signed messages. This results in shorter messages.

# The Requirement
Code revision is required:
- new signing algorithm
- extraction algorithm
- new functions: invert, modular multiplication, elliptic curve point multiplication

**Comment by avive** [comment]
Please see this PR w the request for code review... https://github.com/spacemeshos/ed25519/pull/1

**Comment by lrettig** [comment]
Duplicate of #670
