### ISSUE TITLE
Code Revision: Ed25519

### ISSUE THREAD

**Issue by barakshani** [spacemeshos/go-spacemesh#670]
# Overview / Motivation
We enable public key extraction from signed messages. This results in shorter messages.

# The Task
Code revision is required:
- new signing algorithm
- extraction algorithm
- new functions: invert, modular multiplication, elliptic curve point multiplication

# Implementation Notes
See code in https://github.com/spacemeshos/ed25519:
- signing and extraction in ed25519_ext.go
- new functions in internal/edwards25519/invert.go

See also
https://github.com/spacemeshos/ed25519/pull/1

# Contribution Guidelines
Important: Issue assignment to developers will be by the order of their application and proficiency level according to the tasks complexity. We will not assign tasks to developers who have'nt introduced themselves on our Gitter [dev channel](https://gitter.im/spacemesh-os/Lobby)

1. Introduce yourself on go-spacemesh [dev chat channel](https://gitter.im/spacemesh-os/Lobby) - ask our team any question you may have about this task
2. Fork branch `develop` to your own repo and work in your repo
3. You must document all methods, enums and types with [godoc comments](https://blog.golang.org/godoc-documenting-go-code)
4. You must write go unit tests for all types and methods when submitting a component, and integration tests if you submit a feature
5. When ready for code review, submit a PR from your repo back to branch `develop`
6. Attach relevant issue to PR

**Comment by moshababo** [comment]
Obsolete.
