### ISSUE TITLE
Check for accumulative data/messages in the hare protocol

### ISSUE THREAD

**Issue by gavraz** [spacemeshos/go-spacemesh#673]
Should make sure no one can DDOS us by spamming in the hare protocol

**Comment by gavraz** [comment]
Preround scenario: malicious sends multiple preround msgs with different set causing the honest participant to store the union of all msgs

**Comment by jonZlotnik** [comment]
See comments on #3287 for network security.

However this will need further safeguards for accumulation of data in memory that either doesn't get put into a message or is spread over many incoming messages.
See #1052 for an example of the latter.

**Comment by jonZlotnik** [comment]
More examples:
https://github.com/spacemeshos/go-spacemesh/issues/1038
https://github.com/spacemeshos/go-spacemesh/issues/563
