### ISSUE TITLE
Low-influence epoch beacon

### ISSUE THREAD

**Issue by zalmen** [spacemeshos/go-spacemesh#689]
# Overview / Motivation (from paper)
The Spacemesh protocol uses three, slightly different, types of “random beacons”. Our requirements
from the beacons all share one important property: they don’t have to be provable. This means it’s
enough that honest parties agree on the beacon value; we don’t care if the adversary “lies” about it.
Provable beacons are much more difficult to achieve; this relaxation makes implementing the beacons
simpler and more robust.

**low-influence epoch beacon:**
The beacon for epoch z, is denoted echz (see section 3.4.1 for an explanation of epochs). All honest parties must agree on echz, must be both unpredictable and hard to influence: (1) before the start of epoch z, no adversary can predict echz with more than negligible probability. (2) For any (efficiently-computable) function f and any value y in its range, the probability that Pr[f(echz)] = y< 2^(−k)· Pr[f(U) = y]. That is, the adversary can only increase the probability of a given outcome that depends only on the beacon by a factor of 2−k. We will require k on the order of (TBD)

# The Task
We can use a combination of the coin-flip and a modified version
of the tortoise protocol itself to implement this beacon. The basic idea is to sample identities in
epoch z − 1 using the VRF output (e.g., check if the VRF output passed a “difficulty threshold”),
such that on average 3k identities are sampled. The parties then XOR the VRF outputs from the
selected identities to compose the beacon value. Since the adversary can’t control the value of
the unique signature, only whether or not it appears, it has one bit of influence for every selected
ATX. If q < 1/3, this means on average it has less than k bits of influence. This isn’t quite
sufficient since honest parties might disagree on which ids were sampled (e.g., if the adversary
delays sending a “successful” identity proof). To overcome this, the parties use epoch z to reach
consensus about which ATXs actually passed the threshold, by voting for them using the tortoise
protocol’s self-healing mechanism (we use a modified version of the protocol that ignores the
votes from “heavy” layers, in order make grinding on the previous epoch’s beacon ineffective).

**Comment by nkryuchkov** [comment]
Implemented in https://github.com/spacemeshos/go-spacemesh/pull/2267
