### ISSUE TITLE
Add app config file support

### ISSUE THREAD

**Issue by avive** [spacemeshos/go-spacemesh#7]
Implement support for app configuration via a config file, and write tests for app configs using a file.
Choose TOML or YAML as file format and integrate with cli1.v1

**Comment by avive** [comment]
Refs: 
https://github.com/toml-lang/toml
https://github.com/urfave/cli

**Comment by jreyeshdez** [comment]
I am working on this feature and came across same issue as pointed here:
https://github.com/urfave/cli/issues/599

It looks like it is a bug and still open

**Comment by y0sher** [comment]
Hi @jreyeshdez,
I'm also working on this, I tried to overcome some limitations caused by the cli parser bugs.
I'll push it to a branch and edit this comment so we can combine forces :)

**Comment by avive** [comment]
@y0sher - looking into this today

**Comment by avive** [comment]
@y0sher - do you mind opening a PR from your forked code so I can have a look and comment? Just please mark it as WIP

**Comment by avive** [comment]
Thanks @y0sher for the good work on getting this done!
