### ISSUE TITLE
Query MeshDB for d active set

### ISSUE THREAD

**Issue by antonlerner** [spacemeshos/go-spacemesh#705]
# Overview / Motivation
In order to validate an ATX, an active set of d must be pointed to by the ATXs view. 
# The Task
Add a method that allows to query amount of seen active ids from a given blocks view. 
The method should be able to traverse the mesh until a certain layer, counting all seen active IDs found in ATXs that were pointed to by the blocks in the mesh
# Implementation Notes
A general api can look like so:
`CountActiveSet(block hash, stopLayer LayerID) (activeSet uint64, error)`
# Contribution Guidelines
Important: Issue assignment to developers will be by the order of their application and proficiency level according to the tasks complexity. We will not assign tasks to developers who have'nt introduced themselves on our Gitter [dev channel](https://gitter.im/spacemesh-os/Lobby)

1. Introduce yourself on go-spacemesh [dev chat channel](https://gitter.im/spacemesh-os/Lobby) - ask our team any question you may have about this task
2. Fork branch `develop` to your own repo and work in your repo
3. You must document all methods, enums and types with [godoc comments](https://blog.golang.org/godoc-documenting-go-code)
4. You must write go unit tests for all types and methods when submitting a component, and integration tests if you submit a feature
5. When ready for code review, submit a PR from your repo back to branch `develop`
6. Attach relevant issue to PR

**Comment by almogdepaz** [comment]
@antonlerner i think you already implemented this
