### ISSUE TITLE
build fails due to go fmt issues

### ISSUE THREAD

**Issue by avive** [spacemeshos/go-spacemesh#71]
#### Expected behavior
validate-gofmt.sh to not return any error.

#### Actual behavior
go fmt fails due to what looks like a vendor issue. However, the script is supposed to skip all vendored packages.

#### Steps to reproduce the actual behavior
$ ./ci/validate-gofmt.sh

Result:
vendor/golang.org/x/net/context/go19.go:15:14: expected type, found '='
vendor/golang.org/x/net/context/go19.go:20:17: expected type, found '='
validate-gofmt.sh: error vendor/gopkg.in/natefinch/lumberjack.v2/lumberjack.go

Also see: https://travis-ci.org/spacemeshos/go-spacemesh/jobs/333154598

**Comment by y0sher** [comment]
the problem is that the first relative path is "." 
that causes gofmt to run on all the files in the root folder which goes recursively into the vendor packages.
then it stops there because of the error.
the solution would be the to remove the first line that we get form go list. (which translates to ".")

**Comment by jreyeshdez** [comment]
Hi @avive 

Could you try the following instead?

pkgs=`find . -name '*.go' -not -path "./vendor/*"`

And after done with inner for loop:

output=`gofmt -s -l $relative_path`
if [ "$output" != "${relative_path}" ]; then
  echo "validate-gofmt.sh: error $output" 1>&2
  exit 1
fi

**Comment by jreyeshdez** [comment]
@avive 

Also, output=`gofmt -s -l $relative_path`
-l → This flags will print the file name to standard output if a file's formatting is different from gofmt's.

**Comment by jreyeshdez** [comment]
@y0sher you are right, following change will sort out the issue.

pkgs=`go list ./... | grep -vF vendor/`
pkgs=${pkgs/#$import_path/}

**Comment by y0sher** [comment]
A better solution. fixed ignoring packages. added "." to the ignored packages.
https://github.com/spacemeshos/go-spacemesh/pull/72
there's still one thing.  main.go file in the root directory won't get formatted with the script.

**Comment by avive** [comment]
@y0sher thanks for the quick fix!
