### ISSUE TITLE
Sometimes the test fails (the second run solves it)

### ISSUE THREAD

**Issue by gavraz** [spacemeshos/go-spacemesh#731]
Testing started at 15:46 ...
/Users/elad/go/src/github.com/spacemeshos/go-spacemesh/tests/venv/bin/python "/Applications/PyCharm CE.app/Contents/helpers/pycharm/_jb_pytest_runner.py" --target test_bs.py::test_hare -- --tc-file=hare/config.yaml --tc-format=yaml
Launching pytest with arguments --tc-file=hare/config.yaml --tc-format=yaml test_bs.py::test_hare in /Users/elad/go/src/github.com/spacemeshos/go-spacemesh/tests

============================= test session starts ==============================
platform darwin -- Python 3.7.2, pytest-4.2.0, py-1.8.0, pluggy-0.9.0
rootdir: /Users/elad/go/src/github.com/spacemeshos/go-spacemesh/tests, inifile:
plugins: testconfig-0.1.1collected 1 item

test_bs.py Econfigmap: conf already exist.

test setup failed
request = <SubRequest 'create_configmap' for <Function test_hare>>

    @pytest.fixture
    def create_configmap(request):
        def _create_configmap_in_namespace(nspace):
            # Configure ConfigMap metadata
            # This function assume that there is only 1 configMap in the each namespace
            configmap_name = testconfig['config_map_name']
            metadata = client.V1ObjectMeta(annotations=None,
                                           deletion_grace_period_seconds=30,
                                           labels=None,
                                           name=configmap_name,
                                           namespace=nspace)
            # Get File Content
            with open('../config.toml', 'r') as f:
                file_content = f.read()
            # Instantiate the configmap object
            d = {'config.toml': file_content}
            configmap = client.V1ConfigMap(api_version="v1",
                                           kind="ConfigMap",
                                           data=d,
                                           metadata=metadata)
            try:
                client.CoreV1Api().create_namespaced_config_map(namespace=nspace,
                                                                body=configmap,
                                                                pretty='pretty_example')
            except ApiException as e:
                if eval(e.body)['reason'] == 'AlreadyExists':
                    print('configmap: {0} already exist.'.format(configmap_name))
                raise e
            return configmap_name
    
        def fin():
            client.CoreV1Api().delete_namespaced_config_map(testconfig['config_map_name'],
                                                            testconfig['namespace'],
                                                            body=client.V1DeleteOptions(propagation_policy='Foreground',
                                                                                        grace_period_seconds=5))
    
        request.addfinalizer(fin)
>       return _create_configmap_in_namespace(testconfig['namespace'])

test_bs.py:248: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test_bs.py:238: in _create_configmap_in_namespace
    raise e
test_bs.py:234: in _create_configmap_in_namespace
    pretty='pretty_example')
venv/lib/python3.7/site-packages/kubernetes/client/apis/core_v1_api.py:5540: in create_namespaced_config_map
    (data) = self.create_namespaced_config_map_with_http_info(namespace, body, **kwargs)
venv/lib/python3.7/site-packages/kubernetes/client/apis/core_v1_api.py:5631: in create_namespaced_config_map_with_http_info
    collection_formats=collection_formats)
venv/lib/python3.7/site-packages/kubernetes/client/api_client.py:321: in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
venv/lib/python3.7/site-packages/kubernetes/client/api_client.py:155: in __call_api
    _request_timeout=_request_timeout)
venv/lib/python3.7/site-packages/kubernetes/client/api_client.py:364: in request
    body=body)
venv/lib/python3.7/site-packages/kubernetes/client/rest.py:266: in POST
    body=body)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <kubernetes.client.rest.RESTClientObject object at 0x110ffd710>
method = 'POST'
url = 'https://35.234.101.237/api/v1/namespaces/gavrad/configmaps?pretty=pretty_example'
query_params = [('pretty', 'pretty_example')]
headers = {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'Swagger-Codegen/8.0.1/python', 'auth...fwdmSxg3NCGoGJABlM9_j5YsOXDct4d-Xdr7hEpGU0Q6rYvF76_myfkD6y7TGUzdTyig49iczvJ3Dq8pdgnVH5n3buvLIxR8i3dqgG5-v89hRXzfk0rlg'}
body = {'apiVersion': 'v1', 'data': {'config.toml': '# sample spacemesh config file\n# use the config flag to start a node wi...es = 3\n'}, 'kind': 'ConfigMap', 'metadata': {'deletionGracePeriodSeconds': 30, 'name': 'conf', 'namespace': 'gavrad'}}
post_params = {}, _preload_content = True, _request_timeout = None

    def request(self, method, url, query_params=None, headers=None,
                body=None, post_params=None, _preload_content=True, _request_timeout=None):
        """
        :param method: http request method
        :param url: http request url
        :param query_params: query parameters in the url
        :param headers: http request headers
        :param body: request json body, for `application/json`
        :param post_params: request post parameters,
                            `application/x-www-form-urlencoded`
                            and `multipart/form-data`
        :param _preload_content: if False, the urllib3.HTTPResponse object will be returned without
                                 reading/decoding response data. Default is True.
        :param _request_timeout: timeout setting for this request. If one number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of (connection, read) timeouts.
        """
        method = method.upper()
        assert method in ['GET', 'HEAD', 'DELETE', 'POST', 'PUT', 'PATCH', 'OPTIONS']
    
        if post_params and body:
            raise ValueError(
                "body parameter cannot be used with post_params parameter."
            )
    
        post_params = post_params or {}
        headers = headers or {}
    
        timeout = None
        if _request_timeout:
            if isinstance(_request_timeout, (int, ) if PY3 else (int, long)):
                timeout = urllib3.Timeout(total=_request_timeout)
            elif isinstance(_request_timeout, tuple) and len(_request_timeout) == 2:
                timeout = urllib3.Timeout(connect=_request_timeout[0], read=_request_timeout[1])
    
        if 'Content-Type' not in headers:
            headers['Content-Type'] = 'application/json'
    
        try:
            # For `POST`, `PUT`, `PATCH`, `OPTIONS`, `DELETE`
            if method in ['POST', 'PUT', 'PATCH', 'OPTIONS', 'DELETE']:
                if query_params:
                    url += '?' + urlencode(query_params)
                if re.search('json', headers['Content-Type'], re.IGNORECASE):
                    if headers['Content-Type'] == 'application/json-patch+json':
                        if not isinstance(body, list):
                            headers['Content-Type'] = \
                                'application/strategic-merge-patch+json'
                    request_body = None
                    if body is not None:
                        request_body = json.dumps(body)
                    r = self.pool_manager.request(method, url,
                                                  body=request_body,
                                                  preload_content=_preload_content,
                                                  timeout=timeout,
                                                  headers=headers)
                elif headers['Content-Type'] == 'application/x-www-form-urlencoded':
                    r = self.pool_manager.request(method, url,
                                                  fields=post_params,
                                                  encode_multipart=False,
                                                  preload_content=_preload_content,
                                                  timeout=timeout,
                                                  headers=headers)
                elif headers['Content-Type'] == 'multipart/form-data':
                    # must del headers['Content-Type'], or the correct Content-Type
                    # which generated by urllib3 will be overwritten.
                    del headers['Content-Type']
                    r = self.pool_manager.request(method, url,
                                                  fields=post_params,
                                                  encode_multipart=True,
                                                  preload_content=_preload_content,
                                                  timeout=timeout,
                                                  headers=headers)
                # Pass a `string` parameter directly in the body to support
                # other content types than Json when `body` argument is provided
                # in serialized form
                elif isinstance(body, str):
                    request_body = body
                    r = self.pool_manager.request(method, url,
                                                  body=request_body,
                                                  preload_content=_preload_content,
                                                  timeout=timeout,
                                                  headers=headers)
                else:
                    # Cannot generate the request from given parameters
                    msg = """Cannot prepare a request message for provided arguments.
                             Please check that your arguments match declared content type."""
                    raise ApiException(status=0, reason=msg)
            # For `GET`, `HEAD`
            else:
                r = self.pool_manager.request(method, url,
                                              fields=query_params,
                                              preload_content=_preload_content,
                                              timeout=timeout,
                                              headers=headers)
        except urllib3.exceptions.SSLError as e:
            msg = "{0}\n{1}".format(type(e).__name__, str(e))
            raise ApiException(status=0, reason=msg)
    
        if _preload_content:
            r = RESTResponse(r)
    
            # In the python 3, the response.data is bytes.
            # we need to decode it to string.
            if PY3:
                r.data = r.data.decode('utf8')
    
            # log response body
            logger.debug("response body: %s", r.data)
    
        if not 200 <= r.status <= 299:
>           raise ApiException(http_resp=r)
E           kubernetes.client.rest.ApiException: (409)
E           Reason: Conflict
E           HTTP response headers: HTTPHeaderDict({'Audit-Id': '73263e85-e97a-4503-b36e-bed73ab921aa', 'Content-Type': 'application/json', 'Date': 'Mon, 25 Mar 2019 13:46:37 GMT', 'Content-Length': '198'})
E           HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"configmaps \"conf\" already exists","reason":"AlreadyExists","details":{"name":"conf","kind":"configmaps"},"code":409}

venv/lib/python3.7/site-packages/kubernetes/client/rest.py:222: ApiException
                                                             [100%]

==================================== ERRORS ====================================
_________________________ ERROR at setup of test_hare __________________________

request = <SubRequest 'create_configmap' for <Function test_hare>>

    @pytest.fixture
    def create_configmap(request):
        def _create_configmap_in_namespace(nspace):
            # Configure ConfigMap metadata
            # This function assume that there is only 1 configMap in the each namespace
            configmap_name = testconfig['config_map_name']
            metadata = client.V1ObjectMeta(annotations=None,
                                           deletion_grace_period_seconds=30,
                                           labels=None,
                                           name=configmap_name,
                                           namespace=nspace)
            # Get File Content
            with open('../config.toml', 'r') as f:
                file_content = f.read()
            # Instantiate the configmap object
            d = {'config.toml': file_content}
            configmap = client.V1ConfigMap(api_version="v1",
                                           kind="ConfigMap",
                                           data=d,
                                           metadata=metadata)
            try:
                client.CoreV1Api().create_namespaced_config_map(namespace=nspace,
                                                                body=configmap,
                                                                pretty='pretty_example')
            except ApiException as e:
                if eval(e.body)['reason'] == 'AlreadyExists':
                    print('configmap: {0} already exist.'.format(configmap_name))
                raise e
            return configmap_name
    
        def fin():
            client.CoreV1Api().delete_namespaced_config_map(testconfig['config_map_name'],
                                                            testconfig['namespace'],
                                                            body=client.V1DeleteOptions(propagation_policy='Foreground',
                                                                                        grace_period_seconds=5))
    
        request.addfinalizer(fin)
>       return _create_configmap_in_namespace(testconfig['namespace'])

test_bs.py:248: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test_bs.py:238: in _create_configmap_in_namespace
    raise e
test_bs.py:234: in _create_configmap_in_namespace
    pretty='pretty_example')
venv/lib/python3.7/site-packages/kubernetes/client/apis/core_v1_api.py:5540: in create_namespaced_config_map
    (data) = self.create_namespaced_config_map_with_http_info(namespace, body, **kwargs)
venv/lib/python3.7/site-packages/kubernetes/client/apis/core_v1_api.py:5631: in create_namespaced_config_map_with_http_info
    collection_formats=collection_formats)
venv/lib/python3.7/site-packages/kubernetes/client/api_client.py:321: in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
venv/lib/python3.7/site-packages/kubernetes/client/api_client.py:155: in __call_api
    _request_timeout=_request_timeout)
venv/lib/python3.7/site-packages/kubernetes/client/api_client.py:364: in request
    body=body)
venv/lib/python3.7/site-packages/kubernetes/client/rest.py:266: in POST
    body=body)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <kubernetes.client.rest.RESTClientObject object at 0x110ffd710>
method = 'POST'
url = 'https://35.234.101.237/api/v1/namespaces/gavrad/configmaps?pretty=pretty_example'
query_params = [('pretty', 'pretty_example')]
headers = {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'Swagger-Codegen/8.0.1/python', 'auth...fwdmSxg3NCGoGJABlM9_j5YsOXDct4d-Xdr7hEpGU0Q6rYvF76_myfkD6y7TGUzdTyig49iczvJ3Dq8pdgnVH5n3buvLIxR8i3dqgG5-v89hRXzfk0rlg'}
body = {'apiVersion': 'v1', 'data': {'config.toml': '# sample spacemesh config file\n# use the config flag to start a node wi...es = 3\n'}, 'kind': 'ConfigMap', 'metadata': {'deletionGracePeriodSeconds': 30, 'name': 'conf', 'namespace': 'gavrad'}}
post_params = {}, _preload_content = True, _request_timeout = None

    def request(self, method, url, query_params=None, headers=None,
                body=None, post_params=None, _preload_content=True, _request_timeout=None):
        """
        :param method: http request method
        :param url: http request url
        :param query_params: query parameters in the url
        :param headers: http request headers
        :param body: request json body, for `application/json`
        :param post_params: request post parameters,
                            `application/x-www-form-urlencoded`
                            and `multipart/form-data`
        :param _preload_content: if False, the urllib3.HTTPResponse object will be returned without
                                 reading/decoding response data. Default is True.
        :param _request_timeout: timeout setting for this request. If one number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of (connection, read) timeouts.
        """
        method = method.upper()
        assert method in ['GET', 'HEAD', 'DELETE', 'POST', 'PUT', 'PATCH', 'OPTIONS']
    
        if post_params and body:
            raise ValueError(
                "body parameter cannot be used with post_params parameter."
            )
    
        post_params = post_params or {}
        headers = headers or {}
    
        timeout = None
        if _request_timeout:
            if isinstance(_request_timeout, (int, ) if PY3 else (int, long)):
                timeout = urllib3.Timeout(total=_request_timeout)
            elif isinstance(_request_timeout, tuple) and len(_request_timeout) == 2:
                timeout = urllib3.Timeout(connect=_request_timeout[0], read=_request_timeout[1])
    
        if 'Content-Type' not in headers:
            headers['Content-Type'] = 'application/json'
    
        try:
            # For `POST`, `PUT`, `PATCH`, `OPTIONS`, `DELETE`
            if method in ['POST', 'PUT', 'PATCH', 'OPTIONS', 'DELETE']:
                if query_params:
                    url += '?' + urlencode(query_params)
                if re.search('json', headers['Content-Type'], re.IGNORECASE):
                    if headers['Content-Type'] == 'application/json-patch+json':
                        if not isinstance(body, list):
                            headers['Content-Type'] = \
                                'application/strategic-merge-patch+json'
                    request_body = None
                    if body is not None:
                        request_body = json.dumps(body)
                    r = self.pool_manager.request(method, url,
                                                  body=request_body,
                                                  preload_content=_preload_content,
                                                  timeout=timeout,
                                                  headers=headers)
                elif headers['Content-Type'] == 'application/x-www-form-urlencoded':
                    r = self.pool_manager.request(method, url,
                                                  fields=post_params,
                                                  encode_multipart=False,
                                                  preload_content=_preload_content,
                                                  timeout=timeout,
                                                  headers=headers)
                elif headers['Content-Type'] == 'multipart/form-data':
                    # must del headers['Content-Type'], or the correct Content-Type
                    # which generated by urllib3 will be overwritten.
                    del headers['Content-Type']
                    r = self.pool_manager.request(method, url,
                                                  fields=post_params,
                                                  encode_multipart=True,
                                                  preload_content=_preload_content,
                                                  timeout=timeout,
                                                  headers=headers)
                # Pass a `string` parameter directly in the body to support
                # other content types than Json when `body` argument is provided
                # in serialized form
                elif isinstance(body, str):
                    request_body = body
                    r = self.pool_manager.request(method, url,
                                                  body=request_body,
                                                  preload_content=_preload_content,
                                                  timeout=timeout,
                                                  headers=headers)
                else:
                    # Cannot generate the request from given parameters
                    msg = """Cannot prepare a request message for provided arguments.
                             Please check that your arguments match declared content type."""
                    raise ApiException(status=0, reason=msg)
            # For `GET`, `HEAD`
            else:
                r = self.pool_manager.request(method, url,
                                              fields=query_params,
                                              preload_content=_preload_content,
                                              timeout=timeout,
                                              headers=headers)
        except urllib3.exceptions.SSLError as e:
            msg = "{0}\n{1}".format(type(e).__name__, str(e))
            raise ApiException(status=0, reason=msg)
    
        if _preload_content:
            r = RESTResponse(r)
    
            # In the python 3, the response.data is bytes.
            # we need to decode it to string.
            if PY3:
                r.data = r.data.decode('utf8')
    
            # log response body
            logger.debug("response body: %s", r.data)
    
        if not 200 <= r.status <= 299:
>           raise ApiException(http_resp=r)
E           kubernetes.client.rest.ApiException: (409)
E           Reason: Conflict
E           HTTP response headers: HTTPHeaderDict({'Audit-Id': '73263e85-e97a-4503-b36e-bed73ab921aa', 'Content-Type': 'application/json', 'Date': 'Mon, 25 Mar 2019 13:46:37 GMT', 'Content-Length': '198'})
E           HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"configmaps \"conf\" already exists","reason":"AlreadyExists","details":{"name":"conf","kind":"configmaps"},"code":409}

venv/lib/python3.7/site-packages/kubernetes/client/rest.py:222: ApiException
---------------------------- Captured stdout setup -----------------------------
configmap: conf already exist.
=========================== 1 error in 2.71 seconds ============================
Process finished with exit code 0

**Comment by beckmani** [comment]
This no longer happens. We handle the deletion of configmap in its teardown
