### ISSUE TITLE
Add Active set according to view in ATX

### ISSUE THREAD

**Issue by antonlerner** [spacemeshos/go-spacemesh#745]
# Overview / Motivation
ATX must contain at least d active identities in it's view, therefore a proper view must be selected. 
# The Task
Use BFS search toget proper view.  
# Implementation Notes
TODO: Add links to relevant resources, specs, related issues, etc...

# Contribution Guidelines
Important: Issue assignment to developers will be by the order of their application and proficiency level according to the tasks complexity. We will not assign tasks to developers who have'nt introduced themselves on our Gitter [dev channel](https://gitter.im/spacemesh-os/Lobby)

1. Introduce yourself on go-spacemesh [dev chat channel](https://gitter.im/spacemesh-os/Lobby) - ask our team any question you may have about this task
2. Fork branch `develop` to your own repo and work in your repo
3. You must document all methods, enums and types with [godoc comments](https://blog.golang.org/godoc-documenting-go-code)
4. You must write go unit tests for all types and methods when submitting a component, and integration tests if you submit a feature
5. When ready for code review, submit a PR from your repo back to branch `develop`
6. Attach relevant issue to PR

**Comment by barakshani** [comment]
1. It should be exactly d.
2. Maybe there is no need to declare d.
3. We need to count only the ATX that give eligibility for the current epoch (e.g. free-standing ATXs give eligibility for the previous epoch).
