### ISSUE TITLE
Disk should be handled if post init failed (crash recovery)

### ISSUE THREAD

**Issue by zalmen** [spacemeshos/go-spacemesh#753]
In case of an error during the PoST initialization, we should make sure the files on the disk are either removed or set in a way that the initialization can continue from the current step sometime later.

**Comment by noamnelke** [comment]
I don't think we should delete the files. Knowing the initialization didn't finish is relatively easy -- just check the size of the file and see if it's a multiple of the minimal storage size.

I do think we should add logic that checks the file size and performs recovery if needed once we have the pause/resume functionality.

The current behaviour is to overwrite previous storage with the same id.

**Comment by moshababo** [comment]
Closed by https://github.com/spacemeshos/post/pull/22.
