### ISSUE TITLE
Consider optimizing proposal validation to the end of the round

### ISSUE THREAD

**Issue by gavraz** [spacemeshos/go-spacemesh#767]
We can validate the SVP at the end of the proposal round.
Pros:
No need to validate multiple proposals, only the lowest.
Cons
An SVP is relatively expensive to validate.

**Comment by jonZlotnik** [comment]
This depends on how the leader is supposed to be selected. If the leader is selected by taking the lowest VRF output from the participating status nodes, then there’s no need to validate multiple proposals. We just wait until we get the proposal message from the correct leader.

See https://github.com/spacemeshos/pm/issues/179

2 steps for resolving this issue:
1. no matter what, we should wait until the end of the proposal round to compute the leader
That will entail collecting the messages, and sorting them by vrf output (but not validating the Safe Value Proofs). Once all messages are received, validate the SVP at the lower end of the sorted list.
2. decide on the leader selection method and update the current code if it needs to change from the current implementation.

**Comment by jonZlotnik** [comment]
Leader selection does not need to change, but SVP validation should only happen once the final leader is ready to be selected. (as explained by @gavraz ) no need to validate all incoming proposals.

- [ ] keep only the proposal with the lowest valid eligibility proof during the proposal round.
- [ ] validate the proposal at the end of the round. (be careful to make sure it's completed in time for the commit round so we can broadcast our commit message in time if eligible)
