### ISSUE TITLE
cache docker image with prerequisites for running automation tests

### ISSUE THREAD

**Issue by noamnelke** [spacemeshos/go-spacemesh#800]
Currently every `make dockerrun-test` causes downloading and installing gcloud and other prerequisites. This makes the testing process (when performed locally for debugging) clunky and slow. It would be wise to store a base image with all required software pre-installed so that each run is quick.

**Comment by beckmani** [comment]
@noamnelke , can we close this issue now that https://github.com/spacemeshos/go-spacemesh/pull/1231 was merged?

**Comment by noamnelke** [comment]
Sure, forgot I created this issue!
