### ISSUE TITLE
key collision in JSON logs 

### ISSUE THREAD

**Issue by gavraz** [spacemeshos/go-spacemesh#801]
Key collision in JSON logs causes errors and retransmission of logs in fluentbit.
Ultimately, it causes issues in the test assertions.
We need to be able to identify this issue as soon as possible and not reach the failed assertion - in which it is harder to understand what is the problem.
Moreover, we should be able to retrieve the keys that cause the collision if possible.

**Comment by lrettig** [comment]
@ilans is this still an issue?

**Comment by lrettig** [comment]
Ping @ilans does anything need to be done here?

**Comment by moshababo** [comment]
Obsolete.
