### ISSUE TITLE
Concurrent implementation of PoST init

### ISSUE THREAD

**Issue by zalmen** [spacemeshos/go-spacemesh#831]
# Overview / Motivation
When doing post init we should support 2 modes - one slow but easy on the host which uses only one core and a fast but resource consuming which uses all cores.

# The Task
Provide support for the fast mode (slow mode is already implemented). The fast mode should split the init work between several go routines. 

# Implementation Notes
As part of this work you should also compare the fast mode vs the slow mode and verify that the ratio is more or less the same as the ratio between the number of cores used.

# Contribution Guidelines
Important: Issue assignment to developers will be by the order of their application and proficiency level according to the tasks complexity. We will not assign tasks to developers who have'nt introduced themselves on our Gitter [dev channel](https://gitter.im/spacemesh-os/Lobby)

1. Introduce yourself on go-spacemesh [dev chat channel](https://gitter.im/spacemesh-os/Lobby) - ask our team any question you may have about this task
2. Fork branch `develop` to your own repo and work in your repo
3. You must document all methods, enums and types with [godoc comments](https://blog.golang.org/godoc-documenting-go-code)
4. You must write go unit tests for all types and methods when submitting a component, and integration tests if you submit a feature
5. When ready for code review, submit a PR from your repo back to branch `develop`
6. Attach relevant issue to PR

**Comment by moshababo** [comment]
Closed by https://github.com/spacemeshos/post/pull/13 & https://github.com/spacemeshos/post/pull/15.
