### ISSUE TITLE
Support Variable Post Commitment Size

### ISSUE THREAD

**Issue by zalmen** [spacemeshos/go-spacemesh#838]
The PoST commitment will be in the granularity of 256 GiB (pending changes). A miner can choose an initial number of commitments units and later add/reduce units. The on-disk representation of the commitment will always be a single tree. Adding more units will result with appending more leaves (labels) to the tree and removing units will result with trimming the leaves. Each unit will be represented by a sub ID (basically an index) that is only relevant when proving/validating the eligibility for the layer/hare committee.

**Comment by avive** [comment]
Variable post is the single most important user-facing new feature of Spacemesh 0.2

**Comment by avive** [comment]
The ideal post size unit is 100GB base and not 250GB. With mesh growth, we can't expect users to give 0.5TB on home drives. The gpu-post scrypt params should target 24 hours of work for the base unit on a fast gpu.

**Comment by rkasterstein** [comment]
This epic includes multiple items :
https://github.com/spacemeshos/go-spacemesh/issues/498
https://github.com/spacemeshos/go-spacemesh/issues/842
https://github.com/spacemeshos/go-spacemesh/issues/846
https://github.com/spacemeshos/go-spacemesh/issues/848
https://github.com/spacemeshos/go-spacemesh/issues/849
https://github.com/spacemeshos/go-spacemesh/issues/851
https://github.com/spacemeshos/go-spacemesh/issues/852

**Comment by noamnelke** [comment]
Irrelevant due to #2039
