### ISSUE TITLE
Initialize multiple commitment units

### ISSUE THREAD

**Issue by zalmen** [spacemeshos/go-spacemesh#842]
# Overview / Motivation
If a user wants to expend more than one post commitment unit, we need to expand the post init with the additional units (according to the current design, the final design might change a bit).

# The Task
Support expanding of the init commitment. At the first stage, we can allow blocking of any proof generation during the init work.

# Implementation Notes
TODO: Add links to relevant resources, specs, related issues, etc...

# Contribution Guidelines
Important: Issue assignment to developers will be by the order of their application and proficiency level according to the tasks complexity. We will not assign tasks to developers who have'nt introduced themselves on our Gitter [dev channel](https://gitter.im/spacemesh-os/Lobby)

1. Introduce yourself on go-spacemesh [dev chat channel](https://gitter.im/spacemesh-os/Lobby) - ask our team any question you may have about this task
2. Fork branch `develop` to your own repo and work in your repo
3. You must document all methods, enums and types with [godoc comments](https://blog.golang.org/godoc-documenting-go-code)
4. You must write go unit tests for all types and methods when submitting a component, and integration tests if you submit a feature
5. When ready for code review, submit a PR from your repo back to branch `develop`
6. Attach relevant issue to PR

**Comment by rkasterstein** [comment]
Part of the https://github.com/spacemeshos/go-spacemesh/issues/838 epic

**Comment by noamnelke** [comment]
Irrelevant due to #2039
