### ISSUE TITLE
handle 2 blocks with same eligibility in tortoise

### ISSUE THREAD

**Issue by almogdepaz** [spacemeshos/go-spacemesh#844]
# Overview / Motivation
we do not enforce these rules in the tortoise 
the code for non voting blocks should be added

# The Task
implement as was discussed with barak and yuval

**Comment by dshulyak** [comment]
From Tal on slack:

> The translation to our case is if someone publishes two ATXs with the same id and the same epoch, or two ballots with the same ATX in the same slot. This is verifiably malicious behavior, and should cause the ID to be canceled (all of its ballots have weight 0, and the node should vote against any type of reward being given to this ID) .

I don't know if we are going to implement proofs of malicious behaviour for mainnet. But the solution for this particular issue should be:
- if there are two or more ballots using the same atxid and same slot they should not be counted by the tortoise (e.g. as the weight is 0)
- we can verify it when the ballot is received and add an additional bit to the ballot stored on disk
- tortoise should load this bit and act accordingly
- malicious ballot can't be pruned, as they will be used during rerun

**Comment by dshulyak** [comment]
lets track this in https://github.com/spacemeshos/go-spacemesh/issues/2999
