### ISSUE TITLE
Remove commitment units

### ISSUE THREAD

**Issue by zalmen** [spacemeshos/go-spacemesh#848]
# Overview / Motivation
The PoST commitment will be in the granularity of 256 GiB (pending changes). A miner can choose an initial number of commitments units and later add/reduce units. The on-disk representation of the commitment will always be a single tree. Adding more units will result with appending more leaves (labels) to the tree and removing units will result with trimming the leaves

# The Task
Support reducing the number of commitment units.

# Implementation Notes
If needed, we can allow locking the tree for proof generation while increasing the init file - let's talk about it before you begin working on this task

# Contribution Guidelines
Important: Issue assignment to developers will be by the order of their application and proficiency level according to the tasks complexity. We will not assign tasks to developers who have'nt introduced themselves on our Gitter [dev channel](https://gitter.im/spacemesh-os/Lobby)

1. Introduce yourself on go-spacemesh [dev chat channel](https://gitter.im/spacemesh-os/Lobby) - ask our team any question you may have about this task
2. Fork branch `develop` to your own repo and work in your repo
3. You must document all methods, enums and types with [godoc comments](https://blog.golang.org/godoc-documenting-go-code)
4. You must write go unit tests for all types and methods when submitting a component, and integration tests if you submit a feature
5. When ready for code review, submit a PR from your repo back to branch `develop`
6. Attach relevant issue to PR

**Comment by rkasterstein** [comment]
Part of the https://github.com/spacemeshos/go-spacemesh/issues/838 epic

**Comment by noamnelke** [comment]
Irrelevant due to #2039
