### ISSUE TITLE
Hare eligibility should consider sub IDs

### ISSUE THREAD

**Issue by zalmen** [spacemeshos/go-spacemesh#851]
# Overview / Motivation
On every round, we need to check the eligibility to participate in the Hare committee for each sub ID.
When generating or validating an eligibility proof we need to have as an input the relevant sub ID 

# The Task
This issue includes 3 tasks:
1. Run Hare committee participation flow for each sub ID.
2. When checking eligibility and generating eligibility proofs, the sub ID should be an input to the VRF.
3. When validating eligibility, the sub ID should be an input to the VRF.

# Implementation Notes
TODO: Add links to relevant resources, specs, related issues, etc...

# Contribution Guidelines
Important: Issue assignment to developers will be by the order of their application and proficiency level according to the tasks complexity. We will not assign tasks to developers who have'nt introduced themselves on our Gitter [dev channel](https://gitter.im/spacemesh-os/Lobby)

1. Introduce yourself on go-spacemesh [dev chat channel](https://gitter.im/spacemesh-os/Lobby) - ask our team any question you may have about this task
2. Fork branch `develop` to your own repo and work in your repo
3. You must document all methods, enums and types with [godoc comments](https://blog.golang.org/godoc-documenting-go-code)
4. You must write go unit tests for all types and methods when submitting a component, and integration tests if you submit a feature
5. When ready for code review, submit a PR from your repo back to branch `develop`
6. Attach relevant issue to PR

**Comment by rkasterstein** [comment]
Part of the https://github.com/spacemeshos/go-spacemesh/issues/838 epic

**Comment by noamnelke** [comment]
Irrelevant due to #2039
