### ISSUE TITLE
conversion naming methods convention

### ISSUE THREAD

**Issue by almogdepaz** [spacemeshos/go-spacemesh#873]
Our conversion functions (from one type to another) use different naming.

E.g. in `common/types/encode.go`, we have `BlockIdsAsBytes` ("as"), but `BytesToBlockIds` ("to").

Some methods on types have the same issue, e.g. 
```golang
(id BlockID) AsHash32()
```
vs.
```golang
(id NodeID) ToBytes()
```

We should use the same naming convention for all conversion functions. I personally like X to Y (kind of like `itoa` is "integer to ascii").

For methods on types, the general Go convention is to call the method like the return type, with no prefix (e.g. `.String()`).

**Comment by shibe-dev** [comment]
ill love to work on this!

**Comment by avive** [comment]
@antonlerner

**Comment by kulak** [comment]
Sorry for no notice.
