### ISSUE TITLE
Genesis flow

### ISSUE THREAD

**Issue by zalmen** [spacemeshos/go-spacemesh#897]
# The Motivation
Kickstarting the network requires special handling. 

# The Requirement
The network can start in a decentralized way with minimal security compromises.

# Activation Flow
**Prerequisites:** 
(1) Free standing ATXs; 
(2) Using the actual number of ATXs targeting the current epoch as the active set size (instead of declaring the active set size in the ATX).

**The solution:** Allow a time (about the length of an epoch) for miners to publish free-standing ATXs, referencing a "Golden-ATX" as their positioning ATX. Blocks can then only be created in the next epoch (targeted by their first ATX).

A description of changes to be made in current transaction flow to support a complete flow of creating activation transactions and proving eligibility from genesis

## Activation transaction creation
- Configurable pre-defined ATX0
- LayerID should be changed to epoch ID
- Activation transaction should be published as soon as it's ready
- First activation transaction created must point to ATX0 of the same network
- Active set size should not be declared in ATX
- Active set size view should not be declared in ATX
- ATX pool should be persisted and able to sync(?)

## Block creation
- all ATXs received must be stored per epoch
- A block must contain a special list of refrences for seen ATXs
    - can be stored as a batch with hash for optimisation and deduplication
    - we must optimize this list because it means that every new first block will probably contain it or a subset of it
    - this defines active set size for block
- First block should contain an active set size number
- All other blocks in layers after must point to this block as proof
    - maybe we can aggregate all blocks from miner per epoch and not need the refrence
    - on the other hand we might need it in order to fetch it from neighbors if doesn't exist
- It's ok for a block to have a different size ATX list and different active set size
- There needs to be a limit of how many blocks can be created from a single miner
    - what happens if a miner creates more than this amount?

## Sync implications
- ATX list for first block must be synced
- Refrenced block that contains active set size needs to be synced
- If sync fails then block is invalid
- Refrenced ATX should be synced as well

## hare active set size
- Take the maximum active set size of blocks in several layer in the past within a safe distance

## Security
- Conflicting ATXs - is there a problem with publishing more than 1 atx that references another?

## Hare eligibility
make sure hare is able to have an active set size in first epoch

The Golden-ATX will include some proof that it didn't exist before the claimed creation time (Bitcoin's latest block hash, or equivalent value).

## Alternative solutions
1. Pre-submitting ATXs for epoch0 (offchain)
2. Running a short PoET to allow miners to generate an ATX for epoch 1 during epoch 0.

## Tech-Debt Related to the Genesis Flow
###`oracle/blockoracle.go` / `oracle/blockeligibilityvalidator.go`
- Uses `genesisActiveSetSize` as a hard-coded number of miners in the first two epochs.
- Since no ATX is published for epoch 0, no signature or VRF validation is performed for blocks in this epoch (the VRF and Eduards public keys are only published in the ATX). No VRF validation means that any block is considered eligible for any layer.

**Comment by barakshani** [comment]
Need to implement https://github.com/spacemeshos/research/issues/25

**Comment by rkasterstein** [comment]
@antonlerner leads and @noamnelke review

**Comment by barakshani** [comment]
Make sure to remove this patch https://github.com/spacemeshos/go-spacemesh/issues/1930 once the task is completed

**Comment by barakshani** [comment]
https://github.com/spacemeshos/go-spacemesh/issues/1681 can be closed once the task is completed
