### ISSUE TITLE
Make all comments show up good on godoc.

### ISSUE THREAD

**Issue by y0sher** [spacemeshos/go-spacemesh#90]
#### Feature description
Make all comments show up good on godoc.
Some comments are missing some just don't show up well on godoc

#### Main Reason for adding this feature
GoDoc is an awesome tool and we can leverage it to have our code fully documented online.

**Comment by influx6** [comment]
Hi, since no one has taking this up and to provide a simply walk into the project, I can take this up and go through the sources to fix comments as needed.

**Comment by y0sher** [comment]
@influx6 Can be a great intro to the project would be great if you can take it!

**Comment by y0sher** [comment]
this was done but we have to revisit

**Comment by avive** [comment]
@y0sher is this still relevant?

**Comment by moshababo** [comment]
Obsolete.
