### ISSUE TITLE
ATX/NIPST builder should respond to PoET messages immediately

### ISSUE THREAD

**Issue by noamnelke** [spacemeshos/go-spacemesh#908]
Currently, the NIPST builder polls for PoET membership proofs and PoET proofs once per layer. Since the PoET server now publishes proofs on gossip we can listen for those messages and immediately continue building the NIPST.

**Comment by moshababo** [comment]
@noamnelke `PoetClient` can still be a facade around the p2p msg listener (that was the intention).

**Comment by noamnelke** [comment]
Yes, but this issue is about changing the semantics: instead of having to poll the `PoetClient` (or whatever other mechanism) to check if the proof is ready, we want to have some mechanism in place where we wait for the proof (or timeout) and wake up immediately when we the time comes.

**Comment by noamnelke** [comment]
Solved in https://github.com/spacemeshos/go-spacemesh/pull/913
