### ISSUE TITLE
Genesis flow for Hare protocol

### ISSUE THREAD

**Issue by gavraz** [spacemeshos/go-spacemesh#953]
Since genesis flow is yet to be agreed, the current implementation has a few points that should be addressed:
1. func NewMsg (called by the Broker/MessageValidation) is checking that the sender is active only for non-genesis epochs.
2. The ElegibilityValidator can't fetch BLS key for genesis epoch. Hence, only validated on the non-genesis flow. 
3. Some unit tests in the Hare package has a TODO comment indicating that we remove the comment or change the unit test.
4. The current number of actives for Genesis is a constant number (5)

We should decide if we want to modify the current impl and the tests after we decide on the genesis flow. It is likely that the current implementation will be the solution to the genesis problem.

**Comment by barakshani** [comment]
See relevant part here https://github.com/spacemeshos/research/issues/25
