### ISSUE TITLE
ATX validity

### ISSUE THREAD

**Issue by barakshani** [spacemeshos/go-spacemesh#962]
# The Motivation
ATX validation should be divided into 2:
1. "syntactic" validity -- determines whether it should be propagated.
2. "contextual" validity -- determines whether the source of the ATX is "playing by the rules".

# The Requirement
Under syntactic validity we have all the conditions that could be determined by the ATX itself (and its view).
Everything else, like conflicting sequence numbers or appropriate amount of ticks (if we add this in the future), is under contextual validity.

A syntactically ATX is considered "Valid", and should be propagated.
If an ATX is not contextually valid, the flow is as follows:
1. The *miner* becomes invalid -- all of her votes (in previous and in future blocks) are considered 0; other miners vote against her future blocks (we may, in the future, won't let her publish ATX/blocks, i.e. won't propagate them).
2. An evidence of the fault should be put on the mesh: if the miner is currently valid (no evidence on the chain) we publish the conflicting ATX* (put it in a block). If the miner is invalid, we do nothing more.

* if there are several (conflicting) ATXs at the same time, we sort them and take the lower one to be the evidence.

**Comment by barakshani** [comment]
finalise this once https://github.com/spacemeshos/research/issues/31 is agreed upon

Would be good to print "late ATX", similar to "late blocks", once we clarify what _late_ is/means.

**Comment by moshababo** [comment]
Already implemented.
