### ISSUE TITLE
Canceling blocks/ATXs

### ISSUE THREAD

**Issue by zalmen** [spacemeshos/go-spacemesh#971]
# The Motivation
A malicious miner might send more than one ATX for the same epoch or it might use his eligibility to send more than one block. We need to handle such cases according to the protocol (TODO @barakshani point to a reference of the part of the protocol that handles such cases
# The Requirement
TODO: What is the expected behaviour of this epic?

**Comment by barakshani** [comment]
Related issue:
https://github.com/spacemeshos/go-spacemesh/issues/962

**Comment by moshababo** [comment]
Obsolete.
