### ISSUE TITLE
start multiple boot nodes in automation

### ISSUE THREAD

**Issue by y0sher** [spacemeshos/go-spacemesh#987]
# Overview / Motivation

Currently all our tests in automation relay about all the nodes bootstrapping from a single node. we want to be able to boot from more than one node.

# The Task

Create multiple bootstrap nodes and make them know each other. (load from peers.json with fixed ips or we'll need to add an `AddAddress` api call. 
pass the whole list of bootstrap nodes to other nodes that will start.

# Implementation Notes
TODO: Add links to relevant resources, specs, related issues, etc...

# Contribution Guidelines
Important: Issue assignment to developers will be by the order of their application and proficiency level according to the tasks complexity. We will not assign tasks to developers who have'nt introduced themselves on our Gitter [dev channel](https://gitter.im/spacemesh-os/Lobby)

1. Introduce yourself on go-spacemesh [dev chat channel](https://gitter.im/spacemesh-os/Lobby) - ask our team any question you may have about this task
2. Fork branch `develop` to your own repo and work in your repo
3. You must document all methods, enums and types with [godoc comments](https://blog.golang.org/godoc-documenting-go-code)
4. You must write go unit tests for all types and methods when submitting a component, and integration tests if you submit a feature
5. When ready for code review, submit a PR from your repo back to branch `develop`
6. Attach relevant issue to PR

**Comment by y0sher** [comment]
this is regarding any "testnet" setup we're going to have. one bootstrap isn't enough.

**Comment by avive** [comment]
todo: discuss this w @y0sher

**Comment by y0sher** [comment]
we should set up the tests to create more than one bootstrap node in order to simulate how we do it irl

**Comment by barakshani** [comment]
migrated to https://github.com/spacemeshos/go-spacemesh/issues/1666
