### ISSUE TITLE
Gossip should use hash (data w/o signature) when storing old messages

### ISSUE THREAD

**Issue by zalmen** [spacemeshos/go-spacemesh#988]
# Overview / Motivation
Currently, in the Gossip handler, we store old messages based on the hash of the entire message (payload + signature), this allows a node to take someone else's old message, change it's XDR format without breaking the signature and redistribute it.   
Instead, we should maintain the old messages cache according to the hash of the data itself, this way the hash and the signature are aligned.
 
# The Task
TODO: Clearly describe the issue requirements here...

# Implementation Notes
TODO: Add links to relevant resources, specs, related issues, etc...

# Contribution Guidelines
Important: Issue assignment to developers will be by the order of their application and proficiency level according to the tasks complexity. We will not assign tasks to developers who have'nt introduced themselves on our Gitter [dev channel](https://gitter.im/spacemesh-os/Lobby)

1. Introduce yourself on go-spacemesh [dev chat channel](https://gitter.im/spacemesh-os/Lobby) - ask our team any question you may have about this task
2. Fork branch `develop` to your own repo and work in your repo
3. You must document all methods, enums and types with [godoc comments](https://blog.golang.org/godoc-documenting-go-code)
4. You must write go unit tests for all types and methods when submitting a component, and integration tests if you submit a feature
5. When ready for code review, submit a PR from your repo back to branch `develop`
6. Attach relevant issue to PR

**Comment by lrettig** [comment]
@y0sher is this still relevant?
