### ISSUE TITLE
Add network id to account and node store

### ISSUE THREAD

**Issue by avive** [spacemeshos/go-spacemesh#99]
#### Feature description
Add network id to the account and node persisted data.
`localnodestore.go` should be expanded to save to node's NetworkId for future loads.
check `NodeData` struct and `persistData` func

in `accounts/store.go` should have pretty much the same. (though its not the same networkID param)
check `AccountData` struct and `Persist` func
  

#### Main Reason for adding this feature
For nodes it is necessary to load the node's network id when starting from a persisted node for users to be able to easily stop and restart nodes.

For accounts,  this will help mitigate attempts to use an account on the wrong network id which can be quite confusing to the user and introduce some nasty bugs. The account data in local store is supposed to be used with an account that was created on-chain. There's not much use to an account that is not associated with a specific network id.

**Comment by y0sher** [comment]
@avive Is it ok if I address that in the PR  https://github.com/spacemeshos/go-spacemesh/pull/96 ? 
as it looks like a direct continuation of my prev work side effects.

**Comment by y0sher** [comment]
merged in #123
