### ISSUE TITLE
Error when running "make dockerrun-all" after pytest execution

### ISSUE THREAD

**Issue by zalmen** [spacemeshos/go-spacemesh#994]
Getting this error -
________________________________________________________________________________________________________ ERROR collecting test_bs.py _________________________________________________________________________________________________________
import file mismatch:
imported module 'tests.test_bs' has this __file__ attribute:
  /Users/yuval/dev/sm/go/src/github.com/spacemeshos/go-spacemesh/tests/test_bs.py
which is not the same as the test file we want to collect:
  /go-spacemesh/tests/test_bs.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================================================================================== 1 error in 0.44 seconds ===========================================================================================================

It is better if we canfail the execution at the beggining instead of waiting until it is needed to fail it

**Comment by beckmani** [comment]
should not happen anymore as pycache is now in dockerignore
